graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[hash-graph-authorization]
    class 0 root
    1[<a href="../type_system/index.html">type-system</a>]
    2[<a href="../hash_graph_types/index.html">hash-graph-types</a>]
    3[<a href="../hash_codec/index.html">hash-codec</a>]
    4[<a href="../error_stack/index.html">error-stack</a>]
    5[<a href="../hash_graph_test_data/index.html">hash-graph-test-data</a>]
    6[<a href="../hash_graph_temporal_versioning/index.html">hash-graph-temporal-versioning</a>]
    7[<a href="../harpc_types/index.html">harpc-types</a>]
    8[<a href="../harpc_wire_protocol/index.html">harpc-wire-protocol</a>]
    9[<a href="../hash_graph/index.html">hash-graph</a>]
    10[<a href="../hash_graph_api/index.html">hash-graph-api</a>]
    11[<a href="../hash_graph_benches/index.html">hash-graph-benches</a>]
    12[<a href="../hash_graph_integration/index.html">hash-graph-integration</a>]
    13[<a href="../hash_graph_postgres_store/index.html">hash-graph-postgres-store</a>]
    14[<a href="../hash_graph_store/index.html">hash-graph-store</a>]
    15[<a href="../hash_graph_test_server/index.html">hash-graph-test-server</a>]
    16[<a href="../hash_graph_type_fetcher/index.html">hash-graph-type-fetcher</a>]
    17[<a href="../hash_graph_validation/index.html">hash-graph-validation</a>]
    0 --> 2
    1 -.-> 5
    1 --> 3
    2 --> 1
    2 --> 6
    3 --> 8
    6 --> 3
    8 -.-> 7
    8 --> 7
    8 --> 4
    14 --> 0
    11 -.-> 10
    15 --> 10
    10 --> 13
    12 -.-> 13
    16 --> 14
    17 --> 14
    9 --> 15
    10 --> 16
    13 --> 17