graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hash_graph/index.html">hash-graph</a>]
    1[<a href="../type_system/index.html">type-system</a>]
    2[<a href="../hash_codec/index.html">hash-codec</a>]
    3[<a href="../hash_codegen/index.html">hash-codegen</a>]
    4[<a href="../hash_graph_api/index.html">hash-graph-api</a>]
    5[<a href="../hash_graph_atlas/index.html">hash-graph-atlas</a>]
    6[<a href="../hash_graph_authentication/index.html">hash-graph-authentication</a>]
    7[<a href="../hash_graph_authorization/index.html">hash-graph-authorization</a>]
    8[<a href="../hash_graph_store/index.html">hash-graph-store</a>]
    9[<a href="../hash_graph_temporal_versioning/index.html">hash-graph-temporal-versioning</a>]
    10[<a href="../hash_graph_types/index.html">hash-graph-types</a>]
    11[<a href="../harpc_types/index.html">harpc-types</a>]
    12[<a href="../harpc_wire_protocol/index.html">harpc-wire-protocol</a>]
    13[hash-middleware]
    class 13 root
    14[<a href="../hash_temporal_client/index.html">hash-temporal-client</a>]
    15[<a href="../error_stack/index.html">error-stack</a>]
    16[<a href="../hash_graph_benches/index.html">hash-graph-benches</a>]
    17[<a href="../hash_graph_test_data/index.html">hash-graph-test-data</a>]
    0 --> 4
    0 --> 5
    1 --> 9
    1 -.-> 17
    2 -.-> 3
    2 --> 12
    4 -.-> 6
    4 --> 6
    5 --> 8
    5 --> 13
    6 --> 8
    6 -.-> 13
    6 --> 13
    7 --> 1
    8 --> 7
    8 --> 10
    8 --> 14
    9 --> 2
    10 -.-> 17
    12 -.-> 11
    12 --> 11
    12 --> 15
    13 --> 1
    14 --> 1
    16 -.-> 4
    17 --> 8
