# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Init(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Init()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInit(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Init
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Init
    def SharedContext(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from SharedContext import SharedContext
            obj = SharedContext()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Init
    def PackageConfig(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from PackageConfig import PackageConfig
            obj = PackageConfig()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Start(builder): builder.StartObject(2)
def InitStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddSharedContext(builder, sharedContext): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(sharedContext), 0)
def InitAddSharedContext(builder, sharedContext):
    """This method is deprecated. Please switch to AddSharedContext."""
    return AddSharedContext(builder, sharedContext)
def AddPackageConfig(builder, packageConfig): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(packageConfig), 0)
def InitAddPackageConfig(builder, packageConfig):
    """This method is deprecated. Please switch to AddPackageConfig."""
    return AddPackageConfig(builder, packageConfig)
def End(builder): return builder.EndObject()
def InitEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)