# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

class RunnerOutboundMsgPayload(object):
    NONE = 0
    TaskMsg = 1
    TaskCancelled = 2
    RunnerError = 3
    RunnerErrors = 4
    RunnerWarning = 5
    RunnerWarnings = 6
    PackageError = 7
    UserErrors = 8
    UserWarnings = 9
    SyncCompletion = 10

