graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hql_core/index.html">hql-core</a>]
    1[<a href="../hql_syntax_jexpr/index.html">hql-syntax-jexpr</a>]
    2[hql-ast]
    class 2 root
    2 --> 0
    1 --> 2