import { ReactNode } from "react";

import { StatusId } from "./statuses";
import { UseCaseId } from "./use-cases";
import { VariantId } from "./variants";

export type TechnologyTreeNodeData = {
  id: string;
  heading: ReactNode;
  body?: ReactNode;
  variant: VariantId;
  status: StatusId;
  useCases: UseCaseId[];
  parentIds?: string[];
};

export const technologyTreeData: TechnologyTreeNodeData[] = [
  {
    id: "0",
    heading: "Block Protocol Core Specification",
    body: "Placeholder body two lines hopefully bla bla bla",
    status: "done",
    useCases: ["website-building"],
    variant: "block-protocol",
  },
  {
    id: "1",
    heading: "UX/UI Outline",
    status: "done",
    useCases: ["website-building"],
    variant: "infrastructure",
  },
  {
    id: "3",
    heading: "Block Protocol Graph Module - inc. type system",
    status: "done",
    useCases: ["website-building"],
    variant: "block-protocol",
  },
  {
    id: "4",
    heading: "Block Protocol Hook Module",
    body: "placeholder body",
    parentIds: ["0"],
    status: "done",
    useCases: ["website-building"],
    variant: "block-protocol",
  },
  {
    id: "5",
    heading: "Frontend App Scaffolding",
    body: "placeholder body",
    parentIds: ["1"],
    status: "done",
    useCases: ["website-building"],
    variant: "infrastructure",
  },
  {
    id: "6",
    heading: "Rust Graph",
    body: "placeholder body",
    parentIds: ["1", "3"],
    status: "done",
    useCases: ["website-building"],
    variant: "infrastructure",
  },
  {
    id: "7",
    heading: "Hook Providers",
    body: "placeholder body",
    parentIds: ["4"],
    status: "done",
    useCases: ["website-building"],
    variant: "infrastructure",
  },
  {
    id: "8",
    heading: "Core System Types - e.g. User, Org, etc.",
    body: "placeholder body",
    parentIds: ["6"],
    status: "done",
    useCases: ["website-building"],
    variant: "infrastructure",
  },
  {
    id: "9",
    heading: "Basic Primitive Blocks - e.g. heading, paragraph",
    body: "placeholder body",
    parentIds: ["7"],
    status: "done",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "10",
    heading: "Entity Type Editor",
    body: "placeholder body",
    parentIds: ["8"],
    status: "done",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "11",
    heading: "Basic Authentication - Kratos and login/logout/signup",
    body: "placeholder body",
    parentIds: ["8"],
    status: "done",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "12",
    heading: "Block Protocol Service Module",
    body: "placeholder body",
    parentIds: ["9"],
    status: "done",
    useCases: ["website-building"],
    variant: "block-protocol",
  },
  {
    id: "13",
    heading: "Entity Editor",
    body: "placeholder body",
    parentIds: ["10"],
    status: "done",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "14",
    heading: "Block Protocol API Middleware",
    body: "placeholder body",
    parentIds: ["12"],
    status: "done",
    useCases: ["website-building"],
    variant: "block-protocol",
  },
  {
    id: "15",
    heading: "Linear Pages",
    body: "placeholder body",
    parentIds: ["5"],
    status: "done",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "16",
    heading: "Prototype Multiplayer",
    body: "placeholder body",
    parentIds: ["11"],
    status: "done",
    useCases: ["website-building"],
    variant: "experiment",
  },
  {
    id: "17",
    heading: "Entity Archival (Soft Deletion)",
    body: "placeholder body",
    parentIds: ["13", "3"],
    status: "done",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "18",
    heading: "Canvas Pages",
    body: "placeholder body",
    parentIds: ["15"],
    status: "done",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "19",
    heading: "Block-Level Comments",
    body: "placeholder body",
    parentIds: ["15"],
    status: "done",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "20",
    heading: "Prototype implementation of search",
    body: "placeholder body",
    parentIds: ["15"],
    status: "done",
    useCases: ["website-building"],
    variant: "experiment",
  },
  {
    id: "21",
    heading: "Task Executor - powered by Temporal",
    body: "placeholder body",
    parentIds: ["14"],
    status: "done",
    useCases: ["website-building"],
    variant: "infrastructure",
  },
  {
    id: "22",
    heading: "@mentioning of users and entities",
    body: "placeholder body",
    parentIds: ["15", "7"],
    status: "done",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "23",
    heading: "API-powered blocks - e.g. OpenAI & Mapbox",
    body: "placeholder body",
    parentIds: ["14"],
    status: "done",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "24",
    heading: "Command Bar",
    body: "placeholder body",
    parentIds: ["20"],
    status: "done",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "25",
    heading: "Type Inheritance RFC",
    body: "placeholder body",
    parentIds: ["3"],
    status: "done",
    useCases: ["website-building"],
    variant: "block-protocol",
  },
  {
    id: "26",
    heading: "AI Type Creation",
    body: "placeholder body",
    parentIds: ["21"],
    status: "in-progress",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "27",
    heading: "User & Org Management",
    body: "placeholder body",
    parentIds: ["23"],
    status: "in-progress",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "28",
    heading: "Entity Validation",
    body: "placeholder body",
    parentIds: ["3"],
    status: "in-progress",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "29",
    heading: "Type Archival (Soft Deletion)",
    body: "placeholder body",
    parentIds: ["26"],
    status: "next-up",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "30",
    heading: "AI Entity Creation",
    body: "placeholder body",
    parentIds: ["26"],
    status: "next-up",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "31",
    heading: "Block Protocol Actions Module",
    body: "placeholder body",
    parentIds: ["24"],
    status: "next-up",
    useCases: ["website-building"],
    variant: "block-protocol",
  },
  {
    id: "32",
    heading: "Type Inheritance",
    body: "placeholder body",
    parentIds: ["25", "28"],
    status: "next-up",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "33",
    heading: "Notifications",
    body: "placeholder body",
    parentIds: ["21", "22", "27"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "34",
    heading: "Data Query & Selection Interfaces",
    body: "placeholder body",
    parentIds: ["9"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "35",
    heading: "Authorization",
    body: "placeholder body",
    parentIds: ["23", "27"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "36",
    heading: "Block Action Mapping",
    body: "placeholder body",
    parentIds: ["31"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "37",
    heading: "Realtime Service",
    body: "basically a sync engine, powers our multi-backend & collab",
    parentIds: ["16"],
    status: "future",
    useCases: ["website-building"],
    variant: "infrastructure",
  },
  {
    id: "38",
    heading: "Multi-Type Entities",
    body: "placeholder body",
    parentIds: ["32"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "39",
    heading: "Custom Data Types RFC",
    body: "placeholder body",
    parentIds: ["25"],
    status: "future",
    useCases: ["website-building"],
    variant: "block-protocol",
  },
  {
    id: "40",
    heading: "Flows",
    body: "placeholder body",
    parentIds: ["21", "33", "34"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "41",
    heading: "Advanced Blocks - entity table and kanban",
    body: "placeholder body",
    parentIds: ["34"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "42",
    heading: "External-Facing API & Webhooks",
    body: "placeholder body",
    parentIds: ["35"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "43",
    heading: "Datastore Transactions",
    body: "placeholder body",
    parentIds: ["38"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "44",
    heading: "Data Mapping RFC",
    body: "placeholder body",
    parentIds: ["39"],
    status: "future",
    useCases: ["website-building"],
    variant: "block-protocol",
  },
  {
    id: "45",
    heading: "Custom Data Types",
    body: "placeholder body",
    parentIds: ["39"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "46",
    heading: "Structural Data Mapping",
    body: "placeholder body",
    parentIds: ["44"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "47",
    heading: "Semantic Data Mapping",
    body: "placeholder body",
    parentIds: ["44"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "48",
    heading: "File Entity Viewer",
    body: "placeholder body",
    parentIds: ["45", "13"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "49",
    heading: "Integrations: One-time load",
    body: "placeholder body",
    parentIds: ["40"],
    status: "future",
    useCases: ["website-building"],
    variant: "infrastructure",
  },
  {
    id: "50",
    heading: "Integrations: One-time write",
    body: "placeholder body",
    parentIds: ["40"],
    status: "future",
    useCases: ["website-building"],
    variant: "infrastructure",
  },
  {
    id: "51",
    heading: "Integrations: Realtime sync",
    body: "placeholder body",
    parentIds: ["40", "42"],
    status: "future",
    useCases: ["website-building"],
    variant: "infrastructure",
  },
  {
    id: "52",
    heading: "Action Blocks - e.g. button, dropdown, etc.",
    body: "placeholder body",
    parentIds: ["36"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "53",
    heading: "Similarity Search - powered by Weaviate",
    body: "placeholder body",
    parentIds: ["24", "37"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "54",
    heading: "Production Multiplayer - built atop Yrs",
    body: "placeholder body",
    parentIds: ["37"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "55",
    heading: "Entity/Property Hard Deletion",
    body: "placeholder body",
    parentIds: ["43"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "56",
    heading: "Calculated Properties",
    body: "placeholder body",
    parentIds: ["46"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "57",
    heading: "Apps - builds on canvas page type UI",
    body: "placeholder body",
    parentIds: ["52"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "58",
    heading: "Semantic Q&A - powered by AI",
    body: "placeholder body",
    parentIds: ["53"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "59",
    heading: "Financial Accounting DB graph backend -- TigerBeetle",
    body: "placeholder body",
    parentIds: ["37"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "60",
    heading: "Notion Integration (one-time import only: no webhooks)",
    body: "placeholder body",
    parentIds: ["49"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "61",
    heading: "Send emails (via something like an SES integration)",
    body: "placeholder body",
    parentIds: ["50"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "62",
    heading: "Linear Integration (2-way sync)",
    body: "placeholder body",
    parentIds: ["51"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "63",
    heading: "Ramp Integration (read-only)",
    body: "placeholder body",
    parentIds: ["59"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "64",
    heading: "Asana Integration (one-time import only)",
    body: "placeholder body",
    parentIds: ["60"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "65",
    heading: "GitHub Integration (2-way sync)",
    body: "placeholder body",
    parentIds: ["62"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "66",
    heading: "Brex Integration (read-only)",
    body: "placeholder body",
    parentIds: ["63"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "67",
    heading: "Gmail/Google Workspace email sync",
    body: "placeholder body",
    parentIds: ["65"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "68",
    heading: "App Store",
    body: "placeholder body",
    parentIds: ["57"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "69",
    heading: "Text Search - powered by OpenSearch",
    body: "placeholder body",
    parentIds: ["58"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "70",
    heading: "Keyboard Navigability",
    body: "placeholder body",
    parentIds: ["24"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "71",
    heading: "Git DB graph backend",
    body: "libgit2 or Gitea, replace legacy GitLab infra",
    parentIds: ["68"],
    status: "future",
    useCases: ["website-building"],
    variant: "infrastructure",
  },
  {
    id: "72",
    heading: "Shortcut Cheatsheet",
    body: "placeholder body",
    parentIds: ["69"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "73",
    heading: "HASH Simulation Blocks - replaces hCore",
    body: "placeholder body",
    parentIds: ["70"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "74",
    heading: "Canvas AutoLayout",
    body: "placeholder body",
    parentIds: ["18"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "75",
    heading: "Time Series DB graph backend",
    body: "tech TBD",
    parentIds: ["72"],
    status: "future",
    useCases: ["website-building"],
    variant: "infrastructure",
  },
  {
    id: "76",
    heading: "Optimized Simulation Run Storage",
    body: "placeholder body",
    parentIds: ["74"],
    status: "future",
    useCases: ["website-building"],
    variant: "infrastructure",
  },
  {
    id: "77",
    heading: "REPL Block - e.g. Python Notebook",
    body: "placeholder body",
    parentIds: ["75"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "78",
    heading: "Self-service hCloud",
    body: "prev. offered up until May 2023, we plan to reintro this",
    parentIds: ["75"],
    status: "future",
    useCases: ["website-building"],
    variant: "feature",
  },
  {
    id: "79",
    heading: "Improved scalability",
    body: "Intelligent offloading of infrequently accessed data into cold storage",
    parentIds: ["75"],
    status: "future",
    useCases: ["website-building"],
    variant: "infrastructure",
  },
  // {
  //   id: "80",
  //   heading: "Composite Blocks",
  //   body: "placeholder body",
  //   parentIds: [],
  //   status: "future",
  //   useCases: ["website-building"],
  //   variant: "feature",
  // },
  // {
  //   id: "81",
  //   heading: "Improved support for self-hosting",
  //   body: "placeholder body",
  //   parentIds: [],
  //   status: "future",
  //   useCases: ["website-building"],
  //   variant: "feature",
  // },
  // {
  //   id: "82",
  //   heading: "Federated Instances",
  //   body: "placeholder body",
  //   parentIds: ["80"],
  //   status: "future",
  //   useCases: ["website-building"],
  //   variant: "feature",
  // },
  // {
  //   id: "83",
  //   heading: "ALL SIMULATION STUFF (break down)",
  //   body: "placeholder body",
  //   parentIds: [],
  //   status: "future",
  //   useCases: ["website-building"],
  //   variant: "feature",
  // },
  // {
  //   id: "84",
  //   heading: "Type Rebranding and Redirection",
  //   body: "placeholder body",
  //   parentIds: [],
  //   status: "future",
  //   useCases: ["website-building"],
  //   variant: "feature",
  // },
  // {
  //   id: "85",
  //   heading: "iOS & Android mobile apps",
  //   body: "placeholder body",
  //   parentIds: [],
  //   status: "future",
  //   useCases: ["website-building"],
  //   variant: "feature",
  // },
  // {
  //   id: "86",
  //   heading: "macOS, Windows & Linux desktop apps",
  //   body: "placeholder body",
  //   parentIds: [],
  //   status: "future",
  //   useCases: ["website-building"],
  //   variant: "feature",
  // },
];
