[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name              = "hashql-ast"
publish.workspace = true
version.workspace = true

[dependencies]
# Public workspace dependencies
hashql-core        = { workspace = true, public = true }
hashql-diagnostics = { workspace = true, public = true }

# Public third-party dependencies

# Private workspace dependencies

# Private third-party dependencies
simple-mermaid = { workspace = true }

[dev-dependencies]
hashql-compiletest = { workspace = true }

[lints]
workspace = true

[[test]]
harness = false
name    = "compiletest"
