graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hash_graph">hash-graph</a>]
    1[<a href="../hash_codec">hash-codec</a>]
    2[<a href="../hash_graph_api">hash-graph-api</a>]
    3[<a href="../hash_graph_test_server">hash-graph-test-server</a>]
    4[harpc-client]
    class 4 root
    5[<a href="../harpc_codec">harpc-codec</a>]
    6[<a href="../harpc_net">harpc-net</a>]
    7[<a href="../harpc_server">harpc-server</a>]
    8[<a href="../harpc_system">harpc-system</a>]
    9[<a href="../harpc_tower">harpc-tower</a>]
    10[<a href="../harpc_types">harpc-types</a>]
    11[<a href="../harpc_wire_protocol">harpc-wire-protocol</a>]
    12[<a href="../error_stack">error-stack</a>]
    13[<a href="../hash_graph_benches">hash-graph-benches</a>]
    0 --> 3
    1 --> 11
    2 --> 1
    2 --> 7
    3 --> 2
    4 --> 8
    5 --> 10
    5 --> 12
    6 --> 1
    6 -.-> 5
    6 --> 5
    7 -.-> 4
    8 --> 9
    9 -.-> 6
    9 --> 6
    11 -.-> 10
    11 --> 10
    11 --> 12
    13 -.-> 2
