/**
 * Writes the optimization protocol's response shapes as one JSON Schema
 * document, `schemas/optimization-protocol.schema.json`.
 *
 * The document is checked in and regenerated by `codegen`, so CI fails when it
 * drifts from the Zod schemas in `@hashintel/petrinaut-core` that define the
 * protocol. `@local/petrinaut-python` generates its pydantic models from it,
 * including the full HIR grammar the constraints carry.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { z } from "zod";

import {
  constraintSchema,
  hirFunctionSchema,
  parameterConstraintSchema,
  petrinautOptimizationDescribeParameterSchema,
  petrinautOptimizationDescribeResultSchema,
  petrinautOptimizationEvaluateResultSchema,
  petrinautOptimizationReplicateSchema,
  stateConstraintSchema,
} from "@hashintel/petrinaut-core";

import type { ZodType } from "zod";

const packageRoot = fileURLToPath(new URL("..", import.meta.url));

type JsonObject = Record<string, unknown>;

/**
 * Definitions every conversion contributes to. Schemas carrying a `meta.id`
 * (the HIR grammar, the constraint shapes) come out as `$ref`s into the
 * converted schema's own `$defs`; those are hoisted here so every reference
 * resolves against the document root, and one shared model is generated per
 * definition.
 */
const sharedDefs: Record<string, JsonObject> = {};

const hoistDefs = (json: JsonObject): void => {
  const defs = json.$defs as Record<string, JsonObject> | undefined;
  delete json.$defs;
  for (const [name, definition] of Object.entries(defs ?? {})) {
    const existing = sharedDefs[name];
    if (
      existing !== undefined &&
      JSON.stringify(existing) !== JSON.stringify(definition)
    ) {
      throw new Error(`Two different schemas share the definition id ${name}`);
    }
    sharedDefs[name] = definition;
  }
};

/** `io: "output"` describes the serialized result the CLI writes to the wire. */
const convert = (schema: ZodType): JsonObject => {
  const json = z.toJSONSchema(schema, { io: "output" }) as JsonObject;
  delete json.$schema;
  hoistDefs(json);
  return json;
};

/**
 * JSON Schema has no discriminator keyword; model generators read the
 * OpenAPI one, and with it the generated union dispatches on the tag
 * instead of trying every member.
 */
const discriminate = (definition: JsonObject, propertyName: string): void => {
  if (!Array.isArray(definition.oneOf)) {
    throw new Error(
      `Expected a oneOf union to discriminate on ${propertyName}`,
    );
  }
  definition.discriminator = { propertyName };
};

const parameterUnion = petrinautOptimizationDescribeParameterSchema;
const [floatParameter, intParameter, booleanParameter] = parameterUnion.options;

const describeResult = convert(petrinautOptimizationDescribeResultSchema);
// The parameter union is a named definition, so generators emit one shared
// model instead of an anonymous copy inlined at each use.
(
  (describeResult.properties as Record<string, JsonObject>).parameters as {
    items: unknown;
  }
).items = { $ref: "#/$defs/OptimizationDescribeParameter" };

const evaluateResult = convert(petrinautOptimizationEvaluateResultSchema);
(
  (evaluateResult.properties as Record<string, JsonObject>).replicates as {
    items?: unknown;
  }
).items = { $ref: "#/$defs/OptimizationReplicate" };

// The constraint shapes and the HIR grammar arrive through the describe
// result's `constraints`; converting them on their own as well pins their
// definitions even when a future describe result stops carrying them.
convert(parameterConstraintSchema);
convert(stateConstraintSchema);
convert(constraintSchema);
// A root conversion inlines the schema instead of naming it, so the generic
// function shape is registered by hand next to its two pinned variants.
sharedDefs.HirFunction = convert(hirFunctionSchema);

for (const [name, propertyName] of [
  ["Constraint", "space"],
  ["HirExpr", "kind"],
] as const) {
  const definition = sharedDefs[name];
  if (definition === undefined) {
    throw new Error(
      `The converted schemas did not produce a ${name} definition`,
    );
  }
  discriminate(definition, propertyName);
}

// No root schema and no title: the document only carries `$defs`, so model
// generators emit one class per definition and nothing for the document itself.
const document = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $defs: {
    OptimizationFloatParameter: convert(floatParameter),
    OptimizationIntParameter: convert(intParameter),
    OptimizationBooleanParameter: convert(booleanParameter),
    OptimizationDescribeParameter: {
      description: parameterUnion.meta()?.description,
      anyOf: [
        { $ref: "#/$defs/OptimizationFloatParameter" },
        { $ref: "#/$defs/OptimizationIntParameter" },
        { $ref: "#/$defs/OptimizationBooleanParameter" },
      ],
    },
    OptimizationReplicate: convert(petrinautOptimizationReplicateSchema),
    OptimizationDescribeResult: describeResult,
    OptimizationEvaluateResult: evaluateResult,
    ...sharedDefs,
  },
};

const target = join(packageRoot, "schemas/optimization-protocol.schema.json");
await mkdir(dirname(target), { recursive: true });
await writeFile(target, `${JSON.stringify(document, null, 2)}\n`, "utf8");
process.stdout.write(`Wrote ${target}\n`);
