graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hql_ast/index.html">hql-ast</a>]
    1[<a href="../hql_core/index.html">hql-core</a>]
    2[<a href="../error_stack/index.html">error-stack</a>]
    3[<a href="../hql_diagnostics/index.html">hql-diagnostics</a>]
    4[hql-syntax-jexpr]
    class 4 root
    4 --> 0
    0 --> 1
    3 --> 1
    3 --> 2
    4 --> 3