import {
  Resolver,
  User,
} from "../../autoGeneratedTypes";
import { LoggedInGraphQLContext } from "../../context";

export const me: Resolver<
  User,
  {},
  LoggedInGraphQLContext
> = async (_, __, { user }) => user;
