extend = { path = "../../.github/scripts/rust/Makefile.toml" }

[env]
CARGO_MIRI_HACK_FLAGS = "--workspace"
CARGO_DOC_FLAGS = "--no-deps --all-features -Zunstable-options -Zrustdoc-scrape-examples=examples"

# The `test` task will execute these task in the folloing order:
#  1. Run unit tests
#  2. Build the test dependencies (CI only)
#  3. Setup python (CI only)
#  4. Run the integration tests

[tasks.clippy-task]
dependencies = ["install-clippy"]

[tasks.test]
run_task = { name = ["test-task", "run-integrations"] }

[tasks.build-test-deps]
condition = { env_true = ["CARGO_MAKE_CI"] }
private = true
extend = "build-task"
args = ["build", "-p", "memory", "--profile", "${CARGO_MAKE_CARGO_PROFILE}"]

[tasks.setup-python]
condition = { env_true = ["CARGO_MAKE_CI"] }
extend = "bash"
args = ["lib/execution/src/runner/python/setup.sh", "python3.10"]
dependencies = ["build-test-deps"]

[tasks.run-integrations]
private = true
extend = "cargo"
args = ["nextest", "run", "--workspace", "--test", "integration", "--no-fail-fast", "--cargo-profile", "${CARGO_MAKE_CARGO_PROFILE}", "--all-features"]
dependencies = ["install-cargo-nextest", "setup-python"]
