graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hash_graph/index.html">hash-graph</a>]
    1[<a href="../type_system/index.html">type-system</a>]
    2[<a href="../hash_codec/index.html">hash-codec</a>]
    3[<a href="../hash_codegen/index.html">hash-codegen</a>]
    4[<a href="../hash_graph_api/index.html">hash-graph-api</a>]
    5[<a href="../hash_graph_authorization/index.html">hash-graph-authorization</a>]
    6[<a href="../hash_graph_store/index.html">hash-graph-store</a>]
    7[<a href="../hash_graph_temporal_versioning/index.html">hash-graph-temporal-versioning</a>]
    8[<a href="../hash_graph_test_server/index.html">hash-graph-test-server</a>]
    9[<a href="../hash_graph_types/index.html">hash-graph-types</a>]
    10[<a href="../harpc_types/index.html">harpc-types</a>]
    11[<a href="../harpc_wire_protocol/index.html">harpc-wire-protocol</a>]
    12[<a href="../hashql_ast/index.html">hashql-ast</a>]
    13[<a href="../hashql_compiletest/index.html">hashql-compiletest</a>]
    14[<a href="../hashql_core/index.html">hashql-core</a>]
    15[<a href="../hashql_diagnostics/index.html">hashql-diagnostics</a>]
    16[<a href="../hashql_eval/index.html">hashql-eval</a>]
    17[<a href="../hashql_hir/index.html">hashql-hir</a>]
    18[<a href="../hashql_macros/index.html">hashql-macros</a>]
    19[<a href="../hashql_mir/index.html">hashql-mir</a>]
    20[hashql-syntax-jexpr]
    class 20 root
    21[<a href="../hash_temporal_client/index.html">hash-temporal-client</a>]
    22[<a href="../darwin_kperf/index.html">darwin-kperf</a>]
    23[<a href="../darwin_kperf_criterion/index.html">darwin-kperf-criterion</a>]
    24[<a href="../darwin_kperf_events/index.html">darwin-kperf-events</a>]
    25[<a href="../darwin_kperf_sys/index.html">darwin-kperf-sys</a>]
    26[<a href="../error_stack/index.html">error-stack</a>]
    27[<a href="../hash_graph_benches/index.html">hash-graph-benches</a>]
    28[<a href="../hash_graph_test_data/index.html">hash-graph-test-data</a>]
    0 --> 8
    1 --> 7
    1 -.-> 28
    2 -.-> 3
    2 --> 11
    4 --> 16
    4 --> 20
    5 --> 1
    6 --> 5
    6 --> 9
    6 --> 21
    7 --> 2
    8 --> 4
    9 -.-> 28
    11 -.-> 10
    11 --> 10
    11 --> 26
    12 -.-> 13
    13 --> 16
    13 --> 19
    13 --> 20
    13 --> 26
    14 --> 2
    14 --> 15
    14 --> 18
    14 -.-> 23
    16 --> 6
    16 --> 17
    17 -.-> 13
    19 --> 17
    20 --> 12
    20 --> 14
    21 --> 1
    22 --> 24
    22 --> 25
    23 --> 22
    27 -.-> 4
    28 --> 6
