import { VoidFunctionComponent } from "react";
import Link from "next/link";
import { useQuery } from "@apollo/client";

import { getAccountPages } from "../../../graphql/queries/account.queries";
import {
  GetAccountPagesQuery,
  GetAccountPagesQueryVariables,
} from "../../../graphql/autoGeneratedTypes";

import styles from "./PageSidebar.module.scss";
import { CreatePageButton } from "../../Modals/CreatePage/CreatePageButton";

type AccountPageListProps = {
  accountId: string;
  currentPageId: string;
};

export const AccountPageList: VoidFunctionComponent<AccountPageListProps> = ({
  currentPageId,
  accountId,
}) => {
  const { data } = useQuery<
    GetAccountPagesQuery,
    GetAccountPagesQueryVariables
  >(getAccountPages, {
    variables: { accountId },
  });

  return (
    <div className={styles.AccountPageList}>
      {data?.accountPages.map((page) => {
        if (page.id === currentPageId) {
          return <div key={page.id}>{page.properties.title}</div>;
        }
        return (
          <div key={page.id}>
            <Link href={`/${accountId}/${page.id}`}>
              <a>{page.properties.title}</a>
            </Link>
          </div>
        );
      })}
      <CreatePageButton accountId={accountId} />
    </div>
  );
};
