import { VoidFunctionComponent } from "react";
import { useQuery } from "@apollo/client";

import { GetNamespacesQuery } from "../../../graphql/autoGeneratedTypes";
import { getNamespaces } from "../../../graphql/queries/namespace.queries";

import styles from "./PageSidebar.module.scss";

type NamespaceSelectProps = {
  onChange: (namespace: string) => void;
  value: string;
};

export const NamespaceSelect: VoidFunctionComponent<NamespaceSelectProps> = ({
  onChange,
  value,
}) => {
  const { data } = useQuery<GetNamespacesQuery>(getNamespaces);

  return (
    <select
      className={styles.NamespaceSelect}
      onChange={(e) => onChange(e.target.value)}
      value={value}
    >
      {data?.namespaces.map((namespace) => (
        <option key={namespace.id} value={namespace.id}>
          {namespace.properties.shortname}
        </option>
      ))}
    </select>
  );
};
