graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[hash-repo-chores]
    class 0 root
    1[<a href="../hash_telemetry">hash-telemetry</a>]
    2[<a href="../error_stack">error-stack</a>]
    3[<a href="../hash_graph_benches">hash-graph-benches</a>]
    0 --> 1
    1 --> 2
    3 -.-> 0
