import { defineConfig } from "oxfmt";

export default defineConfig({
  // Indentation and line length
  useTabs: false,
  tabWidth: 2,
  printWidth: 80,
  endOfLine: "lf",

  // Quotes
  singleQuote: false,
  jsxSingleQuote: false,
  quoteProps: "as-needed",

  // Syntax
  semi: true,
  trailingComma: "all",
  arrowParens: "always",

  // Brackets and attributes
  bracketSpacing: true,
  bracketSameLine: false,
  singleAttributePerLine: false,

  // Sorting
  sortImports: {
    newlinesBetween: true,
    internalPattern: ["@local/", "@hashintel/", "@blockprotocol/", "@apps/"],
    groups: [
      "value-builtin",
      "value-external",
      "value-internal",
      ["value-parent", "value-sibling", "value-index"],
      [
        "type-import",
        "type-internal",
        "type-parent",
        "type-sibling",
        "type-index",
      ],
      "unknown",
    ],
  },
  sortTailwindcss: true,
  sortPackageJson: {
    sortScripts: true,
  },

  // Per-language overrides
  overrides: [
    {
      files: ["**/*.json", "**/*.jsonc"],
      options: {
        trailingComma: "none",
      },
    },
  ],

  ignorePatterns: [
    // License files have intentional formatting that shouldn't be touched
    "**/LICENSE*.md",
    // While supported, it doesn't yet support the full breadth
    // of taplo configuration options that we have set
    // see: https://github.com/oxc-project/oxc/issues/18580
    "**/*.toml",
    // Autogenerated files
    "**/*.snap.*",
    "**/openapi.json",
    "**/*.aux.mir",
    // The architecture bundle is written by @local/petrinaut-arch-docs, which
    // owns its byte-for-byte output — CI diffs a fresh build against these
    // files to detect drift. Reformatting them here would make every
    // regeneration fail the format check and every format run fail the drift
    // check.
    "libs/@local/petrinaut-arch-docs/bundle/**",
  ],
});
