graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hash_graph/index.html">hash-graph</a>]
    1[<a href="../hash_graph_api/index.html">hash-graph-api</a>]
    2[<a href="../hash_graph_test_server/index.html">hash-graph-test-server</a>]
    3[<a href="../hashql_ast/index.html">hashql-ast</a>]
    4[<a href="../hashql_compiletest/index.html">hashql-compiletest</a>]
    5[<a href="../hashql_core/index.html">hashql-core</a>]
    6[hashql-diagnostics]
    class 6 root
    7[<a href="../hashql_eval/index.html">hashql-eval</a>]
    8[<a href="../hashql_hir/index.html">hashql-hir</a>]
    9[<a href="../hashql_mir/index.html">hashql-mir</a>]
    10[<a href="../hashql_syntax_jexpr/index.html">hashql-syntax-jexpr</a>]
    11[<a href="../hash_graph_benches/index.html">hash-graph-benches</a>]
    0 --> 2
    1 --> 7
    1 --> 10
    2 --> 1
    3 -.-> 4
    4 --> 7
    4 --> 10
    5 --> 6
    7 --> 8
    8 -.-> 4
    9 --> 8
    10 --> 3
    10 --> 5
    11 -.-> 1
