graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hash_graph/index.html">hash-graph</a>]
    1[<a href="../type_system/index.html">type-system</a>]
    2[<a href="../hash_codec/index.html">hash-codec</a>]
    3[<a href="../hash_codegen/index.html">hash-codegen</a>]
    4[<a href="../hash_graph_api/index.html">hash-graph-api</a>]
    5[<a href="../hash_graph_authorization/index.html">hash-graph-authorization</a>]
    6[<a href="../hash_graph_migrations/index.html">hash-graph-migrations</a>]
    7[<a href="../hash_graph_migrations_macros/index.html">hash-graph-migrations-macros</a>]
    8[hash-graph-postgres-queries]
    class 8 root
    9[<a href="../hash_graph_postgres_store/index.html">hash-graph-postgres-store</a>]
    10[<a href="../hash_graph_store/index.html">hash-graph-store</a>]
    11[<a href="../hash_graph_temporal_versioning/index.html">hash-graph-temporal-versioning</a>]
    12[<a href="../hash_graph_test_server/index.html">hash-graph-test-server</a>]
    13[<a href="../hash_graph_types/index.html">hash-graph-types</a>]
    14[<a href="../harpc_types/index.html">harpc-types</a>]
    15[<a href="../harpc_wire_protocol/index.html">harpc-wire-protocol</a>]
    16[<a href="../hash_telemetry/index.html">hash-telemetry</a>]
    17[<a href="../hash_temporal_client/index.html">hash-temporal-client</a>]
    18[<a href="../error_stack/index.html">error-stack</a>]
    19[<a href="../hash_graph_benches/index.html">hash-graph-benches</a>]
    20[<a href="../hash_graph_integration/index.html">hash-graph-integration</a>]
    21[<a href="../hash_graph_test_data/index.html">hash-graph-test-data</a>]
    0 --> 12
    1 --> 11
    1 -.-> 21
    2 -.-> 3
    2 --> 15
    4 --> 9
    5 --> 1
    6 --> 7
    6 --> 16
    8 --> 5
    8 -.-> 6
    9 --> 8
    9 --> 10
    10 --> 5
    10 --> 13
    10 --> 17
    11 --> 2
    12 --> 4
    13 -.-> 21
    15 -.-> 14
    15 --> 14
    15 --> 18
    16 --> 18
    17 --> 1
    19 -.-> 4
    20 -.-> 9
    21 --> 10
