use error_stack::{Report, ResultExt};
use harpc_client::{connection::Connection, utils::invoke_call_discrete};
use harpc_codec::{decode::ReportDecoder, encode::Encoder};
use harpc_server::{
    error::DelegationError,
    session::Session,
    utils::{delegate_call_discrete, parse_procedure_id},
};
use harpc_service::{delegate::ServiceDelegate, role::Role};
use harpc_tower::{body::Body, request::Request, response::Response};
use harpc_types::response_kind::ResponseKind;

use super::{role, session::User};

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, derive_more::Display, derive_more::Error)]
#[display("unable to fullfil ping request")]
pub struct PingError;

pub trait PingService<R>
where
    R: Role,
{
    async fn ping(
        &self,
        session: R::Session,
        payload: Box<str>,
    ) -> Result<Box<str>, Report<PingError>>;
}

// TODO: this can be auto generated by the `harpc` crate
pub mod meta {
    //! The `meta` module contains the metadata for the ping service.
    //! In the future this will be automatically generated by the `harpc` crate.

    use frunk::HList;
    use harpc_service::{
        Service,
        metadata::Metadata,
        procedure::{Procedure, ProcedureIdentifier},
    };
    use harpc_types::{procedure::ProcedureId, service::ServiceId, version::Version};

    pub enum PingProcedureId {
        Ping,
    }

    impl ProcedureIdentifier for PingProcedureId {
        type Service = PingService;

        fn from_id(id: ProcedureId) -> Option<Self> {
            match id.value() {
                0x00 => Some(Self::Ping),
                _ => None,
            }
        }

        fn into_id(self) -> ProcedureId {
            match self {
                Self::Ping => ProcedureId::new(0x00),
            }
        }
    }

    pub struct PingService;

    impl Service for PingService {
        type ProcedureId = PingProcedureId;
        type Procedures = HList![ProcedurePing];

        const ID: ServiceId = ServiceId::new(0x02);
        const VERSION: Version = Version {
            major: 0x00,
            minor: 0x00,
        };

        fn metadata() -> Metadata {
            Metadata {
                since: Version {
                    major: 0x00,
                    minor: 0x00,
                },
                deprecation: None,
            }
        }
    }

    pub struct ProcedurePing;

    impl Procedure for ProcedurePing {
        type Service = PingService;

        const ID: <Self::Service as Service>::ProcedureId = PingProcedureId::Ping;

        fn metadata() -> Metadata {
            Metadata {
                since: Version {
                    major: 0x00,
                    minor: 0x00,
                },
                deprecation: None,
            }
        }
    }
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub struct PingServer;

impl PingService<role::Server> for PingServer {
    async fn ping(
        &self,
        _: Session<User>,
        payload: Box<str>,
    ) -> Result<Box<str>, Report<PingError>> {
        Ok(payload)
    }
}

// TODO: this can be auto generated by the `harpc` crate
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub struct PingDelegate<T> {
    inner: T,
}

impl<T> PingDelegate<T> {
    pub const fn new(inner: T) -> Self {
        Self { inner }
    }
}

impl<T, C> ServiceDelegate<Session<User>, C> for PingDelegate<T>
where
    T: PingService<role::Server, ping(..): Send> + Send,
    C: Encoder + ReportDecoder + Clone + Send,
{
    type Error = Report<DelegationError>;
    type Service = meta::PingService;

    type Body<Source>
        = impl Body<Control: AsRef<ResponseKind>, Error = <C as Encoder>::Error>
    where
        Source: Body<Control = !, Error: Send + Sync> + Send + Sync;

    async fn call<B>(
        self,
        request: Request<B>,
        session: Session<User>,
        codec: C,
    ) -> Result<Response<Self::Body<B>>, Self::Error>
    where
        B: Body<Control = !, Error: Send + Sync> + Send + Sync,
    {
        let id = parse_procedure_id(&request)?;

        match id {
            meta::PingProcedureId::Ping => {
                delegate_call_discrete(request, codec, |payload| async move {
                    self.inner.ping(session, payload).await
                })
                .await
            }
        }
    }
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub struct PingClient;

impl<Svc, C> PingService<role::Client<Svc, C>> for PingClient
where
    Svc: harpc_client::connection::ConnectionService<C>,
    C: harpc_client::connection::ConnectionCodec,
{
    async fn ping(
        &self,
        session: Connection<Svc, C>,
        payload: Box<str>,
    ) -> Result<Box<str>, Report<PingError>> {
        invoke_call_discrete(session, meta::PingProcedureId::Ping, [payload])
            .await
            .change_context(PingError)
    }
}
