import { SNAP_GRID_SIZE } from "../constants/ui";
import type { SDCPN } from "../core/types/sdcpn";

export const supplyChainSDCPN: { title: string; petriNetDefinition: SDCPN } = {
  title: "Drug Production",
  petriNetDefinition: {
    places: [
      {
        id: "place__0",
        name: "PlantASupply",
        colorId: null,
        dynamicsEnabled: false,
        differentialEquationId: null,
        x: SNAP_GRID_SIZE,
        y: 8 * SNAP_GRID_SIZE,
      },
      {
        id: "place__1",
        name: "PlantBSupply",
        colorId: null,
        dynamicsEnabled: false,
        differentialEquationId: null,
        x: SNAP_GRID_SIZE,
        y: 40 * SNAP_GRID_SIZE,
      },
      {
        id: "place__2",
        name: "ManufacturingPlant",
        colorId: null,
        dynamicsEnabled: false,
        differentialEquationId: null,
        x: 20 * SNAP_GRID_SIZE,
        y: 20 * SNAP_GRID_SIZE,
      },
      {
        id: "place__3",
        name: "QAQueue",
        colorId: null,
        dynamicsEnabled: false,
        differentialEquationId: null,
        x: 47 * SNAP_GRID_SIZE,
        y: 23 * SNAP_GRID_SIZE,
      },
      {
        id: "place__4",
        name: "Disposal",
        colorId: null,
        dynamicsEnabled: false,
        differentialEquationId: null,
        x: 73 * SNAP_GRID_SIZE,
        y: 40 * SNAP_GRID_SIZE,
      },
      {
        id: "place__5",
        name: "Dispatch",
        colorId: null,
        dynamicsEnabled: false,
        differentialEquationId: null,
        x: 67 * SNAP_GRID_SIZE,
        y: 13 * SNAP_GRID_SIZE,
      },
      {
        id: "place__6",
        name: "Hospital",
        colorId: null,
        dynamicsEnabled: false,
        differentialEquationId: null,
        x: 87 * SNAP_GRID_SIZE,
        y: 25 * SNAP_GRID_SIZE,
      },
    ],
    transitions: [
      {
        id: "transition__0",
        name: "Deliver to Plant",
        inputArcs: [
          { placeId: "place__0", weight: 1 },
          { placeId: "place__1", weight: 1 },
        ],
        outputArcs: [{ placeId: "place__2", weight: 1 }],
        lambdaType: "predicate",
        lambdaCode: "export default Lambda(() => true);",
        transitionKernelCode: "",
        x: 7 * SNAP_GRID_SIZE,
        y: 27 * SNAP_GRID_SIZE,
      },
      {
        id: "transition__1",
        name: "Manufacture",
        inputArcs: [{ placeId: "place__2", weight: 1 }],
        outputArcs: [{ placeId: "place__3", weight: 1 }],
        lambdaType: "predicate",
        lambdaCode: "export default Lambda(() => true);",
        transitionKernelCode: "",
        x: 33 * SNAP_GRID_SIZE,
        y: 23 * SNAP_GRID_SIZE,
      },
      {
        id: "transition__2",
        name: "Quality Check",
        inputArcs: [{ placeId: "place__3", weight: 1 }],
        outputArcs: [
          { placeId: "place__5", weight: 1 },
          { placeId: "place__4", weight: 1 },
        ],
        lambdaType: "predicate",
        lambdaCode: "export default Lambda(() => true);",
        transitionKernelCode: "",
        x: 58 * SNAP_GRID_SIZE,
        y: 27 * SNAP_GRID_SIZE,
      },
      {
        id: "transition__3",
        name: "Ship",
        inputArcs: [{ placeId: "place__5", weight: 1 }],
        outputArcs: [{ placeId: "place__6", weight: 1 }],
        lambdaType: "predicate",
        lambdaCode: "export default Lambda(() => true);",
        transitionKernelCode: "",
        x: 77 * SNAP_GRID_SIZE,
        y: 19 * SNAP_GRID_SIZE,
      },
    ],
    types: [],
    differentialEquations: [],
    parameters: [],
  },
};
