import type { SDCPN } from "../core/types/sdcpn";

export const supplyChainStochasticSDCPN: {
  title: string;
  petriNetDefinition: SDCPN;
} = {
  title: "Drug Production (Stochastic)",
  petriNetDefinition: {
    places: [
      {
        id: "place__0",
        name: "PlantASupply",
        colorId: null,
        dynamicsEnabled: false,
        differentialEquationId: null,
        x: 20,
        y: 120,
      },
      {
        id: "place__1",
        name: "PlantBSupply",
        colorId: null,
        dynamicsEnabled: false,
        differentialEquationId: null,
        x: 20,
        y: 600,
      },
      {
        id: "place__2",
        name: "ManufacturingPlant",
        colorId: null,
        dynamicsEnabled: false,
        differentialEquationId: null,
        x: 300,
        y: 300,
      },
      {
        id: "place__3",
        name: "QAQueue",
        colorId: null,
        dynamicsEnabled: false,
        differentialEquationId: null,
        x: 700,
        y: 350,
      },
      {
        id: "place__4",
        name: "Disposal",
        colorId: null,
        dynamicsEnabled: false,
        differentialEquationId: null,
        x: 1100,
        y: 600,
      },
      {
        id: "place__5",
        name: "Dispatch",
        colorId: null,
        dynamicsEnabled: false,
        differentialEquationId: null,
        x: 1000,
        y: 200,
      },
      {
        id: "place__6",
        name: "Hospital",
        colorId: null,
        dynamicsEnabled: false,
        differentialEquationId: null,
        x: 1300,
        y: 380,
      },
    ],
    transitions: [
      {
        id: "transition__0",
        name: "Deliver to Plant",
        inputArcs: [
          { placeId: "place__0", weight: 1 },
          { placeId: "place__1", weight: 1 },
        ],
        outputArcs: [{ placeId: "place__2", weight: 1 }],
        lambdaType: "stochastic",
        lambdaCode: "export default Lambda(() => 1);",
        transitionKernelCode: "",
        x: 100,
        y: 400,
      },
      {
        id: "transition__1",
        name: "Manufacture",
        inputArcs: [{ placeId: "place__2", weight: 1 }],
        outputArcs: [{ placeId: "place__3", weight: 1 }],
        lambdaType: "stochastic",
        lambdaCode: "export default Lambda(() => 1);",
        transitionKernelCode: "",
        x: 490,
        y: 350,
      },
      {
        id: "transition__2",
        name: "Quality Check",
        inputArcs: [{ placeId: "place__3", weight: 1 }],
        outputArcs: [
          { placeId: "place__5", weight: 1 },
          { placeId: "place__4", weight: 1 },
        ],
        lambdaType: "stochastic",
        lambdaCode: "export default Lambda(() => 1 / 2);",
        transitionKernelCode: "",
        x: 870,
        y: 400,
      },
      {
        id: "transition__3",
        name: "Ship",
        inputArcs: [{ placeId: "place__5", weight: 1 }],
        outputArcs: [{ placeId: "place__6", weight: 1 }],
        lambdaType: "stochastic",
        lambdaCode: "export default Lambda(() => 1 / 3);",
        transitionKernelCode: "",
        x: 1150,
        y: 280,
      },
    ],
    types: [],
    differentialEquations: [],
    parameters: [],
  },
};
