services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    shm_size: 4g
    command:
      - postgres
      - -c
      - shared_buffers=2GB
      - -c
      - work_mem=256MB
      - -c
      - maintenance_work_mem=1GB
      - -c
      - max_connections=100

volumes:
  pgdata:
