import { Resolver } from "../../autoGeneratedTypes";
import { DbOrg, DbUser } from "../../../types/dbTypes";
import { entities } from "../../../mockData/entities";

export const namespaces: Resolver<Promise<(DbUser | DbOrg)[]>> = async () => {
  const dbNamespaces = (await entities.filter(
    (entity) => entity.type === "User" || entity.type === "Org"
  )) as (DbUser | DbOrg)[];

  return dbNamespaces;
};
