import { checkLowerable } from "./lower-petri-net-ir/check-lowerable";
import { lowerClocks } from "./lower-petri-net-ir/lower-clocks";
import { lowerModular } from "./lower-petri-net-ir/lower-modular";
import { lowerMonolithic } from "./lower-petri-net-ir/lower-monolithic";
import { type CodeParser, planStep } from "./lower-petri-net-ir/step-plan";
import { type PetriNetIr, resolveZerothTarget } from "./petri-net-ir";

import type { ReactiveModuleGraph } from "./reactive-module-graph";
import type { PetriNetIrDiagnostic } from "./sdcpn-to-petri-net-ir";
import type { SpnModuleGraph } from "./spn-module-graph";

/**
 * Lowers a Petri net IR to a module graph in the shape its `zeroth` flags
 * ask for: a reactive module graph in a linear theory under coin rates, an
 * SPN module graph under clock rates. The graph carries no target syntax;
 * an emitter turns it into a file. A construct the lowering cannot express
 * is refused per item, with the IR left intact for the reader.
 */

export type LowerPetriNetIrOptions = {
  /** Named in the file's header as where the net came from. */
  source?: string;
  /**
   * Reads the document's code strings back into HIR. Without one, a
   * document that carries code is refused with `code-not-parsed`.
   */
  parseCode?: CodeParser;
};

/** What a lowering produces: the graph of a linear theory, or of the SPN theory. */
export type LoweredGraph = ReactiveModuleGraph | SpnModuleGraph;

export type LowerPetriNetIrOutcome =
  | { ok: true; graph: LoweredGraph; warnings: PetriNetIrDiagnostic[] }
  | {
      ok: false;
      errors: PetriNetIrDiagnostic[];
      warnings: PetriNetIrDiagnostic[];
    };

const noParser: CodeParser = () => undefined;

export const lowerPetriNetIr = (
  ir: PetriNetIr,
  options: LowerPetriNetIrOptions = {},
): LowerPetriNetIrOutcome => {
  const target = resolveZerothTarget(ir.zeroth);
  const errors = checkLowerable(ir, target);
  const warnings: PetriNetIrDiagnostic[] = [];
  const parse = options.parseCode ?? noParser;
  const origin = options.source === undefined ? "" : ` from ${options.source}`;
  const header = `${ir.name}: generated by Petrinaut${origin}. Do not edit.`;
  if (target.rates === "clock") {
    if (target.control === "open") {
      warnings.push({
        code: "control-open-clocks",
        message:
          "the clocks strategy takes no external choice; the open control flag is ignored",
        item: { kind: "net", id: "net", name: ir.name },
      });
    }
    if (errors.length > 0) {
      return { ok: false, errors, warnings };
    }
    const plan = planStep(ir, target, parse, errors);
    return errors.length > 0
      ? { ok: false, errors, warnings }
      : { ok: true, graph: lowerClocks(plan, header), warnings };
  }
  const plan = planStep(ir, target, parse, errors);
  if (plan.coloured && plan.stochastic && target.marking === "int") {
    warnings.push({
      code: "marking-int-coloured",
      message:
        "a coloured net is lowered in LRA, so its marking is Real; the int flag is ignored",
      item: { kind: "net", id: "net", name: ir.name },
    });
  }
  if (errors.length > 0) {
    return { ok: false, errors, warnings };
  }
  const lowered =
    target.shape === "modular"
      ? lowerModular(plan, header)
      : lowerMonolithic(plan, ir.name, header, errors);
  return errors.length > 0
    ? { ok: false, errors, warnings }
    : { ok: true, graph: lowered, warnings };
};

export {
  describeName,
  type NameDescription,
  type NameSource,
} from "./lower-petri-net-ir/shared/describe-name";
