import { describe, expect, it } from "vitest";

import {
  compilePetriNetIr,
  petriNetIrToReactiveModule,
} from "./petri-net-ir-to-reactive-module";

import type { PetriNetIr } from "./petri-net-ir";

const cycle: PetriNetIr = {
  name: "cycle",
  kind: "plain",
  places: { A: null, B: null },
  marking: { A: 1 },
  transitions: {
    Go: { inputs: { A: null }, outputs: { B: null } },
    Back: { inputs: { B: null }, outputs: { A: null } },
  },
};

const capacity: PetriNetIr = {
  name: "capacity",
  kind: "plain",
  places: {
    LeftSource: null,
    RightSource: null,
    Buffer: { capacity: 2 },
    Sink: null,
  },
  marking: { LeftSource: 5, RightSource: 5 },
  transitions: {
    PutLeft: { inputs: { LeftSource: null }, outputs: { Buffer: null } },
    PutRight: { inputs: { RightSource: null }, outputs: { Buffer: null } },
    Take: { inputs: { Buffer: null }, outputs: { Sink: null } },
  },
};

const queue: PetriNetIr = {
  name: "queue",
  kind: "stochastic",
  places: { Waiting: { capacity: 4 }, Served: null },
  transitions: {
    Arrive: { outputs: { Waiting: null }, rate: 2.5 },
    Serve: { inputs: { Waiting: null }, outputs: { Served: null }, rate: 3 },
  },
  zeroth: { dt: 0.5 },
};

const conflict: PetriNetIr = {
  name: "conflict",
  kind: "plain",
  places: { Pool: null, Left: null, Right: null },
  marking: { Pool: 3 },
  transitions: {
    TakeLeft: {
      inputs: { Pool: { weight: 2 } },
      outputs: { Left: null },
      controllable: true,
    },
    TakeRight: { inputs: { Pool: null }, outputs: { Right: null } },
  },
};

describe("petriNetIrToReactiveModule", () => {
  it("lowers a plain net to an LIA module with one Petrinaut step per update", () => {
    expect(petriNetIrToReactiveModule(cycle, { source: "cycle.pn.yaml" })).toBe(
      `"""cycle: generated by Petrinaut from cycle.pn.yaml. Do not edit."""

from zrth import LIA, Int, Var
from zrth.sugar import Module, ite

INT = Int([1, 1])

A = Var(INT)
B = Var(INT)


class Cycle(Module):
    """Plain Petri net with 2 places and 2 transitions. One update is one Petrinaut step."""

    def init(self):
        return 1, 0

    def update(self, A, B):
        # sweep in order; a firing consumes its input tokens at once
        fire_Go = A >= 1  # Go: A -> B
        A = ite(fire_Go, A - 1, A)
        fire_Back = B >= 1  # Back: B -> A
        B = ite(fire_Back, B - 1, B)
        # end of step: produced tokens land
        A = ite(fire_Back, A + 1, A)
        B = ite(fire_Go, B + 1, B)
        return A, B


net = Cycle(theory=LIA, ctrl=(A, B))
`,
    );
  });

  it("tracks a capped place's pending fill so a later producer sees an earlier one", () => {
    expect(petriNetIrToReactiveModule(capacity)).toBe(
      `"""capacity: generated by Petrinaut. Do not edit."""

from zrth import LIA, Int, Var
from zrth.sugar import Module, ite

INT = Int([1, 1])

LeftSource = Var(INT)
RightSource = Var(INT)
Buffer = Var(INT)
Sink = Var(INT)


class Capacity(Module):
    """Plain Petri net with 4 places and 3 transitions. One update is one Petrinaut step."""

    def init(self):
        return 5, 5, 0, 0

    def update(self, LeftSource, RightSource, Buffer, Sink):
        # tokens a capped place would hold if the step ended now
        fill_Buffer = Buffer
        # sweep in order; a firing consumes its input tokens at once
        fire_PutLeft = (LeftSource >= 1) & (fill_Buffer + 1 <= 2)  # PutLeft: LeftSource -> Buffer
        LeftSource = ite(fire_PutLeft, LeftSource - 1, LeftSource)
        fill_Buffer = ite(fire_PutLeft, fill_Buffer + 1, fill_Buffer)
        fire_PutRight = (RightSource >= 1) & (fill_Buffer + 1 <= 2)  # PutRight: RightSource -> Buffer
        RightSource = ite(fire_PutRight, RightSource - 1, RightSource)
        fill_Buffer = ite(fire_PutRight, fill_Buffer + 1, fill_Buffer)
        fire_Take = Buffer >= 1  # Take: Buffer -> Sink
        Buffer = ite(fire_Take, Buffer - 1, Buffer)
        fill_Buffer = ite(fire_Take, fill_Buffer - 1, fill_Buffer)
        # end of step: produced tokens land
        Sink = ite(fire_Take, Sink + 1, Sink)
        return LeftSource, RightSource, fill_Buffer, Sink


net = Capacity(theory=LIA, ctrl=(LeftSource, RightSource, Buffer, Sink))
`,
    );
  });

  it("tests a stochastic transition against an external draw over dt", () => {
    const arrive = Math.exp(-2.5 * 0.5);
    const serve = Math.exp(-3 * 0.5);
    expect(petriNetIrToReactiveModule(queue)).toBe(
      `"""queue: generated by Petrinaut. Do not edit."""

from zrth import LRA, Real, Var
from zrth.sugar import Module, X, ite

REAL = Real([1, 1])

Waiting = Var(REAL)
Served = Var(REAL)

u_Arrive = Var(REAL)  # uniform draw for Arrive, each step
u_Serve = Var(REAL)  # uniform draw for Serve, each step


class Queue(Module):
    """Stochastic Petri net with 2 places and 2 transitions, dt = 0.5. One update is one Petrinaut step."""

    def init(self, u_Arrive, u_Serve):
        return 0.0, 0.0

    def update(self, Waiting, Served, u_Arrive, u_Serve):
        # tokens a capped place would hold if the step ended now
        fill_Waiting = Waiting
        # sweep in order; a firing consumes its input tokens at once
        fire_Arrive = (fill_Waiting + 1.0 <= 4.0) & (X(u_Arrive) >= ${arrive})  # Arrive: nothing -> Waiting
        fill_Waiting = ite(fire_Arrive, fill_Waiting + 1.0, fill_Waiting)
        fire_Serve = (Waiting >= 1.0) & (X(u_Serve) >= ${serve})  # Serve: Waiting -> Served
        Waiting = ite(fire_Serve, Waiting - 1.0, Waiting)
        fill_Waiting = ite(fire_Serve, fill_Waiting - 1.0, fill_Waiting)
        # end of step: produced tokens land
        Served = ite(fire_Serve, Served + 1.0, Served)
        return fill_Waiting, Served


net = Queue(theory=LRA, ctrl=(Waiting, Served), extl=(u_Arrive, u_Serve))
`,
    );
  });

  it("composes one module per transition and per place in the modular shape", () => {
    expect(
      petriNetIrToReactiveModule(
        { ...cycle, zeroth: { shape: "modular" } },
        { source: "cycle.pn.yaml" },
      ),
    ).toBe(
      `"""cycle: generated by Petrinaut from cycle.pn.yaml. Do not edit."""

from zrth import LIA, Bool, Int, Var
from zrth import Module as compose
from zrth.sugar import Module, X, ite

INT = Int([1, 1])
BOOL = Bool([1, 1])

A = Var(INT)
B = Var(INT)

fire_Go = Var(BOOL)  # Go fires this step
fire_Back = Var(BOOL)  # Back fires this step


class Transition_Go(Module):
    """Go: A -> B"""

    def init(self, A):
        return False

    def update(self, fire_Go, A):
        return A >= 1


class Transition_Back(Module):
    """Back: B -> A"""

    def init(self, B):
        return False

    def update(self, fire_Back, B):
        return B >= 1


class Place_A(Module):
    """A: taken by Go, added by Back"""

    def init(self, fire_Go, fire_Back):
        return 1

    def update(self, A, fire_Go, fire_Back):
        A = ite(X(fire_Go), A - 1, A)  # Go takes 1
        A = ite(X(fire_Back), A + 1, A)  # Back adds 1
        return A


class Place_B(Module):
    """B: taken by Back, added by Go"""

    def init(self, fire_Go, fire_Back):
        return 0

    def update(self, B, fire_Go, fire_Back):
        B = ite(X(fire_Go), B + 1, B)  # Go adds 1
        B = ite(X(fire_Back), B - 1, B)  # Back takes 1
        return B


transition_Go = Transition_Go(theory=LIA, ctrl=(fire_Go,), extl=(A,))
transition_Back = Transition_Back(theory=LIA, ctrl=(fire_Back,), extl=(B,))
place_A = Place_A(theory=LIA, ctrl=(A,), extl=(fire_Go, fire_Back))
place_B = Place_B(theory=LIA, ctrl=(B,), extl=(fire_Go, fire_Back))
net = compose(transition_Go, transition_Back, place_A, place_B)
`,
    );
  });

  it("has a later producer of a capped place await the earlier transitions that move its tokens", () => {
    expect(
      petriNetIrToReactiveModule(
        { ...capacity, zeroth: { shape: "modular" } },
        { source: "capacity.pn.yaml" },
      ),
    ).toBe(
      `"""capacity: generated by Petrinaut from capacity.pn.yaml. Do not edit."""

from zrth import LIA, Bool, Int, Var
from zrth import Module as compose
from zrth.sugar import Module, X, ite

INT = Int([1, 1])
BOOL = Bool([1, 1])

LeftSource = Var(INT)
RightSource = Var(INT)
Buffer = Var(INT)
Sink = Var(INT)

fire_PutLeft = Var(BOOL)  # PutLeft fires this step
fire_PutRight = Var(BOOL)  # PutRight fires this step
fire_Take = Var(BOOL)  # Take fires this step


class Transition_PutLeft(Module):
    """PutLeft: LeftSource -> Buffer"""

    def init(self, LeftSource, Buffer):
        return False

    def update(self, fire_PutLeft, LeftSource, Buffer):
        return (LeftSource >= 1) & (Buffer + 1 <= 2)


class Transition_PutRight(Module):
    """PutRight: RightSource -> Buffer"""

    def init(self, RightSource, Buffer, fire_PutLeft):
        return False

    def update(self, fire_PutRight, RightSource, Buffer, fire_PutLeft):
        fill_Buffer = Buffer
        fill_Buffer = ite(X(fire_PutLeft), fill_Buffer + 1, fill_Buffer)  # PutLeft added 1
        return (RightSource >= 1) & (fill_Buffer + 1 <= 2)


class Transition_Take(Module):
    """Take: Buffer -> Sink"""

    def init(self, Buffer):
        return False

    def update(self, fire_Take, Buffer):
        return Buffer >= 1


class Place_LeftSource(Module):
    """LeftSource: taken by PutLeft"""

    def init(self, fire_PutLeft):
        return 5

    def update(self, LeftSource, fire_PutLeft):
        LeftSource = ite(X(fire_PutLeft), LeftSource - 1, LeftSource)  # PutLeft takes 1
        return LeftSource


class Place_RightSource(Module):
    """RightSource: taken by PutRight"""

    def init(self, fire_PutRight):
        return 5

    def update(self, RightSource, fire_PutRight):
        RightSource = ite(X(fire_PutRight), RightSource - 1, RightSource)  # PutRight takes 1
        return RightSource


class Place_Buffer(Module):
    """Buffer: taken by Take, added by PutLeft, PutRight"""

    def init(self, fire_PutLeft, fire_PutRight, fire_Take):
        return 0

    def update(self, Buffer, fire_PutLeft, fire_PutRight, fire_Take):
        Buffer = ite(X(fire_PutLeft), Buffer + 1, Buffer)  # PutLeft adds 1
        Buffer = ite(X(fire_PutRight), Buffer + 1, Buffer)  # PutRight adds 1
        Buffer = ite(X(fire_Take), Buffer - 1, Buffer)  # Take takes 1
        return Buffer


class Place_Sink(Module):
    """Sink: added by Take"""

    def init(self, fire_Take):
        return 0

    def update(self, Sink, fire_Take):
        Sink = ite(X(fire_Take), Sink + 1, Sink)  # Take adds 1
        return Sink


transition_PutLeft = Transition_PutLeft(theory=LIA, ctrl=(fire_PutLeft,), extl=(LeftSource, Buffer))
transition_PutRight = Transition_PutRight(theory=LIA, ctrl=(fire_PutRight,), extl=(RightSource, Buffer, fire_PutLeft))
transition_Take = Transition_Take(theory=LIA, ctrl=(fire_Take,), extl=(Buffer,))
place_LeftSource = Place_LeftSource(theory=LIA, ctrl=(LeftSource,), extl=(fire_PutLeft,))
place_RightSource = Place_RightSource(theory=LIA, ctrl=(RightSource,), extl=(fire_PutRight,))
place_Buffer = Place_Buffer(theory=LIA, ctrl=(Buffer,), extl=(fire_PutLeft, fire_PutRight, fire_Take))
place_Sink = Place_Sink(theory=LIA, ctrl=(Sink,), extl=(fire_Take,))
net = compose(
    transition_PutLeft,
    transition_PutRight,
    transition_Take,
    place_LeftSource,
    place_RightSource,
    place_Buffer,
    place_Sink,
)
`,
    );
  });

  it("keeps Int places under marking int by moving each draw test into an LRA module", () => {
    expect(
      petriNetIrToReactiveModule(
        { ...queue, zeroth: { shape: "modular", marking: "int", dt: 0.5 } },
        { source: "queue.pn.yaml" },
      ),
    ).toBe(
      `"""queue: generated by Petrinaut from queue.pn.yaml. Do not edit."""

from zrth import LIA, LRA, Bool, Int, Real, Var
from zrth import Module as compose
from zrth.sugar import Module, X, ite

INT = Int([1, 1])
REAL = Real([1, 1])
BOOL = Bool([1, 1])

Waiting = Var(INT)
Served = Var(INT)

u_Arrive = Var(REAL)  # uniform draw for Arrive, each step
u_Serve = Var(REAL)  # uniform draw for Serve, each step

hit_Arrive = Var(BOOL)  # Arrive's draw passed its threshold
hit_Serve = Var(BOOL)  # Serve's draw passed its threshold
fire_Arrive = Var(BOOL)  # Arrive fires this step
fire_Serve = Var(BOOL)  # Serve fires this step


class Draw_Arrive(Module):
    """Arrive at rate 2.5 fires within a step of dt = 0.5 when its draw is at least e^(-2.5 * 0.5)"""

    def init(self, u_Arrive):
        return False

    def update(self, hit_Arrive, u_Arrive):
        return X(u_Arrive) >= 0.2865047968601901


class Draw_Serve(Module):
    """Serve at rate 3 fires within a step of dt = 0.5 when its draw is at least e^(-3 * 0.5)"""

    def init(self, u_Serve):
        return False

    def update(self, hit_Serve, u_Serve):
        return X(u_Serve) >= 0.22313016014842982


class Transition_Arrive(Module):
    """Arrive: nothing -> Waiting, at rate 2.5"""

    def init(self, Waiting, hit_Arrive):
        return False

    def update(self, fire_Arrive, Waiting, hit_Arrive):
        return (Waiting + 1 <= 4) & X(hit_Arrive)


class Transition_Serve(Module):
    """Serve: Waiting -> Served, at rate 3"""

    def init(self, Waiting, hit_Serve):
        return False

    def update(self, fire_Serve, Waiting, hit_Serve):
        return (Waiting >= 1) & X(hit_Serve)


class Place_Waiting(Module):
    """Waiting: taken by Serve, added by Arrive"""

    def init(self, fire_Arrive, fire_Serve):
        return 0

    def update(self, Waiting, fire_Arrive, fire_Serve):
        Waiting = ite(X(fire_Arrive), Waiting + 1, Waiting)  # Arrive adds 1
        Waiting = ite(X(fire_Serve), Waiting - 1, Waiting)  # Serve takes 1
        return Waiting


class Place_Served(Module):
    """Served: added by Serve"""

    def init(self, fire_Serve):
        return 0

    def update(self, Served, fire_Serve):
        Served = ite(X(fire_Serve), Served + 1, Served)  # Serve adds 1
        return Served


draw_Arrive = Draw_Arrive(theory=LRA, ctrl=(hit_Arrive,), extl=(u_Arrive,))
draw_Serve = Draw_Serve(theory=LRA, ctrl=(hit_Serve,), extl=(u_Serve,))
transition_Arrive = Transition_Arrive(theory=LIA, ctrl=(fire_Arrive,), extl=(Waiting, hit_Arrive))
transition_Serve = Transition_Serve(theory=LIA, ctrl=(fire_Serve,), extl=(Waiting, hit_Serve))
place_Waiting = Place_Waiting(theory=LIA, ctrl=(Waiting,), extl=(fire_Arrive, fire_Serve))
place_Served = Place_Served(theory=LIA, ctrl=(Served,), extl=(fire_Serve,))
net = compose(
    draw_Arrive,
    draw_Serve,
    transition_Arrive,
    transition_Serve,
    place_Waiting,
    place_Served,
)
`,
    );
  });

  it("composes the monolithic step module with the draw modules under marking int", () => {
    const python = petriNetIrToReactiveModule({
      ...queue,
      zeroth: { marking: "int", dt: 0.5 },
    });
    expect(python).toContain("Waiting = Var(INT)\n");
    expect(python).toContain(
      'class Draw_Arrive(Module):\n    """Arrive at rate 2.5 fires within a step of dt = 0.5 when its draw is at least e^(-2.5 * 0.5)"""',
    );
    expect(python).toContain(
      "        fire_Arrive = (fill_Waiting + 1 <= 4) & X(hit_Arrive)  # Arrive: nothing -> Waiting\n",
    );
    expect(python).toContain(
      "marking = Queue(theory=LIA, ctrl=(Waiting, Served), extl=(hit_Arrive, hit_Serve))\nnet = compose(draw_Arrive, draw_Serve, marking)\n",
    );
  });

  it("opens a controllable transition to an external choice under control open", () => {
    expect(
      petriNetIrToReactiveModule(
        { ...conflict, zeroth: { control: "open" } },
        { source: "conflict.pn.yaml" },
      ),
    ).toBe(
      `"""conflict: generated by Petrinaut from conflict.pn.yaml. Do not edit."""

from zrth import LIA, Bool, Int, Var
from zrth.sugar import Module, X, ite

INT = Int([1, 1])
BOOL = Bool([1, 1])

Pool = Var(INT)
Left = Var(INT)
Right = Var(INT)

go_TakeLeft = Var(BOOL)  # choice for TakeLeft, each step: it fires only when chosen


class Conflict(Module):
    """Plain Petri net with 3 places and 2 transitions. One update is one Petrinaut step."""

    def init(self, go_TakeLeft):
        return 3, 0, 0

    def update(self, Pool, Left, Right, go_TakeLeft):
        # sweep in order; a firing consumes its input tokens at once
        fire_TakeLeft = (Pool >= 2) & X(go_TakeLeft)  # TakeLeft: 2 Pool -> Left
        Pool = ite(fire_TakeLeft, Pool - 2, Pool)
        fire_TakeRight = Pool >= 1  # TakeRight: Pool -> Right
        Pool = ite(fire_TakeRight, Pool - 1, Pool)
        # end of step: produced tokens land
        Left = ite(fire_TakeLeft, Left + 1, Left)
        Right = ite(fire_TakeRight, Right + 1, Right)
        return Pool, Left, Right


net = Conflict(theory=LIA, ctrl=(Pool, Left, Right), extl=(go_TakeLeft,))
`,
    );
    expect(
      petriNetIrToReactiveModule({
        ...conflict,
        zeroth: { shape: "modular", control: "open" },
      }),
    ).toContain(
      "    def update(self, fire_TakeLeft, Pool, go_TakeLeft):\n        return (Pool >= 2) & X(go_TakeLeft)\n",
    );
  });

  it("fires a controllable transition whenever enabled under control closed", () => {
    const python = petriNetIrToReactiveModule(conflict);
    expect(python).not.toContain("go_TakeLeft");
    expect(python).toContain(
      "        fire_TakeLeft = Pool >= 2  # TakeLeft: 2 Pool -> Left\n",
    );
  });

  it("has a later taker from a shared place await the earlier one in the modular shape", () => {
    expect(
      petriNetIrToReactiveModule({ ...conflict, zeroth: { shape: "modular" } }),
    ).toContain(
      `    def update(self, fire_TakeRight, Pool, fire_TakeLeft):
        avail_Pool = Pool
        avail_Pool = ite(X(fire_TakeLeft), avail_Pool - 2, avail_Pool)  # TakeLeft took 2
        return avail_Pool >= 1
`,
    );
  });

  it("mixes predicate and stochastic transitions, drawing only for the rated ones", () => {
    const python = petriNetIrToReactiveModule({
      name: "mixed",
      kind: "mixed",
      places: { A: null, B: null },
      marking: { A: 3 },
      transitions: {
        Go: { inputs: { A: null }, outputs: { B: null }, rate: 2 },
        Back: { inputs: { B: null }, outputs: { A: null } },
      },
    });
    expect(python).toContain(
      '    """Mixed Petri net with 2 places and 2 transitions, dt = 1.0. One update is one Petrinaut step."""',
    );
    expect(python).toContain(
      "u_Go = Var(REAL)  # uniform draw for Go, each step\n\n",
    );
    expect(python).not.toContain("u_Back");
    expect(python).toContain(
      `        fire_Go = (A >= 1.0) & (X(u_Go) >= ${Math.exp(-2)})  # Go: A -> B\n`,
    );
    expect(python).toContain("        fire_Back = B >= 1.0  # Back: B -> A\n");
    expect(python).toContain(
      "net = Mixed(theory=LRA, ctrl=(A, B), extl=(u_Go,))",
    );
  });

  it("refuses the constructs it does not lower yet, one diagnostic per item", () => {
    const outcome = compilePetriNetIr({
      name: "coloured",
      kind: "mixed",
      colours: { Drone: { battery: "real" } },
      dynamics: {
        Drain: {
          colour: "Drone",
          code: "return tokens.map(() => ({ battery: -1 }));",
        },
      },
      places: { Hangar: { colour: "Drone", dynamics: "Drain" }, Count: null },
      transitions: {
        Launch: {
          inputs: { Hangar: null },
          outputs: { Count: null },
          reads: { Count: null },
          inhibitors: { Count: { weight: 3 } },
          rate: "return input.Hangar[0].battery;",
          kernel: "return {};",
        },
        Reset: { inputs: { Count: null }, guard: "return true;" },
      },
    });
    expect(outcome.ok).toBe(false);
    if (!outcome.ok) {
      expect(
        outcome.errors.map((error) => [error.code, error.item.name]),
      ).toEqual([
        ["coloured-place-not-lowered", "Hangar"],
        ["dynamics-not-lowered", "Hangar"],
        ["rate-code-not-lowered", "Launch"],
        ["kernel-not-lowered", "Launch"],
        ["read-arc-not-lowered", "Launch"],
        ["inhibitor-arc-not-lowered", "Launch"],
        ["guard-not-lowered", "Reset"],
      ]);
    }
    expect(() =>
      petriNetIrToReactiveModule({
        name: "guarded",
        kind: "plain",
        places: { A: null },
        transitions: { Go: { inputs: { A: null }, guard: "return true;" } },
      }),
    ).toThrow(
      "transition Go: a guard over the input tokens is not lowered to a reactive module yet",
    );
  });

  it("writes a plain transition with no inputs as always enabled", () => {
    const python = petriNetIrToReactiveModule({
      name: "source",
      kind: "plain",
      places: { Out: null },
      transitions: { Emit: { outputs: { Out: { weight: 2 } } } },
    });
    expect(python).toContain(
      "        # Emit: nothing -> 2 Out: always enabled\n",
    );
    expect(python).toContain("        Out = Out + 2\n");
    expect(python).toContain("net = Source(theory=LIA, ctrl=(Out,))");
  });
});
