import { useMutation } from "@apollo/client";
import { useRouter } from "next/router";

import {
  CreatePageMutation,
  CreatePageMutationVariables,
} from "../../graphql/autoGeneratedTypes";
import { getNamespacePages } from "../../graphql/queries/namespace.queries";
import { createPage } from "../../graphql/queries/page.queries";

export const useCreatePage = () => {
  const router = useRouter();

  const [createPageFn, { loading, error }] = useMutation<
    CreatePageMutation,
    CreatePageMutationVariables
  >(createPage, {
    onCompleted: (data) => {
      const { createPage } = data;
      const { id, namespaceId } = createPage;
      router.push(`/${namespaceId}/${id}`);
    },
    refetchQueries: ({ data }) => [
      {
        query: getNamespacePages,
        variables: { namespaceId: data.createPage.namespaceId },
      },
    ],
  });

  return {
    create: createPageFn,
    loading,
    error,
  };
};
