graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../type_system/index.html">type-system</a>]
    1[<a href="../hash_codec/index.html">hash-codec</a>]
    2[<a href="../hash_codegen/index.html">hash-codegen</a>]
    3[<a href="../hash_graph_authorization/index.html">hash-graph-authorization</a>]
    4[<a href="../hash_graph_migrations/index.html">hash-graph-migrations</a>]
    5[<a href="../hash_graph_migrations_macros/index.html">hash-graph-migrations-macros</a>]
    6[<a href="../hash_graph_postgres_store/index.html">hash-graph-postgres-store</a>]
    7[<a href="../hash_graph_store/index.html">hash-graph-store</a>]
    8[<a href="../hash_graph_temporal_versioning/index.html">hash-graph-temporal-versioning</a>]
    9[<a href="../hash_graph_types/index.html">hash-graph-types</a>]
    10[<a href="../hash_graph_validation/index.html">hash-graph-validation</a>]
    11[<a href="../harpc_types/index.html">harpc-types</a>]
    12[<a href="../harpc_wire_protocol/index.html">harpc-wire-protocol</a>]
    13[hashql-ast]
    class 13 root
    14[<a href="../hashql_compiletest/index.html">hashql-compiletest</a>]
    15[<a href="../hashql_core/index.html">hashql-core</a>]
    16[<a href="../hashql_diagnostics/index.html">hashql-diagnostics</a>]
    17[<a href="../hashql_eval/index.html">hashql-eval</a>]
    18[<a href="../hashql_hir/index.html">hashql-hir</a>]
    19[<a href="../hashql_macros/index.html">hashql-macros</a>]
    20[<a href="../hashql_mir/index.html">hashql-mir</a>]
    21[<a href="../hashql_syntax_jexpr/index.html">hashql-syntax-jexpr</a>]
    22[<a href="../hash_status/index.html">hash-status</a>]
    23[<a href="../hash_telemetry/index.html">hash-telemetry</a>]
    24[<a href="../hash_temporal_client/index.html">hash-temporal-client</a>]
    25[<a href="../darwin_kperf/index.html">darwin-kperf</a>]
    26[<a href="../darwin_kperf_criterion/index.html">darwin-kperf-criterion</a>]
    27[<a href="../darwin_kperf_events/index.html">darwin-kperf-events</a>]
    28[<a href="../darwin_kperf_sys/index.html">darwin-kperf-sys</a>]
    29[<a href="../error_stack/index.html">error-stack</a>]
    30[<a href="../hash_graph_test_data/index.html">hash-graph-test-data</a>]
    0 --> 8
    0 -.-> 30
    1 -.-> 2
    1 --> 12
    3 --> 0
    4 --> 5
    4 --> 23
    6 -.-> 4
    6 --> 10
    6 --> 22
    7 --> 3
    7 --> 9
    7 --> 24
    8 --> 1
    9 -.-> 30
    10 -.-> 30
    12 -.-> 11
    12 --> 11
    12 --> 29
    13 -.-> 14
    14 --> 17
    14 --> 21
    15 --> 1
    15 --> 16
    15 --> 19
    15 -.-> 26
    17 --> 6
    17 --> 20
    18 -.-> 14
    20 --> 18
    21 --> 13
    21 --> 15
    23 --> 29
    24 --> 0
    25 --> 27
    25 --> 28
    26 --> 25
    30 --> 7
