name: Install Tools
description: Uses Mise to install tools

inputs:
  token:
    required: true

runs:
  using: composite

  steps:
    # We install `cargo-binstall` first to speed up the installation of the other tools.
    - name: Install `cargo-binstall`
      uses: cargo-bins/cargo-binstall@639cca973755257a5103d314f08e37e3f861d9ab # v1.10.22

    # We currently don't manage Rust toolchains in Mise, so we install it manually.
    - name: "Install Rust"
      shell: bash
      run: |
        # regex for components that are only available on nightly and should not be installed on stable
        # these are in variables due to: https://stackoverflow.com/a/56449915/9077988
        NIGHTLY_ONLY="miri|llvm-tools|llvm-tools-preview|rustc-codegen-cranelift-preview"
        NIGHTLY_TOOLCHAIN="nightly-.*"

        # extract components from the rust-toolchain.toml
        COMPONENTS="$(cat rust-toolchain.toml | yq -p toml '.toolchain.components[]')"

        if [[ "${{ inputs.toolchain }}" != "" ]]; then
          TOOLCHAIN_CHANNEL="${{ inputs.toolchain }}"
        else
          TOOLCHAIN_CHANNEL="$(cat rust-toolchain.toml | yq -p toml '.toolchain.channel')"
        fi
        rustup toolchain install "$TOOLCHAIN_CHANNEL"

        for component in $COMPONENTS; do
          # depending on the toolchain we need to conditionally skip specific components
          if [[ ! "$TOOLCHAIN_CHANNEL" =~ $NIGHTLY_TOOLCHAIN ]]; then
            # ensure that we only install components that are meant for stable
            if [[ ! $component =~ $NIGHTLY_ONLY ]]; then
              rustup component add --toolchain "$TOOLCHAIN_CHANNEL" "$component"
            fi
          else
            rustup component add --toolchain "$TOOLCHAIN_CHANNEL" "$component"
          fi
        done

        echo "RUSTUP_TOOLCHAIN=$TOOLCHAIN_CHANNEL" >> $GITHUB_ENV

    - name: Install Tools
      uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11
      with:
        install_args: --jobs 1
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
