import { UserInputError } from "apollo-server-express";

import { entities } from "../../../mockData/entities";
import { DbPage } from "../../../types/dbTypes";
import {
  MutationCreatePageArgs,
  Resolver,
  Visibility,
} from "../../autoGeneratedTypes";
import { namespaceIdFromNamespaceName } from "../shared/namespace";

let i = 100;

export const createPage: Resolver<
  Promise<any>,
  {},
  {},
  MutationCreatePageArgs
> = async (_, { namespace, namespaceId, data }) => {
  if (!namespace && !namespaceId) {
    throw new UserInputError(
      "One of namespace or namespaceId must be provided"
    );
  }
  if (!namespaceId) {
    namespaceId = await namespaceIdFromNamespaceName(namespace!);
  }

  const now = new Date();

  const page: DbPage = {
    id: `page${i++}`,
    namespaceId,
    properties: data,
    createdById: "1",
    type: "Page",
    updatedAt: now,
    createdAt: now,
    visibility: Visibility.Public,
  };

  entities.push(page);

  return page;
};
