import { DbPage } from "../../../types/dbTypes";
import {
  MutationCreatePageArgs,
  Resolver,
  Visibility,
} from "../../autoGeneratedTypes";
import { GraphQLContext } from "../../context";

export const createPage: Resolver<
  Promise<DbPage>,
  {},
  GraphQLContext,
  MutationCreatePageArgs
> = async (_, { namespaceId, properties }, { dataSources }) => {
  const entity = await dataSources.db.createEntity({
    namespaceId,
    createdById: "", // TODO
    type: "Page",
    properties: properties,
  });

  const page: DbPage = {
    ...entity,
    type: "Page",
    visibility: Visibility.Public, // TODO
  };

  return page;
};
