import { QueryNamespacePagesArgs, Resolver } from "../../autoGeneratedTypes";
import { DbPage } from "../../../types/dbTypes";
import { GraphQLContext } from "../../context";

export const namespacePages: Resolver<
  Promise<DbPage[]>,
  {},
  GraphQLContext,
  QueryNamespacePagesArgs
> = async (_, { namespaceId }, { dataSources }) => {
  const pages = await dataSources.db.getEntitiesByType({ namespaceId, type: "Page"});
  return pages as DbPage[];
};
