import { UserInputError } from "apollo-server-express";

import { QueryNamespacePagesArgs, Resolver } from "../../autoGeneratedTypes";
import { DbPage } from "../../../types/dbTypes";
import { entities } from "../../../mockData/entities";
import { namespaceIdFromNamespaceName } from "../shared/namespace";

export const namespacePages: Resolver<
  Promise<DbPage[]>,
  {},
  {},
  QueryNamespacePagesArgs
> = async (_, { namespaceId, namespace }) => {
  if (!namespace && !namespaceId) {
    throw new UserInputError(
      "One of namespace or namespaceId must be provided"
    );
  }
  if (!namespaceId) {
    namespaceId = await namespaceIdFromNamespaceName(namespace!);
  }

  const dbPages = (await entities.filter(
    (entity) => entity.type === "Page" && entity.namespaceId === namespaceId
  )) as DbPage[];

  return dbPages;
};
