graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hash_graph">hash-graph</a>]
    1[<a href="../type_system">type-system</a>]
    2[<a href="../hash_codec">hash-codec</a>]
    3[<a href="../hash_codegen">hash-codegen</a>]
    4[<a href="../hash_graph_api">hash-graph-api</a>]
    5[<a href="../hash_graph_temporal_versioning">hash-graph-temporal-versioning</a>]
    6[<a href="../hash_graph_test_server">hash-graph-test-server</a>]
    7[<a href="../harpc_client">harpc-client</a>]
    8[<a href="../harpc_codec">harpc-codec</a>]
    9[<a href="../harpc_net">harpc-net</a>]
    10[harpc-server]
    class 10 root
    11[<a href="../harpc_system">harpc-system</a>]
    12[<a href="../harpc_tower">harpc-tower</a>]
    13[<a href="../harpc_types">harpc-types</a>]
    14[<a href="../harpc_wire_protocol">harpc-wire-protocol</a>]
    15[<a href="../error_stack">error-stack</a>]
    16[<a href="../hash_graph_benches">hash-graph-benches</a>]
    17[<a href="../hash_graph_test_data">hash-graph-test-data</a>]
    0 --> 6
    1 --> 5
    1 -.-> 17
    2 -.-> 3
    2 --> 14
    4 --> 10
    5 --> 2
    6 --> 4
    7 --> 11
    8 --> 13
    8 --> 15
    9 --> 2
    9 -.-> 8
    9 --> 8
    10 -.-> 1
    10 -.-> 7
    11 --> 12
    12 -.-> 9
    12 --> 9
    14 -.-> 13
    14 --> 13
    14 --> 15
    16 -.-> 4
    17 --> 1
