/**
 * React hook that manages a Pyright WebWorker for Python language intelligence.
 *
 * Uses the pre-built Pyright worker from `monaco-pyright-lsp` and communicates
 * with it via standard LSP over postMessage. Exposes the same {@link LanguageClientApi}
 * interface as {@link useLanguageClient} so the provider can switch transparently.
 *
 * Init flow:
 * 1. Worker posts `{ type: "serverLoaded" }`
 * 2. We send `{ type: "initServer", userFiles, typeshedFallback }` with .pyi stubs
 * 3. Worker posts `{ type: "serverInitialized" }`
 * 4. We create an LSP message connection and send `initialize` + `initialized`
 * 5. We open all virtual Python files as LSP documents
 */
import {
  BrowserMessageReader,
  BrowserMessageWriter,
  createMessageConnection,
  type MessageConnection,
} from "vscode-languageserver/browser";
import {
  type CompletionList,
  type Diagnostic,
  type Hover,
  type SignatureHelp,
} from "vscode-languageserver-types";

import { useCallback, useEffect, useRef } from "react";

import type { SDCPN } from "../../core/types/sdcpn";
import type { VirtualFile } from "../lib/create-language-service-host";
import { filePathToUri, uriToFilePath } from "../lib/document-uris";
import { generatePythonVirtualFiles } from "../lib/generate-python-virtual-files";
import type {
  DocumentUri,
  Position,
  PublishDiagnosticsParams,
} from "./protocol";
import type { LanguageClientApi } from "./use-language-client";

// ---------------------------------------------------------------------------
// Pyright path helpers
// ---------------------------------------------------------------------------

/** User files root inside the Pyright ZenFS filesystem. */
const TYPINGS_ROOT = "/typings";

/**
 * Normalise an internal virtual-file path for Python import compatibility.
 * - `sdcpn-lib` → `sdcpn_lib` (Python can't import hyphens)
 * - Color-ID directories: strip non-identifier chars so the FS path matches
 *   the `from colors.<sanitised>.defs` import generated by the stub.
 */
function toPyrightFsPath(internalPath: string): string {
  return internalPath
    .split("/")
    .map((segment) => {
      if (segment.endsWith(".py") || segment.endsWith(".pyi")) {
        // File names: replace hyphens with underscores
        return segment.replace(/-/g, "_");
      }
      // Directories: strip characters invalid in Python identifiers
      return segment.replace(/-/g, "");
    })
    .join("/");
}

/**
 * Bidirectional mapping between Pyright URIs and internal paths.
 *
 * `toPyrightFsPath` is lossy (strips hyphens from UUIDs), so we can't
 * reconstruct internal paths from Pyright URIs by string manipulation alone.
 * Instead we maintain an explicit reverse map that is rebuilt whenever the
 * virtual file set changes.
 */
class PyrightUriMap {
  /** Internal path → Pyright URI */
  private forward = new Map<string, string>();
  /** Pyright URI → Internal path */
  private reverse = new Map<string, string>();

  rebuild(internalPaths: Iterable<string>): void {
    this.forward.clear();
    this.reverse.clear();
    for (const internalPath of internalPaths) {
      const pyrightUri = `file://${TYPINGS_ROOT}${toPyrightFsPath(internalPath)}`;
      this.forward.set(internalPath, pyrightUri);
      this.reverse.set(pyrightUri, internalPath);
    }
  }

  toPyrightUri(internalPath: string): string {
    return (
      this.forward.get(internalPath) ??
      `file://${TYPINGS_ROOT}${toPyrightFsPath(internalPath)}`
    );
  }

  fromPyrightUri(pyrightUri: string): string | null {
    return this.reverse.get(pyrightUri) ?? null;
  }

  pyrightUriToMonacoUri(pyrightUri: string): DocumentUri | null {
    const internalPath = this.fromPyrightUri(pyrightUri);
    if (!internalPath) {
      return null;
    }
    return filePathToUri(internalPath);
  }

  monacoUriToPyrightUri(monacoUri: DocumentUri): string | null {
    const internalPath = uriToFilePath(monacoUri);
    if (!internalPath) {
      return null;
    }
    return this.toPyrightUri(internalPath);
  }
}

// ---------------------------------------------------------------------------
// File-system builder (UserFolder for initServer)
// ---------------------------------------------------------------------------

interface UserFolder {
  [key: string]: string | UserFolder | ArrayBuffer;
}

function buildUserFolder(files: Map<string, VirtualFile>): UserFolder {
  const root: UserFolder = {};

  for (const [path, file] of files) {
    const fsPath = toPyrightFsPath(path);
    const parts = fsPath.replace(/^\//, "").split("/");
    let current: UserFolder = root;

    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i]!;
      if (!(part in current) || typeof current[part] === "string") {
        current[part] = {};
      }
      current = current[part] as UserFolder;
    }

    const fileName = parts.at(-1)!;
    current[fileName] = (file.prefix ?? "") + file.content;
  }

  return root;
}

// ---------------------------------------------------------------------------
// Prefix offset helpers
// ---------------------------------------------------------------------------

function countNewlines(text: string): number {
  let n = 0;
  for (const ch of text) {
    if (ch === "\n") {
      n++;
    }
  }
  return n;
}

// ---------------------------------------------------------------------------
// Hook
// ---------------------------------------------------------------------------

/**
 * Manage a Pyright WebWorker and expose a {@link LanguageClientApi}-compatible
 * interface. The worker is only created when `enabled` is `true`.
 */
export function usePyrightClient(enabled: boolean): LanguageClientApi {
  const connectionRef = useRef<MessageConnection | null>(null);
  const workerRef = useRef<Worker | null>(null);

  // Bidirectional Pyright URI ↔ internal path mapping
  const uriMapRef = useRef(new PyrightUriMap());

  // Virtual-file bookkeeping
  const virtualFilesRef = useRef<Map<string, VirtualFile>>(new Map());
  /** Maps Pyright URI → document version */
  const docVersionsRef = useRef<Map<string, number>>(new Map());
  /** Maps Pyright FS path → number of prefix lines */
  const prefixLinesRef = useRef<Map<string, number>>(new Map());

  // Diagnostics accumulator (Pyright URI → diagnostics)
  const diagnosticsMapRef = useRef<Map<string, Diagnostic[]>>(new Map());
  const diagnosticsCallbackRef = useRef<
    ((params: PublishDiagnosticsParams[]) => void) | null
  >(null);

  // Ready gate: resolves when the Pyright worker is fully initialised
  const readyPromiseRef = useRef<Promise<void>>(Promise.resolve());
  const readyResolveRef = useRef<(() => void) | null>(null);

  // Track whether the worker has ever been initialised with SDCPN data
  const initializedRef = useRef(false);

  // ------------------------------------------------------------------
  // Flush accumulated diagnostics to the callback
  // ------------------------------------------------------------------
  const flushDiagnostics = useCallback(() => {
    const cb = diagnosticsCallbackRef.current;
    if (!cb) {
      return;
    }

    const uriMap = uriMapRef.current;
    const params: PublishDiagnosticsParams[] = [];
    for (const [pyrightUri, diagnostics] of diagnosticsMapRef.current) {
      const monacoUri = uriMap.pyrightUriToMonacoUri(pyrightUri);
      if (!monacoUri) {
        continue;
      }

      // Adjust positions to remove prefix line offset
      const internalPath = uriMap.fromPyrightUri(pyrightUri);
      const pyrightFsPath = internalPath ? toPyrightFsPath(internalPath) : null;
      const prefixLines = pyrightFsPath
        ? (prefixLinesRef.current.get(pyrightFsPath) ?? 0)
        : 0;

      const adjusted = diagnostics
        .map((d) => ({
          ...d,
          range: {
            start: {
              line: d.range.start.line - prefixLines,
              character: d.range.start.character,
            },
            end: {
              line: d.range.end.line - prefixLines,
              character: d.range.end.character,
            },
          },
        }))
        .filter((d) => d.range.start.line >= 0);

      params.push({ uri: monacoUri, diagnostics: adjusted });
    }

    cb(params);
  }, []);

  // ------------------------------------------------------------------
  // Create / destroy the Pyright worker
  // ------------------------------------------------------------------
  useEffect(() => {
    if (!enabled) {
      return;
    }

    // Create a fresh ready gate
    readyPromiseRef.current = new Promise<void>((resolve) => {
      readyResolveRef.current = resolve;
    });

    const worker = new Worker(
      new URL("monaco-pyright-lsp/dist/worker.js", import.meta.url),
    );

    workerRef.current = worker;

    // Phase 1 + 2 init is triggered by `initialize()` via the API below.
    // The worker immediately posts `{ type: "serverLoaded" }` when ready.

    return () => {
      connectionRef.current?.dispose();
      connectionRef.current = null;
      worker.terminate();
      workerRef.current = null;
      initializedRef.current = false;
      diagnosticsMapRef.current.clear();
      docVersionsRef.current.clear();
      prefixLinesRef.current.clear();
      virtualFilesRef.current.clear();
    };
  }, [enabled]);

  // ------------------------------------------------------------------
  // Boot the Pyright LSP server (called by initialize / notifySDCPNChanged)
  // ------------------------------------------------------------------
  const bootServer = useCallback(
    async (sdcpn: SDCPN): Promise<void> => {
      const worker = workerRef.current;
      if (!worker) {
        return;
      }

      // Generate virtual files
      const files = generatePythonVirtualFiles(sdcpn);
      virtualFilesRef.current = files;

      // Rebuild bidirectional URI map
      uriMapRef.current.rebuild(files.keys());

      // Compute prefix line counts
      prefixLinesRef.current.clear();
      for (const [path, file] of files) {
        if (file.prefix) {
          prefixLinesRef.current.set(
            toPyrightFsPath(path),
            countNewlines(file.prefix),
          );
        }
      }

      // Dispose previous connection if any
      connectionRef.current?.dispose();
      connectionRef.current = null;
      diagnosticsMapRef.current.clear();
      docVersionsRef.current.clear();

      // Phase 1: Wait for serverLoaded
      const serverLoadedPromise = new Promise<void>((resolve) => {
        const handler = (event: MessageEvent) => {
          if (event.data?.type === "serverLoaded") {
            worker.removeEventListener("message", handler);
            resolve();
          }
        };
        worker.addEventListener("message", handler);
      });

      // Phase 2: Wait for serverInitialized
      const serverInitializedPromise = new Promise<void>((resolve) => {
        const handler = (event: MessageEvent) => {
          if (event.data?.type === "serverInitialized") {
            worker.removeEventListener("message", handler);
            resolve();
          }
        };
        worker.addEventListener("message", handler);
      });

      await serverLoadedPromise;

      // Send file-system data to the worker
      worker.postMessage({
        type: "initServer",
        userFiles: buildUserFolder(files),
        typeshedFallback: undefined, // use built-in typeshed
      });

      await serverInitializedPromise;

      // Phase 3: LSP mode — create message connection
      const reader = new BrowserMessageReader(worker);
      const writer = new BrowserMessageWriter(worker);
      const connection = createMessageConnection(reader, writer);
      connectionRef.current = connection;
      connection.listen();

      // LSP initialize
      await connection.sendRequest("initialize", {
        rootUri: "file:///",
        rootPath: "/",
        processId: 1,
        capabilities: {
          textDocument: {
            publishDiagnostics: {
              tagSupport: { valueSet: [1, 2] },
              versionSupport: true,
            },
            hover: { contentFormat: ["markdown", "plaintext"] },
            signatureHelp: {},
            completion: {
              completionItem: { snippetSupport: false },
            },
          },
        },
      });

      // initialized notification
      connection.sendNotification("initialized", {});

      // Configure Pyright
      connection.sendNotification("workspace/didChangeConfiguration", {
        settings: {
          python: {
            pythonVersion: "3.13",
            pythonPlatform: "All",
            analysis: {
              extraPaths: [TYPINGS_ROOT],
              diagnosticSeverityOverrides: {},
              logLevel: "error",
              useLibraryCodeForTypes: true,
            },
          },
        },
      });

      // Handle workspace/configuration requests (Pyright needs this)
      connection.onRequest("workspace/configuration", () => []);

      // Subscribe to diagnostics
      connection.onNotification(
        "textDocument/publishDiagnostics",
        (params: {
          uri: string;
          diagnostics: Diagnostic[];
          version?: number;
        }) => {
          diagnosticsMapRef.current.set(params.uri, params.diagnostics);
          flushDiagnostics();
        },
      );

      // Open all virtual files as documents
      for (const [path, file] of files) {
        const pyrightUri = uriMapRef.current.toPyrightUri(path);
        const version = 1;
        docVersionsRef.current.set(pyrightUri, version);

        const fullText = (file.prefix ?? "") + file.content;
        const languageId = path.endsWith(".pyi") ? "python" : "python";

        connection.sendNotification("textDocument/didOpen", {
          textDocument: {
            uri: pyrightUri,
            languageId,
            version,
            text: fullText,
          },
        });
      }

      readyResolveRef.current?.();
    },
    [flushDiagnostics],
  );

  // ------------------------------------------------------------------
  // LanguageClientApi implementation
  // ------------------------------------------------------------------

  const initialize = useCallback(
    (sdcpn: SDCPN) => {
      if (initializedRef.current) {
        return;
      }
      initializedRef.current = true;
      bootServer(sdcpn);
    },
    [bootServer],
  );

  const notifySDCPNChanged = useCallback(
    (sdcpn: SDCPN) => {
      const connection = connectionRef.current;
      if (!connection) {
        // Not yet initialised — queue via bootServer
        if (!initializedRef.current) {
          initializedRef.current = true;
          bootServer(sdcpn);
        }
        return;
      }

      // Regenerate virtual files and diff
      const newFiles = generatePythonVirtualFiles(sdcpn);
      const oldFiles = virtualFilesRef.current;
      virtualFilesRef.current = newFiles;

      // Rebuild URI map with the union of old + new paths so we can
      // still resolve old Pyright URIs during the close phase.
      const allPaths = new Set([...oldFiles.keys(), ...newFiles.keys()]);
      uriMapRef.current.rebuild(allPaths);

      // Update prefix line counts
      prefixLinesRef.current.clear();
      for (const [path, file] of newFiles) {
        if (file.prefix) {
          prefixLinesRef.current.set(
            toPyrightFsPath(path),
            countNewlines(file.prefix),
          );
        }
      }

      // Close removed files
      for (const oldPath of oldFiles.keys()) {
        if (!newFiles.has(oldPath)) {
          const pyrightUri = uriMapRef.current.toPyrightUri(oldPath);
          connection.sendNotification("textDocument/didClose", {
            textDocument: { uri: pyrightUri },
          });
          docVersionsRef.current.delete(pyrightUri);
          diagnosticsMapRef.current.delete(pyrightUri);
        }
      }

      // Open new files / update changed files
      for (const [path, newFile] of newFiles) {
        const pyrightUri = uriMapRef.current.toPyrightUri(path);
        const newText = (newFile.prefix ?? "") + newFile.content;

        const oldFile = oldFiles.get(path);
        if (!oldFile) {
          // New file → open
          const version = 1;
          docVersionsRef.current.set(pyrightUri, version);
          connection.sendNotification("textDocument/didOpen", {
            textDocument: {
              uri: pyrightUri,
              languageId: "python",
              version,
              text: newText,
            },
          });
        } else {
          const oldText = (oldFile.prefix ?? "") + oldFile.content;
          if (oldText !== newText) {
            // Changed → didChange
            const version = (docVersionsRef.current.get(pyrightUri) ?? 0) + 1;
            docVersionsRef.current.set(pyrightUri, version);
            connection.sendNotification("textDocument/didChange", {
              textDocument: { uri: pyrightUri, version },
              contentChanges: [{ text: newText }],
            });
          }
        }
      }
    },
    [bootServer],
  );

  const notifyDocumentChanged = useCallback(
    (uri: DocumentUri, text: string) => {
      const connection = connectionRef.current;
      if (!connection) {
        return;
      }

      const pyrightUri = uriMapRef.current.monacoUriToPyrightUri(uri);
      if (!pyrightUri) {
        return;
      }

      // Re-attach prefix
      const internalPath = uriToFilePath(uri);
      const file = internalPath
        ? virtualFilesRef.current.get(internalPath)
        : undefined;
      const prefix = file?.prefix ?? "";
      const fullText = prefix + text;

      const version = (docVersionsRef.current.get(pyrightUri) ?? 0) + 1;
      docVersionsRef.current.set(pyrightUri, version);

      // Also update our cached content so diffs work
      if (file) {
        file.content = text;
      }

      connection.sendNotification("textDocument/didChange", {
        textDocument: { uri: pyrightUri, version },
        contentChanges: [{ text: fullText }],
      });
    },
    [],
  );

  const requestCompletion = useCallback(
    async (uri: DocumentUri, position: Position): Promise<CompletionList> => {
      await readyPromiseRef.current;
      const connection = connectionRef.current;
      if (!connection) {
        return { isIncomplete: false, items: [] };
      }

      const uriMap = uriMapRef.current;
      const pyrightUri = uriMap.monacoUriToPyrightUri(uri);
      if (!pyrightUri) {
        return { isIncomplete: false, items: [] };
      }

      const internalPath = uriMap.fromPyrightUri(pyrightUri);
      const pyrightFsPath = internalPath ? toPyrightFsPath(internalPath) : null;
      const prefixLines = pyrightFsPath
        ? (prefixLinesRef.current.get(pyrightFsPath) ?? 0)
        : 0;

      const result = await connection
        .sendRequest("textDocument/completion", {
          textDocument: { uri: pyrightUri },
          position: {
            line: position.line + prefixLines,
            character: position.character,
          },
        })
        .catch(() => null);

      if (!result) {
        return { isIncomplete: false, items: [] };
      }

      // Pyright may return CompletionItem[] or CompletionList
      if (Array.isArray(result)) {
        return { isIncomplete: false, items: result };
      }
      return result as CompletionList;
    },
    [],
  );

  const requestHover = useCallback(
    async (uri: DocumentUri, position: Position): Promise<Hover | null> => {
      await readyPromiseRef.current;
      const connection = connectionRef.current;
      if (!connection) {
        return null;
      }

      const uriMap = uriMapRef.current;
      const pyrightUri = uriMap.monacoUriToPyrightUri(uri);
      if (!pyrightUri) {
        return null;
      }

      const internalPath = uriMap.fromPyrightUri(pyrightUri);
      const pyrightFsPath = internalPath ? toPyrightFsPath(internalPath) : null;
      const prefixLines = pyrightFsPath
        ? (prefixLinesRef.current.get(pyrightFsPath) ?? 0)
        : 0;

      const result = (await connection
        .sendRequest("textDocument/hover", {
          textDocument: { uri: pyrightUri },
          position: {
            line: position.line + prefixLines,
            character: position.character,
          },
        })
        .catch(() => null)) as Hover | null;

      if (!result) {
        return null;
      }

      // Adjust range back
      if (result.range) {
        result.range = {
          start: {
            line: result.range.start.line - prefixLines,
            character: result.range.start.character,
          },
          end: {
            line: result.range.end.line - prefixLines,
            character: result.range.end.character,
          },
        };
      }

      return result;
    },
    [],
  );

  const requestSignatureHelp = useCallback(
    async (
      uri: DocumentUri,
      position: Position,
    ): Promise<SignatureHelp | null> => {
      await readyPromiseRef.current;
      const connection = connectionRef.current;
      if (!connection) {
        return null;
      }

      const uriMap = uriMapRef.current;
      const pyrightUri = uriMap.monacoUriToPyrightUri(uri);
      if (!pyrightUri) {
        return null;
      }

      const internalPath = uriMap.fromPyrightUri(pyrightUri);
      const pyrightFsPath = internalPath ? toPyrightFsPath(internalPath) : null;
      const prefixLines = pyrightFsPath
        ? (prefixLinesRef.current.get(pyrightFsPath) ?? 0)
        : 0;

      const result = (await connection
        .sendRequest("textDocument/signatureHelp", {
          textDocument: { uri: pyrightUri },
          position: {
            line: position.line + prefixLines,
            character: position.character,
          },
        })
        .catch(() => null)) as SignatureHelp | null;

      return result;
    },
    [],
  );

  const onDiagnostics = useCallback(
    (callback: (params: PublishDiagnosticsParams[]) => void) => {
      diagnosticsCallbackRef.current = callback;
    },
    [],
  );

  return {
    initialize,
    notifySDCPNChanged,
    notifyDocumentChanged,
    requestCompletion,
    requestHover,
    requestSignatureHelp,
    onDiagnostics,
  };
}
