extend = { path = "../../.github/scripts/rust/Makefile.toml" }

# This crate has no unsafe code
[tasks.miri]
disabled = true

[tasks.coverage-task]
args = ["llvm-cov", "test", "--workspace", "--all-features", "--doctests", "${@}"]
dependencies = ["install-llvm-tools"]
