/**
 * Diagram generation.
 *
 * Dotted layer ids map straight onto D2's container syntax, so
 * `core.simulation.monte-carlo` nests inside `core.simulation` inside `core`
 * with no extra bookkeeping — the taxonomy the annotations declare *is* the
 * diagram's grouping.
 *
 * A collapsed overview shows the top-level layers; each layer with sub-layers
 * gets a drill-down of its own. Both `.d2` source and rendered `.svg` are
 * written.
 */

import { spawnSync } from "node:child_process";

import type { Edge, Layer } from "../model";

const quote = (text: string): string => JSON.stringify(text);

/** Top-level ancestor of a dotted id, used for colour classing. */
const rootSegment = (id: string): string => id.split(".")[0] ?? id;

const styleClasses = [
  `classes: {`,
  `  core: {style.fill: "#dcecff"; style.stroke: "#3676b8"}`,
  `  react: {style.fill: "#e8e0ff"; style.stroke: "#7051b5"}`,
  `  ui: {style.fill: "#e2f4e8"; style.stroke: "#3d8055"}`,
  `  petrinaut: {style.fill: "#fdeedc"; style.stroke: "#b5762f"}`,
  `  other: {style.fill: "#f2f2f2"; style.stroke: "#777777"}`,
  `  boundary: {style.stroke-dash: 4}`,
  `}`,
].join("\n");

const knownRoots = ["core", "react", "ui", "petrinaut"];

const classFor = (id: string): string => {
  const root = rootSegment(id);
  return knownRoots.includes(root) ? root : "other";
};

const pluralise = (count: number, singular: string, plural?: string): string =>
  `${count} ${count === 1 ? singular : (plural ?? `${singular}s`)}`;

const header = (generatedBy: string): string =>
  `# Generated by ${generatedBy}. Edit the annotations in the source, not this file.\n\ndirection: right\n`;

/**
 * One diagram per layer that has sub-layers, showing only its *direct* children.
 *
 * Nesting the entire sub-tree produced an unreadable tangle — 23 layers under
 * `core` with every inter-layer edge drawn is technically accurate and useless.
 * Showing one level at a time, with edges aggregated up to that level, keeps each
 * diagram legible and lets a reader drill down through the pages instead.
 */
export const buildSubtreeDiagram = (
  parentId: string,
  layers: Layer[],
  edges: Edge[],
  generatedBy: string,
): string => {
  const children = layers.filter((layer) => layer.parent === parentId);
  const childIds = children.map((layer) => layer.id);

  /**
   * D2 reads `.` as container nesting, so a full dotted id as a key would make
   * it synthesise the ancestor boxes this diagram exists to leave out. The leaf
   * segment is unique among siblings, which is all a single-level diagram needs.
   */
  const key = (layerId: string): string => layerId.slice(parentId.length + 1);

  /** The direct child of `parentId` that `layerId` sits under, if any. */
  const childScopeOf = (layerId: string): string | null =>
    childIds.find(
      (childId) => layerId === childId || layerId.startsWith(`${childId}.`),
    ) ?? null;

  /** Total files in a child, including its own descendants. */
  const totalFiles = (childId: string): number =>
    layers
      .filter(
        (layer) => layer.id === childId || layer.id.startsWith(`${childId}.`),
      )
      .reduce((total, layer) => total + layer.fileCount, 0);

  const nodeLines = children.map((child) => {
    const descendants = layers.filter((layer) =>
      layer.id.startsWith(`${child.id}.`),
    ).length;
    const detail =
      descendants === 0
        ? pluralise(totalFiles(child.id), "source file")
        : `${pluralise(totalFiles(child.id), "source file")}, ${pluralise(descendants, "sub-layer")}`;

    return `${key(child.id)}: {class: ${classFor(child.id)}; label: ${quote(child.name)}; tooltip: ${quote(`${detail} · ${child.role}`)}}`;
  });

  const aggregated = new Map<string, number>();
  for (const edge of edges) {
    const from = childScopeOf(edge.from);
    const to = childScopeOf(edge.to);
    if (from === null || to === null || from === to) {
      continue;
    }
    const pairKey = `${from}\u0000${to}`;
    aggregated.set(
      pairKey,
      (aggregated.get(pairKey) ?? 0) + edge.fileDependencies,
    );
  }

  const edgeLines = [...aggregated.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([edgeKey, count]) => {
      const [from = "", to = ""] = edgeKey.split("\u0000");
      return `${key(from)} -> ${key(to)}: {tooltip: ${quote(
        pluralise(count, "file-level dependency", "file-level dependencies"),
      )}}`;
    });

  return [
    header(generatedBy),
    `# direct sub-layers of ${parentId}\n`,
    nodeLines.join("\n"),
    "\n# dependencies\n",
    edgeLines.join("\n"),
    "\n# styling\n",
    styleClasses,
    "",
  ].join("\n");
};

/** The collapsed graph: top-level layers only, edges aggregated. */
export const buildOverviewDiagram = (
  layers: Layer[],
  edges: Edge[],
  generatedBy: string,
): string => {
  interface Group {
    name: string;
    fileCount: number;
    roles: string[];
  }

  const groups = new Map<string, Group>();

  for (const layer of layers) {
    const root = rootSegment(layer.id);
    const group = groups.get(root) ?? { name: root, fileCount: 0, roles: [] };
    group.fileCount += layer.fileCount;
    if (layer.id === root) {
      group.name = layer.name;
      group.roles.unshift(layer.role);
    }
    groups.set(root, group);
  }

  const aggregated = new Map<string, number>();
  for (const edge of edges) {
    const from = rootSegment(edge.from);
    const to = rootSegment(edge.to);
    if (from === to) {
      continue;
    }
    const key = `${from} ${to}`;
    aggregated.set(key, (aggregated.get(key) ?? 0) + edge.fileDependencies);
  }

  const nodeLines = [...groups.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(
      ([id, group]) =>
        `${id}: {class: ${classFor(id)}; label: ${quote(group.name)}; tooltip: ${quote(
          `${pluralise(group.fileCount, "source file")}${group.roles[0] ? ` · ${group.roles[0]}` : ""}`,
        )}}`,
    );

  const edgeLines = [...aggregated.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, count]) => {
      const [from = "", to = ""] = key.split(" ");
      return `${from} -> ${to}: {tooltip: ${quote(
        pluralise(count, "file-level dependency", "file-level dependencies"),
      )}}`;
    });

  return [
    header(generatedBy),
    "# top-level layers\n",
    nodeLines.join("\n"),
    "\n# dependencies\n",
    edgeLines.join("\n"),
    "\n# styling\n",
    styleClasses,
    "",
  ].join("\n");
};

/**
 * Whether the `d2` renderer is available.
 *
 * Checked before pages are emitted so the bundle never references an SVG it
 * did not produce. `d2` is a declared repo tool, but environments that install
 * tools individually (Vercel) can legitimately lack it.
 */
export const canRenderDiagrams = (repoRoot: string): boolean => {
  const result = spawnSync(
    "mise",
    ["exec", "--env", "dev", "--", "d2", "--version"],
    { cwd: repoRoot, encoding: "utf8" },
  );
  return !result.error && result.status === 0;
};
/**
 * Renders a `.d2` file to SVG.
 *
 * `d2` is provided by mise, matching how the previous script invoked it. When it
 * is unavailable the caller is told rather than the build failing outright: the
 * `.d2` sources are the diffable artefact, and a missing renderer should not
 * block regenerating the model and pages.
 */
export const renderD2 = (
  repoRoot: string,
  sourcePath: string,
  outputPath: string,
): { ok: true } | { ok: false; error: string } => {
  const result = spawnSync(
    "mise",
    [
      "exec",
      "--env",
      "dev",
      "--",
      "d2",
      "--layout",
      "elk",
      sourcePath,
      outputPath,
    ],
    { cwd: repoRoot, encoding: "utf8" },
  );

  if (result.error) {
    return { ok: false, error: result.error.message };
  }

  if (result.status !== 0) {
    return {
      ok: false,
      error: result.stderr || result.stdout || "d2 exited non-zero",
    };
  }

  return { ok: true };
};
