/**
 * Diagram generation.
 *
 * Dotted layer ids map straight onto D2's container syntax, so
 * `core.simulation.monte-carlo` nests inside `core.simulation` inside `core`
 * with no extra bookkeeping — the taxonomy the annotations declare *is* the
 * diagram's grouping.
 *
 * Three kinds of diagram, each bounding its node count a different way:
 *
 * - the overview is a level cut at depth 1 — the top-level layers only;
 * - a layer with sub-layers gets a drill-down of its direct children;
 * - every layer, leaf or not, gets a neighbourhood showing what it depends on
 *   and what depends on it.
 *
 * The neighbourhood is the one a reader usually wants: landing on a layer page,
 * the question is what this layer touches, not what sits inside it. Leaves have
 * nothing inside them and are exactly where readers land.
 *
 * Both `.d2` source and rendered `.svg` are written.
 */

import { spawnSync } from "node:child_process";

import {
  isDeclaredEdge,
  isImportEdge,
  type DeclaredEdge,
  type Edge,
  type Layer,
} from "../model";

const quote = (text: string): string => JSON.stringify(text);

/** Top-level ancestor of a dotted id, used for colour classing. */
const rootSegment = (id: string): string => id.split(".")[0] ?? id;

const styleClasses = [
  `classes: {`,
  `  core: {style.fill: "#dcecff"; style.stroke: "#3676b8"}`,
  `  react: {style.fill: "#e8e0ff"; style.stroke: "#7051b5"}`,
  `  ui: {style.fill: "#e2f4e8"; style.stroke: "#3d8055"}`,
  `  petrinaut: {style.fill: "#fdeedc"; style.stroke: "#b5762f"}`,
  `  cli: {style.fill: "#fbe3e8"; style.stroke: "#ad3a5b"}`,
  `  python-bindings: {style.fill: "#fff4d6"; style.stroke: "#a3801f"}`,
  `  optimizer: {style.fill: "#e0f2f1"; style.stroke: "#2b7a72"}`,
  `  other: {style.fill: "#f2f2f2"; style.stroke: "#777777"}`,
  `  boundary: {style.stroke-dash: 4}`,
  `  declared: {style.stroke-dash: 2}`,
  `  focus: {style.stroke-width: 3; style.bold: true}`,
  `  elided: {style.fill: "#ffffff"; style.stroke: "#aaaaaa"; style.stroke-dash: 3; style.italic: true}`,
  `}`,
].join("\n");

const knownRoots = [
  "core",
  "react",
  "ui",
  "petrinaut",
  "cli",
  "python-bindings",
  "optimizer",
];

const classFor = (id: string): string => {
  const root = rootSegment(id);
  return knownRoots.includes(root) ? root : "other";
};

const pluralise = (count: number, singular: string, plural?: string): string =>
  `${count} ${count === 1 ? singular : (plural ?? `${singular}s`)}`;

const header = (generatedBy: string): string =>
  `# Generated by ${generatedBy}. Edit the annotations in the source, not this file.\n\ndirection: right\n`;

/**
 * D2 reads `.` as container nesting, so a dotted id used as a key would make it
 * synthesise ancestor boxes. Flattening to `_` keeps every node a peer, which is
 * what a neighbourhood diagram wants — the focus and its neighbours sit
 * alongside each other regardless of where they live in the taxonomy.
 */
const flatKey = (id: string): string => id.replace(/\./gu, "_");

/** Tooltip shared by every rendering of a `@talksTo` edge. */
const declaredTooltip =
  "declared with @talksTo; no import crosses this boundary";

/** A declared edge: dashed, labelled with the protocol the annotation names. */
const declaredEdgeLine = (
  from: string,
  to: string,
  edge: DeclaredEdge,
): string =>
  `${from} -> ${to}: ${quote(edge.protocol)} {class: declared; tooltip: ${quote(declaredTooltip)}}`;

/**
 * How many neighbours a neighbourhood diagram draws before eliding the rest.
 *
 * Bounded because a widely-depended-on layer (`core.types`) would otherwise
 * produce a diagram with every consumer in the system on it, which is accurate
 * and unreadable. The elided count is drawn as its own node rather than dropped,
 * so the diagram never implies a layer has fewer neighbours than it does.
 */
const maxNeighbours = 12;

/**
 * One diagram per layer, showing what it depends on and what depends on it.
 *
 * Only edges *incident to the focus* are drawn. Edges among the neighbours
 * themselves are real but belong to those layers' own pages; including them
 * turns a readable star into the same tangle the overview already avoids.
 */
export const buildNeighbourhoodDiagram = (
  focusId: string,
  layers: Layer[],
  edges: Edge[],
  generatedBy: string,
): string => {
  const layersById = new Map(layers.map((layer) => [layer.id, layer]));
  const focus = layersById.get(focusId);

  /** Neighbour id → dependencies in each direction. */
  const neighbours = new Map<string, { out: number; in: number }>();

  const record = (
    otherId: string,
    direction: "out" | "in",
    count: number,
  ): void => {
    const entry = neighbours.get(otherId) ?? { out: 0, in: 0 };
    entry[direction] += count;
    neighbours.set(otherId, entry);
  };

  for (const edge of edges) {
    if (!isImportEdge(edge)) {
      continue;
    }
    if (edge.from === focusId && edge.to !== focusId) {
      record(edge.to, "out", edge.fileDependencies);
    } else if (edge.to === focusId && edge.from !== focusId) {
      record(edge.from, "in", edge.fileDependencies);
    }
  }

  // Declared edges bypass the neighbour cap: each is a hand-written annotation,
  // so their number stays small, and eliding one would hide the only record of
  // a boundary no import reaches.
  const declaredEdges = edges
    .filter(isDeclaredEdge)
    .filter(
      (edge) =>
        (edge.from === focusId || edge.to === focusId) && edge.from !== edge.to,
    );

  const ranked = [...neighbours.entries()].sort(
    ([leftId, left], [rightId, right]) =>
      right.out + right.in - (left.out + left.in) ||
      leftId.localeCompare(rightId),
  );

  const shown = ranked.slice(0, maxNeighbours);
  const elided = ranked.slice(maxNeighbours);

  const nodeLines = [
    `${flatKey(focusId)}: {class: [${classFor(focusId)}; focus]; label: ${quote(
      focus?.name ?? focusId,
    )}; tooltip: ${quote(focus?.role ?? focusId)}}`,
    ...shown.map(([id]) => {
      const layer = layersById.get(id);
      return `${flatKey(id)}: {class: ${classFor(id)}; label: ${quote(
        layer?.name ?? id,
      )}; tooltip: ${quote(layer?.role ?? id)}}`;
    }),
  ];

  const drawnIds = new Set(shown.map(([id]) => id));
  for (const edge of declaredEdges) {
    const otherId = edge.from === focusId ? edge.to : edge.from;
    if (drawnIds.has(otherId)) {
      continue;
    }
    drawnIds.add(otherId);
    const other = layersById.get(otherId);
    nodeLines.push(
      `${flatKey(otherId)}: {class: ${classFor(otherId)}; label: ${quote(
        other?.name ?? otherId,
      )}; tooltip: ${quote(other?.role ?? otherId)}}`,
    );
  }

  const elidedOut = elided.reduce((sum, [, counts]) => sum + counts.out, 0);
  const elidedIn = elided.reduce((sum, [, counts]) => sum + counts.in, 0);

  if (elided.length > 0) {
    const total = elidedOut + elidedIn;
    nodeLines.push(
      `elided: {class: elided; label: ${quote(
        `+${pluralise(elided.length, "further layer")}`,
      )}; tooltip: ${quote(
        `${pluralise(total, "file-level dependency", "file-level dependencies")}, omitted to keep the diagram readable — the full list is in the tables below`,
      )}}`,
    );
  }

  const edgeLines: string[] = [];

  for (const [id, counts] of shown) {
    if (counts.out > 0) {
      edgeLines.push(
        `${flatKey(focusId)} -> ${flatKey(id)}: {tooltip: ${quote(
          pluralise(
            counts.out,
            "file-level dependency",
            "file-level dependencies",
          ),
        )}}`,
      );
    }
    if (counts.in > 0) {
      edgeLines.push(
        `${flatKey(id)} -> ${flatKey(focusId)}: {tooltip: ${quote(
          pluralise(
            counts.in,
            "file-level dependency",
            "file-level dependencies",
          ),
        )}}`,
      );
    }
  }

  for (const edge of declaredEdges) {
    edgeLines.push(
      declaredEdgeLine(flatKey(edge.from), flatKey(edge.to), edge),
    );
  }

  // Drawn dashed and in whichever directions the elided layers actually use, so
  // the summary node reads as part of the graph rather than as a stray legend.
  if (elidedOut > 0) {
    edgeLines.push(
      `${flatKey(focusId)} -> elided: {class: boundary; tooltip: ${quote(
        pluralise(
          elidedOut,
          "file-level dependency",
          "file-level dependencies",
        ),
      )}}`,
    );
  }
  if (elidedIn > 0) {
    edgeLines.push(
      `elided -> ${flatKey(focusId)}: {class: boundary; tooltip: ${quote(
        pluralise(elidedIn, "file-level dependency", "file-level dependencies"),
      )}}`,
    );
  }

  if (nodeLines.length === 1) {
    nodeLines.push(
      `isolated: {class: elided; label: ${quote("no dependencies either way")}}`,
    );
  }

  return [
    header(generatedBy),
    `# what ${focusId} depends on, and what depends on it\n`,
    nodeLines.join("\n"),
    "\n# dependencies\n",
    edgeLines.join("\n"),
    "\n# styling\n",
    styleClasses,
    "",
  ].join("\n");
};

/**
 * One diagram per layer that has sub-layers, showing only its *direct* children.
 *
 * Nesting the entire sub-tree produced an unreadable tangle — 23 layers under
 * `core` with every inter-layer edge drawn is technically accurate and useless.
 * Showing one level at a time, with edges aggregated up to that level, keeps each
 * diagram legible and lets a reader drill down through the pages instead.
 */
export const buildSubtreeDiagram = (
  parentId: string,
  layers: Layer[],
  edges: Edge[],
  generatedBy: string,
): string => {
  const children = layers.filter((layer) => layer.parent === parentId);
  const childIds = children.map((layer) => layer.id);

  /**
   * D2 reads `.` as container nesting, so a full dotted id as a key would make
   * it synthesise the ancestor boxes this diagram exists to leave out. The leaf
   * segment is unique among siblings, which is all a single-level diagram needs.
   */
  const key = (layerId: string): string => layerId.slice(parentId.length + 1);

  /** The direct child of `parentId` that `layerId` sits under, if any. */
  const childScopeOf = (layerId: string): string | null =>
    childIds.find(
      (childId) => layerId === childId || layerId.startsWith(`${childId}.`),
    ) ?? null;

  /** Total files in a child, including its own descendants. */
  const totalFiles = (childId: string): number =>
    layers
      .filter(
        (layer) => layer.id === childId || layer.id.startsWith(`${childId}.`),
      )
      .reduce((total, layer) => total + layer.fileCount, 0);

  const nodeLines = children.map((child) => {
    const descendants = layers.filter((layer) =>
      layer.id.startsWith(`${child.id}.`),
    ).length;
    const detail =
      descendants === 0
        ? pluralise(totalFiles(child.id), "source file")
        : `${pluralise(totalFiles(child.id), "source file")}, ${pluralise(descendants, "sub-layer")}`;

    return `${key(child.id)}: {class: ${classFor(child.id)}; label: ${quote(child.name)}; tooltip: ${quote(`${detail} · ${child.role}`)}}`;
  });

  const aggregated = new Map<string, number>();
  for (const edge of edges) {
    if (!isImportEdge(edge)) {
      continue;
    }
    const from = childScopeOf(edge.from);
    const to = childScopeOf(edge.to);
    if (from === null || to === null || from === to) {
      continue;
    }
    const pairKey = `${from}\u0000${to}`;
    aggregated.set(
      pairKey,
      (aggregated.get(pairKey) ?? 0) + edge.fileDependencies,
    );
  }

  const edgeLines = [...aggregated.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([edgeKey, count]) => {
      const [from = "", to = ""] = edgeKey.split("\u0000");
      return `${key(from)} -> ${key(to)}: {tooltip: ${quote(
        pluralise(count, "file-level dependency", "file-level dependencies"),
      )}}`;
    });

  // Declared edges keep their individual protocol labels rather than being
  // aggregated: two protocols between the same pair are two facts.
  for (const edge of edges.filter(isDeclaredEdge)) {
    const from = childScopeOf(edge.from);
    const to = childScopeOf(edge.to);
    if (from === null || to === null || from === to) {
      continue;
    }
    edgeLines.push(declaredEdgeLine(key(from), key(to), edge));
  }

  return [
    header(generatedBy),
    `# direct sub-layers of ${parentId}\n`,
    nodeLines.join("\n"),
    "\n# dependencies\n",
    edgeLines.join("\n"),
    "\n# styling\n",
    styleClasses,
    "",
  ].join("\n");
};

/** The collapsed graph: top-level layers only, edges aggregated. */
export const buildOverviewDiagram = (
  layers: Layer[],
  edges: Edge[],
  generatedBy: string,
): string => {
  interface Group {
    name: string;
    fileCount: number;
    roles: string[];
  }

  const groups = new Map<string, Group>();

  for (const layer of layers) {
    const root = rootSegment(layer.id);
    const group = groups.get(root) ?? { name: root, fileCount: 0, roles: [] };
    group.fileCount += layer.fileCount;
    if (layer.id === root) {
      group.name = layer.name;
      group.roles.unshift(layer.role);
    }
    groups.set(root, group);
  }

  const aggregated = new Map<string, number>();
  for (const edge of edges) {
    if (!isImportEdge(edge)) {
      continue;
    }
    const from = rootSegment(edge.from);
    const to = rootSegment(edge.to);
    if (from === to) {
      continue;
    }
    const key = `${from} ${to}`;
    aggregated.set(key, (aggregated.get(key) ?? 0) + edge.fileDependencies);
  }

  const nodeLines = [...groups.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(
      ([id, group]) =>
        `${id}: {class: ${classFor(id)}; label: ${quote(group.name)}; tooltip: ${quote(
          `${pluralise(group.fileCount, "source file")}${group.roles[0] ? ` · ${group.roles[0]}` : ""}`,
        )}}`,
    );

  const edgeLines = [...aggregated.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, count]) => {
      const [from = "", to = ""] = key.split(" ");
      return `${from} -> ${to}: {tooltip: ${quote(
        pluralise(count, "file-level dependency", "file-level dependencies"),
      )}}`;
    });

  for (const edge of edges.filter(isDeclaredEdge)) {
    const from = rootSegment(edge.from);
    const to = rootSegment(edge.to);
    if (from === to) {
      continue;
    }
    edgeLines.push(declaredEdgeLine(from, to, edge));
  }

  return [
    header(generatedBy),
    "# top-level layers\n",
    nodeLines.join("\n"),
    "\n# dependencies\n",
    edgeLines.join("\n"),
    "\n# styling\n",
    styleClasses,
    "",
  ].join("\n");
};

/**
 * Whether the `d2` renderer is available.
 *
 * Checked before pages are emitted so the bundle never references an SVG it
 * did not produce. `d2` is a declared repo tool, but environments that install
 * tools individually (Vercel) can legitimately lack it.
 */
export const canRenderDiagrams = (repoRoot: string): boolean => {
  const result = spawnSync(
    "mise",
    ["exec", "--env", "dev", "--", "d2", "--version"],
    { cwd: repoRoot, encoding: "utf8" },
  );
  return !result.error && result.status === 0;
};
/**
 * Renders a `.d2` file to SVG.
 *
 * `d2` is provided by mise, matching how the previous script invoked it. When it
 * is unavailable the caller is told rather than the build failing outright: the
 * `.d2` sources are the diffable artefact, and a missing renderer should not
 * block regenerating the model and pages.
 */
export const renderD2 = (
  repoRoot: string,
  sourcePath: string,
  outputPath: string,
): { ok: true } | { ok: false; error: string } => {
  const result = spawnSync(
    "mise",
    [
      "exec",
      "--env",
      "dev",
      "--",
      "d2",
      "--layout",
      "elk",
      sourcePath,
      outputPath,
    ],
    { cwd: repoRoot, encoding: "utf8" },
  );

  if (result.error) {
    return { ok: false, error: result.error.message };
  }

  if (result.status !== 0) {
    return {
      ok: false,
      error: result.stderr || result.stdout || "d2 exited non-zero",
    };
  }

  return { ok: true };
};
