//! RMS alignment error over point correspondences.
//!
//! For n > 0 paired points pᵢ and qᵢ, the model is RMS = √(Σᵢ‖aRpᵢ + t − qᵢ‖² / n), using the
//! similarity's scale a, rotation R and translation t. This measures the error left after
//! alignment. Coefficients widen to `f64` before application, and squared errors accumulate in
//! `f64`, serially or in parallel.
//!
//! Finite fields and finite similarity coefficients keep this computation within `f64` range on
//! 32-bit and 64-bit targets. The fields establish coordinate finiteness, but the similarity
//! constructors do not validate every coefficient. SIMD batches and the scalar remainder use
//! different fusion, and parallel reduction changes grouping. The result is an approximation with
//! no bitwise-equivalence promise between these evaluations.

use core::simd::{Simd, num::SimdFloat as _};

use hashql_core::id::Id;
use rayon::{
    iter::{IndexedParallelIterator as _, ParallelIterator as _},
    slice::ParallelSlice as _,
};

use super::Similarity;
use crate::math::{
    DNonNegative, FinitePointField,
    dvec2::{DVec2, DVec2x4T},
    vec2::{Vec2, Vec2x4, Vec2x4T},
};

impl Similarity {
    /// Returns the root-mean-square distance from transformed source points to their targets.
    ///
    /// For a fitted alignment, this measures the remaining movement beyond uniform scale, rotation
    /// and translation. Coefficients widen to `f64` before application. This can differ from
    /// measuring the `f32` outputs of [`apply`](Self::apply), even for targets generated by that
    /// method.
    ///
    /// The similarity's rotation and translation coefficients must be finite. Successful fits
    /// establish this condition, but arbitrary construction and inverse/composition operations may
    /// not. With this condition and the fields' finite coordinates, the squared sum and RMS remain
    /// finite on 32-bit and 64-bit targets.
    ///
    /// # Panics
    ///
    /// This panics when the field lengths differ or the fields are empty, because the residual
    /// is defined over matched pairs and an empty set has no mean.
    ///
    /// # Complexity
    ///
    /// O(n) time and constant additional storage for n pairs.
    ///
    /// # Example
    ///
    /// This example is ignored because [`Similarity`] and [`FinitePointField`] are crate-private.
    ///
    /// ```ignore
    /// use hashql_core::id::IdSlice;
    /// use crate::math::{FinitePointField, Similarity, Vec2};
    /// # hashql_core::id::newtype! { struct RowId(u32) }
    ///
    /// let source = [Vec2::new(0.0, 0.0), Vec2::new(1.0, 0.0)];
    /// // Both targets are displaced by (0.0, 3.0) from the identity images.
    /// // The RMS is exactly √((9 + 9) / 2) = 3.
    /// let target = [Vec2::new(0.0, 3.0), Vec2::new(1.0, 3.0)];
    ///
    /// let source = FinitePointField::new(IdSlice::<RowId, _>::from_raw(&source))
    ///     .expect("the sources are finite");
    /// let target = FinitePointField::new(IdSlice::from_raw(&target))
    ///     .expect("the targets are finite");
    /// let residual = Similarity::IDENTITY.rms_residual(source, target);
    /// assert!((residual.get() - 3.0).abs() < 1e-12);
    /// ```
    #[must_use]
    pub(crate) fn rms_residual<I: Id>(
        self,
        source: &FinitePointField<I>,
        target: &FinitePointField<I>,
    ) -> DNonNegative {
        assert_eq!(
            source.len(),
            target.len(),
            "paired fields must cover the same rows"
        );
        assert!(
            !source.is_empty(),
            "an RMS residual needs at least one pair"
        );

        finish_rms(
            self.squared_residuals(source.as_raw(), target.as_raw()),
            source.len(),
        )
    }

    /// Returns the root-mean-square residual of large fields in parallel.
    ///
    /// The coefficient-finiteness requirement and numerical model are those of
    /// [`rms_residual`](Self::rms_residual). Work splits into chunks of
    /// [`PARALLEL_CHUNK`](Self::PARALLEL_CHUNK) pairs. Different grouping changes rounding, and no
    /// fixed ULP difference or bitwise reproducibility is promised. Benchmark the serial and
    /// parallel forms for the intended input size and hardware.
    ///
    /// # Panics
    ///
    /// This panics when the field lengths differ or the fields are empty.
    #[must_use]
    pub(crate) fn rms_residual_par<I: Id>(
        self,
        source: &FinitePointField<I>,
        target: &FinitePointField<I>,
    ) -> DNonNegative {
        assert_eq!(
            source.len(),
            target.len(),
            "paired fields must cover the same rows"
        );
        assert!(
            !source.is_empty(),
            "an RMS residual needs at least one pair"
        );

        let chunk = Self::PARALLEL_CHUNK.get();
        let squared = source
            .as_raw()
            .par_chunks(chunk)
            .zip(target.as_raw().par_chunks(chunk))
            .map(|(source, target)| self.squared_residuals(source, target))
            .sum();

        finish_rms(squared, source.len())
    }

    /// Accumulates squared transformed-source-to-target distances in double precision.
    ///
    /// The slices must have equal lengths and finite coordinates, and the similarity's coefficients
    /// must all be finite. The sum is then nonnegative and finite on 32-bit and 64-bit targets, by
    /// the bound at [`finish_rms`].
    fn squared_residuals(self, source: &[Vec2], target: &[Vec2]) -> f64 {
        // fold the scale into the rotation columns in double precision
        let scale = f64::from(self.scale);
        let cos = scale * f64::from(self.rotation.cos());
        let sin = scale * f64::from(self.rotation.sin());
        let translation = DVec2::from(self.translation);

        let (source_batches, source_rest) = source.as_chunks::<4>();
        let (target_batches, target_rest) = target.as_chunks::<4>();

        let cos_lanes = Simd::splat(cos);
        let sin_lanes = Simd::splat(sin);
        let mut squared_sum = Simd::splat(0.0_f64);
        for (source, target) in source_batches.iter().zip(target_batches) {
            let source = DVec2x4T::from(Vec2x4T::from(Vec2x4::from(*source)));
            let target = DVec2x4T::from(Vec2x4T::from(Vec2x4::from(*target)));

            let residual = DVec2x4T::from_lanes(
                cos_lanes * source.xs() - sin_lanes * source.ys() + Simd::splat(translation.x())
                    - target.xs(),
                sin_lanes * source.xs() + cos_lanes * source.ys() + Simd::splat(translation.y())
                    - target.ys(),
            );
            squared_sum += residual.length_squared();
        }

        let mut squared = squared_sum.reduce_sum();
        for (&source, &target) in source_rest.iter().zip(target_rest) {
            let source = DVec2::from(source);
            let target = DVec2::from(target);

            let residual = DVec2::new(
                cos.mul_add(source.x(), (-sin).mul_add(source.y(), translation.x())) - target.x(),
                sin.mul_add(source.x(), cos.mul_add(source.y(), translation.y())) - target.y(),
            );
            squared += residual.norm_squared().into_raw();
        }

        squared
    }
}

/// Divides a squared-error sum by its positive pair count and takes the square root.
///
/// `squared` must be nonnegative and finite, and `pairs` must be nonzero.
#[expect(
    clippy::cast_precision_loss,
    reason = "pair counts remain exactly representable in f64 far beyond any corpus"
)]
fn finish_rms(squared: f64, pairs: usize) -> DNonNegative {
    // Finite f32 coordinates and coefficients have magnitude below 2¹²⁸. Each residual component
    // has two scale-rotation-coordinate products below 2³⁸⁴, plus translation and target terms.
    // Allowing for the fixed-operation rounding, a squared pair error is nonnegative and below B =
    // 2⁷⁷⁴. On 32-bit and 64-bit targets, an 8-byte-point slice contains n < 2⁶⁰ pairs. Adding
    // initialization or unused-lane zeros is exact for these nonnegative finite terms. Along a
    // term's path, fewer than n additions combine contributions. With binary64 unit roundoff u =
    // 2⁻⁵³, their amplification is at most (1 + u)ⁿ < exp(128) < 2¹⁸⁵. Thus the rounded sum is
    // below nB · 2¹⁸⁵ < 2¹⁰¹⁹, within f64 range. Subnormal additions cannot threaten this upper
    // bound. Dividing by the positive converted count and taking its square root preserve
    // finiteness and nonnegativity. Therefore the result satisfies DNonNegative's numerical
    // domain.
    DNonNegative::new_unchecked((squared / pairs as f64).sqrt())
}
