[package]
authors.workspace = true
description       = "The HASH Status and Error Model."
edition.workspace = true
license           = "MIT OR Apache-2.0"
name              = "hash-status"
publish.workspace = true
version.workspace = true

[dependencies]
# Public workspace dependencies

# Public third-party dependencies
serde_core = { workspace = true, public = true }

# Private workspace dependencies

# Private third-party dependencies
serde          = { workspace = true, features = ["alloc", "derive"] }
simple-mermaid = { workspace = true }

[lints]
workspace = true
