export type AppState = {
  embedUrl: string;
  embedType: ProviderName | undefined;
  html?: string;
  height?: number;
  width?: number;
  maxWidth: number;
  loading: boolean;
  errorString: string;
};

export type Actions =
  | { type: "UPDATE_STATE"; payload: Partial<AppState> }
  | { type: "RESET_STATE" };

export type ProviderName =
  | "23HQ"
  | "Bopp"
  | "GIPHY"
  | "Infoveave"
  | "Injurymap"
  | "TikTok"
  | "Abraia"
  | "ActBlue"
  | "Adways"
  | "Alpha App Net"
  | "Altium LLC"
  | "Altru"
  | "amCharts Live Editor"
  | "Animatron"
  | "Animoto"
  | "AnnieMusic"
  | "Apester"
  | "Archivos"
  | "Audioboom"
  | "AudioClip"
  | "Audiomack"
  | "Avocode"
  | "AxiomNinja"
  | "Backtracks"
  | "Beautiful.AI"
  | "Blackfire.io"
  | "Blogcast"
  | "Box Office Buz"
  | "BrioVR"
  | "Buttondown"
  | "Byzart Project"
  | "Cacoo"
  | "Carbon Health"
  | "CatBoat"
  | "Ceros"
  | "Chainflix"
  | "ChartBlocks"
  | "chirbit.com"
  | "CircuitLab"
  | "Clipland"
  | "Clyp"
  | "CoCo Corp"
  | "CodeHS"
  | "CodePen"
  | "Codepoints"
  | "CodeSandbox"
  | "CollegeHumor"
  | "Commaful"
  | "Coub"
  | "Crowd Ranking"
  | "Cueup DJ Booking"
  | "Curated"
  | "CustomerDB"
  | "Cyrano Systems"
  | "Dailymotion"
  | "Datawrapper"
  | "Deseret News"
  | "Deviantart.com"
  | "Didacte"
  | "Digiteka"
  | "Dipity"
  | "DocDroid"
  | "Dotsub"
  | "DTube"
  | "edocr"
  | "eduMedia"
  | "EgliseInfo"
  | "Embed Articles"
  | "Embedery"
  | "Embedly"
  | "Enystre Music"
  | "Ethfiddle"
  | "Ex.Co"
  | "Eyrie"
  | "Facebook"
  | "Fader"
  | "Faithlife TV"
  | "Firework"
  | "FITE"
  | "Flat"
  | "Flickr"
  | "Flourish"
  | "FOX SPORTS Australia"
  | "FrameBuzz"
  | "Framer"
  | "FunnyOrDie"
  | "Geograph Britain and Ireland"
  | "Geograph Channel Islands"
  | "Geograph Germany"
  | "Show by Animaker"
  | "Getty Images"
  | "Gfycat"
  | "Gifnote"
  | "GloriaTV"
  | "Gong"
  | "Grain"
  | "GT Channel"
  | "Gyazo"
  | "HASH"
  | "hearthis.at"
  | "hihaho"
  | "HippoVideo"
  | "Homey"
  | "Hosted by You"
  | "HuffDuffer"
  | "Hulu"
  | "Idomoo"
  | "iFixit"
  | "IFTTT"
  | "iHeartRadio"
  | "Indaco"
  | "Infogram"
  | "Inoreader"
  | "inphood"
  | "Instagram"
  | "Insticator Inc"
  | "Issuu"
  | "ivlismusic"
  | "Jovian"
  | "KakaoTv"
  | "Kickstarter"
  | "Kidoju"
  | "Kirim.Email"
  | "Kit"
  | "Kitchenbowl"
  | "kmdr"
  | "Knacki"
  | "Knowledge Pad"
  | "LearningApps.org"
  | "Livestream"
  | "LottieFiles"
  | "Ludus"
  | "Lumiere"
  | "MathEmbed"
  | "Matterport"
  | "MediaLab"
  | "Medienarchiv der Künste - Zürcher Hochschule der Künste"
  | "Meetup"
  | "me.me"
  | "Mermaid Ink"
  | "Microlink"
  | "Microsoft Stream"
  | "Minerva"
  | "MixCloud"
  | "Moby Picture"
  | "Modelo"
  | "MorphCast"
  | "Music Box Maniacs"
  | "myBeweeg"
  | "Namchey"
  | "nanoo.tv"
  | "Nasjonalbiblioteket"
  | "Natural Atlas"
  | "nfb.ca"
  | "NoPaste"
  | "Observable"
  | "Odds.com.au"
  | "Official FM"
  | "Omniscope"
  | "Omny Studio"
  | "On Aol"
  | "Opsomai"
  | "Ora TV"
  | "Orbitvu"
  | "Oumy"
  | "Outplayed.tv"
  | "Overflow"
  | "OZ"
  | "Padlet"
  | "Pastery"
  | "PingVP"
  | "Pinpoll"
  | "Pinterest"
  | "Pixdor"
  | "LeMans.Pod"
  | "Lille.Pod"
  | "Upec.Pod"
  | "UnivParis1.Pod"
  | "Podbean"
  | "Polaris Share"
  | "Poll Daddy"
  | "Port"
  | "Portfolium"
  | "posiXion"
  | "Prezi Video"
  | "Qualifio"
  | "Quiz.biz"
  | "Quizz.biz"
  | "RadioPublic"
  | "rcvis"
  | "Reddit"
  | "ReleaseWire"
  | "Replit"
  | "RepubHub"
  | "ReverbNation"
  | "RiffReporter"
  | "Roomshare"
  | "RoosterTeeth"
  | "Rumble"
  | "Runkit"
  | "Saooti"
  | "Sapo Videos"
  | "Screen9"
  | "Screencast.com"
  | "Screenr"
  | "ScribbleMaps"
  | "Scribd"
  | "SendtoNews"
  | "ShortNote"
  | "Shoudio"
  | "Show the Way, actionable location info"
  | "Simplecast"
  | "Sizzle"
  | "Sketchfab"
  | "SlideShare"
  | "SmashNotes"
  | "SmugMug"
  | "SocialExplorer"
  | "Odesli (formerly Songlink)"
  | "SoundCloud"
  | "SpeakerDeck"
  | "Spotful"
  | "Spotify"
  | "Spreaker"
  | "SproutVideo"
  | "Stanford Digital Repository"
  | "ArcGIS StoryMaps"
  | "Streamable"
  | "StreamOneCloud"
  | "Subscribi"
  | "Sudomemo"
  | "Sutori"
  | "Sway"
  | "TED"
  | "The New York Times"
  | "They Said So"
  | "TickCounter"
  | "Toornament"
  | "Topy"
  | "TourHero"
  | "Tumblr"
  | "Tuxx"
  | "tvcf"
  | "Twitter"
  | "TypeCast"
  | "Typlog"
  | "Ubideo"
  | "University of Cambridge Map"
  | "UOL"
  | "uppy"
  | "Ustream"
  | "uStudio, Inc."
  | "Utposts"
  | "Uttles"
  | "VeeR VR"
  | "Verse"
  | "VEVO"
  | "VideoJug"
  | "Vidlit"
  | "Vidmizer"
  | "Vidyard"
  | "Vimeo"
  | "Viously"
  | "Viziosphere"
  | "Vizydrop"
  | "Vlipsy"
  | "VLIVE"
  | "Vlurb"
  | "VoxSnap"
  | "Wave.video"
  | "wecandeo"
  | "Wiredrive"
  | "Wistia, Inc."
  | "wizer.me"
  | "Wokwi"
  | "Wolfram Cloud"
  | "Wootled"
  | "WordPress.com"
  | "Xpression"
  | "Yes, I Know IT!"
  | "YFrog"
  | "YouTube"
  | "Zeplin"
  | "ZingSoft"
  | "ZnipeTV"
  | "Zoomable";
