graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hash_graph/index.html">hash-graph</a>]
    1[<a href="../type_system/index.html">type-system</a>]
    2[<a href="../hash_codec/index.html">hash-codec</a>]
    3[<a href="../hash_codegen/index.html">hash-codegen</a>]
    4[<a href="../hash_graph_api/index.html">hash-graph-api</a>]
    5[<a href="../hash_graph_authorization/index.html">hash-graph-authorization</a>]
    6[<a href="../hash_graph_embeddings/index.html">hash-graph-embeddings</a>]
    7[<a href="../hash_graph_migrations/index.html">hash-graph-migrations</a>]
    8[<a href="../hash_graph_migrations_macros/index.html">hash-graph-migrations-macros</a>]
    9[<a href="../hash_graph_postgres_store/index.html">hash-graph-postgres-store</a>]
    10[<a href="../hash_graph_store/index.html">hash-graph-store</a>]
    11[<a href="../hash_graph_temporal_versioning/index.html">hash-graph-temporal-versioning</a>]
    12[<a href="../hash_graph_types/index.html">hash-graph-types</a>]
    13[<a href="../hash_graph_validation/index.html">hash-graph-validation</a>]
    14[<a href="../harpc_types/index.html">harpc-types</a>]
    15[<a href="../harpc_wire_protocol/index.html">harpc-wire-protocol</a>]
    16[<a href="../hashql_ast/index.html">hashql-ast</a>]
    17[hashql-compiletest]
    class 17 root
    18[<a href="../hashql_core/index.html">hashql-core</a>]
    19[<a href="../hashql_diagnostics/index.html">hashql-diagnostics</a>]
    20[<a href="../hashql_eval/index.html">hashql-eval</a>]
    21[<a href="../hashql_hir/index.html">hashql-hir</a>]
    22[<a href="../hashql_macros/index.html">hashql-macros</a>]
    23[<a href="../hashql_mir/index.html">hashql-mir</a>]
    24[<a href="../hashql_syntax_jexpr/index.html">hashql-syntax-jexpr</a>]
    25[<a href="../hash_status/index.html">hash-status</a>]
    26[<a href="../hash_telemetry/index.html">hash-telemetry</a>]
    27[<a href="../hash_temporal_client/index.html">hash-temporal-client</a>]
    28[<a href="../darwin_kperf/index.html">darwin-kperf</a>]
    29[<a href="../darwin_kperf_criterion/index.html">darwin-kperf-criterion</a>]
    30[<a href="../darwin_kperf_events/index.html">darwin-kperf-events</a>]
    31[<a href="../darwin_kperf_sys/index.html">darwin-kperf-sys</a>]
    32[<a href="../error_stack/index.html">error-stack</a>]
    33[<a href="../hash_graph_benches/index.html">hash-graph-benches</a>]
    34[<a href="../hash_graph_test_data/index.html">hash-graph-test-data</a>]
    0 --> 4
    1 --> 11
    1 -.-> 34
    2 -.-> 3
    2 --> 15
    4 --> 20
    4 --> 24
    5 --> 1
    6 --> 12
    6 -.-> 29
    7 --> 8
    7 --> 26
    9 --> 6
    9 --> 7
    9 -.-> 9
    9 --> 13
    9 --> 25
    10 --> 5
    10 --> 12
    10 --> 27
    11 --> 2
    12 -.-> 34
    13 -.-> 34
    15 -.-> 14
    15 --> 14
    15 --> 32
    16 -.-> 17
    17 --> 20
    17 --> 24
    18 --> 2
    18 --> 19
    18 --> 22
    18 -.-> 29
    20 --> 9
    20 --> 23
    21 -.-> 17
    23 --> 21
    24 --> 16
    24 --> 18
    26 --> 32
    27 --> 1
    28 --> 30
    28 --> 31
    29 --> 28
    33 -.-> 4
    34 --> 10
