graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hashql_ast">hashql-ast</a>]
    1[hashql-compiletest]
    class 1 root
    2[<a href="../hashql_core">hashql-core</a>]
    3[<a href="../hashql_diagnostics">hashql-diagnostics</a>]
    4[<a href="../hashql_hir">hashql-hir</a>]
    5[<a href="../hashql_syntax_jexpr">hashql-syntax-jexpr</a>]
    6[<a href="../error_stack">error-stack</a>]
    0 -.-> 1
    1 --> 4
    1 --> 5
    2 --> 3
    3 --> 6
    4 -.-> 1
    5 --> 0
    5 --> 2
