[package]
authors.workspace = true
description       = "HTTP Problem Details with typed extensions and JSON Schema support"
documentation     = "https://docs.rs/problematic"
edition.workspace = true
exclude           = ["turbo.json", "docs/task-dependencies.json"]
license           = "MIT OR Apache-2.0"
name              = "problematic"
repository        = "https://github.com/hashintel/hash/tree/main/libs/problematic/rust"
version           = "0.0.0"

[dependencies]
# Public workspace dependencies

# Public third-party dependencies
erased-serde = { workspace = true, public = true, features = ["alloc"] }
http         = { workspace = true, public = true }
schemars     = { workspace = true, public = true }
serde_core   = { workspace = true, public = true }

# Public third-party dependencies (optional)
aide      = { workspace = true, public = true, optional = true }
axum-core = { workspace = true, public = true, optional = true }

# Private workspace dependencies

# Private third-party dependencies
serde      = { workspace = true, features = ["alloc", "derive"] }
serde_json = { workspace = true, optional = true, features = ["alloc"] }
tracing    = { workspace = true, optional = true }

[dev-dependencies]
insta      = { workspace = true, features = ["json"] }
serde_json = { workspace = true, features = ["arbitrary_precision"] }

[[test]]
name              = "aide"
required-features = ["aide"]

[features]
aide = ["dep:aide", "dep:serde_json"]
axum = ["dep:axum-core", "dep:serde_json", "dep:tracing"]

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
cargo-args   = ["-Z", "unstable-options", "-Z", "rustdoc-scrape-examples"]
targets      = ["x86_64-unknown-linux-gnu"]
