[package]
authors.workspace = true
description       = "HTTP Problem Details with typed extensions and JSON Schema support"
documentation     = "https://docs.rs/problematic"
edition.workspace = true
exclude           = ["turbo.json", "docs/task-dependencies.json"]
license           = "MIT OR Apache-2.0"
name              = "problematic"
repository        = "https://github.com/hashintel/hash/tree/main/libs/problematic/rust"
version           = "0.0.0"

[dependencies]
# Public workspace dependencies
error-stack = { workspace = true, public = true, optional = true }

# Public third-party dependencies
http = { workspace = true, public = true }

# Public third-party dependencies (optional)
aide       = { workspace = true, public = true, optional = true }
schemars   = { workspace = true, public = true, optional = true }
serde_core = { workspace = true, public = true, optional = true }

# Private workspace dependencies

# Private third-party dependencies
erased-serde = { workspace = true, optional = true, features = ["alloc"] }
serde        = { workspace = true, optional = true, features = ["alloc", "derive"] }

[dev-dependencies]
insta      = { workspace = true, features = ["json"] }
serde_json = { workspace = true, features = ["arbitrary_precision"] }

[[test]]
name              = "aide"
required-features = ["aide"]

[[test]]
name              = "error_stack"
required-features = ["error-stack"]

[[test]]
name              = "extensions"
required-features = ["serde"]

[[test]]
name              = "problem"
required-features = ["serde"]

[[test]]
name              = "problem_details"
required-features = ["serde"]

[[test]]
name              = "schema"
required-features = ["schemars"]

[features]
aide        = ["dep:aide", "schemars"]
error-stack = ["dep:error-stack", "dep:erased-serde", "serde"]
schemars    = ["dep:schemars"]
serde       = ["dep:serde_core", "dep:serde"]

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
cargo-args   = ["-Z", "unstable-options", "-Z", "rustdoc-scrape-examples"]
targets      = ["x86_64-unknown-linux-gnu"]
