# This file either runs with JetBrains' http requests or using httpYac (https://httpyac.github.io).

### Seed default policies
GET http://127.0.0.1:4000/policies/seed
Content-Type: application/json

> {%
  client.test("status", function() {
    client.assert(response.status === 204, "Response status is not 204");
  });
%}

### Get system user
GET http://127.0.0.1:4000/actors/machine/identifier/system/h
Content-Type: application/json

> {%
  client.test("status", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.global.set("system_machine_id", response.body);
%}


### Create account
POST http://127.0.0.1:4000/actors/user
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{system_machine_id}}

{
  "shortname": "alice",
  "registrationComplete": true
}

> {%
  client.test("status", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.global.set("user_id", response.body.userId);
%}

### Insert length and meter data type
POST http://127.0.0.1:4000/data-types
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "schema": [
      {
        "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/data-type",
        "kind": "dataType",
        "$id": "http://localhost:3000/@alice/types/data-type/length/v/1",
        "allOf": [{
            "$ref": "https://blockprotocol.org/@blockprotocol/types/data-type/number/v/1"
        }],
        "title": "Length",
        "type": "number",
        "description": "A unit of length",
        "minimum": 0,
        "abstract": true
      },
      {
        "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/data-type",
        "kind": "dataType",
        "$id": "http://localhost:3000/@alice/types/data-type/meter/v/1",
        "allOf": [{
            "$ref": "http://localhost:3000/@alice/types/data-type/length/v/1"
        }],
        "title": "Meter",
        "type": "number",
        "description": "A unit of length"
      }
  ],
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  },
  "conversions": {}
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert millimeter data types
POST http://127.0.0.1:4000/data-types
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "schema": {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/data-type",
    "kind": "dataType",
    "$id": "http://localhost:3000/@alice/types/data-type/millimeter/v/1",
    "allOf": [{
        "$ref": "http://localhost:3000/@alice/types/data-type/length/v/1"
    }],
    "title": "Millimeter",
    "type": "number",
    "description": "A unit of length"
  },
  "conversions": {
    "http://localhost:3000/@alice/types/data-type/meter/": {
      "from": { "expression": ["*", "self", { "const": 1000, "type": "number" }] },
      "to": { "expression": ["/", "self", { "const": 1000, "type": "number" }] }
    }
  },
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert miles data types
POST http://127.0.0.1:4000/data-types
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "schema": {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/data-type",
    "kind": "dataType",
    "$id": "http://localhost:3000/@alice/types/data-type/miles/v/1",
    "allOf": [{
        "$ref": "http://localhost:3000/@alice/types/data-type/length/v/1"
    }],
    "title": "Miles",
    "type": "number",
    "description": "A unit of length"
  },
  "conversions": {
    "http://localhost:3000/@alice/types/data-type/meter/": {
      "from": { "expression": ["/", "self", { "const": 1609.344, "type": "number" }] },
      "to": { "expression": ["*", "self", { "const": 1609.344, "type": "number" }] }
    }
  },
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Insert property types
POST http://127.0.0.1:4000/property-types
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "schema": {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/property-type",
    "kind": "propertyType",
    "$id": "http://localhost:3000/@alice/types/property-type/length/v/1",
    "title": "Length",
    "description": "A length",
    "oneOf": [
      {
        "$ref": "http://localhost:3000/@alice/types/data-type/length/v/1"
      }
    ]
  },
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Insert Friendship entity link type
POST http://127.0.0.1:4000/entity-types
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "schema": {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/entity-type",
    "kind": "entityType",
    "$id": "http://localhost:3000/@alice/types/entity-type/line/v/1",
    "type": "object",
    "title": "Line",
    "description": "A line with a length",
    "properties": {
      "http://localhost:3000/@alice/types/property-type/length/": {
        "$ref": "http://localhost:3000/@alice/types/property-type/length/v/1"
      }
    }
  },
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert ambiuous entity
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "entityTypeIds": ["http://localhost:3000/@alice/types/entity-type/line/v/1"],
  "properties": {
    "value": {
      "http://localhost:3000/@alice/types/property-type/length/": {
        "value": 10,
        "metadata": {
          "dataTypeId": null
        }
      }
    }
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### Insert entity
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "entityTypeIds": ["http://localhost:3000/@alice/types/entity-type/line/v/1"],
  "properties": {
    "value": {
      "http://localhost:3000/@alice/types/property-type/length/": {
        "value": 10,
        "metadata": {
          "dataTypeId": "http://localhost:3000/@alice/types/data-type/millimeter/v/1",
          "originalDataTypeId": "http://localhost:3000/@alice/types/data-type/miles/v/1"
        }
      }
    }
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert second entity to test filtering
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "entityTypeIds": ["http://localhost:3000/@alice/types/entity-type/line/v/1"],
  "properties": {
    "value": {
      "http://localhost:3000/@alice/types/property-type/length/": {
        "value": 1,
        "metadata": {
          "dataTypeId": "http://localhost:3000/@alice/types/data-type/meter/v/1",
          "originalDataTypeId": "http://localhost:3000/@alice/types/data-type/millimeter/v/1"
        }
      }
    }
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Filter by data type ID
POST http://127.0.0.1:4000/entities/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "sortingPaths": [
    {
      "path": ["properties", "http://localhost:3000/@alice/types/property-type/length/", "convert", "http://localhost:3000/@alice/types/data-type/length/"],
      "ordering": "ascending"
    }
  ],
  "filter": {
    "greater": [
      { "path": ["properties", "http://localhost:3000/@alice/types/property-type/length/", "convert", "http://localhost:3000/@alice/types/data-type/meter/"] },
      { "parameter": 1000.0, "convert": { "from": "http://localhost:3000/@alice/types/data-type/millimeter/v/1", "to": "http://localhost:3000/@alice/types/data-type/meter/v/1" } }
    ]
  },
  "conversions": [
    {
      "path": ["http://localhost:3000/@alice/types/property-type/length/"],
      "dataTypeId": "http://localhost:3000/@alice/types/data-type/miles/v/1"
    }
  ],
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
        "start": null,
        "end": null
      }
    }
  },
  "includeDrafts": false,
  "includePermissions": false
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.entities.length === 1, "Unexpected number of entities");
        client.assert(response.body.entities[0].properties["http://localhost:3000/@alice/types/property-type/length/"] === 10, "Unexpected value");
    });
%}
