# This file either runs with JetBrains' http requests or using httpYac (https://httpyac.github.io).

### Seed default policies
GET http://127.0.0.1:4000/policies/seed
Content-Type: application/json

> {%
  client.test("status", function() {
    client.assert(response.status === 204, "Response status is not 204");
  });
%}

### Get system user
GET http://127.0.0.1:4000/actors/machine/identifier/system/h
Content-Type: application/json

> {%
  client.test("status", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.global.set("system_machine_id", response.body);
%}


### Create account
POST http://127.0.0.1:4000/actors/user
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{system_machine_id}}

{
  "shortname": "test-user",
  "registrationComplete": true
}

> {%
  client.test("status", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.global.set("user_id", response.body.userId);
%}

### Insert entity types
POST http://127.0.0.1:4000/entity-types
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "schema": [{
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/entity-type",
    "kind": "entityType",
    "$id": "http://localhost:3000/@snapshot/types/entity-type/left1/v/1",
    "type": "object",
    "title": "Left1",
    "description": "The first left entity type",
    "properties": {},
    "links": {
      "http://localhost:3000/@snapshot/types/entity-type/link1/v/1": {
        "type": "array",
        "items": {
          "oneOf": [
            {
              "$ref": "http://localhost:3000/@snapshot/types/entity-type/right1/v/1"
            }
          ]
        }
      }
    }
  }, {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/entity-type",
    "kind": "entityType",
    "$id": "http://localhost:3000/@snapshot/types/entity-type/left2/v/1",
    "type": "object",
    "title": "Left2",
    "description": "The second left entity type",
    "allOf": [{ "$ref": "http://localhost:3000/@snapshot/types/entity-type/left1/v/1" }],
    "properties": {},
    "links": {
      "http://localhost:3000/@snapshot/types/entity-type/link2/v/1": {
        "type": "array",
        "items": {
          "oneOf": [
            {
              "$ref": "http://localhost:3000/@snapshot/types/entity-type/right2/v/1"
            }
          ]
        }
      }
    }
  }, {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/entity-type",
    "kind": "entityType",
    "$id": "http://localhost:3000/@snapshot/types/entity-type/left3/v/1",
    "type": "object",
    "title": "Left3",
    "description": "The third left entity type",
    "allOf": [{ "$ref": "http://localhost:3000/@snapshot/types/entity-type/left2/v/1" }],
    "properties": {},
    "links": {
      "http://localhost:3000/@snapshot/types/entity-type/link3/v/1": {
        "type": "array",
        "items": {
          "oneOf": [
            {
              "$ref": "http://localhost:3000/@snapshot/types/entity-type/right3/v/1"
            }
          ]
        }
      }
    }
  },
  {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/entity-type",
    "kind": "entityType",
    "$id": "http://localhost:3000/@snapshot/types/entity-type/link1/v/1",
    "type": "object",
    "title": "Link1",
    "description": "A link between `Left1` and `Right1`",
    "allOf": [{ "$ref": "https://blockprotocol.org/@blockprotocol/types/entity-type/link/v/1" }],
    "properties": {}
  }, {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/entity-type",
    "kind": "entityType",
    "$id": "http://localhost:3000/@snapshot/types/entity-type/link2/v/1",
    "type": "object",
    "title": "Link2",
    "description": "A link between `Left2` and `Right2`",
    "allOf": [{ "$ref": "http://localhost:3000/@snapshot/types/entity-type/link1/v/1" }],
    "properties": {}
  }, {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/entity-type",
    "kind": "entityType",
    "$id": "http://localhost:3000/@snapshot/types/entity-type/link3/v/1",
    "type": "object",
    "title": "Link3",
    "description": "A link between `Left3` and `Right3`",
    "allOf": [{ "$ref": "http://localhost:3000/@snapshot/types/entity-type/link2/v/1" }],
    "properties": {}
  },
  {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/entity-type",
    "kind": "entityType",
    "$id": "http://localhost:3000/@snapshot/types/entity-type/right1/v/1",
    "type": "object",
    "title": "Right1",
    "description": "The first right entity type",
    "properties": {}
  }, {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/entity-type",
    "kind": "entityType",
    "$id": "http://localhost:3000/@snapshot/types/entity-type/right2/v/1",
    "type": "object",
    "title": "Right2",
    "description": "The second right entity type",
    "allOf": [{ "$ref": "http://localhost:3000/@snapshot/types/entity-type/right1/v/1" }],
    "properties": {}
  }, {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/entity-type",
    "kind": "entityType",
    "$id": "http://localhost:3000/@snapshot/types/entity-type/right3/v/1",
    "type": "object",
    "title": "Right3",
    "description": "The third right entity type",
    "allOf": [{ "$ref": "http://localhost:3000/@snapshot/types/entity-type/right2/v/1" }],
    "properties": {}
  }],
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert entity Left1
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/left1/v/1"],
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("left1", response.body.metadata.recordId.entityId);
%}

### Insert entity Left2
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/left2/v/1"],
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("left2", response.body.metadata.recordId.entityId);
%}

### Insert entity Left3
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/left3/v/1"],
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("left3", response.body.metadata.recordId.entityId);
%}

### Insert entity Right1
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/right1/v/1"],
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("right1", response.body.metadata.recordId.entityId);
%}

### Insert entity Right2
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/right2/v/1"],
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("right2", response.body.metadata.recordId.entityId);
%}

### Insert entity Right3
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/right3/v/1"],
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("right3", response.body.metadata.recordId.entityId);
%}

### Insert link1 between left1 and right1
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link1/v/1"],
  "linkData": {
    "leftEntityId": "{{left1}}",
    "rightEntityId": "{{right1}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link1 between left1 and right2
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link1/v/1"],
  "linkData": {
    "leftEntityId": "{{left1}}",
    "rightEntityId": "{{right2}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link1 between left1 and right3
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link1/v/1"],
  "linkData": {
    "leftEntityId": "{{left1}}",
    "rightEntityId": "{{right3}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link1 between left2 and right1
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link1/v/1"],
  "linkData": {
    "leftEntityId": "{{left2}}",
    "rightEntityId": "{{right1}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link1 between left2 and right2
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link1/v/1"],
  "linkData": {
    "leftEntityId": "{{left2}}",
    "rightEntityId": "{{right2}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link1 between left2 and right3
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link1/v/1"],
  "linkData": {
    "leftEntityId": "{{left2}}",
    "rightEntityId": "{{right3}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link1 between left3 and right1
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link1/v/1"],
  "linkData": {
    "leftEntityId": "{{left3}}",
    "rightEntityId": "{{right1}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link1 between left3 and right2
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link1/v/1"],
  "linkData": {
    "leftEntityId": "{{left3}}",
    "rightEntityId": "{{right2}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link1 between left3 and right3
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link1/v/1"],
  "linkData": {
    "leftEntityId": "{{left3}}",
    "rightEntityId": "{{right3}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link2 between left1 and right1
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link2/v/1"],
  "linkData": {
    "leftEntityId": "{{left1}}",
    "rightEntityId": "{{right1}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link2 between left1 and right2
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link2/v/1"],
  "linkData": {
    "leftEntityId": "{{left1}}",
    "rightEntityId": "{{right2}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link2 between left1 and right3
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link2/v/1"],
  "linkData": {
    "leftEntityId": "{{left1}}",
    "rightEntityId": "{{right3}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link2 between left2 and right1
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link2/v/1"],
  "linkData": {
    "leftEntityId": "{{left2}}",
    "rightEntityId": "{{right1}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### Insert link2 between left2 and right2
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link2/v/1"],
  "linkData": {
    "leftEntityId": "{{left2}}",
    "rightEntityId": "{{right2}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link2 between left2 and right3
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link2/v/1"],
  "linkData": {
    "leftEntityId": "{{left2}}",
    "rightEntityId": "{{right3}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link2 between left3 and right1
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link2/v/1"],
  "linkData": {
    "leftEntityId": "{{left3}}",
    "rightEntityId": "{{right1}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### Insert link2 between left3 and right2
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link2/v/1"],
  "linkData": {
    "leftEntityId": "{{left3}}",
    "rightEntityId": "{{right2}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link2 between left3 and right3
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link2/v/1"],
  "linkData": {
    "leftEntityId": "{{left3}}",
    "rightEntityId": "{{right3}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link3 between left1 and right1
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link3/v/1"],
  "linkData": {
    "leftEntityId": "{{left1}}",
    "rightEntityId": "{{right1}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link3 between left1 and right2
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link3/v/1"],
  "linkData": {
    "leftEntityId": "{{left1}}",
    "rightEntityId": "{{right2}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link3 between left1 and right3
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link3/v/1"],
  "linkData": {
    "leftEntityId": "{{left1}}",
    "rightEntityId": "{{right3}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link3 between left2 and right1
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link3/v/1"],
  "linkData": {
    "leftEntityId": "{{left2}}",
    "rightEntityId": "{{right1}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### Insert link3 between left2 and right2
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link3/v/1"],
  "linkData": {
    "leftEntityId": "{{left2}}",
    "rightEntityId": "{{right2}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link3 between left2 and right3
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link3/v/1"],
  "linkData": {
    "leftEntityId": "{{left2}}",
    "rightEntityId": "{{right3}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert link3 between left3 and right1
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link3/v/1"],
  "linkData": {
    "leftEntityId": "{{left3}}",
    "rightEntityId": "{{right1}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### Insert link3 between left3 and right2
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link3/v/1"],
  "linkData": {
    "leftEntityId": "{{left3}}",
    "rightEntityId": "{{right2}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### Insert link3 between left3 and right3
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{user_id}}

{
  "webId": "{{user_id}}",
  "properties": { "value": {} },
  "entityTypeIds": ["http://localhost:3000/@snapshot/types/entity-type/link3/v/1"],
  "linkData": {
    "leftEntityId": "{{left3}}",
    "rightEntityId": "{{right3}}"
  },
  "draft": false,
  "provenance": {
    "actorType": "machine",
    "origin": {
      "type": "api"
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
