
### Delete entities
DELETE http://127.0.0.1:4001/entities

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Delete entity types
DELETE http://127.0.0.1:4001/entity-types

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Delete property types
DELETE http://127.0.0.1:4001/property-types

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Delete data types
DELETE http://127.0.0.1:4001/data-types

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Delete principals
DELETE http://127.0.0.1:4001/accounts

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
