# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GroupIndex(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # GroupIndex
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GroupIndex
    def Inner(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateGroupIndex(builder, inner):
    builder.Prep(8, 8)
    builder.PrependUint64(inner)
    return builder.Offset()
