# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UserErrors(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UserErrors()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUserErrors(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UserErrors
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UserErrors
    def Inner(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from UserError import UserError
            obj = UserError()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # UserErrors
    def InnerLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UserErrors
    def InnerIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def UserErrorsStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddInner(builder, inner): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(inner), 0)
def UserErrorsAddInner(builder, inner):
    """This method is deprecated. Please switch to AddInner."""
    return AddInner(builder, inner)
def StartInnerVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def UserErrorsStartInnerVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartInnerVector(builder, numElems)
def End(builder): return builder.EndObject()
def UserErrorsEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)