graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hash_graph/index.html">hash-graph</a>]
    1[<a href="../type_system/index.html">type-system</a>]
    2[<a href="../hash_codec/index.html">hash-codec</a>]
    3[<a href="../hash_codegen/index.html">hash-codegen</a>]
    4[hash-graph-api]
    class 4 root
    5[<a href="../hash_graph_authorization/index.html">hash-graph-authorization</a>]
    6[<a href="../hash_graph_migrations/index.html">hash-graph-migrations</a>]
    7[<a href="../hash_graph_migrations_macros/index.html">hash-graph-migrations-macros</a>]
    8[<a href="../hash_graph_postgres_store/index.html">hash-graph-postgres-store</a>]
    9[<a href="../hash_graph_store/index.html">hash-graph-store</a>]
    10[<a href="../hash_graph_temporal_versioning/index.html">hash-graph-temporal-versioning</a>]
    11[<a href="../hash_graph_test_server/index.html">hash-graph-test-server</a>]
    12[<a href="../hash_graph_type_defs/index.html">hash-graph-type-defs</a>]
    13[<a href="../hash_graph_type_fetcher/index.html">hash-graph-type-fetcher</a>]
    14[<a href="../hash_graph_types/index.html">hash-graph-types</a>]
    15[<a href="../hash_graph_validation/index.html">hash-graph-validation</a>]
    16[<a href="../harpc_client/index.html">harpc-client</a>]
    17[<a href="../harpc_codec/index.html">harpc-codec</a>]
    18[<a href="../harpc_net/index.html">harpc-net</a>]
    19[<a href="../harpc_server/index.html">harpc-server</a>]
    20[<a href="../harpc_system/index.html">harpc-system</a>]
    21[<a href="../harpc_tower/index.html">harpc-tower</a>]
    22[<a href="../harpc_types/index.html">harpc-types</a>]
    23[<a href="../harpc_wire_protocol/index.html">harpc-wire-protocol</a>]
    24[<a href="../hashql_ast/index.html">hashql-ast</a>]
    25[<a href="../hashql_compiletest/index.html">hashql-compiletest</a>]
    26[<a href="../hashql_core/index.html">hashql-core</a>]
    27[<a href="../hashql_diagnostics/index.html">hashql-diagnostics</a>]
    28[<a href="../hashql_eval/index.html">hashql-eval</a>]
    29[<a href="../hashql_hir/index.html">hashql-hir</a>]
    30[<a href="../hashql_macros/index.html">hashql-macros</a>]
    31[<a href="../hashql_mir/index.html">hashql-mir</a>]
    32[<a href="../hashql_syntax_jexpr/index.html">hashql-syntax-jexpr</a>]
    33[<a href="../hash_status/index.html">hash-status</a>]
    34[<a href="../hash_telemetry/index.html">hash-telemetry</a>]
    35[<a href="../hash_temporal_client/index.html">hash-temporal-client</a>]
    36[<a href="../darwin_kperf/index.html">darwin-kperf</a>]
    37[<a href="../darwin_kperf_criterion/index.html">darwin-kperf-criterion</a>]
    38[<a href="../darwin_kperf_events/index.html">darwin-kperf-events</a>]
    39[<a href="../darwin_kperf_sys/index.html">darwin-kperf-sys</a>]
    40[<a href="../error_stack/index.html">error-stack</a>]
    41[<a href="../hash_graph_benches/index.html">hash-graph-benches</a>]
    42[<a href="../hash_graph_test_data/index.html">hash-graph-test-data</a>]
    0 --> 11
    1 --> 10
    1 -.-> 42
    2 -.-> 3
    2 --> 23
    4 --> 8
    4 --> 12
    4 --> 13
    4 --> 19
    4 --> 28
    4 --> 32
    5 --> 1
    6 --> 7
    6 --> 34
    8 -.-> 6
    8 --> 15
    8 --> 33
    9 --> 5
    9 --> 14
    9 --> 35
    10 --> 2
    11 --> 4
    12 --> 33
    13 --> 9
    14 -.-> 42
    15 -.-> 42
    16 --> 20
    17 --> 22
    17 --> 40
    18 --> 2
    18 -.-> 17
    18 --> 17
    19 -.-> 1
    19 -.-> 16
    20 --> 21
    21 -.-> 18
    21 --> 18
    23 -.-> 22
    23 --> 22
    23 --> 40
    24 -.-> 25
    25 --> 28
    25 --> 31
    25 --> 32
    25 --> 40
    26 --> 2
    26 --> 27
    26 --> 30
    26 -.-> 37
    28 --> 9
    28 --> 29
    29 -.-> 25
    31 --> 29
    32 --> 24
    32 --> 26
    34 --> 40
    35 --> 1
    36 --> 38
    36 --> 39
    37 --> 36
    41 -.-> 4
    42 --> 9
