graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hash_graph/index.html">hash-graph</a>]
    1[<a href="../type_system/index.html">type-system</a>]
    2[<a href="../hash_codec/index.html">hash-codec</a>]
    3[<a href="../hash_codegen/index.html">hash-codegen</a>]
    4[hash-graph-api]
    class 4 root
    5[<a href="../hash_graph_authentication/index.html">hash-graph-authentication</a>]
    6[<a href="../hash_graph_authorization/index.html">hash-graph-authorization</a>]
    7[<a href="../hash_graph_embeddings/index.html">hash-graph-embeddings</a>]
    8[<a href="../hash_graph_migrations/index.html">hash-graph-migrations</a>]
    9[<a href="../hash_graph_migrations_macros/index.html">hash-graph-migrations-macros</a>]
    10[<a href="../hash_graph_postgres_store/index.html">hash-graph-postgres-store</a>]
    11[<a href="../hash_graph_store/index.html">hash-graph-store</a>]
    12[<a href="../hash_graph_temporal_versioning/index.html">hash-graph-temporal-versioning</a>]
    13[<a href="../hash_graph_type_defs/index.html">hash-graph-type-defs</a>]
    14[<a href="../hash_graph_type_fetcher/index.html">hash-graph-type-fetcher</a>]
    15[<a href="../hash_graph_types/index.html">hash-graph-types</a>]
    16[<a href="../hash_graph_validation/index.html">hash-graph-validation</a>]
    17[<a href="../harpc_client/index.html">harpc-client</a>]
    18[<a href="../harpc_codec/index.html">harpc-codec</a>]
    19[<a href="../harpc_net/index.html">harpc-net</a>]
    20[<a href="../harpc_server/index.html">harpc-server</a>]
    21[<a href="../harpc_system/index.html">harpc-system</a>]
    22[<a href="../harpc_tower/index.html">harpc-tower</a>]
    23[<a href="../harpc_types/index.html">harpc-types</a>]
    24[<a href="../harpc_wire_protocol/index.html">harpc-wire-protocol</a>]
    25[<a href="../hashql_ast/index.html">hashql-ast</a>]
    26[<a href="../hashql_compiletest/index.html">hashql-compiletest</a>]
    27[<a href="../hashql_core/index.html">hashql-core</a>]
    28[<a href="../hashql_diagnostics/index.html">hashql-diagnostics</a>]
    29[<a href="../hashql_eval/index.html">hashql-eval</a>]
    30[<a href="../hashql_hir/index.html">hashql-hir</a>]
    31[<a href="../hashql_macros/index.html">hashql-macros</a>]
    32[<a href="../hashql_mir/index.html">hashql-mir</a>]
    33[<a href="../hashql_syntax_jexpr/index.html">hashql-syntax-jexpr</a>]
    34[<a href="../hash_status/index.html">hash-status</a>]
    35[<a href="../hash_telemetry/index.html">hash-telemetry</a>]
    36[<a href="../hash_temporal_client/index.html">hash-temporal-client</a>]
    37[<a href="../darwin_kperf/index.html">darwin-kperf</a>]
    38[<a href="../darwin_kperf_criterion/index.html">darwin-kperf-criterion</a>]
    39[<a href="../darwin_kperf_events/index.html">darwin-kperf-events</a>]
    40[<a href="../darwin_kperf_sys/index.html">darwin-kperf-sys</a>]
    41[<a href="../error_stack/index.html">error-stack</a>]
    42[<a href="../hash_graph_benches/index.html">hash-graph-benches</a>]
    43[<a href="../hash_graph_test_data/index.html">hash-graph-test-data</a>]
    0 --> 4
    1 --> 12
    1 -.-> 43
    2 -.-> 3
    2 --> 24
    4 -.-> 5
    4 --> 5
    4 --> 13
    4 --> 14
    4 --> 20
    4 --> 29
    4 --> 33
    5 --> 11
    5 --> 34
    6 --> 1
    7 --> 15
    7 -.-> 38
    8 --> 9
    8 --> 35
    10 --> 7
    10 --> 8
    10 -.-> 10
    10 --> 16
    10 --> 34
    11 --> 6
    11 --> 15
    11 --> 36
    12 --> 2
    13 --> 34
    14 --> 11
    15 -.-> 43
    16 -.-> 43
    17 --> 21
    18 --> 23
    18 --> 41
    19 --> 2
    19 -.-> 18
    19 --> 18
    20 -.-> 1
    20 -.-> 17
    21 --> 22
    22 -.-> 19
    22 --> 19
    24 -.-> 23
    24 --> 23
    24 --> 41
    25 -.-> 26
    26 --> 29
    26 --> 33
    27 --> 2
    27 --> 28
    27 --> 31
    27 -.-> 38
    29 --> 10
    29 --> 32
    30 -.-> 26
    32 --> 30
    33 --> 25
    33 --> 27
    35 --> 41
    36 --> 1
    37 --> 39
    37 --> 40
    38 --> 37
    42 -.-> 4
    43 --> 11
