# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Serialized(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Serialized()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSerialized(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Serialized
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Serialized
    def Inner(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Serialized
    def InnerAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Serialized
    def InnerLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Serialized
    def InnerIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def SerializedStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddInner(builder, inner): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(inner), 0)
def SerializedAddInner(builder, inner):
    """This method is deprecated. Please switch to AddInner."""
    return AddInner(builder, inner)
def StartInnerVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def SerializedStartInnerVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartInnerVector(builder, numElems)
def End(builder): return builder.EndObject()
def SerializedEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)