import { IconProvider, type IconPack } from "@hashintel/ds-components";
import {
  ExperimentalIconProvider as IconSetProvider,
  experimentalIconPack,
  useExperimentalIconPackEnabled,
} from "@hashintel/ds-icons";

import type { ExperimentalIconDefaults } from "@hashintel/ds-icons";
import type { PropsWithChildren } from "react";

export {
  AddPlaceIcon,
  AddTransitionIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowTrendDownIcon,
  ArrowTrendUpIcon,
  ArrowUpIcon,
  ArrowUpRightIcon,
  ArrowsLeftRightIcon,
  AssistantIcon,
  AsteriskIcon,
  AtIcon,
  BarcodeIcon,
  BellIcon,
  BracketsCurlyIcon,
  BracketsSquareIcon,
  BugIcon,
  BullseyeIcon,
  CalendarClockIcon,
  CalendarIcon,
  ChartBarSimpleIcon,
  ChartLineIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleCheckIcon,
  CircleEllipsisIcon,
  CircleOneIcon,
  ClockIcon,
  ClockRotateLeftIcon,
  CloseIcon,
  CodeIcon,
  CollapseIcon,
  CopyIcon,
  CubeIcon,
  CubesIcon,
  CursorIcon,
  DiagnosticsIcon,
  DiagramNestedIcon,
  DiagramNodesIcon,
  DiagramProjectIcon,
  DiagramSubtaskIcon,
  DiamondExclamationIcon,
  DownloadIcon,
  EllipsisIcon,
  EllipsisVerticalIcon,
  EmptySetIcon,
  ErrorIcon,
  ExperimentalIcon,
  ExternalLinkIcon,
  EyeIcon,
  EyeSlashIcon,
  FeatherIcon,
  FileIcon,
  FileLinesIcon,
  FileSpreadsheetIcon,
  FilterIcon,
  FitViewIcon,
  FlaskIcon,
  FunctionIcon,
  GridIcon,
  GripVerticalIcon,
  HandIcon,
  ImageIcon,
  InfinityIcon,
  InfoIcon,
  InputPipeIcon,
  LambdaIcon,
  LayerIcon,
  LightbulbOnIcon,
  LightningIcon,
  ListIcon,
  ListTreeIcon,
  LoadingIcon,
  LockClosedIcon,
  LockOpenIcon,
  MagicIcon,
  MemoCircleCheckIcon,
  MenuIcon,
  MicrophoneIcon,
  MicroscopeIcon,
  MinusIcon,
  OneHundredIcon,
  ParameterIcon,
  PauseIcon,
  PencilIcon,
  PersonRunningIcon,
  Petricon,
  PlaceIcon,
  PlayIcon,
  PlaybackIcon,
  PlugIcon,
  PlusIcon,
  PrintIcon,
  PuzzlePieceIcon,
  ResetIcon,
  RightToLineIcon,
  RotateIcon,
  RulerIcon,
  ScribbleIcon,
  SearchIcon,
  SettingsIcon,
  ShapesIcon,
  SidebarIcon,
  SortDownAlphabeticalIcon,
  SortDownIcon,
  SortDownNumericIcon,
  SortUpAlphabeticalIcon,
  SortUpIcon,
  SortUpNumericIcon,
  SparklesIcon,
  SquareCheckIcon,
  StarIcon,
  StepForwardIcon,
  StopIcon,
  TableIcon,
  TerminalIcon,
  TextIcon,
  ThoughtBubbleIcon,
  TokenTypeIcon,
  TranscriptionIcon,
  TransitionIcon,
  TrashIcon,
  TruckIcon,
  UserIcon,
  UserPlusIcon,
  VoiceIcon,
  WarningIcon,
  ZoomInIcon,
  ZoomOutIcon,
  experimentalIconEffects,
  experimentalIconNames,
  experimentalIconPack,
  getExperimentalIconEffects,
  getPetriconEffects,
  petriconCatalog,
  petriconEffects,
  petriconHints,
  petriconNames,
  petriconPack,
  petriconStudies,
  useExperimentalIconMotionAllowed,
  useExperimentalIconPackEnabled,
  usePetriconMotionAllowed,
} from "@hashintel/ds-icons";
export type {
  ExperimentalIconBadgeVisibility,
  ExperimentalIconChoreography,
  ExperimentalIconComponentProps,
  ExperimentalIconDefaults,
  ExperimentalIconEffect,
  ExperimentalIconMotion,
  ExperimentalIconName,
  ExperimentalIconProps,
  ExperimentalIconStatus,
  ExperimentalIconTransition,
  ExperimentalIconVariant,
  PetriconBadgeVisibility,
  PetriconChoreography,
  PetriconDefaults,
  PetriconEffect,
  PetriconMotion,
  PetriconName,
  PetriconProps,
  PetriconStatus,
  PetriconTransition,
  PetriconVariant,
} from "@hashintel/ds-icons";

const defaultIconPack: IconPack = {};

const ExperimentalIconPackProvider = ({ children }: PropsWithChildren) => {
  const enabled = useExperimentalIconPackEnabled();
  return (
    <IconProvider
      icons={
        enabled
          ? (experimentalIconPack satisfies Required<IconPack>)
          : defaultIconPack
      }
    >
      {children}
    </IconProvider>
  );
};

export const ExperimentalIconProvider = ({
  children,
  ...props
}: PropsWithChildren<ExperimentalIconDefaults & { enabled?: boolean }>) => (
  <IconSetProvider {...props}>
    <ExperimentalIconPackProvider>{children}</ExperimentalIconPackProvider>
  </IconSetProvider>
);

export { ExperimentalIconProvider as PetriconProvider };
