import { IconProvider, type IconPack } from "@hashintel/ds-components";
import {
  HashIconProvider as IconSetProvider,
  hashIconPack,
  useHashIconPackEnabled,
} from "@hashintel/ds-icons";

import type { HashIconDefaults } from "@hashintel/ds-icons";
import type { PropsWithChildren } from "react";

export {
  AddPlaceIcon,
  AddTransitionIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowTrendDownIcon,
  ArrowTrendUpIcon,
  ArrowUpIcon,
  ArrowUpRightIcon,
  ArrowsLeftRightIcon,
  AssistantIcon,
  AsteriskIcon,
  AtIcon,
  BarcodeIcon,
  BellIcon,
  BracketsCurlyIcon,
  BracketsSquareIcon,
  BugIcon,
  BullseyeIcon,
  CalendarClockIcon,
  CalendarIcon,
  ChartBarSimpleIcon,
  ChartLineIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleCheckIcon,
  CircleEllipsisIcon,
  CircleOneIcon,
  ClockIcon,
  ClockRotateLeftIcon,
  CloseIcon,
  CodeIcon,
  CollapseIcon,
  CopyIcon,
  CubeIcon,
  CubesIcon,
  CursorIcon,
  DiagnosticsIcon,
  DiagramNestedIcon,
  DiagramNodesIcon,
  DiagramProjectIcon,
  DiagramSubtaskIcon,
  DiamondExclamationIcon,
  DownloadIcon,
  EllipsisIcon,
  EllipsisVerticalIcon,
  EmptySetIcon,
  ErrorIcon,
  HashIcon as ExperimentalIcon,
  ExternalLinkIcon,
  EyeIcon,
  EyeSlashIcon,
  FeatherIcon,
  FileIcon,
  FileLinesIcon,
  FileSpreadsheetIcon,
  FilterIcon,
  FitViewIcon,
  FlaskIcon,
  FunctionIcon,
  GridIcon,
  GripVerticalIcon,
  HandIcon,
  ImageIcon,
  InfinityIcon,
  InfoIcon,
  InputPipeIcon,
  LambdaIcon,
  LayerIcon,
  LightbulbOnIcon,
  LightningIcon,
  ListIcon,
  ListTreeIcon,
  LoadingIcon,
  LockClosedIcon,
  LockOpenIcon,
  MagicIcon,
  MemoCircleCheckIcon,
  MenuIcon,
  MicrophoneIcon,
  MicroscopeIcon,
  MinusIcon,
  OneHundredIcon,
  ParameterIcon,
  PauseIcon,
  PencilIcon,
  PersonRunningIcon,
  HashIcon as Petricon,
  PlaceIcon,
  PlayIcon,
  PlaybackIcon,
  PlugIcon,
  PlusIcon,
  PrintIcon,
  PuzzlePieceIcon,
  ResetIcon,
  RightToLineIcon,
  RotateIcon,
  RulerIcon,
  ScribbleIcon,
  SearchIcon,
  SettingsIcon,
  ShapesIcon,
  SidebarIcon,
  SortDownAlphabeticalIcon,
  SortDownIcon,
  SortDownNumericIcon,
  SortUpAlphabeticalIcon,
  SortUpIcon,
  SortUpNumericIcon,
  SparklesIcon,
  SquareCheckIcon,
  StarIcon,
  StepForwardIcon,
  StopIcon,
  TableIcon,
  TerminalIcon,
  TextIcon,
  ThoughtBubbleIcon,
  TokenTypeIcon,
  TranscriptionIcon,
  TransitionIcon,
  TrashIcon,
  TruckIcon,
  UserIcon,
  UserPlusIcon,
  VoiceIcon,
  WarningIcon,
  ZoomInIcon,
  ZoomOutIcon,
  hashIconEffects as experimentalIconEffects,
  hashIconNames as experimentalIconNames,
  hashIconPack as experimentalIconPack,
  getHashIconEffects as getExperimentalIconEffects,
  getHashIconEffects as getPetriconEffects,
  hashIconCatalog as petriconCatalog,
  hashIconEffects as petriconEffects,
  hashIconHints as petriconHints,
  hashIconNames as petriconNames,
  hashIconPack as petriconPack,
  hashIconStudies as petriconStudies,
  useHashIconMotionAllowed as useExperimentalIconMotionAllowed,
  useHashIconPackEnabled as useExperimentalIconPackEnabled,
  useHashIconMotionAllowed as usePetriconMotionAllowed,
} from "@hashintel/ds-icons";
export type {
  HashIconBadgeVisibility as ExperimentalIconBadgeVisibility,
  HashIconChoreography as ExperimentalIconChoreography,
  HashIconComponentProps as ExperimentalIconComponentProps,
  HashIconDefaults as ExperimentalIconDefaults,
  HashIconEffect as ExperimentalIconEffect,
  HashIconMotion as ExperimentalIconMotion,
  HashIconName as ExperimentalIconName,
  HashIconProps as ExperimentalIconProps,
  HashIconStatus as ExperimentalIconStatus,
  HashIconTransition as ExperimentalIconTransition,
  HashIconVariant as ExperimentalIconVariant,
  HashIconBadgeVisibility as PetriconBadgeVisibility,
  HashIconChoreography as PetriconChoreography,
  HashIconDefaults as PetriconDefaults,
  HashIconEffect as PetriconEffect,
  HashIconMotion as PetriconMotion,
  HashIconName as PetriconName,
  HashIconProps as PetriconProps,
  HashIconStatus as PetriconStatus,
  HashIconTransition as PetriconTransition,
  HashIconVariant as PetriconVariant,
} from "@hashintel/ds-icons";

const defaultIconPack: IconPack = {};

const ExperimentalIconPackProvider = ({ children }: PropsWithChildren) => {
  const enabled = useHashIconPackEnabled();
  return (
    <IconProvider
      icons={
        enabled ? (hashIconPack satisfies Required<IconPack>) : defaultIconPack
      }
    >
      {children}
    </IconProvider>
  );
};

export const ExperimentalIconProvider = ({
  children,
  ...props
}: PropsWithChildren<HashIconDefaults & { enabled?: boolean }>) => (
  <IconSetProvider {...props}>
    <ExperimentalIconPackProvider>{children}</ExperimentalIconPackProvider>
  </IconSetProvider>
);

export { ExperimentalIconProvider as PetriconProvider };
