//! The header page every artifact format opens with.
//!
//! Every artifact file starts with one [`PAGE`]-sized header, then page-aligned data regions. The
//! fields in that header differ per format. The padding out to the page boundary does not, and
//! neither does the parse of the leading page that a reader then borrows from. This module carries
//! both so that no format repeats them.
//!
//! A format declares only its own fields and calls [`header!`], which generates the padded
//! companion occupying the full page and wires up [`Header`] and [`PaddedHeader`]. [`HeaderMap`]
//! maps a file and parses its leading page once, after which [`HeaderMap::header`] hands that
//! header out as an ordinary reference. Geometry validation and error vocabulary stay with the
//! format that declares them, because only that format knows what its fields mean.
//!
//! A reader borrows the header and never copies it out of the mapping, so it reports the bytes on
//! disk rather than a snapshot taken at open that could later disagree with them.
//!
//! [`PAGE`]: super::PAGE

use core::{error::Error, fmt, marker::PhantomData, ops::Deref};
use std::{io, path::Path};

use zerocopy::{TryFromBytes as _, error::ConvertError};

use super::{PAGE_BYTES, PageMap};

/// A format's header fields, paired with the page-sized companion that persists them.
pub(crate) trait Header {
    /// The page-sized form of these fields, generated by [`header!`].
    type Padded: PaddedHeader<Inner = Self>;
}

/// A format's header fields followed by zero padding to the page boundary.
///
/// [`header!`] generates every implementation of this trait. The zerocopy bounds let a reader parse
/// a mapped page in place instead of reading it out, and [`Deref`] projects the page back to the
/// fields the format declared.
pub(crate) trait PaddedHeader:
    zerocopy::IntoBytes
    + zerocopy::Immutable
    + zerocopy::Unaligned
    + zerocopy::KnownLayout
    + zerocopy::TryFromBytes
    + Deref<Target = <Self as PaddedHeader>::Inner>
{
    /// The header fields this page pads.
    type Inner;
}

/// Generates the page-sized companion of a header type and wires up [`Header`] and
/// [`PaddedHeader`].
///
/// The header type names only the fields it persists. This macro adds the padding that carries it
/// out to [`PAGE`] and implements the two traits [`HeaderMap`] needs. A compile-time assert pins
/// the result at exactly one page, so a format that outgrows a page fails to compile rather than
/// silently writing a shorter header.
///
/// The companion takes the header's name behind a `Padded` prefix, and is crate-visible.
///
/// [`PAGE`]: super::PAGE
macro_rules! header {
    ($header:ident) => {
        /// The full header page of this format.
        ///
        #[doc = concat!("[`", stringify!($header), "`] followed by zero padding to the page")]
        /// boundary. This is the form that persists and that a mapped page parses as, and a
        /// dereference reaches the fields themselves.
        #[derive(
            zerocopy::IntoBytes,
            zerocopy::Immutable,
            zerocopy::Unaligned,
            zerocopy::KnownLayout,
            zerocopy::TryFromBytes,
        )]
        #[repr(C)]
        pub(crate) struct ${concat(Padded, $header)} {
            header: $header,
            padding: [u8; $crate::file::region::PAGE_BYTES - size_of::<$header>()],
        }

        impl ${concat(Padded, $header)} {
            /// Pads `header` out to a full page.
            #[must_use]
            pub(crate) const fn new(header: $header) -> Self {
                Self {
                    header,
                    padding: [0; $crate::file::region::PAGE_BYTES - size_of::<$header>()],
                }
            }
        }

        // The padding carries no information, so the page prints as the header it pads.
        impl ::core::fmt::Debug for ${concat(Padded, $header)} {
            fn fmt(&self, fmt: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                ::core::fmt::Debug::fmt(&self.header, fmt)
            }
        }

        impl ::core::ops::Deref for ${concat(Padded, $header)} {
            type Target = $header;

            fn deref(&self) -> &Self::Target {
                &self.header
            }
        }

        impl $crate::file::region::header::PaddedHeader for ${concat(Padded, $header)} {
            type Inner = $header;
        }

        impl $crate::file::region::header::Header for $header {
            type Padded = ${concat(Padded, $header)};
        }

        const _: () = assert!(
            size_of::<${concat(Padded, $header)}>() == $crate::file::region::PAGE_BYTES,
            concat!(stringify!($header), " must pad to exactly one page"),
        );
    };
}

pub(crate) use header;

/// Reading a file's header page failed.
///
/// These are the failures a format cannot describe better than this module can. Either the file was
/// too short to hold a header at all, or its leading page is not a header this format speaks. A
/// format's own error keeps everything that depends on what its fields mean, its geometry check
/// above all.
#[derive(Debug)]
pub enum HeaderError {
    /// Opening, locking, or mapping the file failed.
    Io(io::Error),
    /// The file ends before one full header page.
    Undersized {
        /// The file's length in bytes.
        actual: u64,
    },
    /// The leading page is not a header this format speaks.
    ///
    /// Which field rejected the bytes is not reported.
    Invalid,
}

impl fmt::Display for HeaderError {
    fn fmt(&self, fmt: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io(error) => write!(fmt, "the file could not be read: {error}"),
            Self::Undersized { actual } => write!(
                fmt,
                "the file holds {actual} bytes, fewer than the {PAGE_BYTES}-byte header page",
            ),
            Self::Invalid => fmt.write_str("the leading page is not a header of this format"),
        }
    }
}

impl Error for HeaderError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Io(error) => Some(error),
            Self::Undersized { .. } | Self::Invalid => None,
        }
    }
}

/// A mapped artifact file whose leading page has parsed as `H`.
///
/// The read-side spine of every format: it holds the mapping and a validated reference to the
/// header inside it, so [`Self::header`] is an ordinary safe accessor and a format's reader states
/// no safety argument of its own. Formats carve their data regions out of [`Self::map`] once their
/// own geometry check has accepted what the header describes.
pub(crate) struct HeaderMap<H> {
    map: PageMap,
    header: PhantomData<H>,
}

impl<H: Header> HeaderMap<H> {
    /// Opens, locks, and maps the file at `path`, parsing its leading page as `H`.
    ///
    /// # Errors
    ///
    /// Returns [`HeaderError::Io`] when opening, locking, or mapping the file fails,
    /// [`HeaderError::Undersized`] when the file ends before one full header page, and
    /// [`HeaderError::Invalid`] when the leading page is not a header of this format.
    pub(crate) fn open(path: impl AsRef<Path>) -> Result<Self, HeaderError> {
        Self::new(PageMap::open(path).map_err(HeaderError::Io)?)
    }

    /// Parses the leading page of an already-mapped file as `H`.
    ///
    /// # Errors
    ///
    /// As [`Self::open`], except that the mapping already exists, so [`HeaderError::Io`] is never
    /// returned.
    pub(crate) fn new(map: PageMap) -> Result<Self, HeaderError> {
        let Some(page) = map.header_page() else {
            return Err(HeaderError::Undersized { actual: map.len() });
        };

        match <H::Padded>::try_ref_from_bytes(page) {
            Ok(_) => {}
            Err(ConvertError::Validity(_)) => return Err(HeaderError::Invalid),
            Err(ConvertError::Alignment(_)) => {
                unreachable!("a header page is `Unaligned`")
            }
            Err(ConvertError::Size(_)) => {
                unreachable!("the slice is exactly one page long")
            }
        }

        Ok(Self {
            map,
            header: PhantomData,
        })
    }

    /// Borrows the header at the head of the mapping.
    pub(crate) fn header(&self) -> &H {
        let page = self.map.bytes().as_ptr().cast::<H::Padded>();

        // SAFETY: the dereference needs a live, aligned, validly initialized target that is not
        // mutably aliased, for no longer than the borrow.
        // - `Self::new` parsed the leading page as `H::Padded` and rejected the file otherwise, and
        //   `H::Padded` occupies exactly the page that parse accepted, so the target holds an
        //   initialized value.
        // - `H::Padded` is `Unaligned`, so it imposes no alignment on the address.
        // - This reads `&self.map` here rather than a stored pointer, so the address belongs to a
        //   mapping that is alive at this moment.
        // - The mapped file is immutable under the `crate::file` publish contract, and the shared
        //   advisory lock `PageMap` holds stops a cooperating writer from rewriting it in place, so
        //   no `&mut` to these bytes can exist.
        // - The borrow is `&self`'s, which ends no later than the mapping.
        unsafe { &*page }
    }

    /// The mapping, for carving out the data regions the header describes.
    pub(crate) const fn map(&self) -> &PageMap {
        &self.map
    }

    /// The mapped length in bytes.
    pub(crate) fn len(&self) -> u64 {
        self.map.len()
    }
}

impl<H> fmt::Debug for HeaderMap<H> {
    fn fmt(&self, fmt: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt.debug_struct("HeaderMap")
            .field("map", &self.map)
            .finish()
    }
}
