[package]
name              = "hash-graph-authentication"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
authors.workspace = true

[dependencies]
# Public workspace dependencies
error-stack              = { workspace = true, public = true }
hash-graph-authorization = { workspace = true, public = true }
hash-graph-store         = { workspace = true, public = true }
hash-middleware          = { workspace = true, public = true }
type-system              = { workspace = true, public = true }

# Public third-party dependencies
http         = { workspace = true, public = true, features = ["std"] }
jsonwebtoken = { workspace = true, public = true, features = ["aws_lc_rs"] }
reqwest      = { workspace = true, public = true }

# Private workspace dependencies

# Private third-party dependencies
cookie         = { workspace = true }
derive_more    = { workspace = true, features = ["display", "error"] }
moka           = { workspace = true, features = ["future"] }
serde          = { workspace = true, features = ["derive"] }
serde_json     = { workspace = true }
sha2           = { workspace = true }
simple-mermaid = { workspace = true }
tokio          = { workspace = true, features = ["sync"] }
tracing        = { workspace = true }
uuid           = { workspace = true }

[dev-dependencies]
axum            = { workspace = true }
hash-middleware = { workspace = true, features = ["test-utils"] }
jsonwebtoken    = { workspace = true, features = ["use_pem"] }
rstest          = { workspace = true }
tokio           = { workspace = true, features = ["macros", "rt-multi-thread"] }
uuid            = { workspace = true, features = ["v4"] }

[features]
test-utils = []

[lints]
workspace = true
