import type { PetrinautAiMessage } from "../views/Editor/panels/ai-assistant-panel/types";
import type { ReactNode } from "react";

/** Current lifecycle state of Petrinaut's AI SDK conversation. */
export type PetrinautAiComposerStatus =
  | "submitted"
  | "streaming"
  | "ready"
  | "error";

/** Outcome from submitting finalized text through the assistant composer. */
export type PetrinautAiComposerSubmitTextResult =
  | { kind: "message"; messageId: string }
  | { kind: "interactive-tool"; toolCallId: string };

export type PetrinautAiComposerSubmitText = (params: {
  id?: string;
  /** Defaults to `auto`; use `message` for text that must not answer a pending tool. */
  target?: "auto" | "message";
  text: string;
}) => Promise<PetrinautAiComposerSubmitTextResult>;

/** Stable controls and current conversation state supplied to a host control. */
export type PetrinautAiComposerControlContext = {
  /** Effective AI SDK identity, whether host-supplied or generated by `useChat`. */
  conversationId: string;
  messages: PetrinautAiMessage[];
  status: PetrinautAiComposerStatus;
  /** Call from an event handler or effect, never while rendering. */
  stop: () => Promise<void>;
  /** Call from an event handler or effect, never while rendering. */
  submitText: PetrinautAiComposerSubmitText;
  /**
   * Submit one voice turn, deferring it while another AI response is active.
   * Call from an event handler or effect, never while rendering.
   */
  submitVoiceInput: PetrinautAiComposerSubmitText;
};

/** Render callback for a host-owned control inside the assistant composer. */
export type PetrinautAiComposerControl = (
  context: PetrinautAiComposerControlContext,
) => ReactNode;
