import type {
  PetrinautAiVoiceSessionPhase,
  PetrinautAiVoiceSessionState,
} from "../../react/voice-session/types";
import type { PetrinautAiMessage } from "../views/Editor/panels/ai-assistant-panel/types";
import type { ReactNode } from "react";

export type { PetrinautAiVoiceSessionPhase, PetrinautAiVoiceSessionState };

/** The active way a user is providing input to the AI assistant. */
export type PetrinautAiInputMode = "text" | "voice";

/** Current lifecycle state of Petrinaut's AI SDK conversation. */
export type PetrinautAiComposerStatus =
  | "submitted"
  | "streaming"
  | "ready"
  | "error";

/** Outcome from submitting finalized text through the assistant composer. */
export type PetrinautAiComposerSubmitTextResult =
  | { kind: "message"; messageId: string }
  | { kind: "interactive-tool"; toolCallId: string };

export type PetrinautAiComposerSubmitText = (params: {
  id?: string;
  /** Persist this finalized text as voice-origin input. */
  source?: "voice";
  /** Defaults to `auto`; use `message` for text that must not answer a pending tool. */
  target?: "auto" | "message";
  text: string;
}) => Promise<PetrinautAiComposerSubmitTextResult>;

/** Stable controls and current conversation state supplied to a host control. */
export type PetrinautAiComposerControlContext = {
  /** Effective AI SDK identity, whether host-supplied or generated by `useChat`. */
  conversationId: string;
  messages: PetrinautAiMessage[];
  status: PetrinautAiComposerStatus;
  /** Call from an event handler or effect, never while rendering. */
  stop: () => Promise<void>;
  /** Call from an event handler or effect, never while rendering. */
  submitText: PetrinautAiComposerSubmitText;
};

/** Render callback for a host-owned control inside the assistant composer. */
export type PetrinautAiComposerControl = (
  context: PetrinautAiComposerControlContext,
) => ReactNode;

/** Imperative lifecycle controls registered by a host-owned Voice mode. */
export type PetrinautAiVoiceModeControls = {
  /**
   * Invalidates the active Voice generation synchronously, then finishes
   * disconnecting its provider resources.
   */
  end: () => Promise<void>;
  /** Pauses microphone capture and active Voice output synchronously. */
  pause: () => void;
  /** Re-establishes a session that dropped, keeping the conversation. */
  reconnect: () => void;
  /** Resumes microphone capture after `pause`. */
  resume: () => void;
  /** Replays the exact retained canonical assistant response when available. */
  readFullResponse?: () => void;
  /** Replays the final segment of the retained canonical response. */
  repeatQuestion?: () => void;
  /**
   * Stops or restarts microphone capture while the session keeps running, so
   * the assistant carries on speaking. Unlike `pause`, which suspends the
   * whole session when Petrinaut closes the panel.
   */
  setMicrophoneMuted: (muted: boolean) => void;
  /** Cancels Voice output and hands the live microphone turn to the user. */
  takeTurn?: () => Promise<void> | void;
};

/** Stable controls and conversation state supplied to a host-owned Voice mode. */
export type PetrinautAiVoiceModeContext = PetrinautAiComposerControlContext & {
  /** True when Petrinaut can retain one next voice turn while chat settles. */
  canAcceptVoiceInput: boolean;
  inputMode: PetrinautAiInputMode;
  isAiAssistantOpen: boolean;
  /**
   * Registers the controls Petrinaut uses to coordinate panel closure and
   * typed-message handoff with the host-owned Voice lifecycle.
   */
  registerVoiceModeControls: (
    controls: PetrinautAiVoiceModeControls,
  ) => () => void;
  /**
   * Publishes the live session state Petrinaut renders from. Pass `null` once
   * no session is running so Petrinaut can retire its Voice surfaces.
   */
  reportVoiceSessionState: (state: PetrinautAiVoiceSessionState | null) => void;
  setInputMode: (mode: PetrinautAiInputMode) => void;
  /** Tell Petrinaut to protect an active voice session from accidental clearing. */
  setVoiceActive: (active: boolean) => void;
  /**
   * Accept one finalized voice turn immediately. If generic chat is still busy,
   * Petrinaut retains it and submits it through the canonical composer path
   * as soon as that path is ready.
   */
  submitVoiceInput: (
    params: Omit<
      Parameters<PetrinautAiComposerControlContext["submitText"]>[0],
      "source"
    > & {
      /**
       * Withdraws a retained turn that has not been submitted yet, for example
       * when the Voice session ends while chat is still busy. A turn already
       * handed to the composer is not cancelled.
       */
      readonly signal?: AbortSignal;
    },
  ) => Promise<PetrinautAiComposerSubmitTextResult>;
};

/** Render callback for a persistent host-owned Voice mode. */
export type PetrinautAiVoiceMode = (
  context: PetrinautAiVoiceModeContext,
) => ReactNode;
