graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hash_graph">hash-graph</a>]
    1[<a href="../type_system">type-system</a>]
    2[<a href="../hash_codec">hash-codec</a>]
    3[<a href="../hash_codegen">hash-codegen</a>]
    4[<a href="../hash_graph_api">hash-graph-api</a>]
    5[<a href="../hash_graph_postgres_store">hash-graph-postgres-store</a>]
    6[<a href="../hash_graph_store">hash-graph-store</a>]
    7[<a href="../hash_graph_temporal_versioning">hash-graph-temporal-versioning</a>]
    8[<a href="../hash_graph_test_server">hash-graph-test-server</a>]
    9[<a href="../hash_graph_type_fetcher">hash-graph-type-fetcher</a>]
    10[hash-graph-types]
    class 10 root
    11[<a href="../hash_graph_validation">hash-graph-validation</a>]
    12[<a href="../harpc_types">harpc-types</a>]
    13[<a href="../harpc_wire_protocol">harpc-wire-protocol</a>]
    14[<a href="../error_stack">error-stack</a>]
    15[<a href="../hash_graph_benches">hash-graph-benches</a>]
    16[<a href="../hash_graph_integration">hash-graph-integration</a>]
    17[<a href="../hash_graph_test_data">hash-graph-test-data</a>]
    0 --> 8
    1 --> 7
    1 -.-> 17
    2 -.-> 3
    2 --> 13
    4 --> 5
    4 --> 9
    5 --> 11
    6 --> 10
    7 --> 2
    8 --> 4
    9 --> 6
    10 --> 1
    11 --> 6
    13 -.-> 12
    13 --> 12
    13 --> 14
    15 -.-> 4
    16 -.-> 5
