graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hash_codec/index.html">hash-codec</a>]
    1[<a href="../hash_codegen/index.html">hash-codegen</a>]
    2[<a href="../harpc_types/index.html">harpc-types</a>]
    3[<a href="../harpc_wire_protocol/index.html">harpc-wire-protocol</a>]
    4[<a href="../hashql_ast/index.html">hashql-ast</a>]
    5[<a href="../hashql_compiletest/index.html">hashql-compiletest</a>]
    6[hashql-core]
    class 6 root
    7[<a href="../hashql_diagnostics/index.html">hashql-diagnostics</a>]
    8[<a href="../hashql_eval/index.html">hashql-eval</a>]
    9[<a href="../hashql_hir/index.html">hashql-hir</a>]
    10[<a href="../hashql_macros/index.html">hashql-macros</a>]
    11[<a href="../hashql_mir/index.html">hashql-mir</a>]
    12[<a href="../hashql_syntax_jexpr/index.html">hashql-syntax-jexpr</a>]
    13[<a href="../darwin_kperf/index.html">darwin-kperf</a>]
    14[<a href="../darwin_kperf_criterion/index.html">darwin-kperf-criterion</a>]
    15[<a href="../darwin_kperf_events/index.html">darwin-kperf-events</a>]
    16[<a href="../darwin_kperf_sys/index.html">darwin-kperf-sys</a>]
    17[<a href="../error_stack/index.html">error-stack</a>]
    0 -.-> 1
    0 --> 3
    3 -.-> 2
    3 --> 2
    3 --> 17
    4 -.-> 5
    5 --> 8
    5 --> 12
    6 --> 0
    6 --> 7
    6 --> 10
    6 -.-> 14
    8 --> 11
    9 -.-> 5
    11 --> 9
    12 --> 4
    12 --> 6
    13 --> 15
    13 --> 16
    14 --> 13
