graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hash_graph/index.html">hash-graph</a>]
    1[<a href="../hash_codec/index.html">hash-codec</a>]
    2[<a href="../hash_codegen/index.html">hash-codegen</a>]
    3[<a href="../hash_graph_api/index.html">hash-graph-api</a>]
    4[<a href="../hash_graph_test_server/index.html">hash-graph-test-server</a>]
    5[<a href="../harpc_types/index.html">harpc-types</a>]
    6[<a href="../harpc_wire_protocol/index.html">harpc-wire-protocol</a>]
    7[<a href="../hashql_ast/index.html">hashql-ast</a>]
    8[<a href="../hashql_compiletest/index.html">hashql-compiletest</a>]
    9[hashql-core]
    class 9 root
    10[<a href="../hashql_diagnostics/index.html">hashql-diagnostics</a>]
    11[<a href="../hashql_eval/index.html">hashql-eval</a>]
    12[<a href="../hashql_hir/index.html">hashql-hir</a>]
    13[<a href="../hashql_mir/index.html">hashql-mir</a>]
    14[<a href="../hashql_syntax_jexpr/index.html">hashql-syntax-jexpr</a>]
    15[<a href="../darwin_kperf/index.html">darwin-kperf</a>]
    16[<a href="../darwin_kperf_criterion/index.html">darwin-kperf-criterion</a>]
    17[<a href="../darwin_kperf_events/index.html">darwin-kperf-events</a>]
    18[<a href="../darwin_kperf_sys/index.html">darwin-kperf-sys</a>]
    19[<a href="../error_stack/index.html">error-stack</a>]
    20[<a href="../hash_graph_benches/index.html">hash-graph-benches</a>]
    0 --> 4
    1 -.-> 2
    1 --> 6
    3 --> 11
    3 --> 14
    4 --> 3
    6 -.-> 5
    6 --> 5
    6 --> 19
    7 -.-> 8
    8 --> 11
    8 --> 13
    8 --> 14
    8 --> 19
    9 --> 1
    9 --> 10
    9 -.-> 16
    11 --> 12
    12 -.-> 8
    13 --> 12
    14 --> 7
    14 --> 9
    15 --> 17
    15 --> 18
    16 --> 15
    20 -.-> 3
