graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hash_graph">hash-graph</a>]
    1[<a href="../type_system">type-system</a>]
    2[<a href="../hash_codec">hash-codec</a>]
    3[<a href="../hash_graph_api">hash-graph-api</a>]
    4[<a href="../hash_graph_authorization">hash-graph-authorization</a>]
    5[<a href="../hash_graph_postgres_queries">hash-graph-postgres-queries</a>]
    6[<a href="../hash_graph_postgres_store">hash-graph-postgres-store</a>]
    7[<a href="../hash_graph_store">hash-graph-store</a>]
    8[<a href="../hash_graph_temporal_versioning">hash-graph-temporal-versioning</a>]
    9[<a href="../hash_graph_test_server">hash-graph-test-server</a>]
    10[<a href="../hash_graph_type_fetcher">hash-graph-type-fetcher</a>]
    11[<a href="../hash_graph_types">hash-graph-types</a>]
    12[<a href="../hash_graph_validation">hash-graph-validation</a>]
    13[<a href="../harpc_client">harpc-client</a>]
    14[<a href="../harpc_codec">harpc-codec</a>]
    15[<a href="../harpc_net">harpc-net</a>]
    16[<a href="../harpc_server">harpc-server</a>]
    17[<a href="../harpc_system">harpc-system</a>]
    18[<a href="../harpc_tower">harpc-tower</a>]
    19[harpc-types]
    class 19 root
    20[<a href="../harpc_wire_protocol">harpc-wire-protocol</a>]
    21[<a href="../hash_temporal_client">hash-temporal-client</a>]
    22[<a href="../hash_graph_benches">hash-graph-benches</a>]
    23[<a href="../hash_graph_integration">hash-graph-integration</a>]
    0 --> 9
    1 --> 8
    2 --> 20
    3 --> 6
    3 --> 10
    3 --> 16
    4 --> 1
    5 --> 4
    6 --> 5
    6 --> 12
    7 --> 4
    7 --> 11
    7 --> 21
    8 --> 2
    9 --> 3
    10 --> 7
    11 --> 1
    12 --> 7
    13 --> 17
    14 --> 19
    15 --> 2
    15 -.-> 14
    15 --> 14
    16 -.-> 1
    16 -.-> 13
    17 --> 18
    18 -.-> 15
    18 --> 15
    20 -.-> 19
    20 --> 19
    21 --> 1
    22 -.-> 3
    23 -.-> 6
