#![expect(
    non_upper_case_globals,
    non_snake_case,
    clippy::min_ident_chars,
    clippy::non_ascii_literal,
    unused_imports
)]
use super::Symbol;

hashql_macros::define_symbols! {
    // [tidy] sort alphabetically start
    access,
    ActorGroupEntityUuid,
    add,
    and,
    archived,
    archived_by_id,
    bar,
    base_url,
    BaseUrl,
    bit_and,
    bit_not,
    bit_or,
    bit_shl,
    bit_shr,
    bit_xor,
    bits,
    bool,
    Boolean,
    cbrt,
    cmp,
    collect,
    Confidence,
    confidence,
    core,
    created_at_decision_time,
    created_at_transaction_time,
    created_by_id,
    decision_time,
    DecisionTime,
    Dict,
    div,
    draft_id,
    DraftId,
    dummy: "<!dummy!>",
    E,
    edition,
    edition_id,
    encodings,
    end,
    entity,
    Entity,
    entity_edition_id,
    entity_id,
    entity_type_ids,
    entity_uuid,
    EntityEditionId,
    EntityEditionProvenance,
    EntityEncodings,
    EntityId,
    EntityMetadata,
    EntityProvenance,
    EntityUuid,
    eq,
    Err,
    ExclusiveTemporalBound,
    filter,
    FiniteTemporalBound,
    foo,
    gt,
    gte,
    id,
    InclusiveTemporalBound,
    index,
    inferred,
    InferredEntityProvenance,
    input,
    input_exists: "$exists",
    Integer,
    Intersection,
    Interval,
    kernel,
    left_entity_confidence,
    left_entity_id,
    left_entity_provenance,
    left_entity_uuid,
    left_entity_web_id,
    LeftClosedTemporalInterval,
    link_data,
    LinkData,
    List,
    lt,
    lte,
    math,
    metadata,
    mul,
    ne,
    Never,
    None,
    not,
    Null,
    null,
    Number,
    Ok,
    OntologyTypeVersion,
    OpenTemporalBound,
    option,
    Option,
    or,
    pinned,
    PinnedDecisionTimeTemporalAxes,
    PinnedTransactionTimeTemporalAxes,
    pow,
    properties,
    property_metadata,
    PropertyObjectMetadata,
    PropertyProvenance,
    provenance,
    provenance_edition,
    provenance_inferred,
    provided,
    QueryTemporalAxes,
    r#as: "as",
    r#as_force: "as!",
    r#else: "else",
    r#false: "false",
    r#fn: "fn",
    r#if: "if",
    r#in: "in",
    r#is: "is",
    r#let: "let",
    r#mod: "mod",
    r#newtype: "newtype",
    r#true: "true",
    r#type: "type",
    r#use: "use",
    R,
    record_id,
    RecordId,
    rem,
    Result,
    right_entity_confidence,
    right_entity_id,
    right_entity_provenance,
    right_entity_uuid,
    right_entity_web_id,
    RightBoundedTemporalInterval,
    root,
    S,
    shl,
    shr,
    Some,
    special_form,
    sqrt,
    start,
    String,
    sub,
    T,
    temporal,
    temporal_versioning,
    TemporalBound,
    TemporalInterval,
    TemporalMetadata,
    then,
    thunk,
    Timestamp,
    transaction_time,
    TransactionTime,
    U,
    UnboundedTemporalBound,
    Union,
    Unknown,
    unknown,
    Url,
    uuid,
    Uuid,
    variable,
    vectors,
    version,
    VersionedUrl,
    web_id,
    WebId,
    xor,
    tail,
    head,
    entities,
    is_of_type,
    property,
    body,
    tmp,
    decision_time_now,
    graph,
    types,
    principal,
    web,
    actor_group,
    ontology,
    entity_type,
    knowledge,
    url,
    result,
    json,
    // [tidy] sort alphabetically end

    internal: {
        ClosureEnv: "'<ClosureEnv>"
    },

    symbol: {
        // [tidy] sort alphabetically start
        ampamp: "&&",
        upwards: "↑",
        sqrt: "√",
        cbrt: "∛",
        percent: "%",
        ampersand: "&",
        arrow: "->",
        arrow_head: "|>",
        asterisk: "*",
        asteriskasterisk: "**",
        exclamation: "!",
        excleq: "!=",
        brackets: "[]",
        caret: "^",
        colon: ":",
        coloncolon: "::",
        comma: ",",
        dollar: "$",
        dollar_question_mark: "$?",
        dot: ".",
        eq: "=",
        eqeq: "==",
        gt: ">",
        gteq: ">=",
        gtgt: ">>",
        lt: "<",
        lteq: "<=",
        ltlt: "<<",
        minus: "-",
        pipepipe: "||",
        pipe: "|",
        plus: "+",
        question_mark: "?",
        slash: "/",
        tilde: "~",
        // [tidy] sort alphabetically end
    },

    digit: {
        zero: "0",
        one: "1",
        two: "2",
        three: "3",
        four: "4",
        five: "5",
        six: "6",
        seven: "7",
        eight: "8",
        nine: "9",
    },

    path: {
        // [tidy] sort alphabetically start
        access: "::kernel::special_form::access",
        ActorGroupEntityUuid: "::graph::types::principal::actor_group::ActorGroupEntityUuid",
        BaseUrl: "::graph::types::ontology::BaseUrl",
        Confidence: "::graph::types::knowledge::entity::Confidence",
        DecisionTime: "::graph::temporal::DecisionTime",
        Dict: "::kernel::type::Dict",
        Union: "::kernel::type::Union",
        Intersection: "::kernel::type::Intersection",
        DraftId: "::graph::types::knowledge::entity::DraftId",
        Entity: "::graph::types::knowledge::entity::Entity",
        EntityEditionId: "::graph::types::knowledge::entity::EntityEditionId",
        EntityEditionProvenance: "::graph::types::knowledge::entity::EntityEditionProvenance",
        EntityEncodings: "::graph::types::knowledge::entity::EntityEncodings",
        EntityId: "::graph::types::knowledge::entity::EntityId",
        EntityMetadata: "::graph::types::knowledge::entity::EntityMetadata",
        EntityProvenance: "::graph::types::knowledge::entity::EntityProvenance",
        EntityUuid: "::graph::types::knowledge::entity::EntityUuid",
        ExclusiveTemporalBound: "::graph::temporal::ExclusiveTemporalBound",
        graph_body_filter: "::graph::body::filter",
        graph_head_entities: "::graph::head::entities",
        graph_tail_collect: "::graph::tail::collect",
        InclusiveTemporalBound: "::graph::temporal::InclusiveTemporalBound",
        index: "::kernel::special_form::index",
        InferredEntityProvenance: "::graph::types::knowledge::entity::InferredEntityProvenance",
        input: "::kernel::special_form::input",
        Interval: "::graph::temporal::Interval",
        LeftClosedTemporalInterval: "::graph::temporal::LeftClosedTemporalInterval",
        LinkData: "::graph::types::knowledge::entity::LinkData",
        List: "::kernel::type::List",
        main: "::main",
        newtype: "::kernel::special_form::newtype",
        None: "::core::option::None",
        OntologyTypeVersion: "::graph::ontology::OntologyTypeVersion",
        OpenTemporalBound: "::graph::temporal::OpenTemporalBound",
        Option: "::core::option::Option",
        PinnedDecisionTimeTemporalAxes: "::graph::temporal::PinnedDecisionTimeTemporalAxes",
        PinnedTransactionTimeTemporalAxes: "::graph::temporal::PinnedTransactionTimeTemporalAxes",
        PropertyObjectMetadata: "::graph::types::knowledge::entity::PropertyObjectMetadata",
        PropertyProvenance: "::graph::types::knowledge::entity::PropertyProvenance",
        r#as: "::kernel::special_form::as",
        r#fn: "::kernel::special_form::fn",
        r#if: "::kernel::special_form::if",
        r#let: "::kernel::special_form::let",
        r#type: "::kernel::special_form::type",
        r#use: "::kernel::special_form::use",
        RecordId: "::graph::types::knowledge::entity::RecordId",
        RightBoundedTemporalInterval: "::graph::temporal::RightBoundedTemporalInterval",
        Some: "::core::option::Some",
        TemporalInterval: "::graph::types::knowledge::entity::TemporalInterval",
        TemporalMetadata: "::graph::types::knowledge::entity::TemporalMetadata",
        Timestamp: "::graph::temporal::Timestamp",
        TransactionTime: "::graph::temporal::TransactionTime",
        UnboundedTemporalBound: "::graph::temporal::UnboundedTemporalBound",
        Url: "::core::url::Url",
        Uuid: "::core::uuid::Uuid",
        VersionedUrl: "::graph::types::ontology::VersionedUrl",
        WebId: "::graph::types::principal::actor_group::web::WebId",
        core: {
            bits: {
                and: "::core::bits::and",
                or: "::core::bits::or",
                xor: "::core::bits::xor",
                not: "::core::bits::not",
                shl: "::core::bits::shl",
                shr: "::core::bits::shr",
            },
            bool: {
                not: "::core::bool::not",
                and: "::core::bool::and",
                or: "::core::bool::or",
            },
            cmp: {
                gt: "::core::cmp::gt",
                lt: "::core::cmp::lt",
                gte: "::core::cmp::gte",
                lte: "::core::cmp::lte",
                eq: "::core::cmp::eq",
                ne: "::core::cmp::ne",
            },
            math: {
                add: "::core::math::add",
                sub: "::core::math::sub",
                mul: "::core::math::mul",
                div: "::core::math::div",
                rem: "::core::math::rem",
                r#mod: "::core::math::mod",
                pow: "::core::math::pow",
                sqrt: "::core::math::sqrt",
                cbrt: "::core::math::cbrt",
                root: "::core::math::root",
            }
        },
        graph: {
            entity: {
                is_of_type: "::graph::entity::is_of_type",
                property: "::graph::entity::property",
            },
            tmp: {
                decision_time_now: "::graph::tmp::decision_time_now",
            }
        }
        // [tidy] sort alphabetically end
    }
}

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use super::SYMBOLS;

    #[test]
    fn symbols_are_unique() {
        let mut set = HashSet::with_capacity(SYMBOLS.len());

        for symbol in SYMBOLS {
            set.insert(*symbol);
        }

        assert_eq!(set.len(), SYMBOLS.len(), "duplicate symbol value found");
    }
}
