#![expect(non_upper_case_globals, non_snake_case, clippy::min_ident_chars)]
use super::Symbol;

hashql_macros::define_symbols! {
    // [tidy] sort alphabetically start
    access,
    ActorGroupEntityUuid,
    add,
    and,
    archived,
    archived_by_id,
    bar,
    base_url,
    BaseUrl,
    bit_and,
    bit_not,
    bit_or,
    bit_shl,
    bit_shr,
    bit_xor,
    Boolean,
    collect,
    Confidence,
    confidence,
    core,
    created_at_decision_time,
    created_at_transaction_time,
    created_by_id,
    decision_time,
    DecisionTime,
    Dict,
    div,
    draft_id,
    DraftId,
    dummy: "<!dummy!>",
    E,
    edition,
    edition_id,
    encodings,
    end,
    entity,
    Entity,
    entity_edition_id,
    entity_id,
    entity_type_ids,
    entity_uuid,
    EntityEditionId,
    EntityEditionProvenance,
    EntityEncodings,
    EntityId,
    EntityMetadata,
    EntityProvenance,
    EntityUuid,
    eq,
    Err,
    ExclusiveTemporalBound,
    filter,
    FiniteTemporalBound,
    foo,
    gt,
    gte,
    id,
    InclusiveTemporalBound,
    index,
    inferred,
    InferredEntityProvenance,
    input,
    input_exists: "$exists",
    Integer,
    Intersection,
    Interval,
    kernel,
    left_entity_confidence,
    left_entity_id,
    left_entity_provenance,
    left_entity_uuid,
    left_entity_web_id,
    link_data,
    LinkData,
    List,
    lt,
    lte,
    math,
    metadata,
    mul,
    ne,
    Never,
    None,
    not,
    Null,
    null,
    Number,
    Ok,
    OntologyTypeVersion,
    option,
    Option,
    or,
    pinned,
    PinnedDecisionTimeTemporalAxes,
    PinnedTransactionTimeTemporalAxes,
    pow,
    properties,
    property_metadata,
    PropertyObjectMetadata,
    PropertyProvenance,
    provenance,
    provenance_edition,
    provenance_inferred,
    provided,
    QueryTemporalAxes,
    r#as: "as",
    r#as_force: "as!",
    r#else: "else",
    r#false: "false",
    r#fn: "fn",
    r#if: "if",
    r#in: "in",
    r#is: "is",
    r#let: "let",
    r#mod: "mod",
    r#newtype: "newtype",
    r#true: "true",
    r#type: "type",
    r#use: "use",
    R,
    record_id,
    RecordId,
    Result,
    right_entity_confidence,
    right_entity_id,
    right_entity_provenance,
    right_entity_uuid,
    right_entity_web_id,
    Some,
    special_form,
    start,
    String,
    sub,
    T,
    temporal,
    temporal_versioning,
    TemporalBound,
    TemporalInterval,
    TemporalMetadata,
    then,
    thunk,
    Timestamp,
    transaction_time,
    TransactionTime,
    U,
    UnboundedTemporalBound,
    Union,
    Unknown,
    unknown,
    Url,
    uuid,
    Uuid,
    variable,
    vectors,
    version,
    VersionedUrl,
    web_id,
    WebId,
    // [tidy] sort alphabetically end

    internal: {
        ClosureEnv: "'<ClosureEnv>"
    },

    symbol: {
        // [tidy] sort alphabetically start
        ampamp: "&&",
        ampersand: "&",
        arrow: "->",
        arrow_head: "|>",
        asterisk: "*",
        exclamation: "!",
        excleq: "!=",
        brackets: "[]",
        caret: "^",
        colon: ":",
        coloncolon: "::",
        comma: ",",
        dollar: "$",
        dollar_question_mark: "$?",
        dot: ".",
        eq: "=",
        eqeq: "==",
        gt: ">",
        gteq: ">=",
        gtgt: ">>",
        lt: "<",
        lteq: "<=",
        ltlt: "<<",
        minus: "-",
        pipepipe: "||",
        pipe: "|",
        plus: "+",
        question_mark: "?",
        slash: "/",
        tilde: "~",
        // [tidy] sort alphabetically end
    },

    digit: {
        zero: "0",
        one: "1",
        two: "2",
        three: "3",
        four: "4",
        five: "5",
        six: "6",
        seven: "7",
        eight: "8",
        nine: "9",
    },

    path: {
        // [tidy] sort alphabetically start
        ActorGroupEntityUuid: "::graph::types::principal::actor_group::ActorGroupEntityUuid",
        BaseUrl: "::graph::types::ontology::BaseUrl",
        Confidence: "::graph::types::knowledge::entity::Confidence",
        DecisionTime: "::graph::temporal::DecisionTime",
        DraftId: "::graph::types::knowledge::entity::DraftId",
        Entity: "::graph::types::knowledge::entity::Entity",
        EntityEditionId: "::graph::types::knowledge::entity::EntityEditionId",
        EntityEditionProvenance: "::graph::types::knowledge::entity::EntityEditionProvenance",
        EntityEncodings: "::graph::types::knowledge::entity::EntityEncodings",
        EntityId: "::graph::types::knowledge::entity::EntityId",
        EntityMetadata: "::graph::types::knowledge::entity::EntityMetadata",
        EntityProvenance: "::graph::types::knowledge::entity::EntityProvenance",
        EntityUuid: "::graph::types::knowledge::entity::EntityUuid",
        ExclusiveTemporalBound: "::graph::temporal::ExclusiveTemporalBound",
        graph_body_filter: "::graph::body::filter",
        graph_head_entities: "::graph::head::entities",
        graph_tail_collect: "::graph::tail::collect",
        InclusiveTemporalBound: "::graph::temporal::InclusiveTemporalBound",
        InferredEntityProvenance: "::graph::types::knowledge::entity::InferredEntityProvenance",
        Interval: "::graph::temporal::Interval",
        LinkData: "::graph::types::knowledge::entity::LinkData",
        None: "::core::option::None",
        OntologyTypeVersion: "::graph::ontology::OntologyTypeVersion",
        option: "::core::option::Option",
        PinnedDecisionTimeTemporalAxes: "::graph::temporal::PinnedDecisionTimeTemporalAxes",
        PinnedTransactionTimeTemporalAxes: "::graph::temporal::PinnedTransactionTimeTemporalAxes",
        PropertyObjectMetadata: "::graph::types::knowledge::entity::PropertyObjectMetadata",
        PropertyProvenance: "::graph::types::knowledge::entity::PropertyProvenance",
        RecordId: "::graph::types::knowledge::entity::RecordId",
        Some: "::core::option::Some",
        TemporalInterval: "::graph::types::knowledge::entity::TemporalInterval",
        TemporalMetadata: "::graph::types::knowledge::entity::TemporalMetadata",
        Timestamp: "::graph::temporal::Timestamp",
        TransactionTime: "::graph::temporal::TransactionTime",
        UnboundedTemporalBound: "::graph::temporal::UnboundedTemporalBound",
        Url: "::core::url::Url",
        Uuid: "::core::uuid::Uuid",
        VersionedUrl: "::graph::types::ontology::VersionedUrl",
        WebId: "::graph::types::principal::actor_group::web::WebId",
        // [tidy] sort alphabetically end
    }
}

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use super::SYMBOLS;

    #[test]
    fn symbols_are_unique() {
        let mut set = HashSet::with_capacity(SYMBOLS.len());

        for symbol in SYMBOLS {
            set.insert(*symbol);
        }

        assert_eq!(set.len(), SYMBOLS.len(), "duplicate symbol value found");
    }
}
