graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hash_graph">hash-graph</a>]
    1[<a href="../type_system">type-system</a>]
    2[<a href="../hash_codec">hash-codec</a>]
    3[<a href="../hash_codegen">hash-codegen</a>]
    4[<a href="../hash_graph_api">hash-graph-api</a>]
    5[<a href="../hash_graph_authorization">hash-graph-authorization</a>]
    6[hash-graph-postgres-store]
    class 6 root
    7[<a href="../hash_graph_store">hash-graph-store</a>]
    8[<a href="../hash_graph_temporal_versioning">hash-graph-temporal-versioning</a>]
    9[<a href="../hash_graph_test_server">hash-graph-test-server</a>]
    10[<a href="../hash_graph_types">hash-graph-types</a>]
    11[<a href="../hash_graph_validation">hash-graph-validation</a>]
    12[<a href="../harpc_types">harpc-types</a>]
    13[<a href="../harpc_wire_protocol">harpc-wire-protocol</a>]
    14[<a href="../hash_status">hash-status</a>]
    15[<a href="../hash_temporal_client">hash-temporal-client</a>]
    16[<a href="../hash_tracing">hash-tracing</a>]
    17[<a href="../error_stack">error-stack</a>]
    18[<a href="../hash_graph_benches">hash-graph-benches</a>]
    19[<a href="../hash_graph_integration">hash-graph-integration</a>]
    20[<a href="../hash_graph_test_data">hash-graph-test-data</a>]
    0 --> 9
    1 --> 8
    1 -.-> 20
    2 --> 3
    2 --> 13
    3 -.-> 1
    4 --> 6
    5 --> 3
    6 --> 11
    6 --> 14
    6 -.-> 16
    7 --> 5
    7 --> 10
    7 --> 15
    8 --> 2
    9 --> 4
    10 --> 1
    11 --> 7
    13 -.-> 12
    13 --> 12
    13 --> 17
    15 --> 1
    16 --> 17
    18 -.-> 4
    19 -.-> 6
