import { defineTokens } from "@pandacss/dev";

export const radii = defineTokens.radii({
  md: {
    "0": { value: "0px" },
    "1": { value: "2px" },
    "2": { value: "4px" },
    "3": { value: "6px" },
    "4": { value: "8px" },
    "5": { value: "10px" },
    "6": { value: "12px" },
    "7": { value: "16px" },
    "8": { value: "20px" },
    "9": { value: "24px" },
    "10": { value: "32px" },
    full: { value: "9999px" },
  },
  sm: {
    "0": { value: "0px" },
    "1": { value: "1px" },
    "2": { value: "2px" },
    "3": { value: "4px" },
    "4": { value: "6px" },
    "5": { value: "8px" },
    "6": { value: "10px" },
    "7": { value: "12px" },
    "8": { value: "16px" },
    "9": { value: "20px" },
    "10": { value: "24px" },
    full: { value: "9999px" },
  },
  lg: {
    "0": { value: "0px" },
    "1": { value: "4px" },
    "2": { value: "6px" },
    "3": { value: "8px" },
    "4": { value: "10px" },
    "5": { value: "12px" },
    "6": { value: "16px" },
    "7": { value: "20px" },
    "8": { value: "24px" },
    "9": { value: "32px" },
    "10": { value: "40px" },
    full: { value: "9999px" },
  },
  full: {
    "0": { value: "9999px" },
    "1": { value: "9999px" },
    "2": { value: "9999px" },
    "3": { value: "9999px" },
    "4": { value: "9999px" },
    "5": { value: "9999px" },
    "6": { value: "9999px" },
    "7": { value: "9999px" },
    "8": { value: "9999px" },
    "9": { value: "9999px" },
    "10": { value: "9999px" },
    full: { value: "9999px" },
  },
  none: {
    "0": { value: "0px" },
    "1": { value: "0px" },
    "2": { value: "0px" },
    "3": { value: "0px" },
    "4": { value: "0px" },
    "5": { value: "0px" },
    "6": { value: "0px" },
    "7": { value: "0px" },
    "8": { value: "0px" },
    "9": { value: "0px" },
    "10": { value: "0px" },
    full: { value: "0px" },
  },
  component: {
    button: {
      sm: { value: "{radii.md.4}" },
      md: { value: "{radii.md.4}" },
      lg: { value: "{radii.md.5}" },
      xs: { value: "{radii.md.3}" },
    },
  },
});
