graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hash_graph/index.html">hash-graph</a>]
    1[<a href="../type_system/index.html">type-system</a>]
    2[hash-codec]
    class 2 root
    3[<a href="../hash_codegen/index.html">hash-codegen</a>]
    4[<a href="../hash_graph_api/index.html">hash-graph-api</a>]
    5[<a href="../hash_graph_authorization/index.html">hash-graph-authorization</a>]
    6[<a href="../hash_graph_postgres_store/index.html">hash-graph-postgres-store</a>]
    7[<a href="../hash_graph_store/index.html">hash-graph-store</a>]
    8[<a href="../hash_graph_temporal_versioning/index.html">hash-graph-temporal-versioning</a>]
    9[<a href="../hash_graph_test_server/index.html">hash-graph-test-server</a>]
    10[<a href="../hash_graph_type_fetcher/index.html">hash-graph-type-fetcher</a>]
    11[<a href="../hash_graph_types/index.html">hash-graph-types</a>]
    12[<a href="../hash_graph_validation/index.html">hash-graph-validation</a>]
    13[<a href="../harpc_client/index.html">harpc-client</a>]
    14[<a href="../harpc_net/index.html">harpc-net</a>]
    15[<a href="../harpc_server/index.html">harpc-server</a>]
    16[<a href="../harpc_system/index.html">harpc-system</a>]
    17[<a href="../harpc_tower/index.html">harpc-tower</a>]
    18[<a href="../harpc_types/index.html">harpc-types</a>]
    19[<a href="../harpc_wire_protocol/index.html">harpc-wire-protocol</a>]
    20[<a href="../hashql_ast/index.html">hashql-ast</a>]
    21[<a href="../hashql_compiletest/index.html">hashql-compiletest</a>]
    22[<a href="../hashql_core/index.html">hashql-core</a>]
    23[<a href="../hashql_eval/index.html">hashql-eval</a>]
    24[<a href="../hashql_hir/index.html">hashql-hir</a>]
    25[<a href="../hashql_mir/index.html">hashql-mir</a>]
    26[<a href="../hashql_syntax_jexpr/index.html">hashql-syntax-jexpr</a>]
    27[<a href="../hash_temporal_client/index.html">hash-temporal-client</a>]
    28[<a href="../error_stack/index.html">error-stack</a>]
    29[<a href="../hash_graph_benches/index.html">hash-graph-benches</a>]
    30[<a href="../hash_graph_integration/index.html">hash-graph-integration</a>]
    31[<a href="../hash_graph_test_data/index.html">hash-graph-test-data</a>]
    0 --> 9
    1 --> 8
    1 -.-> 31
    2 -.-> 3
    2 --> 19
    4 --> 6
    4 --> 10
    4 --> 15
    4 --> 23
    4 --> 26
    5 --> 1
    6 --> 12
    7 --> 5
    7 --> 11
    7 --> 27
    8 --> 2
    9 --> 4
    10 --> 7
    11 -.-> 31
    12 -.-> 31
    13 --> 16
    14 --> 2
    15 -.-> 1
    15 -.-> 13
    16 --> 17
    17 -.-> 14
    17 --> 14
    19 -.-> 18
    19 --> 18
    19 --> 28
    20 -.-> 21
    21 --> 23
    21 --> 25
    21 --> 26
    21 --> 28
    22 --> 2
    23 --> 7
    23 --> 24
    24 -.-> 21
    25 --> 24
    26 --> 20
    26 --> 22
    27 --> 1
    29 -.-> 4
    30 -.-> 6
    31 --> 7
