/**
 * This file was automatically generated – do not edit it.
 */

import type { ObjectMetadata } from "@blockprotocol/type-system";

import type {
  Actor,
  ActorOutgoingLinkAndTarget,
  ActorOutgoingLinksByLinkEntityTypeId,
  ActorProperties,
  ActorPropertiesWithMetadata,
  ApplicationPreferencesPropertyValue,
  ApplicationPreferencesPropertyValueWithMetadata,
  ArchivedPropertyValue,
  ArchivedPropertyValueWithMetadata,
  AuthoredBy,
  AuthoredByOutgoingLinkAndTarget,
  AuthoredByOutgoingLinksByLinkEntityTypeId,
  AuthoredByProperties,
  AuthoredByPropertiesWithMetadata,
  AutomaticInferenceConfigurationPropertyValue,
  AutomaticInferenceConfigurationPropertyValueWithMetadata,
  Block,
  BlockCollection,
  BlockCollectionOutgoingLinkAndTarget,
  BlockCollectionOutgoingLinksByLinkEntityTypeId,
  BlockCollectionProperties,
  BlockCollectionPropertiesWithMetadata,
  BlockHasDataLink,
  BlockOutgoingLinkAndTarget,
  BlockOutgoingLinksByLinkEntityTypeId,
  BlockProperties,
  BlockPropertiesWithMetadata,
  BooleanDataType,
  BooleanDataTypeWithMetadata,
  BrowserPluginSettings,
  BrowserPluginSettingsOutgoingLinkAndTarget,
  BrowserPluginSettingsOutgoingLinksByLinkEntityTypeId,
  BrowserPluginSettingsProperties,
  BrowserPluginSettingsPropertiesWithMetadata,
  BrowserPluginTabPropertyValue,
  BrowserPluginTabPropertyValueWithMetadata,
  BytesDataType,
  BytesDataTypeWithMetadata,
  Comment,
  CommentAuthoredByLink,
  CommentHasParentLink,
  CommentHasTextLink,
  CommentOutgoingLinkAndTarget,
  CommentOutgoingLinksByLinkEntityTypeId,
  CommentProperties,
  CommentPropertiesWithMetadata,
  ComponentIdPropertyValue,
  ComponentIdPropertyValueWithMetadata,
  DateTimeDataType,
  DateTimeDataTypeWithMetadata,
  DeletedAtPropertyValue,
  DeletedAtPropertyValueWithMetadata,
  DescriptionPropertyValue,
  DescriptionPropertyValueWithMetadata,
  DisplayNamePropertyValue,
  DisplayNamePropertyValueWithMetadata,
  DraftNotePropertyValue,
  DraftNotePropertyValueWithMetadata,
  EmailDataType,
  EmailDataTypeWithMetadata,
  EmailPropertyValue,
  EmailPropertyValueWithMetadata,
  EnabledFeatureFlagsPropertyValue,
  EnabledFeatureFlagsPropertyValueWithMetadata,
  EntityEditionIdPropertyValue,
  EntityEditionIdPropertyValueWithMetadata,
  ExpiredAtPropertyValue,
  ExpiredAtPropertyValueWithMetadata,
  File,
  FileHashPropertyValue,
  FileHashPropertyValueWithMetadata,
  FileNamePropertyValue,
  FileNamePropertyValueWithMetadata,
  FileOutgoingLinkAndTarget,
  FileOutgoingLinksByLinkEntityTypeId,
  FileProperties,
  FilePropertiesWithMetadata,
  FileSizePropertyValue,
  FileSizePropertyValueWithMetadata,
  FileStorageBucketPropertyValue,
  FileStorageBucketPropertyValueWithMetadata,
  FileStorageEndpointPropertyValue,
  FileStorageEndpointPropertyValueWithMetadata,
  FileStorageForcePathStylePropertyValue,
  FileStorageForcePathStylePropertyValueWithMetadata,
  FileStorageKeyPropertyValue,
  FileStorageKeyPropertyValueWithMetadata,
  FileStorageProviderPropertyValue,
  FileStorageProviderPropertyValueWithMetadata,
  FileStorageRegionPropertyValue,
  FileStorageRegionPropertyValueWithMetadata,
  FileURLPropertyValue,
  FileURLPropertyValueWithMetadata,
  FractionalIndexPropertyValue,
  FractionalIndexPropertyValueWithMetadata,
  Has,
  HasAvatar,
  HasAvatarOutgoingLinkAndTarget,
  HasAvatarOutgoingLinksByLinkEntityTypeId,
  HasAvatarProperties,
  HasAvatarPropertiesWithMetadata,
  HasBio,
  HasBioOutgoingLinkAndTarget,
  HasBioOutgoingLinksByLinkEntityTypeId,
  HasBioProperties,
  HasBioPropertiesWithMetadata,
  HasCoverImage,
  HasCoverImageOutgoingLinkAndTarget,
  HasCoverImageOutgoingLinksByLinkEntityTypeId,
  HasCoverImageProperties,
  HasCoverImagePropertiesWithMetadata,
  HasData,
  HasDataOutgoingLinkAndTarget,
  HasDataOutgoingLinksByLinkEntityTypeId,
  HasDataProperties,
  HasDataPropertiesWithMetadata,
  HasIndexedContent,
  HasIndexedContentOutgoingLinkAndTarget,
  HasIndexedContentOutgoingLinksByLinkEntityTypeId,
  HasIndexedContentProperties,
  HasIndexedContentPropertiesWithMetadata,
  HasIssuedInvitation,
  HasIssuedInvitationOutgoingLinkAndTarget,
  HasIssuedInvitationOutgoingLinksByLinkEntityTypeId,
  HasIssuedInvitationProperties,
  HasIssuedInvitationPropertiesWithMetadata,
  HasOutgoingLinkAndTarget,
  HasOutgoingLinksByLinkEntityTypeId,
  HasParent,
  HasParentOutgoingLinkAndTarget,
  HasParentOutgoingLinksByLinkEntityTypeId,
  HasParentProperties,
  HasParentPropertiesWithMetadata,
  HasProperties,
  HasPropertiesWithMetadata,
  HasServiceAccount,
  HasServiceAccountOutgoingLinkAndTarget,
  HasServiceAccountOutgoingLinksByLinkEntityTypeId,
  HasServiceAccountProperties,
  HasServiceAccountPropertiesWithMetadata,
  HasText,
  HasTextOutgoingLinkAndTarget,
  HasTextOutgoingLinksByLinkEntityTypeId,
  HasTextProperties,
  HasTextPropertiesWithMetadata,
  IconPropertyValue,
  IconPropertyValueWithMetadata,
  ImageFile,
  ImageFileOutgoingLinkAndTarget,
  ImageFileOutgoingLinksByLinkEntityTypeId,
  ImageFileProperties,
  ImageFilePropertiesWithMetadata,
  InformationDataType,
  InformationDataTypeWithMetadata,
  Invitation,
  InvitationOutgoingLinkAndTarget,
  InvitationOutgoingLinksByLinkEntityTypeId,
  InvitationProperties,
  InvitationPropertiesWithMetadata,
  InvitationViaEmail,
  InvitationViaEmailOutgoingLinkAndTarget,
  InvitationViaEmailOutgoingLinksByLinkEntityTypeId,
  InvitationViaEmailProperties,
  InvitationViaEmailPropertiesWithMetadata,
  InvitationViaShortname,
  InvitationViaShortnameOutgoingLinkAndTarget,
  InvitationViaShortnameOutgoingLinksByLinkEntityTypeId,
  InvitationViaShortnameProperties,
  InvitationViaShortnamePropertiesWithMetadata,
  IsMemberOf,
  IsMemberOfOutgoingLinkAndTarget,
  IsMemberOfOutgoingLinksByLinkEntityTypeId,
  IsMemberOfProperties,
  IsMemberOfPropertiesWithMetadata,
  KratosIdentityIdPropertyValue,
  KratosIdentityIdPropertyValueWithMetadata,
  Link,
  LinkOutgoingLinkAndTarget,
  LinkOutgoingLinksByLinkEntityTypeId,
  LinkProperties,
  LinkPropertiesWithMetadata,
  LocationPropertyValue,
  LocationPropertyValueWithMetadata,
  ManualInferenceConfigurationPropertyValue,
  ManualInferenceConfigurationPropertyValueWithMetadata,
  MIMETypePropertyValue,
  MIMETypePropertyValueWithMetadata,
  Notification,
  NotificationOutgoingLinkAndTarget,
  NotificationOutgoingLinksByLinkEntityTypeId,
  NotificationProperties,
  NotificationPropertiesWithMetadata,
  NumberDataType,
  NumberDataTypeWithMetadata,
  ObjectDataType,
  ObjectDataTypeWithMetadata,
  OccurredInBlock,
  OccurredInBlockOutgoingLinkAndTarget,
  OccurredInBlockOutgoingLinksByLinkEntityTypeId,
  OccurredInBlockProperties,
  OccurredInBlockPropertiesWithMetadata,
  OccurredInEntity,
  OccurredInEntityOutgoingLinkAndTarget,
  OccurredInEntityOutgoingLinksByLinkEntityTypeId,
  OccurredInEntityProperties,
  OccurredInEntityPropertiesWithMetadata,
  Organization,
  OrganizationHasAvatarLink,
  OrganizationHasBioLink,
  OrganizationHasCoverImageLink,
  OrganizationHasIssuedInvitationLink,
  OrganizationNamePropertyValue,
  OrganizationNamePropertyValueWithMetadata,
  OrganizationOutgoingLinkAndTarget,
  OrganizationOutgoingLinksByLinkEntityTypeId,
  OrganizationProperties,
  OrganizationPropertiesWithMetadata,
  OriginalFileNamePropertyValue,
  OriginalFileNamePropertyValueWithMetadata,
  OriginalSourcePropertyValue,
  OriginalSourcePropertyValueWithMetadata,
  OriginalURLPropertyValue,
  OriginalURLPropertyValueWithMetadata,
  Page,
  PageHasParentLink,
  PageOutgoingLinkAndTarget,
  PageOutgoingLinksByLinkEntityTypeId,
  PageProperties,
  PagePropertiesWithMetadata,
  PinnedEntityTypeBaseURLPropertyValue,
  PinnedEntityTypeBaseURLPropertyValueWithMetadata,
  PreferredPronounsPropertyValue,
  PreferredPronounsPropertyValueWithMetadata,
  ProfileBio,
  ProfileBioHasIndexedContentLink,
  ProfileBioOutgoingLinkAndTarget,
  ProfileBioOutgoingLinksByLinkEntityTypeId,
  ProfileBioProperties,
  ProfileBioPropertiesWithMetadata,
  ProfileURLPropertyValue,
  ProfileURLPropertyValueWithMetadata,
  ReadAtPropertyValue,
  ReadAtPropertyValueWithMetadata,
  ResolvedAtPropertyValue,
  ResolvedAtPropertyValueWithMetadata,
  ServiceAccount,
  ServiceAccountOutgoingLinkAndTarget,
  ServiceAccountOutgoingLinksByLinkEntityTypeId,
  ServiceAccountProperties,
  ServiceAccountPropertiesWithMetadata,
  ShortnamePropertyValue,
  ShortnamePropertyValueWithMetadata,
  SummaryPropertyValue,
  SummaryPropertyValueWithMetadata,
  Text,
  TextDataType,
  TextDataTypeWithMetadata,
  TextOutgoingLinkAndTarget,
  TextOutgoingLinksByLinkEntityTypeId,
  TextProperties,
  TextPropertiesWithMetadata,
  TextualContentPropertyValue,
  TextualContentPropertyValueWithMetadata,
  TitlePropertyValue,
  TitlePropertyValueWithMetadata,
  TriggeredByUser,
  TriggeredByUserOutgoingLinkAndTarget,
  TriggeredByUserOutgoingLinksByLinkEntityTypeId,
  TriggeredByUserProperties,
  TriggeredByUserPropertiesWithMetadata,
  UploadCompletedAtPropertyValue,
  UploadCompletedAtPropertyValueWithMetadata,
  URIDataType,
  URIDataTypeWithMetadata,
  User,
  UserHasAvatarLink,
  UserHasBioLink,
  UserHasCoverImageLink,
  UserHasLink,
  UserHasServiceAccountLink,
  UserIsMemberOfLink,
  UserOutgoingLinkAndTarget,
  UserOutgoingLinksByLinkEntityTypeId,
  UserProperties,
  UserPropertiesWithMetadata,
  WebsiteURLPropertyValue,
  WebsiteURLPropertyValueWithMetadata,
} from "./shared.js";

export type {
  Actor,
  ActorOutgoingLinkAndTarget,
  ActorOutgoingLinksByLinkEntityTypeId,
  ActorProperties,
  ActorPropertiesWithMetadata,
  ApplicationPreferencesPropertyValue,
  ApplicationPreferencesPropertyValueWithMetadata,
  ArchivedPropertyValue,
  ArchivedPropertyValueWithMetadata,
  AuthoredBy,
  AuthoredByOutgoingLinkAndTarget,
  AuthoredByOutgoingLinksByLinkEntityTypeId,
  AuthoredByProperties,
  AuthoredByPropertiesWithMetadata,
  AutomaticInferenceConfigurationPropertyValue,
  AutomaticInferenceConfigurationPropertyValueWithMetadata,
  Block,
  BlockCollection,
  BlockCollectionOutgoingLinkAndTarget,
  BlockCollectionOutgoingLinksByLinkEntityTypeId,
  BlockCollectionProperties,
  BlockCollectionPropertiesWithMetadata,
  BlockHasDataLink,
  BlockOutgoingLinkAndTarget,
  BlockOutgoingLinksByLinkEntityTypeId,
  BlockProperties,
  BlockPropertiesWithMetadata,
  BooleanDataType,
  BooleanDataTypeWithMetadata,
  BrowserPluginSettings,
  BrowserPluginSettingsOutgoingLinkAndTarget,
  BrowserPluginSettingsOutgoingLinksByLinkEntityTypeId,
  BrowserPluginSettingsProperties,
  BrowserPluginSettingsPropertiesWithMetadata,
  BrowserPluginTabPropertyValue,
  BrowserPluginTabPropertyValueWithMetadata,
  BytesDataType,
  BytesDataTypeWithMetadata,
  Comment,
  CommentAuthoredByLink,
  CommentHasParentLink,
  CommentHasTextLink,
  CommentOutgoingLinkAndTarget,
  CommentOutgoingLinksByLinkEntityTypeId,
  CommentProperties,
  CommentPropertiesWithMetadata,
  ComponentIdPropertyValue,
  ComponentIdPropertyValueWithMetadata,
  DateTimeDataType,
  DateTimeDataTypeWithMetadata,
  DeletedAtPropertyValue,
  DeletedAtPropertyValueWithMetadata,
  DescriptionPropertyValue,
  DescriptionPropertyValueWithMetadata,
  DisplayNamePropertyValue,
  DisplayNamePropertyValueWithMetadata,
  DraftNotePropertyValue,
  DraftNotePropertyValueWithMetadata,
  EmailDataType,
  EmailDataTypeWithMetadata,
  EmailPropertyValue,
  EmailPropertyValueWithMetadata,
  EnabledFeatureFlagsPropertyValue,
  EnabledFeatureFlagsPropertyValueWithMetadata,
  EntityEditionIdPropertyValue,
  EntityEditionIdPropertyValueWithMetadata,
  ExpiredAtPropertyValue,
  ExpiredAtPropertyValueWithMetadata,
  File,
  FileHashPropertyValue,
  FileHashPropertyValueWithMetadata,
  FileNamePropertyValue,
  FileNamePropertyValueWithMetadata,
  FileOutgoingLinkAndTarget,
  FileOutgoingLinksByLinkEntityTypeId,
  FileProperties,
  FilePropertiesWithMetadata,
  FileSizePropertyValue,
  FileSizePropertyValueWithMetadata,
  FileStorageBucketPropertyValue,
  FileStorageBucketPropertyValueWithMetadata,
  FileStorageEndpointPropertyValue,
  FileStorageEndpointPropertyValueWithMetadata,
  FileStorageForcePathStylePropertyValue,
  FileStorageForcePathStylePropertyValueWithMetadata,
  FileStorageKeyPropertyValue,
  FileStorageKeyPropertyValueWithMetadata,
  FileStorageProviderPropertyValue,
  FileStorageProviderPropertyValueWithMetadata,
  FileStorageRegionPropertyValue,
  FileStorageRegionPropertyValueWithMetadata,
  FileURLPropertyValue,
  FileURLPropertyValueWithMetadata,
  FractionalIndexPropertyValue,
  FractionalIndexPropertyValueWithMetadata,
  Has,
  HasAvatar,
  HasAvatarOutgoingLinkAndTarget,
  HasAvatarOutgoingLinksByLinkEntityTypeId,
  HasAvatarProperties,
  HasAvatarPropertiesWithMetadata,
  HasBio,
  HasBioOutgoingLinkAndTarget,
  HasBioOutgoingLinksByLinkEntityTypeId,
  HasBioProperties,
  HasBioPropertiesWithMetadata,
  HasCoverImage,
  HasCoverImageOutgoingLinkAndTarget,
  HasCoverImageOutgoingLinksByLinkEntityTypeId,
  HasCoverImageProperties,
  HasCoverImagePropertiesWithMetadata,
  HasData,
  HasDataOutgoingLinkAndTarget,
  HasDataOutgoingLinksByLinkEntityTypeId,
  HasDataProperties,
  HasDataPropertiesWithMetadata,
  HasIndexedContent,
  HasIndexedContentOutgoingLinkAndTarget,
  HasIndexedContentOutgoingLinksByLinkEntityTypeId,
  HasIndexedContentProperties,
  HasIndexedContentPropertiesWithMetadata,
  HasIssuedInvitation,
  HasIssuedInvitationOutgoingLinkAndTarget,
  HasIssuedInvitationOutgoingLinksByLinkEntityTypeId,
  HasIssuedInvitationProperties,
  HasIssuedInvitationPropertiesWithMetadata,
  HasOutgoingLinkAndTarget,
  HasOutgoingLinksByLinkEntityTypeId,
  HasParent,
  HasParentOutgoingLinkAndTarget,
  HasParentOutgoingLinksByLinkEntityTypeId,
  HasParentProperties,
  HasParentPropertiesWithMetadata,
  HasProperties,
  HasPropertiesWithMetadata,
  HasServiceAccount,
  HasServiceAccountOutgoingLinkAndTarget,
  HasServiceAccountOutgoingLinksByLinkEntityTypeId,
  HasServiceAccountProperties,
  HasServiceAccountPropertiesWithMetadata,
  HasText,
  HasTextOutgoingLinkAndTarget,
  HasTextOutgoingLinksByLinkEntityTypeId,
  HasTextProperties,
  HasTextPropertiesWithMetadata,
  IconPropertyValue,
  IconPropertyValueWithMetadata,
  ImageFile,
  ImageFileOutgoingLinkAndTarget,
  ImageFileOutgoingLinksByLinkEntityTypeId,
  ImageFileProperties,
  ImageFilePropertiesWithMetadata,
  InformationDataType,
  InformationDataTypeWithMetadata,
  Invitation,
  InvitationOutgoingLinkAndTarget,
  InvitationOutgoingLinksByLinkEntityTypeId,
  InvitationProperties,
  InvitationPropertiesWithMetadata,
  InvitationViaEmail,
  InvitationViaEmailOutgoingLinkAndTarget,
  InvitationViaEmailOutgoingLinksByLinkEntityTypeId,
  InvitationViaEmailProperties,
  InvitationViaEmailPropertiesWithMetadata,
  InvitationViaShortname,
  InvitationViaShortnameOutgoingLinkAndTarget,
  InvitationViaShortnameOutgoingLinksByLinkEntityTypeId,
  InvitationViaShortnameProperties,
  InvitationViaShortnamePropertiesWithMetadata,
  IsMemberOf,
  IsMemberOfOutgoingLinkAndTarget,
  IsMemberOfOutgoingLinksByLinkEntityTypeId,
  IsMemberOfProperties,
  IsMemberOfPropertiesWithMetadata,
  KratosIdentityIdPropertyValue,
  KratosIdentityIdPropertyValueWithMetadata,
  Link,
  LinkOutgoingLinkAndTarget,
  LinkOutgoingLinksByLinkEntityTypeId,
  LinkProperties,
  LinkPropertiesWithMetadata,
  LocationPropertyValue,
  LocationPropertyValueWithMetadata,
  ManualInferenceConfigurationPropertyValue,
  ManualInferenceConfigurationPropertyValueWithMetadata,
  MIMETypePropertyValue,
  MIMETypePropertyValueWithMetadata,
  Notification,
  NotificationOutgoingLinkAndTarget,
  NotificationOutgoingLinksByLinkEntityTypeId,
  NotificationProperties,
  NotificationPropertiesWithMetadata,
  NumberDataType,
  NumberDataTypeWithMetadata,
  ObjectDataType,
  ObjectDataTypeWithMetadata,
  OccurredInBlock,
  OccurredInBlockOutgoingLinkAndTarget,
  OccurredInBlockOutgoingLinksByLinkEntityTypeId,
  OccurredInBlockProperties,
  OccurredInBlockPropertiesWithMetadata,
  OccurredInEntity,
  OccurredInEntityOutgoingLinkAndTarget,
  OccurredInEntityOutgoingLinksByLinkEntityTypeId,
  OccurredInEntityProperties,
  OccurredInEntityPropertiesWithMetadata,
  Organization,
  OrganizationHasAvatarLink,
  OrganizationHasBioLink,
  OrganizationHasCoverImageLink,
  OrganizationHasIssuedInvitationLink,
  OrganizationNamePropertyValue,
  OrganizationNamePropertyValueWithMetadata,
  OrganizationOutgoingLinkAndTarget,
  OrganizationOutgoingLinksByLinkEntityTypeId,
  OrganizationProperties,
  OrganizationPropertiesWithMetadata,
  OriginalFileNamePropertyValue,
  OriginalFileNamePropertyValueWithMetadata,
  OriginalSourcePropertyValue,
  OriginalSourcePropertyValueWithMetadata,
  OriginalURLPropertyValue,
  OriginalURLPropertyValueWithMetadata,
  Page,
  PageHasParentLink,
  PageOutgoingLinkAndTarget,
  PageOutgoingLinksByLinkEntityTypeId,
  PageProperties,
  PagePropertiesWithMetadata,
  PinnedEntityTypeBaseURLPropertyValue,
  PinnedEntityTypeBaseURLPropertyValueWithMetadata,
  PreferredPronounsPropertyValue,
  PreferredPronounsPropertyValueWithMetadata,
  ProfileBio,
  ProfileBioHasIndexedContentLink,
  ProfileBioOutgoingLinkAndTarget,
  ProfileBioOutgoingLinksByLinkEntityTypeId,
  ProfileBioProperties,
  ProfileBioPropertiesWithMetadata,
  ProfileURLPropertyValue,
  ProfileURLPropertyValueWithMetadata,
  ReadAtPropertyValue,
  ReadAtPropertyValueWithMetadata,
  ResolvedAtPropertyValue,
  ResolvedAtPropertyValueWithMetadata,
  ServiceAccount,
  ServiceAccountOutgoingLinkAndTarget,
  ServiceAccountOutgoingLinksByLinkEntityTypeId,
  ServiceAccountProperties,
  ServiceAccountPropertiesWithMetadata,
  ShortnamePropertyValue,
  ShortnamePropertyValueWithMetadata,
  SummaryPropertyValue,
  SummaryPropertyValueWithMetadata,
  Text,
  TextDataType,
  TextDataTypeWithMetadata,
  TextOutgoingLinkAndTarget,
  TextOutgoingLinksByLinkEntityTypeId,
  TextProperties,
  TextPropertiesWithMetadata,
  TextualContentPropertyValue,
  TextualContentPropertyValueWithMetadata,
  TitlePropertyValue,
  TitlePropertyValueWithMetadata,
  TriggeredByUser,
  TriggeredByUserOutgoingLinkAndTarget,
  TriggeredByUserOutgoingLinksByLinkEntityTypeId,
  TriggeredByUserProperties,
  TriggeredByUserPropertiesWithMetadata,
  UploadCompletedAtPropertyValue,
  UploadCompletedAtPropertyValueWithMetadata,
  URIDataType,
  URIDataTypeWithMetadata,
  User,
  UserHasAvatarLink,
  UserHasBioLink,
  UserHasCoverImageLink,
  UserHasLink,
  UserHasServiceAccountLink,
  UserIsMemberOfLink,
  UserOutgoingLinkAndTarget,
  UserOutgoingLinksByLinkEntityTypeId,
  UserProperties,
  UserPropertiesWithMetadata,
  WebsiteURLPropertyValue,
  WebsiteURLPropertyValueWithMetadata,
};

/**
 * A notification related to a comment.
 */
export type CommentNotification = {
  entityTypeIds: [
    "https://hash.ai/@h/types/entity-type/comment-notification/v/7",
  ];
  properties: CommentNotificationProperties;
  propertiesWithMetadata: CommentNotificationPropertiesWithMetadata;
};

export type CommentNotificationOccurredInBlockLink = {
  linkEntity: OccurredInBlock;
  rightEntity: Block;
};

export type CommentNotificationOccurredInEntityLink = {
  linkEntity: OccurredInEntity;
  rightEntity: Page;
};

export type CommentNotificationOutgoingLinkAndTarget =
  | CommentNotificationOccurredInBlockLink
  | CommentNotificationOccurredInEntityLink
  | CommentNotificationRepliedToCommentLink
  | CommentNotificationTriggeredByCommentLink
  | CommentNotificationTriggeredByUserLink;

export type CommentNotificationOutgoingLinksByLinkEntityTypeId = {
  "https://hash.ai/@h/types/entity-type/occurred-in-block/v/1": CommentNotificationOccurredInBlockLink;
  "https://hash.ai/@h/types/entity-type/occurred-in-entity/v/2": CommentNotificationOccurredInEntityLink;
  "https://hash.ai/@h/types/entity-type/replied-to-comment/v/1": CommentNotificationRepliedToCommentLink;
  "https://hash.ai/@h/types/entity-type/triggered-by-comment/v/1": CommentNotificationTriggeredByCommentLink;
  "https://hash.ai/@h/types/entity-type/triggered-by-user/v/1": CommentNotificationTriggeredByUserLink;
};

/**
 * A notification related to a comment.
 */
export type CommentNotificationProperties = NotificationProperties & {};

export type CommentNotificationPropertiesWithMetadata =
  NotificationPropertiesWithMetadata & {
    metadata?: ObjectMetadata;
    value: {};
  };

export type CommentNotificationRepliedToCommentLink = {
  linkEntity: RepliedToComment;
  rightEntity: Comment;
};

export type CommentNotificationTriggeredByCommentLink = {
  linkEntity: TriggeredByComment;
  rightEntity: Comment;
};

export type CommentNotificationTriggeredByUserLink = {
  linkEntity: TriggeredByUser;
  rightEntity: User;
};

/**
 * The comment that something replied to.
 */
export type RepliedToComment = {
  entityTypeIds: [
    "https://hash.ai/@h/types/entity-type/replied-to-comment/v/1",
  ];
  properties: RepliedToCommentProperties;
  propertiesWithMetadata: RepliedToCommentPropertiesWithMetadata;
};

export type RepliedToCommentOutgoingLinkAndTarget = never;

export type RepliedToCommentOutgoingLinksByLinkEntityTypeId = {};

/**
 * The comment that something replied to.
 */
export type RepliedToCommentProperties = LinkProperties & {};

export type RepliedToCommentPropertiesWithMetadata =
  LinkPropertiesWithMetadata & {
    metadata?: ObjectMetadata;
    value: {};
  };

/**
 * A comment that triggered something.
 */
export type TriggeredByComment = {
  entityTypeIds: [
    "https://hash.ai/@h/types/entity-type/triggered-by-comment/v/1",
  ];
  properties: TriggeredByCommentProperties;
  propertiesWithMetadata: TriggeredByCommentPropertiesWithMetadata;
};

export type TriggeredByCommentOutgoingLinkAndTarget = never;

export type TriggeredByCommentOutgoingLinksByLinkEntityTypeId = {};

/**
 * A comment that triggered something.
 */
export type TriggeredByCommentProperties = LinkProperties & {};

export type TriggeredByCommentPropertiesWithMetadata =
  LinkPropertiesWithMetadata & {
    metadata?: ObjectMetadata;
    value: {};
  };
