/**
 * This file was automatically generated – do not edit it.
 */

import type {
  ChartConfigurationPropertyValue,
  ChartConfigurationPropertyValueWithMetadata,
  ChartTypePropertyValue,
  ChartTypePropertyValueWithMetadata,
  ConfigurationStatusPropertyValue,
  ConfigurationStatusPropertyValueWithMetadata,
  DashboardItem,
  DashboardItemOutgoingLinkAndTarget,
  DashboardItemOutgoingLinksByLinkEntityTypeId,
  DashboardItemProperties,
  DashboardItemPropertiesWithMetadata,
  DescriptionPropertyValue,
  DescriptionPropertyValueWithMetadata,
  GoalPropertyValue,
  GoalPropertyValueWithMetadata,
  GridPositionPropertyValue,
  GridPositionPropertyValueWithMetadata,
  NamePropertyValue,
  NamePropertyValueWithMetadata,
  ObjectDataType,
  ObjectDataTypeWithMetadata,
  PythonScriptPropertyValue,
  PythonScriptPropertyValueWithMetadata,
  StructuralQueryPropertyValue,
  StructuralQueryPropertyValueWithMetadata,
  TextDataType,
  TextDataTypeWithMetadata,
} from "./shared.js";

export type {
  ChartConfigurationPropertyValue,
  ChartConfigurationPropertyValueWithMetadata,
  ChartTypePropertyValue,
  ChartTypePropertyValueWithMetadata,
  ConfigurationStatusPropertyValue,
  ConfigurationStatusPropertyValueWithMetadata,
  DashboardItem,
  DashboardItemOutgoingLinkAndTarget,
  DashboardItemOutgoingLinksByLinkEntityTypeId,
  DashboardItemProperties,
  DashboardItemPropertiesWithMetadata,
  DescriptionPropertyValue,
  DescriptionPropertyValueWithMetadata,
  GoalPropertyValue,
  GoalPropertyValueWithMetadata,
  GridPositionPropertyValue,
  GridPositionPropertyValueWithMetadata,
  NamePropertyValue,
  NamePropertyValueWithMetadata,
  ObjectDataType,
  ObjectDataTypeWithMetadata,
  PythonScriptPropertyValue,
  PythonScriptPropertyValueWithMetadata,
  StructuralQueryPropertyValue,
  StructuralQueryPropertyValueWithMetadata,
  TextDataType,
  TextDataTypeWithMetadata,
};
