/**
 * This file was automatically generated – do not edit it.
 */

import type {
  DescriptionPropertyValue,
  DescriptionPropertyValueWithMetadata,
  FlowDefinition,
  FlowDefinitionOutgoingLinkAndTarget,
  FlowDefinitionOutgoingLinksByLinkEntityTypeId,
  FlowDefinitionProperties,
  FlowDefinitionPropertiesWithMetadata,
  NamePropertyValue,
  NamePropertyValueWithMetadata,
  ObjectDataType,
  ObjectDataTypeWithMetadata,
  OutputDefinitionsPropertyValue,
  OutputDefinitionsPropertyValueWithMetadata,
  StepDefinitionsPropertyValue,
  StepDefinitionsPropertyValueWithMetadata,
  TextDataType,
  TextDataTypeWithMetadata,
  TriggerDefinitionIDPropertyValue,
  TriggerDefinitionIDPropertyValueWithMetadata,
  TriggerDefinitionPropertyValue,
  TriggerDefinitionPropertyValueWithMetadata,
} from "./shared.js";

export type {
  DescriptionPropertyValue,
  DescriptionPropertyValueWithMetadata,
  FlowDefinition,
  FlowDefinitionOutgoingLinkAndTarget,
  FlowDefinitionOutgoingLinksByLinkEntityTypeId,
  FlowDefinitionProperties,
  FlowDefinitionPropertiesWithMetadata,
  NamePropertyValue,
  NamePropertyValueWithMetadata,
  ObjectDataType,
  ObjectDataTypeWithMetadata,
  OutputDefinitionsPropertyValue,
  OutputDefinitionsPropertyValueWithMetadata,
  StepDefinitionsPropertyValue,
  StepDefinitionsPropertyValueWithMetadata,
  TextDataType,
  TextDataTypeWithMetadata,
  TriggerDefinitionIDPropertyValue,
  TriggerDefinitionIDPropertyValueWithMetadata,
  TriggerDefinitionPropertyValue,
  TriggerDefinitionPropertyValueWithMetadata,
};
