/**
 * This file was automatically generated – do not edit it.
 */

import {
  AccountIdPropertyValue,
  ConnectionSourceNamePropertyValue,
  DisplayNamePropertyValue,
  EmailPropertyValue,
  ExpiredAtPropertyValue,
  GoogleAccount,
  GoogleAccountOutgoingLinkAndTarget,
  GoogleAccountOutgoingLinksByLinkEntityTypeId,
  GoogleAccountProperties,
  GoogleAccountUsesUserSecretLink,
  Link,
  LinkOutgoingLinkAndTarget,
  LinkOutgoingLinksByLinkEntityTypeId,
  LinkProperties,
  TextDataType,
  UserSecret,
  UserSecretOutgoingLinkAndTarget,
  UserSecretOutgoingLinksByLinkEntityTypeId,
  UserSecretProperties,
  UsesUserSecret,
  UsesUserSecretOutgoingLinkAndTarget,
  UsesUserSecretOutgoingLinksByLinkEntityTypeId,
  UsesUserSecretProperties,
  VaultPathPropertyValue,
} from "./shared";

export type {
  AccountIdPropertyValue,
  ConnectionSourceNamePropertyValue,
  DisplayNamePropertyValue,
  EmailPropertyValue,
  ExpiredAtPropertyValue,
  GoogleAccount,
  GoogleAccountOutgoingLinkAndTarget,
  GoogleAccountOutgoingLinksByLinkEntityTypeId,
  GoogleAccountProperties,
  GoogleAccountUsesUserSecretLink,
  Link,
  LinkOutgoingLinkAndTarget,
  LinkOutgoingLinksByLinkEntityTypeId,
  LinkProperties,
  TextDataType,
  UserSecret,
  UserSecretOutgoingLinkAndTarget,
  UserSecretOutgoingLinksByLinkEntityTypeId,
  UserSecretProperties,
  UsesUserSecret,
  UsesUserSecretOutgoingLinkAndTarget,
  UsesUserSecretOutgoingLinksByLinkEntityTypeId,
  UsesUserSecretProperties,
  VaultPathPropertyValue,
};
