/**
 * This file was automatically generated – do not edit it.
 */

import type {
  AEDDataType,
  AEDDataTypeWithMetadata,
  AFNDataType,
  AFNDataTypeWithMetadata,
  ALLDataType,
  ALLDataTypeWithMetadata,
  AMDDataType,
  AMDDataTypeWithMetadata,
  ANGDataType,
  ANGDataTypeWithMetadata,
  AOADataType,
  AOADataTypeWithMetadata,
  ARSDataType,
  ARSDataTypeWithMetadata,
  AUDDataType,
  AUDDataTypeWithMetadata,
  AWGDataType,
  AWGDataTypeWithMetadata,
  AZNDataType,
  AZNDataTypeWithMetadata,
  ActualFinishDatePropertyValue,
  ActualFinishDatePropertyValueWithMetadata,
  ActualStartDatePropertyValue,
  ActualStartDatePropertyValueWithMetadata,
  AlternativeBOMPropertyValue,
  AlternativeBOMPropertyValueWithMetadata,
  AreaDataType,
  AreaDataTypeWithMetadata,
  BAMDataType,
  BAMDataTypeWithMetadata,
  BBDDataType,
  BBDDataTypeWithMetadata,
  BDTDataType,
  BDTDataTypeWithMetadata,
  BGNDataType,
  BGNDataTypeWithMetadata,
  BHDDataType,
  BHDDataTypeWithMetadata,
  BIFDataType,
  BIFDataTypeWithMetadata,
  BMDDataType,
  BMDDataTypeWithMetadata,
  BNDDataType,
  BNDDataTypeWithMetadata,
  BOBDataType,
  BOBDataTypeWithMetadata,
  BRLDataType,
  BRLDataTypeWithMetadata,
  BSDDataType,
  BSDDataTypeWithMetadata,
  BTNDataType,
  BTNDataTypeWithMetadata,
  BWPDataType,
  BWPDataTypeWithMetadata,
  BYNDataType,
  BYNDataTypeWithMetadata,
  BZDDataType,
  BZDDataTypeWithMetadata,
  Batch,
  BatchNumberPropertyValue,
  BatchNumberPropertyValueWithMetadata,
  BatchOfMaterialLink,
  BatchOutgoingLinkAndTarget,
  BatchOutgoingLinksByLinkEntityTypeId,
  BatchProperties,
  BatchPropertiesWithMetadata,
  CADDataType,
  CADDataTypeWithMetadata,
  CDFDataType,
  CDFDataTypeWithMetadata,
  CHFDataType,
  CHFDataTypeWithMetadata,
  CLPDataType,
  CLPDataTypeWithMetadata,
  CNYDataType,
  CNYDataTypeWithMetadata,
  COPDataType,
  COPDataTypeWithMetadata,
  CRCDataType,
  CRCDataTypeWithMetadata,
  CUPDataType,
  CUPDataTypeWithMetadata,
  CVEDataType,
  CVEDataTypeWithMetadata,
  CZKDataType,
  CZKDataTypeWithMetadata,
  CalendarYearDataType,
  CalendarYearDataTypeWithMetadata,
  CentimetersDataType,
  CentimetersDataTypeWithMetadata,
  CityPropertyValue,
  CityPropertyValueWithMetadata,
  CountryPropertyValue,
  CountryPropertyValueWithMetadata,
  CubicFeetDataType,
  CubicFeetDataTypeWithMetadata,
  CubicMetresDataType,
  CubicMetresDataTypeWithMetadata,
  CurrencyDataType,
  CurrencyDataTypeWithMetadata,
  CustomerNumberPropertyValue,
  CustomerNumberPropertyValueWithMetadata,
  DJFDataType,
  DJFDataTypeWithMetadata,
  DKKDataType,
  DKKDataTypeWithMetadata,
  DOPDataType,
  DOPDataTypeWithMetadata,
  DZDDataType,
  DZDDataTypeWithMetadata,
  DateDataType,
  DateDataTypeWithMetadata,
  DaysDataType,
  DaysDataTypeWithMetadata,
  DebitCreditIndicatorPropertyValue,
  DebitCreditIndicatorPropertyValueWithMetadata,
  DeliveredQuantityPropertyValue,
  DeliveredQuantityPropertyValueWithMetadata,
  Delivers,
  DeliversOutgoingLinkAndTarget,
  DeliversOutgoingLinksByLinkEntityTypeId,
  DeliversProperties,
  DeliversPropertiesWithMetadata,
  DeliveryItem,
  DeliveryItemDeliversLink,
  DeliveryItemFulfillsLink,
  DeliveryItemHasMaterialLink,
  DeliveryItemLocatedAtLink,
  DeliveryItemNumberPropertyValue,
  DeliveryItemNumberPropertyValueWithMetadata,
  DeliveryItemOutgoingLinkAndTarget,
  DeliveryItemOutgoingLinksByLinkEntityTypeId,
  DeliveryItemProperties,
  DeliveryItemPropertiesWithMetadata,
  DeliveryNumberPropertyValue,
  DeliveryNumberPropertyValueWithMetadata,
  DescriptionPropertyValue,
  DescriptionPropertyValueWithMetadata,
  DivisionPropertyValue,
  DivisionPropertyValueWithMetadata,
  DocumentDatePropertyValue,
  DocumentDatePropertyValueWithMetadata,
  DurationDataType,
  DurationDataTypeWithMetadata,
  EGPDataType,
  EGPDataTypeWithMetadata,
  ERNDataType,
  ERNDataTypeWithMetadata,
  ETBDataType,
  ETBDataTypeWithMetadata,
  EURDataType,
  EURDataTypeWithMetadata,
  ExpiryDatePropertyValue,
  ExpiryDatePropertyValueWithMetadata,
  FJDDataType,
  FJDDataTypeWithMetadata,
  FKPDataType,
  FKPDataTypeWithMetadata,
  FeetDataType,
  FeetDataTypeWithMetadata,
  FiscalYearPropertyValue,
  FiscalYearPropertyValueWithMetadata,
  Fulfills,
  FulfillsOutgoingLinkAndTarget,
  FulfillsOutgoingLinksByLinkEntityTypeId,
  FulfillsProperties,
  FulfillsPropertiesWithMetadata,
  GBPDataType,
  GBPDataTypeWithMetadata,
  GELDataType,
  GELDataTypeWithMetadata,
  GHSDataType,
  GHSDataTypeWithMetadata,
  GIPDataType,
  GIPDataTypeWithMetadata,
  GMDDataType,
  GMDDataTypeWithMetadata,
  GNFDataType,
  GNFDataTypeWithMetadata,
  GTQDataType,
  GTQDataTypeWithMetadata,
  GYDDataType,
  GYDDataTypeWithMetadata,
  GoodsReceiptQuantityPropertyValue,
  GoodsReceiptQuantityPropertyValueWithMetadata,
  GramsDataType,
  GramsDataTypeWithMetadata,
  GrossWeightPropertyValue,
  GrossWeightPropertyValueWithMetadata,
  HKDDataType,
  HKDDataTypeWithMetadata,
  HNLDataType,
  HNLDataTypeWithMetadata,
  HTGDataType,
  HTGDataTypeWithMetadata,
  HUFDataType,
  HUFDataTypeWithMetadata,
  HasLineItem,
  HasLineItemOutgoingLinkAndTarget,
  HasLineItemOutgoingLinksByLinkEntityTypeId,
  HasLineItemProperties,
  HasLineItemPropertiesWithMetadata,
  HasMaterial,
  HasMaterialOutgoingLinkAndTarget,
  HasMaterialOutgoingLinksByLinkEntityTypeId,
  HasMaterialProperties,
  HasMaterialPropertiesWithMetadata,
  HoursDataType,
  HoursDataTypeWithMetadata,
  IDRDataType,
  IDRDataTypeWithMetadata,
  ILSDataType,
  ILSDataTypeWithMetadata,
  INRDataType,
  INRDataTypeWithMetadata,
  IQDDataType,
  IQDDataTypeWithMetadata,
  IRRDataType,
  IRRDataTypeWithMetadata,
  ISKDataType,
  ISKDataTypeWithMetadata,
  ImperialLengthUKDataType,
  ImperialLengthUKDataTypeWithMetadata,
  ImperialLengthUSDataType,
  ImperialLengthUSDataTypeWithMetadata,
  InchesDataType,
  InchesDataTypeWithMetadata,
  IntegerDataType,
  IntegerDataTypeWithMetadata,
  ItemCategoryGroupPropertyValue,
  ItemCategoryGroupPropertyValueWithMetadata,
  ItemNumberPropertyValue,
  ItemNumberPropertyValueWithMetadata,
  JMDDataType,
  JMDDataTypeWithMetadata,
  JODDataType,
  JODDataTypeWithMetadata,
  JPYDataType,
  JPYDataTypeWithMetadata,
  KESDataType,
  KESDataTypeWithMetadata,
  KGSDataType,
  KGSDataTypeWithMetadata,
  KHRDataType,
  KHRDataTypeWithMetadata,
  KMFDataType,
  KMFDataTypeWithMetadata,
  KPWDataType,
  KPWDataTypeWithMetadata,
  KRWDataType,
  KRWDataTypeWithMetadata,
  KWDDataType,
  KWDDataTypeWithMetadata,
  KYDDataType,
  KYDDataTypeWithMetadata,
  KZTDataType,
  KZTDataTypeWithMetadata,
  KilogramsDataType,
  KilogramsDataTypeWithMetadata,
  KilometersDataType,
  KilometersDataTypeWithMetadata,
  LAKDataType,
  LAKDataTypeWithMetadata,
  LBPDataType,
  LBPDataTypeWithMetadata,
  LKRDataType,
  LKRDataTypeWithMetadata,
  LRDDataType,
  LRDDataTypeWithMetadata,
  LSLDataType,
  LSLDataTypeWithMetadata,
  LYDDataType,
  LYDDataTypeWithMetadata,
  LanguagePropertyValue,
  LanguagePropertyValueWithMetadata,
  LengthDataType,
  LengthDataTypeWithMetadata,
  LineItemCategoryPropertyValue,
  LineItemCategoryPropertyValueWithMetadata,
  Link,
  LinkOutgoingLinkAndTarget,
  LinkOutgoingLinksByLinkEntityTypeId,
  LinkProperties,
  LinkPropertiesWithMetadata,
  LitresDataType,
  LitresDataTypeWithMetadata,
  LocatedAt,
  LocatedAtOutgoingLinkAndTarget,
  LocatedAtOutgoingLinksByLinkEntityTypeId,
  LocatedAtProperties,
  LocatedAtPropertiesWithMetadata,
  MADDataType,
  MADDataTypeWithMetadata,
  MDLDataType,
  MDLDataTypeWithMetadata,
  MGADataType,
  MGADataTypeWithMetadata,
  MKDDataType,
  MKDDataTypeWithMetadata,
  MMKDataType,
  MMKDataTypeWithMetadata,
  MNTDataType,
  MNTDataTypeWithMetadata,
  MOPDataType,
  MOPDataTypeWithMetadata,
  MRPControllerPropertyValue,
  MRPControllerPropertyValueWithMetadata,
  MRUDataType,
  MRUDataTypeWithMetadata,
  MURDataType,
  MURDataTypeWithMetadata,
  MVRDataType,
  MVRDataTypeWithMetadata,
  MWKDataType,
  MWKDataTypeWithMetadata,
  MXNDataType,
  MXNDataTypeWithMetadata,
  MYRDataType,
  MYRDataTypeWithMetadata,
  MZNDataType,
  MZNDataTypeWithMetadata,
  MassDataType,
  MassDataTypeWithMetadata,
  Material,
  MaterialGroupPropertyValue,
  MaterialGroupPropertyValueWithMetadata,
  MaterialNumberPropertyValue,
  MaterialNumberPropertyValueWithMetadata,
  MaterialOutgoingLinkAndTarget,
  MaterialOutgoingLinksByLinkEntityTypeId,
  MaterialProperties,
  MaterialPropertiesWithMetadata,
  MaterialTypePropertyValue,
  MaterialTypePropertyValueWithMetadata,
  MetersDataType,
  MetersDataTypeWithMetadata,
  MetricLengthSIDataType,
  MetricLengthSIDataTypeWithMetadata,
  MetricTonnesDataType,
  MetricTonnesDataTypeWithMetadata,
  MilesDataType,
  MilesDataTypeWithMetadata,
  MillilitresDataType,
  MillilitresDataTypeWithMetadata,
  MillimetersDataType,
  MillimetersDataTypeWithMetadata,
  NADDataType,
  NADDataTypeWithMetadata,
  NGNDataType,
  NGNDataTypeWithMetadata,
  NIODataType,
  NIODataTypeWithMetadata,
  NOKDataType,
  NOKDataTypeWithMetadata,
  NPRDataType,
  NPRDataTypeWithMetadata,
  NZDDataType,
  NZDDataTypeWithMetadata,
  NamePropertyValue,
  NamePropertyValueWithMetadata,
  NetValuePropertyValue,
  NetValuePropertyValueWithMetadata,
  NetWeightPropertyValue,
  NetWeightPropertyValueWithMetadata,
  NumberDataType,
  NumberDataTypeWithMetadata,
  OMRDataType,
  OMRDataTypeWithMetadata,
  OfMaterial,
  OfMaterialOutgoingLinkAndTarget,
  OfMaterialOutgoingLinksByLinkEntityTypeId,
  OfMaterialProperties,
  OfMaterialPropertiesWithMetadata,
  OrderQuantityPropertyValue,
  OrderQuantityPropertyValueWithMetadata,
  PABDataType,
  PABDataTypeWithMetadata,
  PENDataType,
  PENDataTypeWithMetadata,
  PGKDataType,
  PGKDataTypeWithMetadata,
  PHPDataType,
  PHPDataTypeWithMetadata,
  PKRDataType,
  PKRDataTypeWithMetadata,
  PLNDataType,
  PLNDataTypeWithMetadata,
  PYGDataType,
  PYGDataTypeWithMetadata,
  PostalCodePropertyValue,
  PostalCodePropertyValueWithMetadata,
  PoundsDataType,
  PoundsDataTypeWithMetadata,
  ProcurementTypePropertyValue,
  ProcurementTypePropertyValueWithMetadata,
  Procures,
  ProcuresOutgoingLinkAndTarget,
  ProcuresOutgoingLinksByLinkEntityTypeId,
  ProcuresProperties,
  ProcuresPropertiesWithMetadata,
  Produces,
  ProducesOutgoingLinkAndTarget,
  ProducesOutgoingLinksByLinkEntityTypeId,
  ProducesProperties,
  ProducesPropertiesWithMetadata,
  ProductionOrder,
  ProductionOrderHasLineItemLink,
  ProductionOrderItem,
  ProductionOrderItemLocatedAtLink,
  ProductionOrderItemOutgoingLinkAndTarget,
  ProductionOrderItemOutgoingLinksByLinkEntityTypeId,
  ProductionOrderItemProducesLink,
  ProductionOrderItemProperties,
  ProductionOrderItemPropertiesWithMetadata,
  ProductionOrderNumberPropertyValue,
  ProductionOrderNumberPropertyValueWithMetadata,
  ProductionOrderOutgoingLinkAndTarget,
  ProductionOrderOutgoingLinksByLinkEntityTypeId,
  ProductionOrderProperties,
  ProductionOrderPropertiesWithMetadata,
  ProductionOrderTypePropertyValue,
  ProductionOrderTypePropertyValueWithMetadata,
  ProductionOrderYieldsLink,
  ProductionQuantityPropertyValue,
  ProductionQuantityPropertyValueWithMetadata,
  PurchaseOrderItem,
  PurchaseOrderItemHasLineItemLink,
  PurchaseOrderItemLocatedAtLink,
  PurchaseOrderItemNumberPropertyValue,
  PurchaseOrderItemNumberPropertyValueWithMetadata,
  PurchaseOrderItemOutgoingLinkAndTarget,
  PurchaseOrderItemOutgoingLinksByLinkEntityTypeId,
  PurchaseOrderItemProcuresLink,
  PurchaseOrderItemProperties,
  PurchaseOrderItemPropertiesWithMetadata,
  PurchaseOrderNumberPropertyValue,
  PurchaseOrderNumberPropertyValueWithMetadata,
  PurchaseOrderScheduleLine,
  PurchaseOrderScheduleLineOutgoingLinkAndTarget,
  PurchaseOrderScheduleLineOutgoingLinksByLinkEntityTypeId,
  PurchaseOrderScheduleLineProperties,
  PurchaseOrderScheduleLinePropertiesWithMetadata,
  PurchasingOrganizationPropertyValue,
  PurchasingOrganizationPropertyValueWithMetadata,
  QARDataType,
  QARDataTypeWithMetadata,
  RONDataType,
  RONDataTypeWithMetadata,
  RSDDataType,
  RSDDataTypeWithMetadata,
  RUBDataType,
  RUBDataTypeWithMetadata,
  RWFDataType,
  RWFDataTypeWithMetadata,
  RegionPropertyValue,
  RegionPropertyValueWithMetadata,
  RejectionReasonPropertyValue,
  RejectionReasonPropertyValueWithMetadata,
  ReleaseDatePropertyValue,
  ReleaseDatePropertyValueWithMetadata,
  SARDataType,
  SARDataTypeWithMetadata,
  SBDDataType,
  SBDDataTypeWithMetadata,
  SCRDataType,
  SCRDataTypeWithMetadata,
  SDGDataType,
  SDGDataTypeWithMetadata,
  SEKDataType,
  SEKDataTypeWithMetadata,
  SGDDataType,
  SGDDataTypeWithMetadata,
  SHPDataType,
  SHPDataTypeWithMetadata,
  SLEDataType,
  SLEDataTypeWithMetadata,
  SOSDataType,
  SOSDataTypeWithMetadata,
  SRDDataType,
  SRDDataTypeWithMetadata,
  SSPDataType,
  SSPDataTypeWithMetadata,
  STNDataType,
  STNDataTypeWithMetadata,
  SVCDataType,
  SVCDataTypeWithMetadata,
  SYPDataType,
  SYPDataTypeWithMetadata,
  SZLDataType,
  SZLDataTypeWithMetadata,
  SalesOrderItem,
  SalesOrderItemHasMaterialLink,
  SalesOrderItemLocatedAtLink,
  SalesOrderItemOutgoingLinkAndTarget,
  SalesOrderItemOutgoingLinksByLinkEntityTypeId,
  SalesOrderItemProperties,
  SalesOrderItemPropertiesWithMetadata,
  SalesOrganizationPropertyValue,
  SalesOrganizationPropertyValueWithMetadata,
  ScheduleLineNumberPropertyValue,
  ScheduleLineNumberPropertyValueWithMetadata,
  ScheduledDeliveryDatePropertyValue,
  ScheduledDeliveryDatePropertyValueWithMetadata,
  ScheduledFinishDatePropertyValue,
  ScheduledFinishDatePropertyValueWithMetadata,
  ScheduledQuantityPropertyValue,
  ScheduledQuantityPropertyValueWithMetadata,
  ScheduledStartDatePropertyValue,
  ScheduledStartDatePropertyValueWithMetadata,
  ShippingPointPropertyValue,
  ShippingPointPropertyValueWithMetadata,
  Site,
  SiteCodePropertyValue,
  SiteCodePropertyValueWithMetadata,
  SiteOutgoingLinkAndTarget,
  SiteOutgoingLinksByLinkEntityTypeId,
  SiteProperties,
  SitePropertiesWithMetadata,
  SiteTypePropertyValue,
  SiteTypePropertyValueWithMetadata,
  SquareCentimetresDataType,
  SquareCentimetresDataTypeWithMetadata,
  SquareFeetDataType,
  SquareFeetDataTypeWithMetadata,
  SquareMetresDataType,
  SquareMetresDataTypeWithMetadata,
  StatisticsRelevantDeliveryDatePropertyValue,
  StatisticsRelevantDeliveryDatePropertyValueWithMetadata,
  StatusPropertyValue,
  StatusPropertyValueWithMetadata,
  StockQuantityPropertyValue,
  StockQuantityPropertyValueWithMetadata,
  StorageBinPropertyValue,
  StorageBinPropertyValueWithMetadata,
  StorageLocationPropertyValue,
  StorageLocationPropertyValueWithMetadata,
  StreetAddressPropertyValue,
  StreetAddressPropertyValueWithMetadata,
  THBDataType,
  THBDataTypeWithMetadata,
  TJSDataType,
  TJSDataTypeWithMetadata,
  TMTDataType,
  TMTDataTypeWithMetadata,
  TNDDataType,
  TNDDataTypeWithMetadata,
  TOPDataType,
  TOPDataTypeWithMetadata,
  TRYDataType,
  TRYDataTypeWithMetadata,
  TTDDataType,
  TTDDataTypeWithMetadata,
  TWDDataType,
  TWDDataTypeWithMetadata,
  TZSDataType,
  TZSDataTypeWithMetadata,
  TextDataType,
  TextDataTypeWithMetadata,
  UAHDataType,
  UAHDataTypeWithMetadata,
  UGXDataType,
  UGXDataTypeWithMetadata,
  USDDataType,
  USDDataTypeWithMetadata,
  UYUDataType,
  UYUDataTypeWithMetadata,
  UZSDataType,
  UZSDataTypeWithMetadata,
  UnitDataType,
  UnitDataTypeWithMetadata,
  UnitOfMeasurePropertyValue,
  UnitOfMeasurePropertyValueWithMetadata,
  VESDataType,
  VESDataTypeWithMetadata,
  VNDDataType,
  VNDDataTypeWithMetadata,
  VUVDataType,
  VUVDataTypeWithMetadata,
  ValueDataType,
  ValueDataTypeWithMetadata,
  VendorNumberPropertyValue,
  VendorNumberPropertyValueWithMetadata,
  VolumeDataType,
  VolumeDataTypeWithMetadata,
  WSTDataType,
  WSTDataTypeWithMetadata,
  XAFDataType,
  XAFDataTypeWithMetadata,
  XCDDataType,
  XCDDataTypeWithMetadata,
  XCGDataType,
  XCGDataTypeWithMetadata,
  XOFDataType,
  XOFDataTypeWithMetadata,
  XPFDataType,
  XPFDataTypeWithMetadata,
  YERDataType,
  YERDataTypeWithMetadata,
  YardsDataType,
  YardsDataTypeWithMetadata,
  Yields,
  YieldsOutgoingLinkAndTarget,
  YieldsOutgoingLinksByLinkEntityTypeId,
  YieldsProperties,
  YieldsPropertiesWithMetadata,
  ZARDataType,
  ZARDataTypeWithMetadata,
  ZMWDataType,
  ZMWDataTypeWithMetadata,
  ZWGDataType,
  ZWGDataTypeWithMetadata,
} from "./shared.js";
import type { ObjectMetadata } from "@blockprotocol/type-system";

export type {
  ActualFinishDatePropertyValue,
  ActualFinishDatePropertyValueWithMetadata,
  ActualStartDatePropertyValue,
  ActualStartDatePropertyValueWithMetadata,
  AEDDataType,
  AEDDataTypeWithMetadata,
  AFNDataType,
  AFNDataTypeWithMetadata,
  ALLDataType,
  ALLDataTypeWithMetadata,
  AlternativeBOMPropertyValue,
  AlternativeBOMPropertyValueWithMetadata,
  AMDDataType,
  AMDDataTypeWithMetadata,
  ANGDataType,
  ANGDataTypeWithMetadata,
  AOADataType,
  AOADataTypeWithMetadata,
  AreaDataType,
  AreaDataTypeWithMetadata,
  ARSDataType,
  ARSDataTypeWithMetadata,
  AUDDataType,
  AUDDataTypeWithMetadata,
  AWGDataType,
  AWGDataTypeWithMetadata,
  AZNDataType,
  AZNDataTypeWithMetadata,
  BAMDataType,
  BAMDataTypeWithMetadata,
  Batch,
  BatchNumberPropertyValue,
  BatchNumberPropertyValueWithMetadata,
  BatchOfMaterialLink,
  BatchOutgoingLinkAndTarget,
  BatchOutgoingLinksByLinkEntityTypeId,
  BatchProperties,
  BatchPropertiesWithMetadata,
  BBDDataType,
  BBDDataTypeWithMetadata,
  BDTDataType,
  BDTDataTypeWithMetadata,
  BGNDataType,
  BGNDataTypeWithMetadata,
  BHDDataType,
  BHDDataTypeWithMetadata,
  BIFDataType,
  BIFDataTypeWithMetadata,
  BMDDataType,
  BMDDataTypeWithMetadata,
  BNDDataType,
  BNDDataTypeWithMetadata,
  BOBDataType,
  BOBDataTypeWithMetadata,
  BRLDataType,
  BRLDataTypeWithMetadata,
  BSDDataType,
  BSDDataTypeWithMetadata,
  BTNDataType,
  BTNDataTypeWithMetadata,
  BWPDataType,
  BWPDataTypeWithMetadata,
  BYNDataType,
  BYNDataTypeWithMetadata,
  BZDDataType,
  BZDDataTypeWithMetadata,
  CADDataType,
  CADDataTypeWithMetadata,
  CalendarYearDataType,
  CalendarYearDataTypeWithMetadata,
  CDFDataType,
  CDFDataTypeWithMetadata,
  CentimetersDataType,
  CentimetersDataTypeWithMetadata,
  CHFDataType,
  CHFDataTypeWithMetadata,
  CityPropertyValue,
  CityPropertyValueWithMetadata,
  CLPDataType,
  CLPDataTypeWithMetadata,
  CNYDataType,
  CNYDataTypeWithMetadata,
  COPDataType,
  COPDataTypeWithMetadata,
  CountryPropertyValue,
  CountryPropertyValueWithMetadata,
  CRCDataType,
  CRCDataTypeWithMetadata,
  CubicFeetDataType,
  CubicFeetDataTypeWithMetadata,
  CubicMetresDataType,
  CubicMetresDataTypeWithMetadata,
  CUPDataType,
  CUPDataTypeWithMetadata,
  CurrencyDataType,
  CurrencyDataTypeWithMetadata,
  CustomerNumberPropertyValue,
  CustomerNumberPropertyValueWithMetadata,
  CVEDataType,
  CVEDataTypeWithMetadata,
  CZKDataType,
  CZKDataTypeWithMetadata,
  DateDataType,
  DateDataTypeWithMetadata,
  DaysDataType,
  DaysDataTypeWithMetadata,
  DebitCreditIndicatorPropertyValue,
  DebitCreditIndicatorPropertyValueWithMetadata,
  DeliveredQuantityPropertyValue,
  DeliveredQuantityPropertyValueWithMetadata,
  Delivers,
  DeliversOutgoingLinkAndTarget,
  DeliversOutgoingLinksByLinkEntityTypeId,
  DeliversProperties,
  DeliversPropertiesWithMetadata,
  DeliveryItem,
  DeliveryItemDeliversLink,
  DeliveryItemFulfillsLink,
  DeliveryItemHasMaterialLink,
  DeliveryItemLocatedAtLink,
  DeliveryItemNumberPropertyValue,
  DeliveryItemNumberPropertyValueWithMetadata,
  DeliveryItemOutgoingLinkAndTarget,
  DeliveryItemOutgoingLinksByLinkEntityTypeId,
  DeliveryItemProperties,
  DeliveryItemPropertiesWithMetadata,
  DeliveryNumberPropertyValue,
  DeliveryNumberPropertyValueWithMetadata,
  DescriptionPropertyValue,
  DescriptionPropertyValueWithMetadata,
  DivisionPropertyValue,
  DivisionPropertyValueWithMetadata,
  DJFDataType,
  DJFDataTypeWithMetadata,
  DKKDataType,
  DKKDataTypeWithMetadata,
  DocumentDatePropertyValue,
  DocumentDatePropertyValueWithMetadata,
  DOPDataType,
  DOPDataTypeWithMetadata,
  DurationDataType,
  DurationDataTypeWithMetadata,
  DZDDataType,
  DZDDataTypeWithMetadata,
  EGPDataType,
  EGPDataTypeWithMetadata,
  ERNDataType,
  ERNDataTypeWithMetadata,
  ETBDataType,
  ETBDataTypeWithMetadata,
  EURDataType,
  EURDataTypeWithMetadata,
  ExpiryDatePropertyValue,
  ExpiryDatePropertyValueWithMetadata,
  FeetDataType,
  FeetDataTypeWithMetadata,
  FiscalYearPropertyValue,
  FiscalYearPropertyValueWithMetadata,
  FJDDataType,
  FJDDataTypeWithMetadata,
  FKPDataType,
  FKPDataTypeWithMetadata,
  Fulfills,
  FulfillsOutgoingLinkAndTarget,
  FulfillsOutgoingLinksByLinkEntityTypeId,
  FulfillsProperties,
  FulfillsPropertiesWithMetadata,
  GBPDataType,
  GBPDataTypeWithMetadata,
  GELDataType,
  GELDataTypeWithMetadata,
  GHSDataType,
  GHSDataTypeWithMetadata,
  GIPDataType,
  GIPDataTypeWithMetadata,
  GMDDataType,
  GMDDataTypeWithMetadata,
  GNFDataType,
  GNFDataTypeWithMetadata,
  GoodsReceiptQuantityPropertyValue,
  GoodsReceiptQuantityPropertyValueWithMetadata,
  GramsDataType,
  GramsDataTypeWithMetadata,
  GrossWeightPropertyValue,
  GrossWeightPropertyValueWithMetadata,
  GTQDataType,
  GTQDataTypeWithMetadata,
  GYDDataType,
  GYDDataTypeWithMetadata,
  HasLineItem,
  HasLineItemOutgoingLinkAndTarget,
  HasLineItemOutgoingLinksByLinkEntityTypeId,
  HasLineItemProperties,
  HasLineItemPropertiesWithMetadata,
  HasMaterial,
  HasMaterialOutgoingLinkAndTarget,
  HasMaterialOutgoingLinksByLinkEntityTypeId,
  HasMaterialProperties,
  HasMaterialPropertiesWithMetadata,
  HKDDataType,
  HKDDataTypeWithMetadata,
  HNLDataType,
  HNLDataTypeWithMetadata,
  HoursDataType,
  HoursDataTypeWithMetadata,
  HTGDataType,
  HTGDataTypeWithMetadata,
  HUFDataType,
  HUFDataTypeWithMetadata,
  IDRDataType,
  IDRDataTypeWithMetadata,
  ILSDataType,
  ILSDataTypeWithMetadata,
  ImperialLengthUKDataType,
  ImperialLengthUKDataTypeWithMetadata,
  ImperialLengthUSDataType,
  ImperialLengthUSDataTypeWithMetadata,
  InchesDataType,
  InchesDataTypeWithMetadata,
  INRDataType,
  INRDataTypeWithMetadata,
  IntegerDataType,
  IntegerDataTypeWithMetadata,
  IQDDataType,
  IQDDataTypeWithMetadata,
  IRRDataType,
  IRRDataTypeWithMetadata,
  ISKDataType,
  ISKDataTypeWithMetadata,
  ItemCategoryGroupPropertyValue,
  ItemCategoryGroupPropertyValueWithMetadata,
  ItemNumberPropertyValue,
  ItemNumberPropertyValueWithMetadata,
  JMDDataType,
  JMDDataTypeWithMetadata,
  JODDataType,
  JODDataTypeWithMetadata,
  JPYDataType,
  JPYDataTypeWithMetadata,
  KESDataType,
  KESDataTypeWithMetadata,
  KGSDataType,
  KGSDataTypeWithMetadata,
  KHRDataType,
  KHRDataTypeWithMetadata,
  KilogramsDataType,
  KilogramsDataTypeWithMetadata,
  KilometersDataType,
  KilometersDataTypeWithMetadata,
  KMFDataType,
  KMFDataTypeWithMetadata,
  KPWDataType,
  KPWDataTypeWithMetadata,
  KRWDataType,
  KRWDataTypeWithMetadata,
  KWDDataType,
  KWDDataTypeWithMetadata,
  KYDDataType,
  KYDDataTypeWithMetadata,
  KZTDataType,
  KZTDataTypeWithMetadata,
  LAKDataType,
  LAKDataTypeWithMetadata,
  LanguagePropertyValue,
  LanguagePropertyValueWithMetadata,
  LBPDataType,
  LBPDataTypeWithMetadata,
  LengthDataType,
  LengthDataTypeWithMetadata,
  LineItemCategoryPropertyValue,
  LineItemCategoryPropertyValueWithMetadata,
  Link,
  LinkOutgoingLinkAndTarget,
  LinkOutgoingLinksByLinkEntityTypeId,
  LinkProperties,
  LinkPropertiesWithMetadata,
  LitresDataType,
  LitresDataTypeWithMetadata,
  LKRDataType,
  LKRDataTypeWithMetadata,
  LocatedAt,
  LocatedAtOutgoingLinkAndTarget,
  LocatedAtOutgoingLinksByLinkEntityTypeId,
  LocatedAtProperties,
  LocatedAtPropertiesWithMetadata,
  LRDDataType,
  LRDDataTypeWithMetadata,
  LSLDataType,
  LSLDataTypeWithMetadata,
  LYDDataType,
  LYDDataTypeWithMetadata,
  MADDataType,
  MADDataTypeWithMetadata,
  MassDataType,
  MassDataTypeWithMetadata,
  Material,
  MaterialGroupPropertyValue,
  MaterialGroupPropertyValueWithMetadata,
  MaterialNumberPropertyValue,
  MaterialNumberPropertyValueWithMetadata,
  MaterialOutgoingLinkAndTarget,
  MaterialOutgoingLinksByLinkEntityTypeId,
  MaterialProperties,
  MaterialPropertiesWithMetadata,
  MaterialTypePropertyValue,
  MaterialTypePropertyValueWithMetadata,
  MDLDataType,
  MDLDataTypeWithMetadata,
  MetersDataType,
  MetersDataTypeWithMetadata,
  MetricLengthSIDataType,
  MetricLengthSIDataTypeWithMetadata,
  MetricTonnesDataType,
  MetricTonnesDataTypeWithMetadata,
  MGADataType,
  MGADataTypeWithMetadata,
  MilesDataType,
  MilesDataTypeWithMetadata,
  MillilitresDataType,
  MillilitresDataTypeWithMetadata,
  MillimetersDataType,
  MillimetersDataTypeWithMetadata,
  MKDDataType,
  MKDDataTypeWithMetadata,
  MMKDataType,
  MMKDataTypeWithMetadata,
  MNTDataType,
  MNTDataTypeWithMetadata,
  MOPDataType,
  MOPDataTypeWithMetadata,
  MRPControllerPropertyValue,
  MRPControllerPropertyValueWithMetadata,
  MRUDataType,
  MRUDataTypeWithMetadata,
  MURDataType,
  MURDataTypeWithMetadata,
  MVRDataType,
  MVRDataTypeWithMetadata,
  MWKDataType,
  MWKDataTypeWithMetadata,
  MXNDataType,
  MXNDataTypeWithMetadata,
  MYRDataType,
  MYRDataTypeWithMetadata,
  MZNDataType,
  MZNDataTypeWithMetadata,
  NADDataType,
  NADDataTypeWithMetadata,
  NamePropertyValue,
  NamePropertyValueWithMetadata,
  NetValuePropertyValue,
  NetValuePropertyValueWithMetadata,
  NetWeightPropertyValue,
  NetWeightPropertyValueWithMetadata,
  NGNDataType,
  NGNDataTypeWithMetadata,
  NIODataType,
  NIODataTypeWithMetadata,
  NOKDataType,
  NOKDataTypeWithMetadata,
  NPRDataType,
  NPRDataTypeWithMetadata,
  NumberDataType,
  NumberDataTypeWithMetadata,
  NZDDataType,
  NZDDataTypeWithMetadata,
  OfMaterial,
  OfMaterialOutgoingLinkAndTarget,
  OfMaterialOutgoingLinksByLinkEntityTypeId,
  OfMaterialProperties,
  OfMaterialPropertiesWithMetadata,
  OMRDataType,
  OMRDataTypeWithMetadata,
  OrderQuantityPropertyValue,
  OrderQuantityPropertyValueWithMetadata,
  PABDataType,
  PABDataTypeWithMetadata,
  PENDataType,
  PENDataTypeWithMetadata,
  PGKDataType,
  PGKDataTypeWithMetadata,
  PHPDataType,
  PHPDataTypeWithMetadata,
  PKRDataType,
  PKRDataTypeWithMetadata,
  PLNDataType,
  PLNDataTypeWithMetadata,
  PostalCodePropertyValue,
  PostalCodePropertyValueWithMetadata,
  PoundsDataType,
  PoundsDataTypeWithMetadata,
  ProcurementTypePropertyValue,
  ProcurementTypePropertyValueWithMetadata,
  Procures,
  ProcuresOutgoingLinkAndTarget,
  ProcuresOutgoingLinksByLinkEntityTypeId,
  ProcuresProperties,
  ProcuresPropertiesWithMetadata,
  Produces,
  ProducesOutgoingLinkAndTarget,
  ProducesOutgoingLinksByLinkEntityTypeId,
  ProducesProperties,
  ProducesPropertiesWithMetadata,
  ProductionOrder,
  ProductionOrderHasLineItemLink,
  ProductionOrderItem,
  ProductionOrderItemLocatedAtLink,
  ProductionOrderItemOutgoingLinkAndTarget,
  ProductionOrderItemOutgoingLinksByLinkEntityTypeId,
  ProductionOrderItemProducesLink,
  ProductionOrderItemProperties,
  ProductionOrderItemPropertiesWithMetadata,
  ProductionOrderNumberPropertyValue,
  ProductionOrderNumberPropertyValueWithMetadata,
  ProductionOrderOutgoingLinkAndTarget,
  ProductionOrderOutgoingLinksByLinkEntityTypeId,
  ProductionOrderProperties,
  ProductionOrderPropertiesWithMetadata,
  ProductionOrderTypePropertyValue,
  ProductionOrderTypePropertyValueWithMetadata,
  ProductionOrderYieldsLink,
  ProductionQuantityPropertyValue,
  ProductionQuantityPropertyValueWithMetadata,
  PurchaseOrderItem,
  PurchaseOrderItemHasLineItemLink,
  PurchaseOrderItemLocatedAtLink,
  PurchaseOrderItemNumberPropertyValue,
  PurchaseOrderItemNumberPropertyValueWithMetadata,
  PurchaseOrderItemOutgoingLinkAndTarget,
  PurchaseOrderItemOutgoingLinksByLinkEntityTypeId,
  PurchaseOrderItemProcuresLink,
  PurchaseOrderItemProperties,
  PurchaseOrderItemPropertiesWithMetadata,
  PurchaseOrderNumberPropertyValue,
  PurchaseOrderNumberPropertyValueWithMetadata,
  PurchaseOrderScheduleLine,
  PurchaseOrderScheduleLineOutgoingLinkAndTarget,
  PurchaseOrderScheduleLineOutgoingLinksByLinkEntityTypeId,
  PurchaseOrderScheduleLineProperties,
  PurchaseOrderScheduleLinePropertiesWithMetadata,
  PurchasingOrganizationPropertyValue,
  PurchasingOrganizationPropertyValueWithMetadata,
  PYGDataType,
  PYGDataTypeWithMetadata,
  QARDataType,
  QARDataTypeWithMetadata,
  RegionPropertyValue,
  RegionPropertyValueWithMetadata,
  RejectionReasonPropertyValue,
  RejectionReasonPropertyValueWithMetadata,
  ReleaseDatePropertyValue,
  ReleaseDatePropertyValueWithMetadata,
  RONDataType,
  RONDataTypeWithMetadata,
  RSDDataType,
  RSDDataTypeWithMetadata,
  RUBDataType,
  RUBDataTypeWithMetadata,
  RWFDataType,
  RWFDataTypeWithMetadata,
  SalesOrderItem,
  SalesOrderItemHasMaterialLink,
  SalesOrderItemLocatedAtLink,
  SalesOrderItemOutgoingLinkAndTarget,
  SalesOrderItemOutgoingLinksByLinkEntityTypeId,
  SalesOrderItemProperties,
  SalesOrderItemPropertiesWithMetadata,
  SalesOrganizationPropertyValue,
  SalesOrganizationPropertyValueWithMetadata,
  SARDataType,
  SARDataTypeWithMetadata,
  SBDDataType,
  SBDDataTypeWithMetadata,
  ScheduledDeliveryDatePropertyValue,
  ScheduledDeliveryDatePropertyValueWithMetadata,
  ScheduledFinishDatePropertyValue,
  ScheduledFinishDatePropertyValueWithMetadata,
  ScheduledQuantityPropertyValue,
  ScheduledQuantityPropertyValueWithMetadata,
  ScheduledStartDatePropertyValue,
  ScheduledStartDatePropertyValueWithMetadata,
  ScheduleLineNumberPropertyValue,
  ScheduleLineNumberPropertyValueWithMetadata,
  SCRDataType,
  SCRDataTypeWithMetadata,
  SDGDataType,
  SDGDataTypeWithMetadata,
  SEKDataType,
  SEKDataTypeWithMetadata,
  SGDDataType,
  SGDDataTypeWithMetadata,
  ShippingPointPropertyValue,
  ShippingPointPropertyValueWithMetadata,
  SHPDataType,
  SHPDataTypeWithMetadata,
  Site,
  SiteCodePropertyValue,
  SiteCodePropertyValueWithMetadata,
  SiteOutgoingLinkAndTarget,
  SiteOutgoingLinksByLinkEntityTypeId,
  SiteProperties,
  SitePropertiesWithMetadata,
  SiteTypePropertyValue,
  SiteTypePropertyValueWithMetadata,
  SLEDataType,
  SLEDataTypeWithMetadata,
  SOSDataType,
  SOSDataTypeWithMetadata,
  SquareCentimetresDataType,
  SquareCentimetresDataTypeWithMetadata,
  SquareFeetDataType,
  SquareFeetDataTypeWithMetadata,
  SquareMetresDataType,
  SquareMetresDataTypeWithMetadata,
  SRDDataType,
  SRDDataTypeWithMetadata,
  SSPDataType,
  SSPDataTypeWithMetadata,
  StatisticsRelevantDeliveryDatePropertyValue,
  StatisticsRelevantDeliveryDatePropertyValueWithMetadata,
  StatusPropertyValue,
  StatusPropertyValueWithMetadata,
  STNDataType,
  STNDataTypeWithMetadata,
  StockQuantityPropertyValue,
  StockQuantityPropertyValueWithMetadata,
  StorageBinPropertyValue,
  StorageBinPropertyValueWithMetadata,
  StorageLocationPropertyValue,
  StorageLocationPropertyValueWithMetadata,
  StreetAddressPropertyValue,
  StreetAddressPropertyValueWithMetadata,
  SVCDataType,
  SVCDataTypeWithMetadata,
  SYPDataType,
  SYPDataTypeWithMetadata,
  SZLDataType,
  SZLDataTypeWithMetadata,
  TextDataType,
  TextDataTypeWithMetadata,
  THBDataType,
  THBDataTypeWithMetadata,
  TJSDataType,
  TJSDataTypeWithMetadata,
  TMTDataType,
  TMTDataTypeWithMetadata,
  TNDDataType,
  TNDDataTypeWithMetadata,
  TOPDataType,
  TOPDataTypeWithMetadata,
  TRYDataType,
  TRYDataTypeWithMetadata,
  TTDDataType,
  TTDDataTypeWithMetadata,
  TWDDataType,
  TWDDataTypeWithMetadata,
  TZSDataType,
  TZSDataTypeWithMetadata,
  UAHDataType,
  UAHDataTypeWithMetadata,
  UGXDataType,
  UGXDataTypeWithMetadata,
  UnitDataType,
  UnitDataTypeWithMetadata,
  UnitOfMeasurePropertyValue,
  UnitOfMeasurePropertyValueWithMetadata,
  USDDataType,
  USDDataTypeWithMetadata,
  UYUDataType,
  UYUDataTypeWithMetadata,
  UZSDataType,
  UZSDataTypeWithMetadata,
  ValueDataType,
  ValueDataTypeWithMetadata,
  VendorNumberPropertyValue,
  VendorNumberPropertyValueWithMetadata,
  VESDataType,
  VESDataTypeWithMetadata,
  VNDDataType,
  VNDDataTypeWithMetadata,
  VolumeDataType,
  VolumeDataTypeWithMetadata,
  VUVDataType,
  VUVDataTypeWithMetadata,
  WSTDataType,
  WSTDataTypeWithMetadata,
  XAFDataType,
  XAFDataTypeWithMetadata,
  XCDDataType,
  XCDDataTypeWithMetadata,
  XCGDataType,
  XCGDataTypeWithMetadata,
  XOFDataType,
  XOFDataTypeWithMetadata,
  XPFDataType,
  XPFDataTypeWithMetadata,
  YardsDataType,
  YardsDataTypeWithMetadata,
  YERDataType,
  YERDataTypeWithMetadata,
  Yields,
  YieldsOutgoingLinkAndTarget,
  YieldsOutgoingLinksByLinkEntityTypeId,
  YieldsProperties,
  YieldsPropertiesWithMetadata,
  ZARDataType,
  ZARDataTypeWithMetadata,
  ZMWDataType,
  ZMWDataTypeWithMetadata,
  ZWGDataType,
  ZWGDataTypeWithMetadata,
};

/**
 * A record of activity related to a material, for example movement, production or consumption.
 */
export type MaterialDocument = {
  entityTypeIds: ["https://hash.ai/@h/types/entity-type/material-document/v/1"];
  properties: MaterialDocumentProperties;
  propertiesWithMetadata: MaterialDocumentPropertiesWithMetadata;
};

/**
 * An item number within a document.
 */
export type MaterialDocumentItemNumberPropertyValue = TextDataType;

export type MaterialDocumentItemNumberPropertyValueWithMetadata =
  TextDataTypeWithMetadata;

export type MaterialDocumentLocatedAtLink = {
  linkEntity: LocatedAt;
  rightEntity: Site;
};

export type MaterialDocumentMovesLink = {
  linkEntity: Moves;
  rightEntity: Material;
};

/**
 * A number identifying a material document.
 */
export type MaterialDocumentNumberPropertyValue = TextDataType;

export type MaterialDocumentNumberPropertyValueWithMetadata =
  TextDataTypeWithMetadata;

export type MaterialDocumentOutgoingLinkAndTarget =
  | MaterialDocumentLocatedAtLink
  | MaterialDocumentMovesLink
  | MaterialDocumentPostedAgainstLink
  | MaterialDocumentRecordsLink;

export type MaterialDocumentOutgoingLinksByLinkEntityTypeId = {
  "https://hash.ai/@h/types/entity-type/located-at/v/1": MaterialDocumentLocatedAtLink;
  "https://hash.ai/@h/types/entity-type/moves/v/1": MaterialDocumentMovesLink;
  "https://hash.ai/@h/types/entity-type/posted-against/v/1": MaterialDocumentPostedAgainstLink;
  "https://hash.ai/@h/types/entity-type/records/v/1": MaterialDocumentRecordsLink;
};

export type MaterialDocumentPostedAgainstLink = {
  linkEntity: PostedAgainst;
  rightEntity: PurchaseOrderItem | ProductionOrder | DeliveryItem;
};

/**
 * A record of activity related to a material, for example movement, production or consumption.
 */
export type MaterialDocumentProperties = {
  "https://hash.ai/@h/types/property-type/batch-number/"?: BatchNumberPropertyValue;
  "https://hash.ai/@h/types/property-type/customer-number/"?: CustomerNumberPropertyValue;
  "https://hash.ai/@h/types/property-type/debit-credit-indicator/"?: DebitCreditIndicatorPropertyValue;
  "https://hash.ai/@h/types/property-type/delivery-item-number/"?: DeliveryItemNumberPropertyValue;
  "https://hash.ai/@h/types/property-type/delivery-number/"?: DeliveryNumberPropertyValue;
  "https://hash.ai/@h/types/property-type/document-date/"?: DocumentDatePropertyValue;
  "https://hash.ai/@h/types/property-type/fiscal-year/"?: FiscalYearPropertyValue;
  "https://hash.ai/@h/types/property-type/material-document-item-number/"?: MaterialDocumentItemNumberPropertyValue;
  "https://hash.ai/@h/types/property-type/material-document-number/"?: MaterialDocumentNumberPropertyValue;
  "https://hash.ai/@h/types/property-type/movement-category/"?: MovementCategoryPropertyValue;
  "https://hash.ai/@h/types/property-type/movement-quantity/"?: MovementQuantityPropertyValue;
  "https://hash.ai/@h/types/property-type/movement-type/"?: MovementTypePropertyValue;
  "https://hash.ai/@h/types/property-type/posting-date/"?: PostingDatePropertyValue;
  "https://hash.ai/@h/types/property-type/production-order-number/"?: ProductionOrderNumberPropertyValue;
  "https://hash.ai/@h/types/property-type/purchase-order-item-number/"?: PurchaseOrderItemNumberPropertyValue;
  "https://hash.ai/@h/types/property-type/purchase-order-number/"?: PurchaseOrderNumberPropertyValue;
  "https://hash.ai/@h/types/property-type/reference-document-number/"?: ReferenceDocumentNumberPropertyValue;
  "https://hash.ai/@h/types/property-type/stock-type/"?: StockTypePropertyValue;
  "https://hash.ai/@h/types/property-type/storage-location/"?: StorageLocationPropertyValue;
  "https://hash.ai/@h/types/property-type/unit-of-measure/"?: UnitOfMeasurePropertyValue;
  "https://hash.ai/@h/types/property-type/vendor-number/"?: VendorNumberPropertyValue;
};

export type MaterialDocumentPropertiesWithMetadata = {
  metadata?: ObjectMetadata;
  value: {
    "https://hash.ai/@h/types/property-type/batch-number/"?: BatchNumberPropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/customer-number/"?: CustomerNumberPropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/debit-credit-indicator/"?: DebitCreditIndicatorPropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/delivery-item-number/"?: DeliveryItemNumberPropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/delivery-number/"?: DeliveryNumberPropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/document-date/"?: DocumentDatePropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/fiscal-year/"?: FiscalYearPropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/material-document-item-number/"?: MaterialDocumentItemNumberPropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/material-document-number/"?: MaterialDocumentNumberPropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/movement-category/"?: MovementCategoryPropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/movement-quantity/"?: MovementQuantityPropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/movement-type/"?: MovementTypePropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/posting-date/"?: PostingDatePropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/production-order-number/"?: ProductionOrderNumberPropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/purchase-order-item-number/"?: PurchaseOrderItemNumberPropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/purchase-order-number/"?: PurchaseOrderNumberPropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/reference-document-number/"?: ReferenceDocumentNumberPropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/stock-type/"?: StockTypePropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/storage-location/"?: StorageLocationPropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/unit-of-measure/"?: UnitOfMeasurePropertyValueWithMetadata;
    "https://hash.ai/@h/types/property-type/vendor-number/"?: VendorNumberPropertyValueWithMetadata;
  };
};

export type MaterialDocumentRecordsLink = {
  linkEntity: Records;
  rightEntity: Batch;
};

/**
 * A broad category of goods movement.
 */
export type MovementCategoryPropertyValue = TextDataType;

export type MovementCategoryPropertyValueWithMetadata =
  TextDataTypeWithMetadata;

/**
 * The quantity recorded on a movement or document line.
 */
export type MovementQuantityPropertyValue = KilogramsDataType;
export type MovementQuantityPropertyValueWithMetadata =
  KilogramsDataTypeWithMetadata;

/**
 * The type of a goods movement, such as a goods receipt, goods issue, or transfer.
 */
export type MovementTypePropertyValue = TextDataType;

export type MovementTypePropertyValueWithMetadata = TextDataTypeWithMetadata;

/**
 * Something moved by something.
 */
export type Moves = {
  entityTypeIds: ["https://hash.ai/@h/types/entity-type/moves/v/1"];
  properties: MovesProperties;
  propertiesWithMetadata: MovesPropertiesWithMetadata;
};

export type MovesOutgoingLinkAndTarget = never;

export type MovesOutgoingLinksByLinkEntityTypeId = {};

/**
 * Something moved by something.
 */
export type MovesProperties = LinkProperties & {};

export type MovesPropertiesWithMetadata = LinkPropertiesWithMetadata & {
  metadata?: ObjectMetadata;
  value: {};
};

/**
 * Something a posting or movement is recorded against, such as the order or document it fulfils.
 */
export type PostedAgainst = {
  entityTypeIds: ["https://hash.ai/@h/types/entity-type/posted-against/v/1"];
  properties: PostedAgainstProperties;
  propertiesWithMetadata: PostedAgainstPropertiesWithMetadata;
};

export type PostedAgainstOutgoingLinkAndTarget = never;

export type PostedAgainstOutgoingLinksByLinkEntityTypeId = {};

/**
 * Something a posting or movement is recorded against, such as the order or document it fulfils.
 */
export type PostedAgainstProperties = LinkProperties & {};

export type PostedAgainstPropertiesWithMetadata = LinkPropertiesWithMetadata & {
  metadata?: ObjectMetadata;
  value: {};
};

/**
 * The date on which a transaction was posted.
 */
export type PostingDatePropertyValue = DateDataType;

export type PostingDatePropertyValueWithMetadata = DateDataTypeWithMetadata;

/**
 * Something recorded by something.
 */
export type Records = {
  entityTypeIds: ["https://hash.ai/@h/types/entity-type/records/v/1"];
  properties: RecordsProperties;
  propertiesWithMetadata: RecordsPropertiesWithMetadata;
};

export type RecordsOutgoingLinkAndTarget = never;

export type RecordsOutgoingLinksByLinkEntityTypeId = {};

/**
 * Something recorded by something.
 */
export type RecordsProperties = LinkProperties & {};

export type RecordsPropertiesWithMetadata = LinkPropertiesWithMetadata & {
  metadata?: ObjectMetadata;
  value: {};
};

/**
 * The number of the document a goods movement references, such as the delivery it was received against or the document it reverses.
 */
export type ReferenceDocumentNumberPropertyValue = TextDataType;

export type ReferenceDocumentNumberPropertyValueWithMetadata =
  TextDataTypeWithMetadata;

/**
 * The stock category or inspection/blocking status for inventory.
 */
export type StockTypePropertyValue = TextDataType;

export type StockTypePropertyValueWithMetadata = TextDataTypeWithMetadata;
