/**
 * This file was automatically generated – do not edit it.
 */

import {
  ArchivedPropertyValue,
  BooleanDataType,
  HasAction,
  HasActionOutgoingLinkAndTarget,
  HasActionOutgoingLinksByLinkEntityTypeId,
  HasActionProperties,
  Link,
  LinkOutgoingLinkAndTarget,
  LinkOutgoingLinksByLinkEntityTypeId,
  LinkProperties,
  Notification,
  NotificationAction,
  NotificationActionOutgoingLinkAndTarget,
  NotificationActionOutgoingLinksByLinkEntityTypeId,
  NotificationActionProperties,
  NotificationHasActionLink,
  NotificationOutgoingLinkAndTarget,
  NotificationOutgoingLinksByLinkEntityTypeId,
  NotificationProperties,
  TextDataType,
  TitlePropertyValue,
  URLPropertyValue,
} from "./shared";

export type {
  ArchivedPropertyValue,
  BooleanDataType,
  HasAction,
  HasActionOutgoingLinkAndTarget,
  HasActionOutgoingLinksByLinkEntityTypeId,
  HasActionProperties,
  Link,
  LinkOutgoingLinkAndTarget,
  LinkOutgoingLinksByLinkEntityTypeId,
  LinkProperties,
  Notification,
  NotificationAction,
  NotificationActionOutgoingLinkAndTarget,
  NotificationActionOutgoingLinksByLinkEntityTypeId,
  NotificationActionProperties,
  NotificationHasActionLink,
  NotificationOutgoingLinkAndTarget,
  NotificationOutgoingLinksByLinkEntityTypeId,
  NotificationProperties,
  TextDataType,
  TitlePropertyValue,
  URLPropertyValue,
};
