/**
 * This file was automatically generated – do not edit it.
 */

import type {
  HasParentPropertiesWithMetadata,
  IconPropertyValue,
  IconPropertyValueWithMetadata,
  Link,
  LinkOutgoingLinkAndTarget,
  LinkOutgoingLinksByLinkEntityTypeId,
  LinkProperties,
  LinkPropertiesWithMetadata,
  Page,
  PageHasParentLink,
  PageOutgoingLinkAndTarget,
  PageOutgoingLinksByLinkEntityTypeId,
  PageProperties,
  PagePropertiesWithMetadata,
  SummaryPropertyValue,
  SummaryPropertyValueWithMetadata,
  TextDataType,
  TextDataTypeWithMetadata,
  TitlePropertyValue,
  TitlePropertyValueWithMetadata,
} from "./shared.js";

export type {
  HasParentPropertiesWithMetadata,
  IconPropertyValue,
  IconPropertyValueWithMetadata,
  Link,
  LinkOutgoingLinkAndTarget,
  LinkOutgoingLinksByLinkEntityTypeId,
  LinkProperties,
  LinkPropertiesWithMetadata,
  Page,
  PageHasParentLink,
  PageOutgoingLinkAndTarget,
  PageOutgoingLinksByLinkEntityTypeId,
  PageProperties,
  PagePropertiesWithMetadata,
  SummaryPropertyValue,
  SummaryPropertyValueWithMetadata,
  TextDataType,
  TextDataTypeWithMetadata,
  TitlePropertyValue,
  TitlePropertyValueWithMetadata,
};

export {
  type ArchivedPropertyValue,
  type ArchivedPropertyValueWithMetadata,
  type BlockCollection,
  type BlockCollectionOutgoingLinkAndTarget,
  type BlockCollectionOutgoingLinksByLinkEntityTypeId,
  type BlockCollectionProperties,
  type BlockCollectionPropertiesWithMetadata,
  type BooleanDataType,
  type BooleanDataTypeWithMetadata,
  type FractionalIndexPropertyValue,
  type FractionalIndexPropertyValueWithMetadata,
  type HasParent,
  type HasParentOutgoingLinkAndTarget,
  type HasParentOutgoingLinksByLinkEntityTypeId,
  type HasParentProperties,
} from "./shared.js";
