/**
 * This file was automatically generated – do not edit it.
 */

import type {
  HasIndexedContent,
  HasIndexedContentOutgoingLinkAndTarget,
  HasIndexedContentOutgoingLinksByLinkEntityTypeId,
  HasIndexedContentProperties,
  HasIndexedContentPropertiesWithMetadata,
  Link,
  LinkOutgoingLinkAndTarget,
  LinkOutgoingLinksByLinkEntityTypeId,
  LinkProperties,
  LinkPropertiesWithMetadata,
  ProfileBio,
  ProfileBioHasIndexedContentLink,
  ProfileBioOutgoingLinkAndTarget,
  ProfileBioOutgoingLinksByLinkEntityTypeId,
  ProfileBioProperties,
  ProfileBioPropertiesWithMetadata,
  TextDataType,
  TextDataTypeWithMetadata,
} from "./shared.js";

export type {
  HasIndexedContent,
  HasIndexedContentOutgoingLinkAndTarget,
  HasIndexedContentOutgoingLinksByLinkEntityTypeId,
  HasIndexedContentProperties,
  HasIndexedContentPropertiesWithMetadata,
  Link,
  LinkOutgoingLinkAndTarget,
  LinkOutgoingLinksByLinkEntityTypeId,
  LinkProperties,
  LinkPropertiesWithMetadata,
  ProfileBio,
  ProfileBioHasIndexedContentLink,
  ProfileBioOutgoingLinkAndTarget,
  ProfileBioOutgoingLinksByLinkEntityTypeId,
  ProfileBioProperties,
  ProfileBioPropertiesWithMetadata,
  TextDataType,
  TextDataTypeWithMetadata,
};

export {
  type Block,
  type BlockCollection,
  type BlockCollectionOutgoingLinkAndTarget,
  type BlockCollectionOutgoingLinksByLinkEntityTypeId,
  type BlockCollectionProperties,
  type BlockCollectionPropertiesWithMetadata,
  type BlockHasDataLink,
  type BlockOutgoingLinkAndTarget,
  type BlockOutgoingLinksByLinkEntityTypeId,
  type BlockProperties,
  type BlockPropertiesWithMetadata,
  type ComponentIdPropertyValue,
  type ComponentIdPropertyValueWithMetadata,
  type FractionalIndexPropertyValue,
  type FractionalIndexPropertyValueWithMetadata,
  type HasData,
  type HasDataOutgoingLinkAndTarget,
  type HasDataOutgoingLinksByLinkEntityTypeId,
  type HasDataProperties,
  type HasDataPropertiesWithMetadata,
} from "./shared.js";
