/**
 * This file was automatically generated – do not edit it.
 */

import type {
  Company,
  CompanyNumberPropertyValue,
  CompanyNumberPropertyValueWithMetadata,
  CompanyOutgoingLinkAndTarget,
  CompanyOutgoingLinksByLinkEntityTypeId,
  CompanyProperties,
  CompanyPropertiesWithMetadata,
  DescriptionPropertyValue,
  DescriptionPropertyValueWithMetadata,
  NamePropertyValue,
  NamePropertyValueWithMetadata,
  TextDataType,
  TextDataTypeWithMetadata,
  ValueDataType,
  ValueDataTypeWithMetadata,
  Vendor,
  VendorNumberPropertyValue,
  VendorNumberPropertyValueWithMetadata,
  VendorOutgoingLinkAndTarget,
  VendorOutgoingLinksByLinkEntityTypeId,
  VendorProperties,
  VendorPropertiesWithMetadata,
} from "./shared.js";

export type {
  Company,
  CompanyNumberPropertyValue,
  CompanyNumberPropertyValueWithMetadata,
  CompanyOutgoingLinkAndTarget,
  CompanyOutgoingLinksByLinkEntityTypeId,
  CompanyProperties,
  CompanyPropertiesWithMetadata,
  DescriptionPropertyValue,
  DescriptionPropertyValueWithMetadata,
  NamePropertyValue,
  NamePropertyValueWithMetadata,
  TextDataType,
  TextDataTypeWithMetadata,
  ValueDataType,
  ValueDataTypeWithMetadata,
  Vendor,
  VendorNumberPropertyValue,
  VendorNumberPropertyValueWithMetadata,
  VendorOutgoingLinkAndTarget,
  VendorOutgoingLinksByLinkEntityTypeId,
  VendorProperties,
  VendorPropertiesWithMetadata,
};
