extend = { path = "../../.github/scripts/rust/Makefile.toml" }

[tasks.yarn-install-openapi]
description = "Installs the required yarn dependencies for generating the API client"
extend = "yarn"
cwd = "${REPO_ROOT}/apps/hash-graph/clients"

[tasks.deployment-up]
run_task = { name = ["docker-compose-deployment-up", "migrate-db"] }

[tasks.docker-compose-deployment-up]
private = false
category = "Deploy"
description = "Spins up the deployment environment"
extend = "yarn"
args = ["external-services", "up", "postgres", "--wait"]
cwd = "${REPO_ROOT}"

[tasks.migrate-db]
private = false
category = "Deploy"
description = "Run DB migrations using the Graph binary"
extend = "yarn"
args = ["external-services", "up", "graph-migrate", "--build"]
cwd = "${REPO_ROOT}"

[tasks.deployment-down]
private = false
category = "Deploy"
description = "Tears down the deployment environment"
extend = "yarn"
args = ["external-services", "down"]
cwd = "${REPO_ROOT}"

[tasks.build-docker]
category = "Deploy"
description = "Spins up the Graph API as external service"
extend = "yarn"
args = ["external-services", "build", "graph", "${@}"]
cwd = "${REPO_ROOT}"
env = { DOCKER_BUILDKIT = 1 }

[tasks.graph-up]
category = "Deploy"
description = "Spins up the Graph API as external service"
extend = "yarn"
args = ["external-services", "up", "--wait", "graph", "${@}"]
cwd = "${REPO_ROOT}"

[tasks.graph-down]
category = "Deploy"
description = "Tears down up the Graph API"
extend = "yarn"
args = ["external-services", "down"]
cwd = "${REPO_ROOT}"

[tasks.test-docker]
run_task = { name = ["yarn-install-openapi", "graph-up", "test-rest-api", "graph-down"] }

[tasks.test-rest-api]
# This is a temporary solution until we have e2e tests in place
extend = "yarn"
args = ["httpyac", "send", "--all", "${REPO_ROOT}/apps/hash-graph/hash_graph/tests/rest-test.http", "${@}"]
