import type { SDCPN } from "../../core/types/sdcpn";
import { nodeDimensions } from "../styling";

export const exampleSDCPN: SDCPN = {
  id: "example-drug-production",
  title: "Drug Production",
  places: [
    {
      id: "place_0",
      name: "Plant A Supply",
      dimensions: 1,
      differentialEquationCode: "",
      x: 20,
      y: 120,
      width: nodeDimensions.place.width,
      height: nodeDimensions.place.height,
    },
    {
      id: "place_1",
      name: "Plant B Supply",
      dimensions: 1,
      differentialEquationCode: "",
      x: 20,
      y: 600,
      width: nodeDimensions.place.width,
      height: nodeDimensions.place.height,
    },
    {
      id: "place_2",
      name: "Manufacturing Plant",
      dimensions: 1,
      differentialEquationCode: "",
      x: 300,
      y: 300,
      width: nodeDimensions.place.width,
      height: nodeDimensions.place.height,
    },
    {
      id: "place_3",
      name: "QA Queue",
      dimensions: 1,
      differentialEquationCode: "",
      x: 700,
      y: 350,
      width: nodeDimensions.place.width,
      height: nodeDimensions.place.height,
    },
    {
      id: "place_4",
      name: "Disposal",
      dimensions: 1,
      differentialEquationCode: "",
      x: 1100,
      y: 600,
      width: nodeDimensions.place.width,
      height: nodeDimensions.place.height,
    },
    {
      id: "place_5",
      name: "Dispatch",
      dimensions: 1,
      differentialEquationCode: "",
      x: 1000,
      y: 200,
      width: nodeDimensions.place.width,
      height: nodeDimensions.place.height,
    },
    {
      id: "place_6",
      name: "Hospital",
      dimensions: 1,
      differentialEquationCode: "",
      x: 1300,
      y: 380,
      width: nodeDimensions.place.width,
      height: nodeDimensions.place.height,
    },
  ],
  transitions: [
    {
      id: "transition_0",
      name: "Deliver to Plant",
      inputArcs: [
        { placeId: "place_0", weight: 1 },
        { placeId: "place_1", weight: 1 },
      ],
      outputArcs: [{ placeId: "place_2", weight: 1 }],
      lambdaCode: "",
      transitionKernelCode: "",
      x: 100,
      y: 400,
      width: nodeDimensions.transition.width,
      height: nodeDimensions.transition.height,
    },
    {
      id: "transition_1",
      name: "Manufacture",
      inputArcs: [{ placeId: "place_2", weight: 1 }],
      outputArcs: [{ placeId: "place_3", weight: 1 }],
      lambdaCode: "",
      transitionKernelCode: "",
      x: 490,
      y: 350,
      width: nodeDimensions.transition.width,
      height: nodeDimensions.transition.height,
    },
    {
      id: "transition_2",
      name: "Quality Check",
      inputArcs: [{ placeId: "place_3", weight: 1 }],
      outputArcs: [
        { placeId: "place_5", weight: 1 },
        { placeId: "place_4", weight: 1 },
      ],
      lambdaCode: "",
      transitionKernelCode: "",
      x: 870,
      y: 400,
      width: nodeDimensions.transition.width,
      height: nodeDimensions.transition.height,
    },
    {
      id: "transition_3",
      name: "Ship",
      inputArcs: [{ placeId: "place_5", weight: 1 }],
      outputArcs: [{ placeId: "place_6", weight: 1 }],
      lambdaCode: "",
      transitionKernelCode: "",
      x: 1150,
      y: 280,
      width: nodeDimensions.transition.width,
      height: nodeDimensions.transition.height,
    },
  ],
};
