import type { SDCPN } from "../core/types/sdcpn";
import { nodeDimensions } from "../views/SDCPN/styles/styling";

export const supplyChainSDCPN: SDCPN = {
  id: "example-drug-production",
  title: "Drug Production",
  types: [],
  differentialEquations: [],
  parameters: [],
  places: [
    {
      id: "place__0",
      name: "PlantASupply",
      type: null,
      dynamicsEnabled: false,
      differentialEquationCode: null,
      x: 20,
      y: 120,
      width: nodeDimensions.place.width,
      height: nodeDimensions.place.height,
    },
    {
      id: "place__1",
      name: "PlantBSupply",
      type: null,
      dynamicsEnabled: false,
      differentialEquationCode: null,
      x: 20,
      y: 600,
      width: nodeDimensions.place.width,
      height: nodeDimensions.place.height,
    },
    {
      id: "place__2",
      name: "ManufacturingPlant",
      type: null,
      dynamicsEnabled: false,
      differentialEquationCode: null,
      x: 300,
      y: 300,
      width: nodeDimensions.place.width,
      height: nodeDimensions.place.height,
    },
    {
      id: "place__3",
      name: "QAQueue",
      type: null,
      dynamicsEnabled: false,
      differentialEquationCode: null,
      x: 700,
      y: 350,
      width: nodeDimensions.place.width,
      height: nodeDimensions.place.height,
    },
    {
      id: "place__4",
      name: "Disposal",
      type: null,
      dynamicsEnabled: false,
      differentialEquationCode: null,
      x: 1100,
      y: 600,
      width: nodeDimensions.place.width,
      height: nodeDimensions.place.height,
    },
    {
      id: "place__5",
      name: "Dispatch",
      type: null,
      dynamicsEnabled: false,
      differentialEquationCode: null,
      x: 1000,
      y: 200,
      width: nodeDimensions.place.width,
      height: nodeDimensions.place.height,
    },
    {
      id: "place__6",
      name: "Hospital",
      type: null,
      dynamicsEnabled: false,
      differentialEquationCode: null,
      x: 1300,
      y: 380,
      width: nodeDimensions.place.width,
      height: nodeDimensions.place.height,
    },
  ],
  transitions: [
    {
      id: "transition__0",
      name: "Deliver to Plant",
      inputArcs: [
        { placeId: "place__0", weight: 1 },
        { placeId: "place__1", weight: 1 },
      ],
      outputArcs: [{ placeId: "place__2", weight: 1 }],
      lambdaType: "predicate",
      lambdaCode: "export default Lambda(() => true);",
      transitionKernelCode: "",
      x: 100,
      y: 400,
      width: nodeDimensions.transition.width,
      height: nodeDimensions.transition.height,
    },
    {
      id: "transition__1",
      name: "Manufacture",
      inputArcs: [{ placeId: "place__2", weight: 1 }],
      outputArcs: [{ placeId: "place__3", weight: 1 }],
      lambdaType: "predicate",
      lambdaCode: "export default Lambda(() => true);",
      transitionKernelCode: "",
      x: 490,
      y: 350,
      width: nodeDimensions.transition.width,
      height: nodeDimensions.transition.height,
    },
    {
      id: "transition__2",
      name: "Quality Check",
      inputArcs: [{ placeId: "place__3", weight: 1 }],
      outputArcs: [
        { placeId: "place__5", weight: 1 },
        { placeId: "place__4", weight: 1 },
      ],
      lambdaType: "predicate",
      lambdaCode: "export default Lambda(() => true);",
      transitionKernelCode: "",
      x: 870,
      y: 400,
      width: nodeDimensions.transition.width,
      height: nodeDimensions.transition.height,
    },
    {
      id: "transition__3",
      name: "Ship",
      inputArcs: [{ placeId: "place__5", weight: 1 }],
      outputArcs: [{ placeId: "place__6", weight: 1 }],
      lambdaType: "predicate",
      lambdaCode: "export default Lambda(() => true);",
      transitionKernelCode: "",
      x: 1150,
      y: 280,
      width: nodeDimensions.transition.width,
      height: nodeDimensions.transition.height,
    },
  ],
};
