graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hash_graph">hash-graph</a>]
    1[<a href="../hash_codec">hash-codec</a>]
    2[<a href="../hash_codegen">hash-codegen</a>]
    3[<a href="../hash_graph_api">hash-graph-api</a>]
    4[<a href="../hash_graph_test_server">hash-graph-test-server</a>]
    5[<a href="../harpc_client">harpc-client</a>]
    6[<a href="../harpc_codec">harpc-codec</a>]
    7[<a href="../harpc_net">harpc-net</a>]
    8[<a href="../harpc_server">harpc-server</a>]
    9[harpc-system]
    class 9 root
    10[<a href="../harpc_tower">harpc-tower</a>]
    11[<a href="../harpc_types">harpc-types</a>]
    12[<a href="../harpc_wire_protocol">harpc-wire-protocol</a>]
    13[<a href="../error_stack">error-stack</a>]
    14[<a href="../hash_graph_benches">hash-graph-benches</a>]
    0 --> 4
    1 -.-> 2
    1 --> 12
    3 --> 1
    3 --> 8
    4 --> 3
    5 --> 9
    6 --> 11
    6 --> 13
    7 --> 1
    7 -.-> 6
    7 --> 6
    8 -.-> 5
    9 --> 10
    10 -.-> 7
    10 --> 7
    12 -.-> 11
    12 --> 11
    12 --> 13
    14 -.-> 3
