graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[harpc-system]
    class 0 root
    1[<a href="../harpc_types/index.html">harpc-types</a>]
    2[<a href="../harpc_tower/index.html">harpc-tower</a>]
    3[<a href="../harpc_net/index.html">harpc-net</a>]
    4[<a href="../harpc_codec/index.html">harpc-codec</a>]
    5[<a href="../error_stack/index.html">error-stack</a>]
    6[<a href="../harpc_wire_protocol/index.html">harpc-wire-protocol</a>]
    7[<a href="../hash_codec/index.html">hash-codec</a>]
    8[<a href="../harpc_client/index.html">harpc-client</a>]
    9[<a href="../harpc_server/index.html">harpc-server</a>]
    10[<a href="../hash_graph_api/index.html">hash-graph-api</a>]
    11[<a href="../hash_graph/index.html">hash-graph</a>]
    12[<a href="../hash_graph_benches/index.html">hash-graph-benches</a>]
    13[<a href="../hash_graph_test_server/index.html">hash-graph-test-server</a>]
    0 --> 2
    2 -.-> 3
    2 --> 3
    3 -.-> 4
    3 --> 7
    3 --> 4
    4 --> 1
    4 --> 5
    6 -.-> 1
    6 --> 1
    6 --> 5
    7 --> 6
    8 --> 0
    9 -.-> 8
    10 --> 9
    12 -.-> 10
    13 --> 10
    11 --> 13