# This file either runs with JetBrains' http requests or using httpYac (https://httpyac.github.io).

### Create account
POST http://127.0.0.1:4000/accounts
X-Authenticated-User-Actor-Id: 00000000-0000-0000-0000-000000000000

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.global.set("account_id", response.body.toString());
    });
%}

### Create account web
POST http://127.0.0.1:4000/webs
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
   "ownedById": "{{account_id}}",
   "owner": {
       "kind": "account",
       "subjectId": "{{account_id}}"
    }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}

### Create account group
POST http://127.0.0.1:4000/account_groups
X-Authenticated-User-Actor-Id: {{account_id}}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.global.set("account_group_id", response.body.toString());
    });
%}

### Create account group web
POST http://127.0.0.1:4000/webs
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
   "ownedById": "{{account_group_id}}",
   "owner": {
       "kind": "accountGroup",
       "subjectId": "{{account_group_id}}"
    }
}

> {%
  client.test("status", function() {
    client.assert(response.status === 204, "Response status is not 204");
  });
%}

### Check permission for adding member to account group
GET http://127.0.0.1:4000/account_groups/{{account_group_id}}/permissions/add_member
X-Authenticated-User-Actor-Id: {{account_id}}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.has_permission, "Account group can not add new owners");
    });
%}

### Get all data types
POST http://127.0.0.1:4000/data-types/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "all": []
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 0,
      "outgoing": 0
    },
    "hasRightEntity": {
      "incoming": 0,
      "outgoing": 0
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
        "start": {
          "kind": "unbounded"
        },
        "end": null
      }
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.roots.length === 0, "Unexpected number of data types"); // The number of primitive data types
    });
%}

### Insert owned data types
POST http://127.0.0.1:4000/data-types
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "ownedById": "{{account_id}}",
  "schema": [
    {
      "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/data-type",
      "kind": "dataType",
      "$id": "http://localhost:3000/@alice/types/data-type/text/v/1",
      "title": "Text",
      "type": "string"
    },
    {
      "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/data-type",
      "kind": "dataType",
      "$id": "http://localhost:3000/@alice/types/data-type/number/v/1",
      "title": "Number",
      "type": "number"
    }
  ]
}

> {%
    client.test("status", function() {
        client.assert(response.status === 403, "Response status is not 200");
    });
%}

### Insert external data types
POST http://127.0.0.1:4000/data-types/load
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "dataTypeId": "https://blockprotocol.org/@blockprotocol/types/data-type/text/v/1"
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("text_data_type_id", `${response.body.recordId.baseUrl}v/${response.body.recordId.version}`);
%}

### Get Text data type
POST http://127.0.0.1:4000/data-types/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "equal": [
      {
        "path": [
          "versionedUrl"
        ]
      },
      {
        "parameter": "{{text_data_type_id}}"
      }
    ]
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 0,
      "outgoing": 0
    },
    "hasRightEntity": {
      "incoming": 0,
      "outgoing": 0
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
        "start": {
          "kind": "unbounded"
        },
        "end": null
      }
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.roots.length === 1, "Unexpected number of data types");
    });
%}

### Update Text data type
PUT http://127.0.0.1:4000/data-types
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "typeToUpdate": "http://localhost:3000/@alice/types/data-type/text/v/1",
  "schema": {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/data-type",
    "kind": "dataType",
    "title": "Text",
    "description": "An ordered sequence of characters",
    "type": "string"
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 403, "Response status is not 200");
    });
%}

### Insert Name property type
POST http://127.0.0.1:4000/property-types
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "ownedById": "{{account_id}}",
  "schema": {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/property-type",
    "kind": "propertyType",
    "$id": "http://localhost:3000/@alice/types/property-type/name/v/1",
    "title": "Name",
    "oneOf": [
      {
        "$ref": "{{text_data_type_id}}"
      }
    ]
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("person_property_type_id", `${response.body.recordId.baseUrl}v/${response.body.recordId.version}`);
%}

### Get Name property type
POST http://127.0.0.1:4000/property-types/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "equal": [
      { "path": ["versionedUrl"] },
      { "parameter": "{{person_property_type_id}}" }
    ]
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 0,
      "outgoing": 0
    },
    "hasRightEntity": {
      "incoming": 0,
      "outgoing": 0
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
        "start": {
          "kind": "unbounded"
        },
        "end": null
      }
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.roots.length === 1, "Unexpected number of property types");
    });
%}

### Update Name property type
PUT http://127.0.0.1:4000/property-types
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "typeToUpdate": "http://localhost:3000/@alice/types/property-type/name/v/1",
  "schema": {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/property-type",
    "kind": "propertyType",
    "title": "Name",
    "oneOf": [
      {
        "$ref": "{{text_data_type_id}}"
      }
    ]
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get all latest property types
POST http://127.0.0.1:4000/property-types/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "equal": [
      {
        "path": [
          "version"
        ]
      },
      {
        "parameter": "latest"
      }
    ]
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 0,
      "outgoing": 0
    },
    "hasRightEntity": {
      "incoming": 0,
      "outgoing": 0
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
          "start": {
          "kind": "unbounded"
          },
          "end": null
      }
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.roots.length === 1, "Unexpected number of property types");
    });
%}

### Insert Friendship entity link type
POST http://127.0.0.1:4000/entity-types
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "ownedById": "{{account_id}}",
  "schema": {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/entity-type",
    "kind": "entityType",
    "$id": "http://localhost:3000/@alice/types/entity-type/friendship/v/1",
    "type": "object",
    "title": "Friendship",
    "allOf": [
      {
        "$ref": "https://blockprotocol.org/@blockprotocol/types/entity-type/link/v/1"
      }
    ],
    "properties": {}
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("friendship_link_entity_type_id", `${response.body.recordId.baseUrl}v/${response.body.recordId.version}`);
%}

### Allow the friendship entity link type to be instantiated by the account
POST http://127.0.0.1:4000/entity-types/relationships
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

[
  {
    "operation": "create",
    "resource": "{{friendship_link_entity_type_id}}",
    "relationAndSubject": {
      "relation": "instantiator",
      "subject": {
        "kind": "account",
        "subjectId": "{{account_id}}"
      }
    }
  }
]

### Get Friendship entity type
POST http://127.0.0.1:4000/entity-types/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "equal": [
      {
        "path": [
          "versionedUrl"
        ]
      },
      {
        "parameter": "{{friendship_link_entity_type_id}}"
      }
    ]
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 2,
      "outgoing": 2
    },
    "hasRightEntity": {
      "incoming": 2,
      "outgoing": 2
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
        "interval": {
          "start": {
            "kind": "unbounded"
          },
          "end": null
        }
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.roots.length === 1, "Unexpected number of entities");
    });
%}

### Insert Person entity type
POST http://127.0.0.1:4000/entity-types
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "ownedById": "{{account_id}}",
  "schema": {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/entity-type",
    "kind": "entityType",
    "$id": "http://localhost:3000/@alice/types/entity-type/person/v/1",
    "type": "object",
    "title": "Person",
    "properties": {
      "http://localhost:3000/@alice/types/property-type/name/": {
        "$ref": "http://localhost:3000/@alice/types/property-type/name/v/1"
      }
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("person_entity_type_id", `${response.body.recordId.baseUrl}v/${response.body.recordId.version}`);
%}

### Allow the person entity type to be instantiated by the account
POST http://127.0.0.1:4000/entity-types/relationships
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

[
  {
    "operation": "create",
    "resource": "{{person_entity_type_id}}",
    "relationAndSubject": {
      "relation": "instantiator",
      "subject": {
        "kind": "account",
        "subjectId": "{{account_id}}"
      }
    }
  }
]

### Get Person entity type
POST http://127.0.0.1:4000/entity-types/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "equal": [
      { "path": ["versionedUrl"] },
      { "parameter": "{{person_entity_type_id}}" }
    ]
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 0,
      "outgoing": 0
    },
    "hasRightEntity": {
      "incoming": 0,
      "outgoing": 0
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
        "start": {
          "kind": "unbounded"
        },
        "end": null
      }
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.roots.length === 1, "Unexpected number of entity types");
    });
%}

### Update Person entity type
PUT http://127.0.0.1:4000/entity-types
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "typeToUpdate": "http://localhost:3000/@alice/types/entity-type/person/v/1",
  "schema": {
    "$schema": "https://blockprotocol.org/types/modules/graph/0.3/schema/entity-type",
    "kind": "entityType",
    "type": "object",
    "title": "Person",
    "properties": {
      "http://localhost:3000/@alice/types/property-type/name/": {
        "$ref": "http://localhost:3000/@alice/types/property-type/name/v/2"
      }
    },
    "links": {
      "{{friendship_link_entity_type_id}}": {
        "type": "array",
        "items": {
          "oneOf": [
            {
              "$ref": "http://localhost:3000/@alice/types/entity-type/person/v/2"
            }
          ]
        },
        "ordered": false
      }
    }
  },
  "labelProperty": "http://localhost:3000/@alice/types/property-type/name/"
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("person_entity_type_id_2", `${response.body.recordId.baseUrl}v/${response.body.recordId.version}`);
%}

### Allow the person entity type to be instantiated by the account
POST http://127.0.0.1:4000/entity-types/relationships
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

[
  {
    "operation": "create",
    "resource": "{{person_entity_type_id_2}}",
    "relationAndSubject": {
      "relation": "instantiator",
      "subject": {
        "kind": "account",
        "subjectId": "{{account_id}}"
      }
    }
  }
]

### Get all latest entity types
POST http://127.0.0.1:4000/entity-types/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "equal": [
      {
        "path": [
          "version"
        ]
      },
      {
        "parameter": "latest"
      }
    ]
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 0,
      "outgoing": 0
    },
    "hasRightEntity": {
      "incoming": 0,
      "outgoing": 0
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
        "start": {
          "kind": "unbounded"
        },
        "end": null
      }
    }
  }
}

> {%
  client.test("status", function() {
    client.assert(response.status === 200, "Response status is not 200");
    client.assert(response.body.roots.length === 3, "Unexpected number of entity types");
  });
%}

### Get entity types by label property
POST http://127.0.0.1:4000/entity-types/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "equal": [
      {
        "path": [
          "labelProperty"
        ]
      },
      {
        "parameter": "http://localhost:3000/@alice/types/property-type/name/"
      }
    ]
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 0,
      "outgoing": 0
    },
    "hasRightEntity": {
      "incoming": 0,
      "outgoing": 0
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
        "start": {
          "kind": "unbounded"
        },
        "end": null
      }
    }
  }
}

> {%
  client.test("status", function() {
    client.assert(response.status === 200, "Response status is not 200");
    client.assert(response.body.roots.length === 1, "Unexpected number of entity types");
  });
%}

### Get all link entity type
POST http://127.0.0.1:4000/entity-types/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "equal": [
      {
        "path": [
          "inheritsFrom",
          "*",
          "versionedUrl"
        ]
      },
      {
        "parameter": "https://blockprotocol.org/@blockprotocol/types/entity-type/link/v/1"
      }
    ]
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 2,
      "outgoing": 2
    },
    "hasRightEntity": {
      "incoming": 2,
      "outgoing": 2
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
          "start": {
          "kind": "unbounded"
          },
          "end": null
      }
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.roots.length === 1, "Unexpected number of entity types");
    });
%}

### Get all parent entity types
POST http://127.0.0.1:4000/entity-types/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "equal": [
      {
        "path": [
          "children",
          "*",
          "versionedUrl"
        ]
      },
      {
        "parameter": "http://localhost:3000/@alice/types/entity-type/friendship/v/1"
      }
    ]
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 0,
      "outgoing": 0
    },
    "hasRightEntity": {
      "incoming": 0,
      "outgoing": 0
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
        "start": null,
        "end": null
      }
    }
  }
}

> {%
  client.test("status", function() {
    client.assert(response.status === 200, "Response status is not 200");
    client.assert(response.body.roots.length === 1, "Unexpected number of entity types");
    client.assert(response.body.roots[0].baseId === "https://blockprotocol.org/@blockprotocol/types/entity-type/link/", "Unexpected parent type");
  });
%}

### Get all entity types which links to a link (should be none)
POST http://127.0.0.1:4000/entity-types/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "all": [
      {
        "equal": [
          {
            "path": [
              "links",
              "*",
              "baseUrl"
            ]
          },
          {
            "parameter": "https://blockprotocol.org/@blockprotocol/types/entity-type/link/"
          }
        ]
      }
    ]
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 2,
      "outgoing": 2
    },
    "hasRightEntity": {
      "incoming": 2,
      "outgoing": 2
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
        "start": {
          "kind": "unbounded"
        },
        "end": null
      }
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.roots.length === 0, "Unexpected number of entity types");
    });
%}

### Get all entity types starting with "http://localhost:3000/@alice"
POST http://127.0.0.1:4000/entity-types/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "startsWith": [
      { "path": ["versionedUrl"] },
      { "parameter": "http://localhost:3000/@alice" }
    ]
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 0,
      "outgoing": 0
    },
    "hasRightEntity": {
      "incoming": 0,
      "outgoing": 0
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
        "start": {
          "kind": "unbounded"
        },
        "end": null
      }
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.roots.length === 3, "Unexpected number of entity types");
    });
%}

### Get all entity types, where the title ends with "ship"
POST http://127.0.0.1:4000/entity-types/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "endsWith": [
      { "path": ["title"] },
      { "parameter": "ship" }
    ]
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 0,
      "outgoing": 0
    },
    "hasRightEntity": {
      "incoming": 0,
      "outgoing": 0
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
        "start": {
          "kind": "unbounded"
        },
        "end": null
      }
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.roots.length === 1, "Unexpected number of entity types");
        client.assert(response.body.roots[0].baseId === "http://localhost:3000/@alice/types/entity-type/friendship/", "Unexpected number of entity types");
    });
%}

### Validate person entity to insert
POST http://127.0.0.1:4000/entities/validate
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "entityTypeId": "https://hash.ai/@hash/types/entity-type/user/v/1",
  "properties": {
    "http://localhost:3000/@alice/types/property-type/name/": "Alice"
  },
  "operations": ["all"]
}

> {%
    client.test("status", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}

### Insert Person entity
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "ownedById": "{{account_id}}",
  "properties": {
    "http://localhost:3000/@alice/types/property-type/name/": "Alice"
  },
  "owner": "{{account_id}}",
  "entityTypeId": "https://hash.ai/@hash/types/entity-type/user/v/1"
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("person_a_entity_id", response.body.recordId.entityId);
    client.global.set("person_a_owned_by_id", response.body.recordId.entityId.split("~")[0])
    client.global.set("person_a_entity_uuid", response.body.recordId.entityId.split("~")[1])
%}

### Get latest Person entity
POST http://127.0.0.1:4000/entities/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
  "all": [
      {
        "equal": [
          {
            "path": [
              "uuid"
            ]
          },
          {
            "parameter": "{{person_a_entity_uuid}}"
          }
        ]
      },
      {
        "equal": [
          {
            "path": [
              "ownedById"
            ]
          },
          {
            "parameter": "{{person_a_owned_by_id}}"
          }
        ]
      }
    ]
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 2,
      "outgoing": 2
    },
    "hasRightEntity": {
      "incoming": 2,
      "outgoing": 2
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
        "start": null,
        "end": null
      }
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.roots.length === 1, "Unexpected number of entities");
    });
%}


### Validate person entity to update
POST http://127.0.0.1:4000/entities/validate
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "entityTypeId": "http://localhost:3000/@alice/types/entity-type/person/v/2",
  "properties": {
    "http://localhost:3000/@alice/types/property-type/name/": "Alice Allison"
  },
  "operations": ["all"]
}

> {%
    client.test("status", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}

### Update Person entity
PUT http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
 "entityId": "{{person_a_entity_id}}",
 "entityTypeId": "http://localhost:3000/@alice/types/entity-type/person/v/2",
 "properties": {
   "http://localhost:3000/@alice/types/property-type/name/": "Alice Allison"
 },
 "archived": false
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Insert second Person entity
POST http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "ownedById": "{{account_id}}",
  "properties": {
    "http://localhost:3000/@alice/types/property-type/name/": "Bob"
  },
  "owner": "{{account_id}}",
  "entityTypeId": "http://localhost:3000/@alice/types/entity-type/person/v/1"
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.global.set("person_b_entity_id", response.body.recordId.entityId);
    client.global.set("person_b_entity_uuid", response.body.recordId.entityId.split("~")[1])
%}

### Get all latest entities by using a query
POST http://127.0.0.1:4000/entities/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "all": []
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 2,
      "outgoing": 2
    },
    "hasRightEntity": {
      "incoming": 2,
      "outgoing": 2
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
        "start": null,
        "end": null
      }
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.roots.length === 2, "Unexpected number of entities");
    });
%}

### Validate link to insert between persons
POST http://127.0.0.1:4000/entities/validate
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "entityTypeId": "{{friendship_link_entity_type_id}}",
  "properties": {},
  "linkData": {
    "leftEntityId": "{{person_a_entity_id}}",
    "rightEntityId": "{{person_b_entity_id}}"
  },
  "operations": ["all"]
}

> {%
    client.test("status", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}

### Insert link between entities
POST http://127.0.0.1:4000/entities
// TODO Use a structural query to check the link was created
// TODO remove this link
// TODO check the link was removed
// TODO insert ordered link
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "ownedById": "{{account_id}}",
  "properties": {},
  "entityTypeId": "{{friendship_link_entity_type_id}}",
  "owner": "{{account_id}}",
  "linkData": {
    "leftEntityId": "{{person_a_entity_id}}",
    "rightEntityId": "{{person_b_entity_id}}"
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get all link entities
POST http://127.0.0.1:4000/entities/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "equal": [
      {
        "path": [
          "type",
          "versionedUrl"
        ]
      },
      {
        "parameter": "https://blockprotocol.org/@blockprotocol/types/entity-type/link/v/1"
      }
    ]
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 0,
      "outgoing": 0
    },
    "hasRightEntity": {
      "incoming": 0,
      "outgoing": 0
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
        "start": {
          "kind": "unbounded"
        },
        "end": null
      }
    }
  }
}

> {%
  client.test("status", function() {
    client.assert(response.status === 200, "Response status is not 200");
    client.assert(response.body.roots.length === 1, "Unexpected number of entity types");
  });
%}



### Get link by source and target
POST http://127.0.0.1:4000/entities/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "all": [
      {
        "equal": [
          {
            "path": [
              "leftEntity",
              "uuid"
            ]
          },
          {
            "parameter": "{{person_a_entity_uuid}}"
          }
        ]
      },
      {
        "equal": [
          {
            "path": [
              "rightEntity",
              "uuid"
            ]
          },
          {
            "parameter": "{{person_b_entity_uuid}}"
          }
        ]
      }
    ]
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 2,
      "outgoing": 2
    },
    "hasRightEntity": {
      "incoming": 2,
      "outgoing": 2
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
        "start": { "kind": "unbounded" },
        "end": null
      }
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.roots.length === 1, "Unexpected number of entities");
    });
%}

### Archive an entity
PUT http://127.0.0.1:4000/entities
Content-Type: application/json
Accept: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
 "entityId": "{{person_b_entity_id}}",
 "entityTypeId": "http://localhost:3000/@alice/types/entity-type/person/v/1",
 "properties": {
   "http://localhost:3000/@alice/types/property-type/name/": "Bob"
 },
 "archived": true
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Get all latest unarchived entities by using a query
// Only person_a and the link remains as entities
POST http://127.0.0.1:4000/entities/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "equal": [
      {
        "path": [
          "archived"
        ]
      },
      {
        "parameter": false
      }
    ]
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 2,
      "outgoing": 2
    },
    "hasRightEntity": {
      "incoming": 2,
      "outgoing": 2
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
        "start": null,
        "end": null
      }
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.roots.length === 2, "Unexpected number of entities");
    });
%}


### Get all archived entities
POST http://127.0.0.1:4000/entities/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "equal": [
      {
        "path": [
          "archived"
        ]
      },
      {
        "parameter": true
      }
    ]
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 2,
      "outgoing": 2
    },
    "hasRightEntity": {
      "incoming": 2,
      "outgoing": 2
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
        "start": { "kind": "unbounded" },
        "end": null
      }
    }
  }
}

> {%
    client.test("status", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.roots.length === 1, "Unexpected number of entities");
    });
%}


### Get all entities where the name property contains "Alice"
POST http://127.0.0.1:4000/entities/query
Content-Type: application/json
X-Authenticated-User-Actor-Id: {{account_id}}

{
  "filter": {
    "containsSegment": [
      { "path": ["properties", "http://localhost:3000/@alice/types/property-type/name/"] },
      { "parameter": "Alice" }
    ]
  },
  "graphResolveDepths": {
    "inheritsFrom": {
      "outgoing": 0
    },
    "constrainsValuesOn": {
      "outgoing": 0
    },
    "constrainsPropertiesOn": {
      "outgoing": 0
    },
    "constrainsLinksOn": {
      "outgoing": 0
    },
    "constrainsLinkDestinationsOn": {
      "outgoing": 0
    },
    "isOfType": {
      "outgoing": 0
    },
    "hasLeftEntity": {
      "incoming": 0,
      "outgoing": 0
    },
    "hasRightEntity": {
      "incoming": 0,
      "outgoing": 0
    }
  },
  "temporalAxes": {
    "pinned": {
      "axis": "transactionTime",
      "timestamp": null
    },
    "variable": {
      "axis": "decisionTime",
      "interval": {
        "start": {
          "kind": "unbounded"
        },
        "end": null
      }
    }
  }
}

> {%
  client.test("status", function() {
    client.assert(response.status === 200, "Response status is not 200");
    client.assert(response.body.roots.length === 2, "Unexpected number of entity types");
  });
%}
