//! The OpenAPI documentation of problem details and rejections, generated by
//! [`aide`](https://docs.rs/aide).

use alloc::{
    borrow::ToOwned as _,
    collections::BTreeMap,
    format,
    string::{String, ToString as _},
    vec,
    vec::Vec,
};

use aide::{
    OperationOutput,
    generate::GenContext,
    openapi::{
        Example, Header, HeaderStyle, MediaType, Operation, ParameterSchemaOrContent, ReferenceOr,
        Response, SchemaObject, StatusCode,
    },
};
use schemars::{JsonSchema, Schema, json_schema};

use crate::{Problem, ProblemDetails, Variant, problem::assert_variants, serde::STANDARD_MEMBERS};

impl<E: JsonSchema> OperationOutput for ProblemDetails<'_, E> {
    type Inner = Self;

    fn operation_response(ctx: &mut GenContext, _operation: &mut Operation) -> Option<Response> {
        Some(problem_response(
            String::from("An RFC 9457 problem details document."),
            problem_media(ctx.schema.subschema_for::<Self>()),
        ))
    }

    fn inferred_responses(
        ctx: &mut GenContext,
        operation: &mut Operation,
    ) -> Vec<(Option<StatusCode>, Response)> {
        Self::operation_response(ctx, operation)
            .map(|response| (None, response))
            .into_iter()
            .collect()
    }
}

/// Documents a rejection through the responses `aide` infers for a handler, or through
/// [`inferred_responses`](Self::inferred_responses). An explicit
/// `TransformOperation::response::<N, Rejection<K>>()` documents nothing.
impl<K: Problem> OperationOutput for crate::Rejection<K> {
    type Inner = Self;

    fn operation_response(_ctx: &mut GenContext, _operation: &mut Operation) -> Option<Response> {
        None
    }

    /// Documents the variants of `K` on the endpoint, joined with the errors every other
    /// [`Problem`] of the endpoint documents at the same status.
    ///
    /// A status that already has a response documenting no variants, such as one for
    /// [`ProblemDetails`] itself, keeps it. The variants of `K` for that status are not documented,
    /// and a warning names them.
    ///
    /// # Panics
    ///
    /// Panics if the fields of a variant serialize as neither an object nor a unit, or one of them
    /// is named like a standard member, or if another [`Problem`] of the endpoint documents the
    /// same type URI and status differently.
    ///
    /// Fails at compile time if `K` lists two variants with the same type URI and status:
    ///
    /// ```compile_fail,E0080
    /// # use std::{borrow::Cow, fmt};
    /// use aide::{OperationOutput as _, generate, openapi::Operation};
    /// use http::StatusCode;
    /// use problematic::{Problem, ProblemType, ProblemVariant, Rejection, Variant};
    ///
    /// #[derive(serde::Serialize, schemars::JsonSchema)]
    /// struct UserNotFound;
    /// # impl fmt::Display for UserNotFound {
    /// #     fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
    /// #         formatter.write_str("The user does not exist.")
    /// #     }
    /// # }
    ///
    /// impl ProblemVariant for UserNotFound {
    ///     const TYPE: ProblemType = ProblemType {
    ///         type_uri: Cow::Borrowed("https://example.com/problems/user-not-found"),
    ///         title: Cow::Borrowed("User not found"),
    ///         status: StatusCode::NOT_FOUND,
    ///     };
    /// }
    ///
    /// struct GetUserProblem;
    ///
    /// impl Problem for GetUserProblem {
    ///     const VARIANTS: &'static [Variant] =
    ///         &[Variant::of::<UserNotFound>(), Variant::of::<UserNotFound>()];
    /// }
    ///
    /// // Fails to compile: `GetUserProblem` lists `UserNotFound` twice.
    /// generate::in_context(|context| {
    ///     Rejection::<GetUserProblem>::inferred_responses(context, &mut Operation::default())
    /// });
    /// ```
    fn inferred_responses(
        ctx: &mut GenContext,
        operation: &mut Operation,
    ) -> Vec<(Option<StatusCode>, Response)> {
        const { assert_variants::<K>() };

        merge(ctx, operation, K::VARIANTS);
        Vec::new()
    }
}

/// One variant as a response documents it.
#[derive(Debug)]
struct Fragment {
    type_uri: String,
    title: String,
    status: u16,
    description: Option<String>,
    schema: Schema,
    example: Option<serde_json::Value>,
    headers: Vec<HeaderFragment>,
}

#[derive(Debug, Clone)]
struct HeaderFragment {
    name: String,
    description: String,
    schema: Schema,
}

impl Fragment {
    fn of(context: &mut GenContext, base: &Schema, variant: &Variant) -> Self {
        let problem_type = variant.problem_type();
        let extensions = variant.extensions(&mut context.schema);
        assert_members(variant, &extensions);
        let description = schema_description(&extensions);

        Self {
            type_uri: problem_type.type_uri.to_string(),
            title: problem_type.title.to_string(),
            status: problem_type.status.as_u16(),
            example: example(variant, &extensions),
            schema: variant_schema(base, variant, extensions, description.as_deref()),
            description,
            headers: variant
                .headers()
                .iter()
                .map(|header| HeaderFragment {
                    name: header.name().to_owned(),
                    description: header.description().to_owned(),
                    schema: header.schema(&mut context.schema),
                })
                .collect(),
        }
    }

    /// The variant a `branch` of a rendered response documents, with `headers`.
    ///
    /// `None` if `branch` does not document a variant.
    fn read(
        branch: &serde_json::Value,
        media: &MediaType,
        single: bool,
        headers: &[HeaderFragment],
    ) -> Option<Self> {
        let (type_uri, status) = branch.get("allOf")?.as_array()?.iter().find_map(|part| {
            let properties = part.get("properties")?;
            Some((
                properties.get("type")?.get("const")?.as_str()?,
                properties.get("status")?.get("const")?.as_u64()?,
            ))
        })?;
        let example = if single {
            media.example.clone()
        } else {
            media
                .examples
                .get(type_uri)
                .and_then(ReferenceOr::as_item)
                .and_then(|example| example.value.clone())
        };

        Some(Self {
            type_uri: type_uri.to_owned(),
            title: branch.get("title")?.as_str()?.to_owned(),
            status: u16::try_from(status).ok()?,
            description: branch
                .get("description")
                .and_then(serde_json::Value::as_str)
                .map(ToOwned::to_owned),
            schema: serde_json::from_value(branch.clone()).ok()?,
            example,
            headers: headers.to_vec(),
        })
    }

    fn same_problem(&self, other: &Self) -> bool {
        self.status == other.status && self.type_uri == other.type_uri
    }

    /// Whether `other` documents the problem as `self` does, leaving the headers aside: a variant
    /// read back from a response knows only the headers every variant at its status lists.
    fn documents_like(&self, other: &Self) -> bool {
        self.title == other.title
            && self.description == other.description
            && self.schema == other.schema
            && self.example == other.example
    }
}

/// The variants documented at one status of an operation.
#[derive(Default)]
struct Documented {
    fragments: Vec<Fragment>,
    /// The headers only some variants list. A response read back no longer tells which ones.
    optional_headers: Vec<HeaderFragment>,
}

impl Documented {
    /// The variants `response` documents, or `None` if `response` does not document variants.
    fn read(response: &Response) -> Option<Self> {
        let media = response.content.get("application/problem+json")?;
        let schema = media.schema.as_ref()?.json_schema.as_value();
        let branches = match schema.get("oneOf") {
            Some(branches) => branches.as_array()?.iter().collect(),
            None => vec![schema],
        };

        let mut required_headers = Vec::new();
        let mut optional_headers = Vec::new();
        for (name, header) in &response.headers {
            let header = header.as_item()?;
            let ParameterSchemaOrContent::Schema(schema) = &header.format else {
                return None;
            };
            let fragment = HeaderFragment {
                name: name.clone(),
                description: header.description.clone().unwrap_or_default(),
                schema: schema.json_schema.clone(),
            };
            if header.required {
                required_headers.push(fragment);
            } else {
                optional_headers.push(fragment);
            }
        }

        let single = branches.len() == 1;
        let fragments = branches
            .into_iter()
            .map(|branch| Fragment::read(branch, media, single, &required_headers))
            .collect::<Option<_>>()?;
        Some(Self {
            fragments,
            optional_headers,
        })
    }

    /// Adds `fragment` unless it is documented already.
    ///
    /// # Panics
    ///
    /// Panics if the problem type and status of `fragment` are documented differently.
    fn join(&mut self, fragment: Fragment) {
        match self
            .fragments
            .iter()
            .find(|present| present.same_problem(&fragment))
        {
            Some(present) => assert!(
                present.documents_like(&fragment),
                "`{}` at {} should be documented the same by every source of the operation",
                fragment.type_uri,
                fragment.status
            ),
            None => self.fragments.push(fragment),
        }
    }

    /// The response documenting the variants.
    fn render(self) -> Response {
        let mut media = problem_media(response_schema(&self.fragments));
        add_examples(&mut media, &self.fragments);

        let mut response = problem_response(describe(&self.fragments), media);
        add_headers(&mut response, &self.fragments, &self.optional_headers);
        response
    }
}

/// Documents `variants` on `operation`, joining the problems already documented per status.
fn merge<'v>(
    context: &mut GenContext,
    operation: &mut Operation,
    variants: impl IntoIterator<Item = &'v Variant>,
) {
    let base = context.schema.subschema_for::<ProblemDetails<'static>>();
    let mut by_status = BTreeMap::<u16, Vec<Fragment>>::new();
    for variant in variants {
        let fragment = Fragment::of(context, &base, variant);
        by_status.entry(fragment.status).or_default().push(fragment);
    }

    let operation_id = operation.operation_id.as_deref();
    let responses = operation.responses.get_or_insert_default();
    for (code, fragments) in by_status {
        let status = StatusCode::Code(code);
        let mut documented = match responses.responses.get(&status) {
            None => Documented::default(),
            Some(existing) => {
                let Some(documented) = existing.as_item().and_then(Documented::read) else {
                    tracing::warn!(
                        operation = operation_id,
                        status = code,
                        variants = ?fragments
                            .iter()
                            .map(|fragment| fragment.type_uri.as_str())
                            .collect::<Vec<_>>(),
                        "problem variants yielded to a response that documents none"
                    );
                    continue;
                };
                documented
            }
        };
        for fragment in fragments {
            documented.join(fragment);
        }
        responses
            .responses
            .insert(status, ReferenceOr::Item(documented.render()));
    }
}

/// The schema of the one variant, or a `oneOf` over every variant.
fn response_schema(fragments: &[Fragment]) -> Schema {
    if let [fragment] = fragments {
        return fragment.schema.clone();
    }

    let schemas = fragments
        .iter()
        .map(|fragment| &fragment.schema)
        .collect::<Vec<_>>();
    json_schema!({ "oneOf": schemas })
}

/// Adds the example of the one variant, or a named example per variant that has one.
fn add_examples(media: &mut MediaType, fragments: &[Fragment]) {
    if let [fragment] = fragments {
        media.example.clone_from(&fragment.example);
        return;
    }

    // `assert_variants` and `join` keep the type URI unique within one status.
    media.examples = fragments
        .iter()
        .filter_map(|fragment| {
            let example = fragment.example.clone()?;
            Some((
                fragment.type_uri.clone(),
                ReferenceOr::Item(Example {
                    summary: Some(fragment.title.clone()),
                    value: Some(example),
                    ..Example::default()
                }),
            ))
        })
        .collect();
}

/// Adds every header the variants list and every one of `optional`, each required if every
/// variant lists it.
fn add_headers(response: &mut Response, fragments: &[Fragment], optional: &[HeaderFragment]) {
    let listed = optional
        .iter()
        .chain(fragments.iter().flat_map(|fragment| &fragment.headers));
    for header in listed {
        if response
            .headers
            .keys()
            .any(|name| name.eq_ignore_ascii_case(&header.name))
        {
            continue;
        }
        let required = !optional
            .iter()
            .any(|candidate| candidate.name.eq_ignore_ascii_case(&header.name))
            && fragments.iter().all(|fragment| {
                fragment
                    .headers
                    .iter()
                    .any(|candidate| candidate.name.eq_ignore_ascii_case(&header.name))
            });
        response.headers.insert(
            header.name.clone(),
            ReferenceOr::Item(Header {
                description: Some(header.description.clone()),
                style: HeaderStyle::Simple,
                required,
                deprecated: None,
                format: ParameterSchemaOrContent::Schema(SchemaObject {
                    json_schema: header.schema.clone(),
                    example: None,
                    external_docs: None,
                }),
                example: None,
                examples: [].into(),
                extensions: [].into(),
            }),
        );
    }
}

fn problem_response(description: String, media: MediaType) -> Response {
    Response {
        description,
        content: [(String::from("application/problem+json"), media)].into(),
        ..Response::default()
    }
}

fn problem_media(schema: Schema) -> MediaType {
    MediaType {
        schema: Some(SchemaObject {
            json_schema: schema,
            example: None,
            external_docs: None,
        }),
        ..MediaType::default()
    }
}

/// The description of a response: that of its one variant, or a list item per variant with its
/// title.
///
/// A variant is described by its extension schema, which a derived schema takes from the doc
/// comment, and otherwise by its title alone.
fn describe(fragments: &[Fragment]) -> String {
    if let [fragment] = fragments {
        return fragment
            .description
            .clone()
            .unwrap_or_else(|| fragment.title.clone());
    }

    fragments
        .iter()
        .map(|fragment| {
            let title = &fragment.title;
            fragment.description.as_ref().map_or_else(
                || format!("- {title}"),
                // Indented, so a description of several paragraphs stays within its list item.
                |description| format!("- {title}: {}", description.replace('\n', "\n  ")),
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Checks that `extensions` describes members the variant's problem details can carry.
///
/// Every branch of `oneOf`, `anyOf` and `allOf` is checked, as an enum's variants are described
/// there. A branch referencing a definition is not followed.
///
/// # Panics
///
/// Panics if the members or one of their branches are neither an object nor a unit, or name a
/// standard member. Either would fail to serialize, and the occurrence would be answered as an
/// internal error.
fn assert_members(variant: &Variant, extensions: &Schema) {
    assert_members_of(&variant.problem_type().type_uri, extensions.as_value());
}

fn assert_members_of(type_uri: &str, schema: &serde_json::Value) {
    if let Some(kind) = schema.get("type").and_then(serde_json::Value::as_str) {
        assert!(
            kind == "object" || kind == "null",
            "the extension members of `{type_uri}` should serialize as an object, not as `{kind}`"
        );
    }
    if let Some(properties) = schema
        .get("properties")
        .and_then(serde_json::Value::as_object)
    {
        for member in STANDARD_MEMBERS {
            assert!(
                !properties.contains_key(member),
                "the extension members of `{type_uri}` should not name the standard member \
                 `{member}`"
            );
        }
    }
    for keyword in ["oneOf", "anyOf", "allOf"] {
        for branch in schema
            .get(keyword)
            .and_then(serde_json::Value::as_array)
            .into_iter()
            .flatten()
        {
            assert_members_of(type_uri, branch);
        }
    }
}

fn schema_description(extensions: &Schema) -> Option<String> {
    extensions
        .get("description")
        .and_then(serde_json::Value::as_str)
        .map(ToOwned::to_owned)
}

/// The example occurrence of `variant`.
///
/// Without one, a variant without extension members is shown as its bare problem type. A variant
/// with members has no example then, as the bare problem type would lack them.
fn example(variant: &Variant, extensions: &Schema) -> Option<serde_json::Value> {
    variant.example().or_else(|| {
        without_members(extensions).then(|| {
            serde_json::to_value(ProblemDetails::from(variant.problem_type()))
                .expect("a bare problem type should serialize")
        })
    })
}

/// Whether `extensions` describes no members: a unit struct, whose schema has type `null`, or a
/// struct whose fields are all skipped.
///
/// Any keyword other than `type`, `title` and `description` counts as members.
fn without_members(extensions: &Schema) -> bool {
    extensions.as_object().is_some_and(|schema| {
        schema
            .iter()
            .all(|(keyword, value)| match keyword.as_str() {
                "type" => value == "null" || value == "object",
                "title" | "description" => true,
                _ => false,
            })
    })
}

/// Removes the keywords that close the members' object, and those of every `oneOf`, `anyOf` and
/// `allOf` branch, to other members.
///
/// In the `allOf` of a variant, `additionalProperties` and `unevaluatedProperties` would also
/// apply to the standard members. schemars adds `additionalProperties: false` to every variant of
/// an externally tagged enum and to a struct that denies unknown fields.
fn open(schema: &mut serde_json::Map<String, serde_json::Value>) {
    schema.remove("additionalProperties");
    schema.remove("unevaluatedProperties");
    for keyword in ["oneOf", "anyOf", "allOf"] {
        for branch in schema
            .get_mut(keyword)
            .and_then(serde_json::Value::as_array_mut)
            .into_iter()
            .flatten()
            .filter_map(serde_json::Value::as_object_mut)
        {
            open(branch);
        }
    }
}

/// The problem details of `variant`, titled with its problem type and described like the variant.
fn variant_schema(
    base: &Schema,
    variant: &Variant,
    extensions: Schema,
    description: Option<&str>,
) -> Schema {
    let problem_type = variant.problem_type();
    let mut all_of = vec![
        base.clone(),
        json_schema!({
            "properties": {
                "type": { "const": problem_type.type_uri },
                "status": { "const": problem_type.status.as_u16() },
            },
            "required": ["type"],
        }),
    ];
    if !without_members(&extensions) {
        let mut extensions = extensions;
        if let Some(members) = extensions.as_object_mut() {
            open(members);
        }
        all_of.push(extensions);
    }

    let mut schema = json_schema!({ "title": problem_type.title, "allOf": all_of });
    if let Some(description) = description {
        schema.insert("description".to_owned(), description.into());
    }
    schema
}
