graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hash_graph_store/index.html">hash-graph-store</a>]
    1[<a href="../hash_graph_temporal_versioning/index.html">hash-graph-temporal-versioning</a>]
    2[<a href="../hash_graph_test_data/index.html">hash-graph-test-data</a>]
    3[<a href="../hash_graph_test_server/index.html">hash-graph-test-server</a>]
    4[<a href="../hash_graph_type_defs/index.html">hash-graph-type-defs</a>]
    5[<a href="../hash_graph_type_fetcher/index.html">hash-graph-type-fetcher</a>]
    6[<a href="../hash_graph_types/index.html">hash-graph-types</a>]
    7[<a href="../error_stack/index.html">error-stack</a>]
    8[<a href="../hash_graph_validation/index.html">hash-graph-validation</a>]
    9[<a href="../harpc_client/index.html">harpc-client</a>]
    10[<a href="../harpc_codec/index.html">harpc-codec</a>]
    11[<a href="../harpc_net/index.html">harpc-net</a>]
    12[<a href="../harpc_server/index.html">harpc-server</a>]
    13[<a href="../harpc_system/index.html">harpc-system</a>]
    14[<a href="../harpc_tower/index.html">harpc-tower</a>]
    15[<a href="../harpc_types/index.html">harpc-types</a>]
    16[<a href="../harpc_wire_protocol/index.html">harpc-wire-protocol</a>]
    17[<a href="../hash_codec/index.html">hash-codec</a>]
    18[hash-graph]
    class 18 root
    19[<a href="../hash_graph_api/index.html">hash-graph-api</a>]
    20[<a href="../hash_graph_authorization/index.html">hash-graph-authorization</a>]
    21[<a href="../type_system/index.html">type-system</a>]
    22[<a href="../hash_status/index.html">hash-status</a>]
    23[<a href="../hash_temporal_client/index.html">hash-temporal-client</a>]
    24[<a href="../hash_tracing/index.html">hash-tracing</a>]
    25[<a href="../hash_graph_postgres_store/index.html">hash-graph-postgres-store</a>]
    4 --> 22
    9 --> 13
    10 --> 7
    10 --> 15
    11 --> 10
    11 --> 17
    11 -.-> 10
    12 -.-> 9
    12 -.-> 6
    13 --> 14
    14 --> 11
    14 -.-> 11
    16 --> 7
    16 --> 15
    16 -.-> 15
    17 --> 16
    18 --> 3
    18 --> 24
    19 --> 12
    19 --> 25
    19 --> 4
    19 --> 5
    20 --> 6
    5 --> 0
    21 --> 17
    6 --> 1
    6 --> 21
    8 --> 0
    21 -.-> 2
    24 --> 7
    23 --> 6
    25 --> 8
    25 --> 22
    0 --> 20
    0 --> 23
    1 --> 17
    3 --> 19