DROP TABLE entity_embeddings;
DROP VIEW entity_is_of_type_ids;
DROP TABLE entity_is_of_type;
DROP TABLE entity_has_left_entity;
DROP TABLE entity_has_right_entity;
DROP TABLE entity_temporal_metadata;
DROP TABLE entity_editions;
DROP TABLE entity_drafts;
DROP TABLE entity_ids;
