graph TD
    %% Configure the diagram
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[hash-graph-types]
    class 0 root
    1[<a href="../hash_graph_test_data/index.html">hash-graph-test-data</a>]
    class 1 dev
    2[<a href="../type_system/index.html">type-system</a>]
    3[<a href="../hash_graph_temporal_versioning/index.html">hash-graph-temporal-versioning</a>]
    4[<a href="../hash_codec/index.html">hash-codec</a>]
    5[<a href="../error_stack/index.html">error-stack</a>]
    6[<a href="../harpc_types/index.html">harpc-types</a>]
    7[<a href="../harpc_wire_protocol/index.html">harpc-wire-protocol</a>]
    8[<a href="../harpc_server/index.html">harpc-server</a>]
    9[<a href="../hash_graph/index.html">hash-graph</a>]
    10[<a href="../hash_graph_api/index.html">hash-graph-api</a>]
    11[<a href="../hash_graph_authorization/index.html">hash-graph-authorization</a>]
    12[<a href="../hash_graph_benches/index.html">hash-graph-benches</a>]
    13[<a href="../hash_graph_integration/index.html">hash-graph-integration</a>]
    14[<a href="../hash_graph_postgres_store/index.html">hash-graph-postgres-store</a>]
    15[<a href="../hash_graph_store/index.html">hash-graph-store</a>]
    16[<a href="../hash_graph_test_server/index.html">hash-graph-test-server</a>]
    class 16 dev
    17[<a href="../hash_graph_type_fetcher/index.html">hash-graph-type-fetcher</a>]
    18[<a href="../hash_graph_validation/index.html">hash-graph-validation</a>]
    19[<a href="../hash_temporal_client/index.html">hash-temporal-client</a>]
    0 --> 2
    0 --> 3
    2 -.-> 1
    2 --> 4
    3 --> 4
    4 --> 7
    7 -.-> 6
    7 --> 6
    7 --> 5
    8 -.-> 0
    11 --> 0
    19 --> 0
    10 --> 8
    12 -.-> 10
    16 --> 10
    15 --> 11
    10 --> 14
    13 -.-> 14
    17 --> 15
    18 --> 15
    9 --> 16
    10 --> 17
    14 --> 18
    15 --> 19