const ISSUE_EXAMPLES = [
  {
    type: "RECORD",
    stream: "issues",
    record: {
      url: "https://api.github.com/repos/khonsulabs/bonsaidb/issues/217",
      repository_url: "https://api.github.com/repos/khonsulabs/bonsaidb",
      labels_url:
        "https://api.github.com/repos/khonsulabs/bonsaidb/issues/217/labels{/name}",
      comments_url:
        "https://api.github.com/repos/khonsulabs/bonsaidb/issues/217/comments",
      events_url:
        "https://api.github.com/repos/khonsulabs/bonsaidb/issues/217/events",
      html_url: "https://github.com/khonsulabs/bonsaidb/pull/217",
      id: 1157570041,
      node_id: "PR_kwDOFNbk3M4z2S66",
      number: 217,
      title: "Testing leaking a secret",
      user: {
        login: "ecton",
        id: 50053,
        node_id: "MDQ6VXNlcjUwMDUz",
        avatar_url: "https://avatars.githubusercontent.com/u/50053?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/ecton",
        html_url: "https://github.com/ecton",
        followers_url: "https://api.github.com/users/ecton/followers",
        following_url:
          "https://api.github.com/users/ecton/following{/other_user}",
        gists_url: "https://api.github.com/users/ecton/gists{/gist_id}",
        starred_url:
          "https://api.github.com/users/ecton/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/ecton/subscriptions",
        organizations_url: "https://api.github.com/users/ecton/orgs",
        repos_url: "https://api.github.com/users/ecton/repos",
        events_url: "https://api.github.com/users/ecton/events{/privacy}",
        received_events_url:
          "https://api.github.com/users/ecton/received_events",
        type: "User",
        site_admin: false,
      },
      labels: [],
      state: "closed",
      locked: false,
      assignee: null,
      comments: 1,
      created_at: "2022-03-02T18:54:28.000000Z",
      updated_at: "2022-03-02T19:02:53.000000Z",
      closed_at: "2022-03-02T19:02:48.000000Z",
      author_association: "MEMBER",
      pull_request: {
        url: "https://api.github.com/repos/khonsulabs/bonsaidb/pulls/217",
        html_url: "https://github.com/khonsulabs/bonsaidb/pull/217",
        diff_url: "https://github.com/khonsulabs/bonsaidb/pull/217.diff",
        patch_url: "https://github.com/khonsulabs/bonsaidb/pull/217.patch",
      },
      body: "If my understanding is correct, this shouldn't show anything.",
      _sdc_repository: "khonsulabs/bonsaidb",
    },
    time_extracted: "2022-03-12T17:30:52.746373Z",
  },
  {
    type: "RECORD",
    stream: "issues",
    record: {
      url: "https://api.github.com/repos/khonsulabs/bonsaidb/issues/5",
      repository_url: "https://api.github.com/repos/khonsulabs/bonsaidb",
      labels_url:
        "https://api.github.com/repos/khonsulabs/bonsaidb/issues/5/labels{/name}",
      comments_url:
        "https://api.github.com/repos/khonsulabs/bonsaidb/issues/5/comments",
      events_url:
        "https://api.github.com/repos/khonsulabs/bonsaidb/issues/5/events",
      html_url: "https://github.com/khonsulabs/bonsaidb/issues/5",
      id: 838223175,
      node_id: "MDU6SXNzdWU4MzgyMjMxNzU=",
      number: 5,
      title: "Add reading of transaction logs and unit tests",
      user: {
        login: "ecton",
        id: 50053,
        node_id: "MDQ6VXNlcjUwMDUz",
        avatar_url: "https://avatars.githubusercontent.com/u/50053?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/ecton",
        html_url: "https://github.com/ecton",
        followers_url: "https://api.github.com/users/ecton/followers",
        following_url:
          "https://api.github.com/users/ecton/following{/other_user}",
        gists_url: "https://api.github.com/users/ecton/gists{/gist_id}",
        starred_url:
          "https://api.github.com/users/ecton/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/ecton/subscriptions",
        organizations_url: "https://api.github.com/users/ecton/orgs",
        repos_url: "https://api.github.com/users/ecton/repos",
        events_url: "https://api.github.com/users/ecton/events{/privacy}",
        received_events_url:
          "https://api.github.com/users/ecton/received_events",
        type: "User",
        site_admin: false,
      },
      labels: [],
      state: "closed",
      locked: false,
      assignee: null,
      comments: 1,
      created_at: "2021-03-23T00:41:49.000000Z",
      updated_at: "2021-03-23T15:49:52.000000Z",
      closed_at: "2021-03-23T15:49:52.000000Z",
      author_association: "MEMBER",
      body: "While we're not working on replication yet, we should add the necessary methods to read the transaction logs so that we can unit test the transactions.",
      _sdc_repository: "khonsulabs/bonsaidb",
    },
    time_extracted: "2022-03-12T17:30:50.663343Z",
  },
  {
    type: "RECORD",
    stream: "issues",
    record: {
      url: "https://api.github.com/repos/khonsulabs/bonsaidb/issues/2",
      repository_url: "https://api.github.com/repos/khonsulabs/bonsaidb",
      labels_url:
        "https://api.github.com/repos/khonsulabs/bonsaidb/issues/2/labels{/name}",
      comments_url:
        "https://api.github.com/repos/khonsulabs/bonsaidb/issues/2/comments",
      events_url:
        "https://api.github.com/repos/khonsulabs/bonsaidb/issues/2/events",
      html_url: "https://github.com/khonsulabs/bonsaidb/issues/2",
      id: 838210542,
      node_id: "MDU6SXNzdWU4MzgyMTA1NDI=",
      number: 2,
      title: "Add unit test for document update failures",
      user: {
        login: "ecton",
        id: 50053,
        node_id: "MDQ6VXNlcjUwMDUz",
        avatar_url: "https://avatars.githubusercontent.com/u/50053?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/ecton",
        html_url: "https://github.com/ecton",
        followers_url: "https://api.github.com/users/ecton/followers",
        following_url:
          "https://api.github.com/users/ecton/following{/other_user}",
        gists_url: "https://api.github.com/users/ecton/gists{/gist_id}",
        starred_url:
          "https://api.github.com/users/ecton/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/ecton/subscriptions",
        organizations_url: "https://api.github.com/users/ecton/orgs",
        repos_url: "https://api.github.com/users/ecton/repos",
        events_url: "https://api.github.com/users/ecton/events{/privacy}",
        received_events_url:
          "https://api.github.com/users/ecton/received_events",
        type: "User",
        site_admin: false,
      },
      labels: [],
      state: "closed",
      locked: false,
      assignee: null,
      comments: 0,
      created_at: "2021-03-23T00:18:27.000000Z",
      updated_at: "2021-03-23T19:24:25.000000Z",
      closed_at: "2021-03-23T19:24:25.000000Z",
      author_association: "MEMBER",
      body: "* Conflict\r\n* Not found\r\n* No change (not a failure but still test it)",
      _sdc_repository: "khonsulabs/bonsaidb",
    },
    time_extracted: "2022-03-12T17:30:50.663343Z",
  },
  {
    type: "RECORD",
    stream: "issues",
    record: {
      url: "https://api.github.com/repos/khonsulabs/bonsaidb/issues/1",
      repository_url: "https://api.github.com/repos/khonsulabs/bonsaidb",
      labels_url:
        "https://api.github.com/repos/khonsulabs/bonsaidb/issues/1/labels{/name}",
      comments_url:
        "https://api.github.com/repos/khonsulabs/bonsaidb/issues/1/comments",
      events_url:
        "https://api.github.com/repos/khonsulabs/bonsaidb/issues/1/events",
      html_url: "https://github.com/khonsulabs/bonsaidb/pull/1",
      id: 837115431,
      node_id: "MDExOlB1bGxSZXF1ZXN0NTk3NTEzMDg2",
      number: 1,
      title: "Switch to LLVM-based code coverage",
      user: {
        login: "ecton",
        id: 50053,
        node_id: "MDQ6VXNlcjUwMDUz",
        avatar_url: "https://avatars.githubusercontent.com/u/50053?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/ecton",
        html_url: "https://github.com/ecton",
        followers_url: "https://api.github.com/users/ecton/followers",
        following_url:
          "https://api.github.com/users/ecton/following{/other_user}",
        gists_url: "https://api.github.com/users/ecton/gists{/gist_id}",
        starred_url:
          "https://api.github.com/users/ecton/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/ecton/subscriptions",
        organizations_url: "https://api.github.com/users/ecton/orgs",
        repos_url: "https://api.github.com/users/ecton/repos",
        events_url: "https://api.github.com/users/ecton/events{/privacy}",
        received_events_url:
          "https://api.github.com/users/ecton/received_events",
        type: "User",
        site_admin: false,
      },
      labels: [],
      state: "closed",
      locked: false,
      assignee: null,
      comments: 1,
      created_at: "2021-03-21T16:00:36.000000Z",
      updated_at: "2021-03-24T13:10:09.000000Z",
      closed_at: "2021-03-24T12:58:59.000000Z",
      author_association: "MEMBER",
      pull_request: {
        url: "https://api.github.com/repos/khonsulabs/bonsaidb/pulls/1",
        html_url: "https://github.com/khonsulabs/bonsaidb/pull/1",
        diff_url: "https://github.com/khonsulabs/bonsaidb/pull/1.diff",
        patch_url: "https://github.com/khonsulabs/bonsaidb/pull/1.patch",
      },
      body: "The code coverage from `-Zprofile` isn't very good -- it tracks documentation lines as code and has issues within the ecosystem requiring a lot of extra compiler flags. I stumbled upon `-Zinstrument-coverage` which uses the LLVM coverage tools and should provide much more accurate results.\r\n\r\nThis PR works and enables it, but unfortunately, it only tracks a single test's coverage due to rust-lang/rust#79899. So, the main branch will use the original coverage until that is resolved -- sounds like it could be a decent task to get involved in those projects.\r\n\r\n",
      _sdc_repository: "khonsulabs/bonsaidb",
    },
    time_extracted: "2022-03-12T17:30:50.663343Z",
  },
  {
    type: "RECORD",
    stream: "issues",
    record: {
      url: "https://api.github.com/repos/khonsulabs/bonsaidb/issues/4",
      repository_url: "https://api.github.com/repos/khonsulabs/bonsaidb",
      labels_url:
        "https://api.github.com/repos/khonsulabs/bonsaidb/issues/4/labels{/name}",
      comments_url:
        "https://api.github.com/repos/khonsulabs/bonsaidb/issues/4/comments",
      events_url:
        "https://api.github.com/repos/khonsulabs/bonsaidb/issues/4/events",
      html_url: "https://github.com/khonsulabs/bonsaidb/issues/4",
      id: 838222760,
      node_id: "MDU6SXNzdWU4MzgyMjI3NjA=",
      number: 4,
      title: "Implement background job service",
      user: {
        login: "ecton",
        id: 50053,
        node_id: "MDQ6VXNlcjUwMDUz",
        avatar_url: "https://avatars.githubusercontent.com/u/50053?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/ecton",
        html_url: "https://github.com/ecton",
        followers_url: "https://api.github.com/users/ecton/followers",
        following_url:
          "https://api.github.com/users/ecton/following{/other_user}",
        gists_url: "https://api.github.com/users/ecton/gists{/gist_id}",
        starred_url:
          "https://api.github.com/users/ecton/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/ecton/subscriptions",
        organizations_url: "https://api.github.com/users/ecton/orgs",
        repos_url: "https://api.github.com/users/ecton/repos",
        events_url: "https://api.github.com/users/ecton/events{/privacy}",
        received_events_url:
          "https://api.github.com/users/ecton/received_events",
        type: "User",
        site_admin: false,
      },
      labels: [],
      state: "closed",
      locked: false,
      assignee: null,
      comments: 0,
      created_at: "2021-03-23T00:40:49.000000Z",
      updated_at: "2021-03-27T23:37:24.000000Z",
      closed_at: "2021-03-27T23:37:24.000000Z",
      author_association: "MEMBER",
      body: "To implement the view system properly, we need to have a background job service. For now, the service can be simple: The ability to launch or check to see if a job with a given ID is running or in queue, and if so, wait for it to complete.",
      _sdc_repository: "khonsulabs/bonsaidb",
    },
    time_extracted: "2022-03-12T17:30:50.663343Z",
  },
  // VVV Pull Request VVV
  {
    type: "RECORD",
    stream: "issues",
    record: {
      url: "https://api.github.com/repos/khonsulabs/bonsaidb/issues/6",
      repository_url: "https://api.github.com/repos/khonsulabs/bonsaidb",
      labels_url:
        "https://api.github.com/repos/khonsulabs/bonsaidb/issues/6/labels{/name}",
      comments_url:
        "https://api.github.com/repos/khonsulabs/bonsaidb/issues/6/comments",
      events_url:
        "https://api.github.com/repos/khonsulabs/bonsaidb/issues/6/events",
      html_url: "https://github.com/khonsulabs/bonsaidb/pull/6",
      id: 840121813,
      node_id: "MDExOlB1bGxSZXF1ZXN0NjAwMDMzNDU5",
      number: 6,
      title: "Implement mapped views",
      user: {
        login: "ecton",
        id: 50053,
        node_id: "MDQ6VXNlcjUwMDUz",
        avatar_url: "https://avatars.githubusercontent.com/u/50053?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/ecton",
        html_url: "https://github.com/ecton",
        followers_url: "https://api.github.com/users/ecton/followers",
        following_url:
          "https://api.github.com/users/ecton/following{/other_user}",
        gists_url: "https://api.github.com/users/ecton/gists{/gist_id}",
        starred_url:
          "https://api.github.com/users/ecton/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/ecton/subscriptions",
        organizations_url: "https://api.github.com/users/ecton/orgs",
        repos_url: "https://api.github.com/users/ecton/repos",
        events_url: "https://api.github.com/users/ecton/events{/privacy}",
        received_events_url:
          "https://api.github.com/users/ecton/received_events",
        type: "User",
        site_admin: false,
      },
      labels: [],
      state: "closed",
      locked: false,
      assignee: null,
      comments: 1,
      created_at: "2021-03-24T20:02:33.000000Z",
      updated_at: "2021-03-27T23:37:25.000000Z",
      closed_at: "2021-03-27T23:37:24.000000Z",
      author_association: "MEMBER",
      pull_request: {
        url: "https://api.github.com/repos/khonsulabs/bonsaidb/pulls/6",
        html_url: "https://github.com/khonsulabs/bonsaidb/pull/6",
        diff_url: "https://github.com/khonsulabs/bonsaidb/pull/6.diff",
        patch_url: "https://github.com/khonsulabs/bonsaidb/pull/6.patch",
      },
      body: "* [x] Add the start of the job queueing system. The goal is to have a layer that is unit tested that gets shared between the local storage and server implementations. There will likely be configuration options that both layers use, but the jobs themselves will be different. Closes #4.\r\n* [x] Implement view caching job. \r\n* [x] Implement view query API. Closes #3.\r\n* [ ] ~Test enabling integrity check on launch~\r\n* [x] Fix integrity check to actually save the values so it doesn't run twice\r\n  * [ ] ~Test it~\r\n* [x] Test last_transaction_id on an empty database\r\n* [x] Test Connection::collection when the collection isn't in the schema\r\n* [x] Test Range-based queries\r\n* [x] Test Multiple-get queries",
      _sdc_repository: "khonsulabs/bonsaidb",
    },
    time_extracted: "2022-03-12T17:30:50.663343Z",
  },
];
