[settings]
# hooks are experimental
experimental = true

# We do not use Rust as it's experimental as well.
disable_tools = ["rust"]

[tools]
node = '22.14.0'
yarn = '4.6.0'
python = '3.13.2'

biome             = '1.9.5-nightly.ff02a0b'
lefthook          = '1.10.10'
markdownlint-cli2 = '0.17.2'
sentry-cli        = '2.41.1'
taplo             = '0.9.3'

"cargo:cargo-binstall" = "1.10.22"
"cargo:cargo-hack"     = "0.6.35"
"cargo:cargo-insta"    = "1.42.1"
"cargo:cargo-llvm-cov" = "0.6.16"
"cargo:cargo-nextest"  = "0.9.80"
"cargo:wasm-pack"      = "0.12.1"

"npm:@napi-rs/cli" = '2.18.4'
"npm:npm-run-all2" = '7.0.2'
"npm:turbo"        = '2.4.1'

"pipx:sqlfluff" = "3.3.1"
uv              = '0.5.30'

[hooks]
postinstall = [
  "echo 'Installing lefthook hooks...'",
  "lefthook install -f && echo 'Done!' || echo 'Failed!'",
  "echo 'Enabling corepack...'",
  "corepack enable && echo 'Done!' || echo 'Failed!'",
]
