[project]
name = "embedding2d"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14,<3.15"
dependencies = [
    "hnswlib>=0.8.0",
    "numpy>=2.1,<2.5",
    "pgvector>=0.5.0",
    "psycopg[binary]>=3.3.4",
    "safetensors>=0.8.0",
    "scikit-image>=0.26.0",
    "torch>=2.12.1",
    "umap-learn>=0.5.12",
]

[tool.pyright]
venvPath = "."
venv     = ".venv"

[tool.ty.environment]
python = "./.venv"
