import { ApolloError } from "apollo-server-express";

import { Resolver, Visibility } from "../../autoGeneratedTypes";
import { DbBlockProperties, DbUnknownEntity } from "../../../types/dbTypes";
import { GraphQLContext } from "../../context";

export const blockEntity: Resolver<
  Promise<DbUnknownEntity>,
  DbBlockProperties,
  GraphQLContext,
  {}
> = async ({ namespaceId, entityId }, {}, { dataSources }) => {
  const entity = await dataSources.db.getEntity({
    accountId: namespaceId,
    entityId: entityId,
  });
  if (!entity) {
    throw new ApolloError(
      `Entity id ${entityId} not found in account ${namespaceId}`,
      "NOT_FOUND"
    );
  }

  return {
    ...entity,
    id: entity.entityId,
    namespaceId: entity.accountId,
    visibility: Visibility.Public, // TODO: get from entity metadata
  };
};
