graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hash_graph/index.html">hash-graph</a>]
    1[<a href="../type_system/index.html">type-system</a>]
    2[<a href="../hash_codec/index.html">hash-codec</a>]
    3[<a href="../hash_graph_api/index.html">hash-graph-api</a>]
    4[<a href="../hash_graph_authorization/index.html">hash-graph-authorization</a>]
    5[<a href="../hash_graph_postgres_store/index.html">hash-graph-postgres-store</a>]
    6[<a href="../hash_graph_store/index.html">hash-graph-store</a>]
    7[<a href="../hash_graph_temporal_versioning/index.html">hash-graph-temporal-versioning</a>]
    8[<a href="../hash_graph_test_server/index.html">hash-graph-test-server</a>]
    9[<a href="../hash_graph_type_fetcher/index.html">hash-graph-type-fetcher</a>]
    10[<a href="../hash_graph_types/index.html">hash-graph-types</a>]
    11[<a href="../hash_graph_validation/index.html">hash-graph-validation</a>]
    12[<a href="../harpc_client/index.html">harpc-client</a>]
    13[<a href="../harpc_net/index.html">harpc-net</a>]
    14[<a href="../harpc_server/index.html">harpc-server</a>]
    15[<a href="../harpc_system/index.html">harpc-system</a>]
    16[<a href="../harpc_tower/index.html">harpc-tower</a>]
    17[<a href="../harpc_types/index.html">harpc-types</a>]
    18[harpc-wire-protocol]
    class 18 root
    19[<a href="../hashql_ast/index.html">hashql-ast</a>]
    20[<a href="../hashql_compiletest/index.html">hashql-compiletest</a>]
    21[<a href="../hashql_core/index.html">hashql-core</a>]
    22[<a href="../hashql_eval/index.html">hashql-eval</a>]
    23[<a href="../hashql_hir/index.html">hashql-hir</a>]
    24[<a href="../hashql_mir/index.html">hashql-mir</a>]
    25[<a href="../hashql_syntax_jexpr/index.html">hashql-syntax-jexpr</a>]
    26[<a href="../hash_temporal_client/index.html">hash-temporal-client</a>]
    27[<a href="../error_stack/index.html">error-stack</a>]
    28[<a href="../hash_graph_benches/index.html">hash-graph-benches</a>]
    29[<a href="../hash_graph_integration/index.html">hash-graph-integration</a>]
    30[<a href="../hash_graph_test_data/index.html">hash-graph-test-data</a>]
    0 --> 8
    1 --> 7
    1 -.-> 30
    2 --> 18
    3 --> 5
    3 --> 9
    3 --> 14
    3 --> 22
    3 --> 25
    4 --> 1
    5 --> 11
    6 --> 4
    6 --> 10
    6 --> 26
    7 --> 2
    8 --> 3
    9 --> 6
    10 -.-> 30
    11 -.-> 30
    12 --> 15
    13 --> 2
    14 -.-> 1
    14 -.-> 12
    15 --> 16
    16 -.-> 13
    16 --> 13
    18 -.-> 17
    18 --> 17
    18 --> 27
    19 -.-> 20
    20 --> 22
    20 --> 24
    20 --> 25
    20 --> 27
    21 --> 2
    22 --> 6
    22 --> 23
    23 -.-> 20
    24 --> 23
    25 --> 19
    25 --> 21
    26 --> 1
    28 -.-> 3
    29 -.-> 5
    30 --> 6
