/**
 * This file was automatically generated – do not edit it.
 */

import type {
  DisplayNamePropertyValue,
  DisplayNamePropertyValueWithMetadata,
  EmailPropertyValue,
  EmailPropertyValueWithMetadata,
  ExpiredAtPropertyValue,
  ExpiredAtPropertyValueWithMetadata,
  Link,
  LinkOutgoingLinkAndTarget,
  LinkOutgoingLinksByLinkEntityTypeId,
  LinkProperties,
  LinkPropertiesWithMetadata,
  TextDataType,
  TextDataTypeWithMetadata,
  UserSecret,
  UserSecretOutgoingLinkAndTarget,
  UserSecretOutgoingLinksByLinkEntityTypeId,
  UserSecretProperties,
  UserSecretPropertiesWithMetadata,
  UsesUserSecret,
  UsesUserSecretOutgoingLinkAndTarget,
  UsesUserSecretOutgoingLinksByLinkEntityTypeId,
  UsesUserSecretProperties,
  UsesUserSecretPropertiesWithMetadata,
  VaultPathPropertyValue,
  VaultPathPropertyValueWithMetadata,
} from "./shared.js";

export type {
  DisplayNamePropertyValue,
  DisplayNamePropertyValueWithMetadata,
  EmailPropertyValue,
  EmailPropertyValueWithMetadata,
  ExpiredAtPropertyValue,
  ExpiredAtPropertyValueWithMetadata,
  Link,
  LinkOutgoingLinkAndTarget,
  LinkOutgoingLinksByLinkEntityTypeId,
  LinkProperties,
  LinkPropertiesWithMetadata,
  TextDataType,
  TextDataTypeWithMetadata,
  UserSecret,
  UserSecretOutgoingLinkAndTarget,
  UserSecretOutgoingLinksByLinkEntityTypeId,
  UserSecretProperties,
  UserSecretPropertiesWithMetadata,
  UsesUserSecret,
  UsesUserSecretOutgoingLinkAndTarget,
  UsesUserSecretOutgoingLinksByLinkEntityTypeId,
  UsesUserSecretProperties,
  UsesUserSecretPropertiesWithMetadata,
  VaultPathPropertyValue,
  VaultPathPropertyValueWithMetadata,
};

export {type Account, type AccountIdPropertyValue, type AccountIdPropertyValueWithMetadata, type AccountOutgoingLinkAndTarget, type AccountOutgoingLinksByLinkEntityTypeId, type AccountProperties, type AccountPropertiesWithMetadata, type AccountUsesUserSecretLink, type ConnectionSourceNamePropertyValue, type ConnectionSourceNamePropertyValueWithMetadata} from "./shared.js";