/**
 * This file was automatically generated – do not edit it.
 */

import type {
  Account,
  AccountIdPropertyValue,
  AccountOutgoingLinkAndTarget,
  AccountOutgoingLinksByLinkEntityTypeId,
  AccountProperties,
  AccountUsesUserSecretLink,
  ConnectionSourceNamePropertyValue,
  DisplayNamePropertyValue,
  EmailPropertyValue,
  ExpiredAtPropertyValue,
  Link,
  LinkOutgoingLinkAndTarget,
  LinkOutgoingLinksByLinkEntityTypeId,
  LinkProperties,
  TextDataType,
  UserSecret,
  UserSecretOutgoingLinkAndTarget,
  UserSecretOutgoingLinksByLinkEntityTypeId,
  UserSecretProperties,
  UsesUserSecret,
  UsesUserSecretOutgoingLinkAndTarget,
  UsesUserSecretOutgoingLinksByLinkEntityTypeId,
  UsesUserSecretProperties,
  VaultPathPropertyValue,
} from "./shared";

export type {
  Account,
  AccountIdPropertyValue,
  AccountOutgoingLinkAndTarget,
  AccountOutgoingLinksByLinkEntityTypeId,
  AccountProperties,
  AccountUsesUserSecretLink,
  ConnectionSourceNamePropertyValue,
  DisplayNamePropertyValue,
  EmailPropertyValue,
  ExpiredAtPropertyValue,
  Link,
  LinkOutgoingLinkAndTarget,
  LinkOutgoingLinksByLinkEntityTypeId,
  LinkProperties,
  TextDataType,
  UserSecret,
  UserSecretOutgoingLinkAndTarget,
  UserSecretOutgoingLinksByLinkEntityTypeId,
  UserSecretProperties,
  UsesUserSecret,
  UsesUserSecretOutgoingLinkAndTarget,
  UsesUserSecretOutgoingLinksByLinkEntityTypeId,
  UsesUserSecretProperties,
  VaultPathPropertyValue,
};
