/* eslint-disable */
export type Token = `colors.${ColorToken}`

export type ColorPalette = "gray" | "red" | "orange" | "green" | "blue" | "neutral" | "purple" | "pink" | "yellow" | "accent" | "accentGray" | "accentAlpha" | "whiteAlpha"

export type ColorToken = "gray.10" | "gray.20" | "gray.30" | "gray.35" | "gray.40" | "gray.50" | "gray.60" | "gray.70" | "gray.80" | "gray.90" | "gray.95" | "gray.00" | "red.10" | "red.20" | "red.30" | "red.40" | "red.50" | "red.60" | "red.70" | "red.80" | "red.90" | "red.00" | "orange.10" | "orange.20" | "orange.30" | "orange.40" | "orange.50" | "orange.60" | "orange.70" | "orange.80" | "orange.90" | "orange.00" | "green.10" | "green.20" | "green.30" | "green.40" | "green.50" | "green.60" | "green.70" | "green.80" | "green.90" | "green.00" | "blue.10" | "blue.20" | "blue.30" | "blue.40" | "blue.50" | "blue.60" | "blue.70" | "blue.80" | "blue.90" | "blue.00" | "neutral.white" | "neutral.black" | "purple.10" | "purple.20" | "purple.30" | "purple.40" | "purple.50" | "purple.60" | "purple.70" | "purple.80" | "purple.90" | "purple.00" | "pink.10" | "pink.20" | "pink.30" | "pink.40" | "pink.50" | "pink.60" | "pink.70" | "pink.80" | "pink.90" | "pink.00" | "yellow.10" | "yellow.20" | "yellow.30" | "yellow.40" | "yellow.50" | "yellow.60" | "yellow.70" | "yellow.80" | "yellow.90" | "yellow.00" | "accent.10" | "accent.20" | "accent.30" | "accent.40" | "accent.50" | "accent.60" | "accent.70" | "accent.80" | "accent.90" | "accent.00" | "accentGray.10" | "accentGray.20" | "accentGray.30" | "accentGray.40" | "accentGray.50" | "accentGray.60" | "accentGray.70" | "accentGray.80" | "accentGray.90" | "accentGray.95" | "accentGray.00" | "accentAlpha.10" | "accentAlpha.20" | "accentAlpha.30" | "accentAlpha.40" | "accentAlpha.50" | "accentAlpha.60" | "accentAlpha.70" | "accentAlpha.80" | "accentAlpha.90" | "accentAlpha.00" | "whiteAlpha.10" | "whiteAlpha.20" | "whiteAlpha.30" | "whiteAlpha.40" | "whiteAlpha.50" | "whiteAlpha.60" | "whiteAlpha.70" | "whiteAlpha.80" | "whiteAlpha.90" | "whiteAlpha.95" | "whiteAlpha.00" | "colorPalette.10" | "colorPalette.20" | "colorPalette.30" | "colorPalette.35" | "colorPalette.40" | "colorPalette.50" | "colorPalette.60" | "colorPalette.70" | "colorPalette.80" | "colorPalette.90" | "colorPalette.95" | "colorPalette.00" | "colorPalette.white" | "colorPalette.black"

export type Tokens = {
		colors: ColorToken
} & { [token: string]: never }

export type TokenCategory = "aspectRatios" | "zIndex" | "opacity" | "colors" | "fonts" | "fontSizes" | "fontWeights" | "lineHeights" | "letterSpacings" | "sizes" | "cursor" | "shadows" | "spacing" | "radii" | "borders" | "borderWidths" | "durations" | "easings" | "animations" | "blurs" | "gradients" | "breakpoints" | "assets"