import { DbUnknownEntity } from "../../../types/dbTypes";
import {
  MutationCreateEntityArgs,
  Resolver,
  Visibility,
} from "../../autoGeneratedTypes";
import { GraphQLContext } from "../../context";


export const createEntity: Resolver<
  Promise<DbUnknownEntity>,
  {},
  GraphQLContext,
  MutationCreateEntityArgs
> = async (_, { namespaceId, createdById, properties, type }, { dataSources }) => {
  const e = await dataSources.db.createEntity({
    namespaceId, createdById, type, properties
  });

  const entity: DbUnknownEntity = {
    ...e,
    visibility: Visibility.Public, // TODO: should be a param?,
  };

  return entity;
};
