import { Block, Page } from "../graphql/autoGeneratedTypes";

export type DbBlock = Omit<Block, "entity"> & { entityId: string };

export type DbPage = Omit<Page, "properties"> & {
  properties: Omit<Page["properties"], "contents"> & { contents: DbBlock[] };
};
