# generated by datamodel-codegen:
#   filename:  optimization-protocol.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class Scale(Enum):
    linear = "linear"
    log = "log"


class OptimizationFloatParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    identifier: str
    type: Literal["float"]
    default: float
    minimum: float
    maximum: float
    scale: Scale


class OptimizationIntParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    identifier: str
    type: Literal["int"]
    default: float
    minimum: float
    maximum: float
    step: float
    scale: Scale


class OptimizationBooleanParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    identifier: str
    type: Literal["boolean"]
    default: bool


class OptimizationReplicate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    seed: int = Field(..., ge=-9007199254740991, le=9007199254740991)
    objective: float


class Direction(Enum):
    maximize = "maximize"
    minimize = "minimize"


class Sampler(Enum):
    tpe = "tpe"
    random = "random"


class Study(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trials: int = Field(..., ge=1, le=1000)
    sampler: Sampler
    seed: int = Field(..., ge=-9007199254740991, le=9007199254740991)
    seedsPerTrial: int | None = Field(None, ge=-9007199254740991, le=9007199254740991)


class OptimizationDescribeResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    direction: Direction
    study: Study = Field(
        ...,
        description="Study settings with the execution seed. `seedsPerTrial` is reported once the CLI runs seeded replicates; absent means 1.",
    )
    parameters: list[
        OptimizationFloatParameter
        | OptimizationIntParameter
        | OptimizationBooleanParameter
    ]


class OptimizationEvaluateResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    objective: float
    replicates: list[OptimizationReplicate] | None = None
