# generated by datamodel-codegen:
#   filename:  optimization-protocol.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class Scale(Enum):
    linear = "linear"
    log = "log"


class OptimizationFloatParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    identifier: str
    type: Literal["float"]
    default: float
    minimum: float
    maximum: float
    scale: Scale


class OptimizationIntParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    identifier: str
    type: Literal["int"]
    default: float
    minimum: int = Field(..., ge=-9007199254740991, le=9007199254740991)
    maximum: int = Field(..., ge=-9007199254740991, le=9007199254740991)
    step: int = Field(..., ge=-9007199254740991, le=9007199254740991)
    scale: Scale


class OptimizationBooleanParameter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    identifier: str
    type: Literal["boolean"]
    default: bool


class Surface(Enum):
    dynamics = "dynamics"
    lambda_ = "lambda"
    kernel = "kernel"
    metric = "metric"
    scenario_expression = "scenario-expression"
    scenario_code = "scenario-code"


class Param(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    __annotations__ = {
        "__pydantic_extra__": dict[str, Any],
    }
    name: str


class Body(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    __annotations__ = {
        "__pydantic_extra__": dict[str, Any],
    }
    kind: str


class Hir(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    __annotations__ = {
        "__pydantic_extra__": dict[str, Any],
    }
    hirVersion: Literal[1]
    surface: Surface
    params: list[Param]
    body: Body


class OptimizationConstraint(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(..., min_length=1)
    name: str | None = Field(
        None,
        description="Optional display name shown wherever the constraint is reported.",
        min_length=1,
    )
    code: str = Field(
        ...,
        description="The authored TypeScript source — the editable text of record. `hir` is its lowered form; regenerating `hir` from `code` must be a no-op.",
        min_length=1,
    )
    hir: Hir = Field(
        ...,
        description="A serialized HIR function (see hir/hir.ts for the full grammar). Carried verbatim; evaluators must reject unknown node kinds.",
    )


class OptimizationConstraints(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    parameterSpace: list[OptimizationConstraint] = Field(
        ...,
        description="Conditions over the sampled scenario parameters (`scenario.*`), e.g. `scenario.min_altitude < scenario.max_altitude`. Intended to let samplers avoid infeasible suggestions; not enforced yet.",
    )
    stateSpace: list[OptimizationConstraint] = Field(
        ...,
        description="Conditions over the simulation state, authored like a metric body but returning boolean. Intended for safe-region margins later; not evaluated yet.",
    )


class OptimizationReplicate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    seed: int = Field(..., ge=-9007199254740991, le=9007199254740991)
    objective: float


class Direction(Enum):
    maximize = "maximize"
    minimize = "minimize"


class Sampler(Enum):
    tpe = "tpe"
    random = "random"


class Study(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trials: int = Field(..., ge=1, le=1000)
    sampler: Sampler
    seed: int = Field(..., ge=-9007199254740991, le=9007199254740991)
    seedsPerTrial: int | None = Field(None, ge=1, le=100)


class OptimizationDescribeResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    direction: Direction
    study: Study = Field(
        ...,
        description="Study settings with the execution seed. `seedsPerTrial` is reported once the CLI runs seeded replicates; absent means 1.",
    )
    parameters: list[
        OptimizationFloatParameter
        | OptimizationIntParameter
        | OptimizationBooleanParameter
    ]
    constraints: OptimizationConstraints | None = None


class OptimizationEvaluateResult(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    objective: float
    replicates: list[OptimizationReplicate] | None = None
