graph TD
    linkStyle default stroke-width:1.5px
    classDef default stroke-width:1px
    classDef root stroke-width:3px
    classDef dev stroke-width:1px
    classDef build stroke-width:1px
    %% Legend
    %% --> : Normal dependency
    %% -.-> : Dev dependency
    %% ---> : Build dependency
    0[<a href="../hql_syntax_jexpr/index.html">hql-syntax-jexpr</a>]
    1[hql-diagnostics]
    class 1 root
    2[<a href="../hql_span/index.html">hql-span</a>]
    3[<a href="../error_stack/index.html">error-stack</a>]
    0 --> 1
    1 --> 3
    1 --> 2