/**
 * WGSL identifier hygiene.
 *
 * User code names bindings freely, but WGSL reserves a large vocabulary — far
 * more than JavaScript does, and including innocuous words like `active`,
 * `sample`, `filter` and `buffer` that real model code plausibly uses. A
 * collision is a shader compile error, which surfaces as a broken simulation
 * rather than a diagnostic, so every emitted name is mangled rather than
 * checked against the list case by case.
 */

/**
 * Reserved and predeclared words that may not be used as WGSL identifiers.
 *
 * From the WGSL spec's reserved-words list plus the predeclared type and
 * builtin-function names an emitted program could otherwise shadow.
 */
const WGSL_RESERVED = new Set([
  // Keywords
  "alias",
  "break",
  "case",
  "const",
  "const_assert",
  "continue",
  "continuing",
  "default",
  "diagnostic",
  "discard",
  "else",
  "enable",
  "false",
  "fn",
  "for",
  "if",
  "let",
  "loop",
  "override",
  "requires",
  "return",
  "struct",
  "switch",
  "true",
  "var",
  "while",
  // Reserved for future use — the spec forbids these outright.
  "NULL",
  "Self",
  "abstract",
  "active",
  "alignas",
  "alignof",
  "as",
  "asm",
  "asm_fragment",
  "async",
  "attribute",
  "auto",
  "await",
  "become",
  "cast",
  "catch",
  "class",
  "co_await",
  "co_return",
  "co_yield",
  "coherent",
  "column_major",
  "common",
  "compile",
  "compile_fragment",
  "concept",
  "const_cast",
  "consteval",
  "constinit",
  "constexpr",
  "crate",
  "debugger",
  "decltype",
  "delete",
  "demote",
  "demote_to_helper",
  "do",
  "dynamic_cast",
  "enum",
  "explicit",
  "export",
  "extends",
  "extern",
  "external",
  "fallthrough",
  "filter",
  "final",
  "finally",
  "friend",
  "from",
  "fxgroup",
  "get",
  "goto",
  "groupuniform",
  "highp",
  "impl",
  "implements",
  "import",
  "inline",
  "instanceof",
  "interface",
  "layout",
  "lowp",
  "macro",
  "macro_rules",
  "match",
  "mediump",
  "meta",
  "mod",
  "module",
  "move",
  "mut",
  "mutable",
  "namespace",
  "new",
  "nil",
  "noexcept",
  "noinline",
  "nointerpolation",
  "non_coherent",
  "noncoherent",
  "noperspective",
  "null",
  "nullptr",
  "of",
  "operator",
  "package",
  "packoffset",
  "partition",
  "pass",
  "patch",
  "pixelfragment",
  "precise",
  "precision",
  "premerge",
  "priv",
  "protected",
  "pub",
  "public",
  "readonly",
  "ref",
  "regardless",
  "register",
  "reinterpret_cast",
  "require",
  "resource",
  "restrict",
  "self",
  "set",
  "shared",
  "sizeof",
  "smooth",
  "snorm",
  "static",
  "static_assert",
  "static_cast",
  "std",
  "subroutine",
  "super",
  "target",
  "template",
  "this",
  "thread_local",
  "throw",
  "trait",
  "try",
  "type",
  "typedef",
  "typeid",
  "typename",
  "typeof",
  "union",
  "unless",
  "unorm",
  "unsafe",
  "unsized",
  "use",
  "using",
  "varying",
  "virtual",
  "volatile",
  "wgsl",
  "where",
  "with",
  "writeonly",
  "yield",
  // Predeclared types and common builtins worth not shadowing.
  "array",
  "atomic",
  "bool",
  "f16",
  "f32",
  "i32",
  "mat2x2",
  "mat3x3",
  "mat4x4",
  "ptr",
  "sampler",
  "texture_1d",
  "texture_2d",
  "texture_3d",
  "u32",
  "vec2",
  "vec3",
  "vec4",
  "abs",
  "all",
  "any",
  "ceil",
  "clamp",
  "cos",
  "cross",
  "dot",
  "exp",
  "floor",
  "fract",
  "length",
  "log",
  "max",
  "min",
  "mix",
  "modf",
  "normalize",
  "pow",
  "round",
  "select",
  "sign",
  "sin",
  "smoothstep",
  "sqrt",
  "step",
  "tan",
  "trunc",
]);

/** Whether `name` cannot be used verbatim as a WGSL identifier. */
export function isReservedWgslIdentifier(name: string): boolean {
  return WGSL_RESERVED.has(name);
}

/**
 * Mangles a user-authored name into a WGSL identifier.
 *
 * Every name is prefixed rather than only the reserved ones, so a model that
 * happens to use a future reserved word does not start failing when the WGSL
 * vocabulary grows. Characters WGSL does not accept are replaced, and a
 * disambiguating ordinal keeps two names that sanitize alike apart.
 *
 * The ordinal only disambiguates names from **one** emitter. Two emitters both
 * counting from zero produce the same identifiers, which is an error if their
 * statements land in one WGSL scope — as the RK stages of a dynamics loop do.
 * Such callers must pass a `scope` that differs per emitter.
 */
export function mangleWgslIdentifier(
  name: string,
  ordinal: number,
  scope = "",
): string {
  const sanitized = name.replaceAll(/[^A-Za-z0-9_]/gu, "_");
  return `${scope}u_${ordinal}_${sanitized}`;
}
