import { useQuery } from "@apollo/client";
import Link from "next/link";

import { GetNamespacesQuery } from "../graphql/autoGeneratedTypes";
import { getNamespaces } from "../graphql/queries/namespace.queries";

import styles from "./index.module.scss";

export default function Home() {
  const { data } = useQuery<GetNamespacesQuery>(getNamespaces);

  return (
    <main className={styles.Main}>
      <header>
        <h1>HASH.dev</h1>
      </header>

      <section>
        <h2>Namespaces in this instance</h2>
        <ul>
          {data?.namespaces.map((namespace) => (
            <li>
              <Link href={`/namespace/${namespace.id}`}>
                <a>{namespace.shortname}</a>
              </Link>
            </li>
          ))}
        </ul>
      </section>

      <section>
        <h2>Block playground</h2>
        <p>
          <Link href="/playground">
            <a>Click here to visit the block playground</a>
          </Link>
        </p>
      </section>
    </main>
  );
}
