import react from "@vitejs/plugin-react";
import { dts } from "rolldown-plugin-dts";
import { defineConfig } from "vite";

const declarationFilePattern = /\.d\.[cm]?ts$/;

export default defineConfig(({ command }) => ({
  plugins: [
    react({
      // The native compiler also transforms TypeScript syntax, so exclude the
      // declarations generated by rolldown-plugin-dts from that transform.
      exclude: [/[\\/]node_modules[\\/]/, declarationFilePattern],
      compiler: {
        target: "19",
        compilationMode: "infer",
        panicThreshold: "critical_errors",
      },
    }),

    command === "build" && dts({ generator: "tsgo" }),
  ],

  build: {
    lib: {
      entry: { index: "src/main.ts" },
      fileName: (_format, entryName) => `${entryName}.js`,
      formats: ["es"],
    },
    rolldownOptions: {
      external: [
        "react",
        "react-dom",
        "react/jsx-runtime",
        "react/jsx-dev-runtime",
        "react/compiler-runtime",
      ],
    },
    sourcemap: true,
    emptyOutDir: true,
    minify: true,
  },

  // rolldown-plugin-dts emits declaration modules that Vite must not
  // transform as JavaScript. Setting this replaces Vite's default exclusions.
  oxc: {
    exclude: [/\.js$/, declarationFilePattern],
  },
}));
