[package]
name              = "hash-integrations-engine"
description       = "Runs integration pipelines in DuckDB"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
authors.workspace = true

[dependencies]
# Public workspace dependencies
error-stack = { workspace = true, public = true, features = ["std"] }

# Public third-party dependencies
duckdb = { workspace = true, public = true, features = ["bundled"] }

# Private workspace dependencies

# Private third-party dependencies
derive_more    = { workspace = true, features = ["display", "error"] }
simple-mermaid = { workspace = true }
tokio          = { workspace = true, features = ["sync"] }
tracing        = { workspace = true }

[dev-dependencies]
proptest = { workspace = true, features = ["std"] }
tempfile = { workspace = true }
tokio    = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
