name: Dependency Review

on:
  pull_request:
  merge_group:

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Dependency Review
    uses: hashintel/.github/.github/workflows/dependency-review.yml@8f5593ef032fa7797bc4d70b6c7b5c02549fc862
