name: Dependency Review

on:
  pull_request:
    paths:
      - ".github/workflows/dependency-review.yml"
  pull_request_target:
  merge_group:

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Dependency Review
    uses: hashintel/.github/.github/workflows/dependency-review.yml@5ba4cedb756d32b66f2c628967e57fad88aeb717
