on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request: {}
  merge_group: {}

env:
  AWS_REGION: eu-central-1

  ARTIFACTS_ECR_URL: 469596578827.dkr.ecr.eu-central-1.amazonaws.com
  OIDC_HASH_CD_PUSH_ROLE: arn:aws:iam::469596578827:role/github-oidc-hash-cd-push
  OIDC_HASH_CD_DEPLOY_ROLE: arn:aws:iam::054238437032:role/github-oidc-hash-cd-deploy

  APP_CLUSTER_NAME: h-stage-euc1-app
  APP_GRAPH_SERVICE_NAME: h-stage-euc1-app-graph
  APP_GRAPH_ADMIN_SERVICE_NAME: h-stage-euc1-app-graph-admin
  APP_TYPE_FETCHER_SERVICE_NAME: h-stage-euc1-app-type-fetcher
  APP_API_SERVICE_NAME: h-stage-euc1-app-api
  WORKER_CLUSTER_NAME: h-stage-euc1-worker
  WORKER_AI_TS_SERVICE_NAME: h-stage-euc1-worker-ai-ts
  WORKER_INTEGRATION_SERVICE_NAME: h-stage-euc1-worker-integration
  AUTH_CLUSTER_NAME: h-stage-euc1-auth
  AUTH_KRATOS_SERVICE_NAME: h-stage-euc1-auth-kratos
  AUTH_HYDRA_SERVICE_NAME: h-stage-euc1-auth-hydra

name: HASH backend deployment
jobs:
  build-graph:
    name: Build${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && '' || ' and push' }} HASH graph image
    runs-on: ubuntu-24.04-arm
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure AWS credentials (ECR push)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ env.OIDC_HASH_CD_PUSH_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && '' || ' and push' }} graph image
        uses: ./.github/actions/docker-build-push
        with:
          SHORTNAME: "graph"
          CONTEXT_PATH: ${{ github.workspace }}/
          DOCKERFILE_LOCATION: ${{ github.workspace }}/apps/hash-graph/docker/Dockerfile
          AWS_ECR_URL: ${{ env.ARTIFACTS_ECR_URL }}
          ECR_IMAGE_NAME: ${{ github.repository }}/graph
          GHCR_IMAGE_NAME: hash-graph
          IMAGE_TAG: staging
          GITHUB_TOKEN: ${{ github.token }}
          PUSH: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

  build-api:
    name: Build${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && '' || ' and push' }} HASH api image
    runs-on: ubuntu-24.04-arm
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure AWS credentials (ECR push)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ env.OIDC_HASH_CD_PUSH_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && '' || ' and push' }} api image
        uses: ./.github/actions/docker-build-push
        with:
          SHORTNAME: "api"
          CONTEXT_PATH: ${{ github.workspace }}
          DOCKERFILE_LOCATION: ${{ github.workspace }}/apps/hash-api/docker/Dockerfile
          AWS_ECR_URL: ${{ env.ARTIFACTS_ECR_URL }}
          ECR_IMAGE_NAME: ${{ github.repository }}/api
          GHCR_IMAGE_NAME: hash-api
          IMAGE_TAG: staging
          GITHUB_TOKEN: ${{ github.token }}
          PUSH: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

  build-frontend:
    name: Build${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && '' || ' and push' }} HASH frontend image
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && '' || ' and push' }} frontend image
        uses: ./.github/actions/docker-build-push
        with:
          SHORTNAME: "frontend"
          CONTEXT_PATH: ${{ github.workspace }}
          DOCKERFILE_LOCATION: ${{ github.workspace }}/apps/hash-frontend/docker/Dockerfile
          GHCR_IMAGE_NAME: hash-frontend
          IMAGE_TAG: staging
          GITHUB_TOKEN: ${{ github.token }}
          PUSH: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

  build-kratos:
    name: Build${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && '' || ' and push' }} Kratos image
    runs-on: ubuntu-24.04-arm
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure AWS credentials (ECR push)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ env.OIDC_HASH_CD_PUSH_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && '' || ' and push' }} kratos image
        uses: ./.github/actions/docker-build-push
        with:
          SHORTNAME: "kratos"
          CONTEXT_PATH: ${{ github.workspace }}/infra/compose/kratos
          DOCKERFILE_LOCATION: ${{ github.workspace }}/infra/compose/kratos/Dockerfile
          AWS_ECR_URL: ${{ env.ARTIFACTS_ECR_URL }}
          ECR_IMAGE_NAME: ${{ github.repository }}/kratos
          GHCR_IMAGE_NAME: hash-kratos
          IMAGE_TAG: staging
          GITHUB_TOKEN: ${{ github.token }}
          PUSH: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

  build-hydra:
    name: Build${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && '' || ' and push' }} Hydra image
    runs-on: ubuntu-24.04-arm
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure AWS credentials (ECR push)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ env.OIDC_HASH_CD_PUSH_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && '' || ' and push' }} hydra image
        uses: ./.github/actions/docker-build-push
        with:
          SHORTNAME: "hydra"
          CONTEXT_PATH: ${{ github.workspace }}/infra/compose/hydra
          DOCKERFILE_LOCATION: ${{ github.workspace }}/infra/compose/hydra/Dockerfile
          AWS_ECR_URL: ${{ env.ARTIFACTS_ECR_URL }}
          ECR_IMAGE_NAME: ${{ github.repository }}/hydra
          GHCR_IMAGE_NAME: hash-hydra
          IMAGE_TAG: staging
          GITHUB_TOKEN: ${{ github.token }}
          PUSH: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

  build-ts-worker:
    name: Build${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && '' || ' and push' }} Temporal TS AI Worker
    runs-on: ubuntu-24.04-arm
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure AWS credentials (ECR push)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ env.OIDC_HASH_CD_PUSH_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && '' || ' and push' }} ai-worker-ts image
        uses: ./.github/actions/docker-build-push
        with:
          SHORTNAME: "temporal-worker-ai-ts"
          CONTEXT_PATH: ${{ github.workspace }}
          DOCKERFILE_LOCATION: ${{ github.workspace }}/apps/hash-ai-worker-ts/docker/Dockerfile
          AWS_ECR_URL: ${{ env.ARTIFACTS_ECR_URL }}
          ECR_IMAGE_NAME: ${{ github.repository }}/ai-worker-ts
          GHCR_IMAGE_NAME: hash-ai-worker-ts
          IMAGE_TAG: staging
          GITHUB_TOKEN: ${{ github.token }}
          PUSH: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

  build-integration-worker:
    name: Build${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && '' || ' and push' }} Temporal integration Worker
    runs-on: ubuntu-24.04-arm
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure AWS credentials (ECR push)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ env.OIDC_HASH_CD_PUSH_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build${{ (github.event_name == 'pull_request' || github.event_name == 'merge_group') && '' || ' and push' }} integration-worker image
        uses: ./.github/actions/docker-build-push
        with:
          SHORTNAME: "temporal-integration-worker"
          CONTEXT_PATH: ${{ github.workspace }}
          DOCKERFILE_LOCATION: ${{ github.workspace }}/apps/hash-integration-worker/docker/Dockerfile
          AWS_ECR_URL: ${{ env.ARTIFACTS_ECR_URL }}
          ECR_IMAGE_NAME: ${{ github.repository }}/integration-worker
          GHCR_IMAGE_NAME: hash-integration-worker
          IMAGE_TAG: staging
          GITHUB_TOKEN: ${{ github.token }}
          PUSH: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

  deploy-graph:
    name: Deploy HASH graph images
    runs-on: ubuntu-latest
    needs:
      - build-graph
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure AWS credentials (ECS deploy)
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ env.OIDC_HASH_CD_DEPLOY_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Redeploy graph staging service
        uses: ./.github/actions/redeploy-ecs-service
        with:
          ECS_CLUSTER_NAME: ${{ env.APP_CLUSTER_NAME }}
          ECS_SERVICE_NAME: ${{ env.APP_GRAPH_SERVICE_NAME }}

      - name: Redeploy graph-admin staging service
        uses: ./.github/actions/redeploy-ecs-service
        with:
          ECS_CLUSTER_NAME: ${{ env.APP_CLUSTER_NAME }}
          ECS_SERVICE_NAME: ${{ env.APP_GRAPH_ADMIN_SERVICE_NAME }}

      - name: Redeploy type-fetcher staging service
        uses: ./.github/actions/redeploy-ecs-service
        with:
          ECS_CLUSTER_NAME: ${{ env.APP_CLUSTER_NAME }}
          ECS_SERVICE_NAME: ${{ env.APP_TYPE_FETCHER_SERVICE_NAME }}

  deploy-app:
    name: Deploy HASH app images
    runs-on: ubuntu-latest
    needs:
      - build-api
      - build-kratos
      - build-hydra
      # Technically not needed but it's good if the graph has been finished already
      - deploy-graph
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure AWS credentials (ECS deploy)
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ env.OIDC_HASH_CD_DEPLOY_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Redeploy API staging service
        uses: ./.github/actions/redeploy-ecs-service
        with:
          ECS_CLUSTER_NAME: ${{ env.APP_CLUSTER_NAME }}
          ECS_SERVICE_NAME: ${{ env.APP_API_SERVICE_NAME }}

      - name: Redeploy kratos staging service
        uses: ./.github/actions/redeploy-ecs-service
        with:
          ECS_CLUSTER_NAME: ${{ env.AUTH_CLUSTER_NAME }}
          ECS_SERVICE_NAME: ${{ env.AUTH_KRATOS_SERVICE_NAME }}

      - name: Redeploy hydra staging service
        uses: ./.github/actions/redeploy-ecs-service
        with:
          ECS_CLUSTER_NAME: ${{ env.AUTH_CLUSTER_NAME }}
          ECS_SERVICE_NAME: ${{ env.AUTH_HYDRA_SERVICE_NAME }}

  deploy-workers:
    name: Deploy HASH worker images
    runs-on: ubuntu-latest
    needs:
      - build-ts-worker
      - build-integration-worker
      # Technically not needed but it's good if the graph has been finished already
      - deploy-graph
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure AWS credentials (ECS deploy)
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: ${{ env.OIDC_HASH_CD_DEPLOY_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Redeploy AI-TS staging service
        uses: ./.github/actions/redeploy-ecs-service
        with:
          ECS_CLUSTER_NAME: ${{ env.WORKER_CLUSTER_NAME }}
          ECS_SERVICE_NAME: ${{ env.WORKER_AI_TS_SERVICE_NAME }}

      - name: Redeploy Integration staging service
        uses: ./.github/actions/redeploy-ecs-service
        with:
          ECS_CLUSTER_NAME: ${{ env.WORKER_CLUSTER_NAME }}
          ECS_SERVICE_NAME: ${{ env.WORKER_INTEGRATION_SERVICE_NAME }}

  notify-slack:
    name: Notify Slack on failure
    needs:
      - deploy-app
      - deploy-graph
      - deploy-workers
    runs-on: ubuntu-latest
    if: ${{ failure() && github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') }}
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@c58b60ee33df2229ed2d2eed86eeaf7e6c527c5a
        env:
          SLACK_LINK_NAMES: true
          SLACK_MESSAGE: "Error deploying the HASH backend <!subteam^S09KH99698T>" # Notifies @devops
          SLACK_TITLE: Backend deployment failed
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: GitHub
