name: Preflight

on:
  pull_request:
    paths:
      - ".github/workflows/preflight-target.yml"
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
  merge_group:

permissions: {}

jobs:
  dependencies:
    name: Dependencies
    permissions:
      contents: read
      pull-requests: write
    uses: hashintel/.github/.github/workflows/preflight-dependencies.yml@9b55800e7975e3baf17f67a8c3d3dcc54cdd3d56 # main

  labeler:
    name: Labeler
    if: github.event_name != 'merge_group'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - name: Apply labels
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          sync-labels: true

  pr-title:
    name: PR title
    permissions:
      contents: read
    uses: hashintel/.github/.github/workflows/preflight-pr-title.yml@9b55800e7975e3baf17f67a8c3d3dcc54cdd3d56 # main
