name: Preflight

on:
  pull_request:
    paths:
      - ".github/workflows/preflight-dependencies.yml"
  pull_request_target:
  merge_group:

permissions:
  contents: read
  pull-requests: write

jobs:
  dependencies:
    name: Dependencies
    uses: hashintel/.github/.github/workflows/dependencies.yml@178dfcde6c67af354901ab4f38330bdc114d0d38
