name: Scheduled production Vercel lambda warm-up

on:
  schedule:
    - cron: "*/5 * * * *" ## Every 5 minutes

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  warm_up_production_site:
    name: Warm up Vercel lambdas
    runs-on: ubuntu-latest

    steps:
      - uses: $/.github/actions/warm-up-vercel
        with:
          deployment-base-url: "https://app.hash.ai"
