name: Redeploy ECS service
description: Force a new ECS service deployment. AWS credentials must be configured upstream.

inputs:
  ECS_CLUSTER_NAME:
    description: ECS cluster name
    required: true
  ECS_SERVICE_NAME:
    description: ECS service name
    required: true

runs:
  using: composite
  steps:
    - name: Redeploy ECS service
      env:
        ECS_CLUSTER_NAME: ${{ inputs.ECS_CLUSTER_NAME }}
        ECS_SERVICE_NAME: ${{ inputs.ECS_SERVICE_NAME }}
      shell: bash
      run: |
        aws ecs update-service \
          --cluster "${ECS_CLUSTER_NAME}" \
          --service "${ECS_SERVICE_NAME}" \
          --force-new-deployment 1> /dev/null
